package modelo.datos.dao.liquidador;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Timestamp;
import java.sql.Types;


import java.util.ArrayList;
import java.util.List;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.liquidador.Factura;

import utilidades.Funciones;


/**
  * Factura Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve Factura object instances.
  */

/**
 * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
 * The usage of generated code is restricted to OpenSource software projects
 * only. DaoGen is available in http://titaniclinux.net/daogen/
 * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
 *
 * DaoGen license: The following DaoGen generated source code is licensed
 * under the terms of GNU GPL license. The full text for license is available
 * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
 *
 * If you wish to use the DaoGen generator to produce code for closed-source
 * commercial applications, you must pay the lisence fee. The price is
 * 5 USD or 5 Eur for each database table, you are generating code for.
 * (That includes unlimited amount of iterations with all supported languages
 * for each database table you are paying for.) Send mail to
 * "Tuomo.Lukka@iki.fi" for more information. Thank you!
 */


public class FacturaDao {


    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public Factura createValueObject() {
        return new Factura();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database
     * using given Primary-Key as identifier. This method is just a convenience method
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public Factura getObject(Connection conn, int LF_ID) throws NotFoundException, SQLException {

        Factura valueObject = createValueObject();
        valueObject.setLF_ID(LF_ID);
        load(conn, valueObject);
        return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, Factura valueObject) throws NotFoundException, SQLException {

        String sql = "SELECT * FROM L_FACTURAS WHERE (LF_ID = ? ) ";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, valueObject.getLF_ID());

            singleQuery(conn, stmt, valueObject);

        } finally {
            //if (stmt != null)
            //    stmt.close();
        }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows.
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

        String sql = "SELECT * FROM L_FACTURAS ORDER BY LF_ID ASC ";
        List searchResults = listQuery(conn, conn.prepareStatement(sql));

        return searchResults;
    }


    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, Factura valueObject, String motor) throws SQLException {

        String sql = "";
        PreparedStatement stmt = null;
        ResultSet result = null;

        try {
            sql =
"INSERT INTO L_FACTURAS ( LF_ID, LF_TIPO, LF_V_ID, " + "LF_ID_PERSONA, LF_ESTADO, LF_FECHA, " + "LF_FECHA_PAGO, LF_FECHA_TRAMITE, LF_TOTAL, " +
  "LF_NOTA, LF_ID_USUARIO, LF_ID_ARQUEO, " + "LF_ID_USUARIOANULA, LF_FECHAANULA, LF_HORAANULA, " +
  "LF_MOTIVOCANCELACION, LF_FACTURAERROR, LF_NUMERO, " + "LF_DESCUENTO, LF_NOTAADICIONAL, LF_SIREVNUMERO, " +
  "LF_SIREVVALOR, LF_IDRADICADO, LF_IDDETCITA, " + "LF_NUMRUNT, LF_IDSOLICRUNT, LF_FECHARADICARUNT, " +
  "LF_IDSOLICITANTE, LF_EMPERSOL, LF_IDAPODERADO, " +
  "LF_TOTALFACTURARUNT, CARGADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, valueObject.getLF_ID());
            stmt.setString(2, valueObject.getLF_TIPO());
            stmt.setString(3, valueObject.getLF_V_ID());
            stmt.setString(4, valueObject.getLF_ID_PERSONA());
            stmt.setString(5, valueObject.getLF_ESTADO());

            if (motor.equals("FIREBIRD"))
                stmt.setString(6, valueObject.getLF_FECHA());
            else if (motor.equals("ORACLE")) {
                java.util.Date ahorautil = new java.util.Date();
                Timestamp t = new Timestamp(ahorautil.getTime());
                stmt.setTimestamp(6, t);
            }

            stmt.setString(7, valueObject.getLF_FECHA_PAGO());
            stmt.setString(8, valueObject.getLF_FECHA_TRAMITE());
            stmt.setString(9, valueObject.getLF_TOTAL());
            stmt.setString(10, valueObject.getLF_NOTA());
            stmt.setString(11, valueObject.getLF_ID_USUARIO());
            stmt.setString(12, valueObject.getLF_ID_ARQUEO());
            stmt.setString(13, valueObject.getLF_ID_USUARIOANULA());
            stmt.setString(14, valueObject.getLF_FECHAANULA());

            //stmt.setString(15, valueObject.getLF_HORAANULA());
            if (Funciones.esTime(valueObject.getLF_HORAANULA()))
                stmt.setTime(15, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getLF_HORAANULA())));
            else
                stmt.setNull(15, Types.TIME);

            stmt.setString(16, valueObject.getLF_MOTIVOCANCELACION());
            stmt.setString(17, valueObject.getLF_FACTURAERROR());
            stmt.setString(18, valueObject.getLF_NUMERO());
            stmt.setString(19, valueObject.getLF_DESCUENTO());
            stmt.setString(20, valueObject.getLF_NOTAADICIONAL());
            stmt.setString(21, valueObject.getLF_SIREVNUMERO());
            stmt.setString(22, valueObject.getLF_SIREVVALOR());
            stmt.setString(23, valueObject.getLF_IDRADICADO());
            stmt.setString(24, valueObject.getLF_IDDETCITA());
            stmt.setString(25, valueObject.getLF_NUMRUNT());
            stmt.setString(26, valueObject.getLF_IDSOLICRUNT());
            stmt.setString(27, valueObject.getLF_FECHARADICARUNT());
            stmt.setString(28, valueObject.getLF_IDSOLICITANTE());
            stmt.setString(29, valueObject.getLF_EMPERSOL());
            stmt.setString(30, valueObject.getLF_IDAPODERADO());
            stmt.setString(31, valueObject.getLF_TOTALFACTURARUNT());
            stmt.setString(32, valueObject.getCARGADO());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount != 1) {
                //System.out.println("PrimaryKey Error when updating DB!");
                throw new SQLException("PrimaryKey Error when updating DB!");
            }

        } finally {
            if (stmt != null)
                stmt.close();
        }


    }


    public synchronized void createSimple(Connection conn, Factura valueObject, String motor) throws SQLException {

        String sql = "";
        PreparedStatement stmt = null;
        ResultSet result = null;

        try {
            sql =
    "INSERT INTO L_FACTURAS ( LF_ID, LF_TIPO, LF_V_ID, " + "LF_ID_PERSONA, LF_ESTADO, LF_FECHA, " + "LF_FECHA_PAGO, LF_FECHA_TRAMITE, LF_TOTAL, " +
    "LF_NOTA, LF_ID_USUARIO, LF_ID_ARQUEO, " + "LF_ID_USUARIOANULA, LF_FECHAANULA, LF_HORAANULA, " +
    "LF_MOTIVOCANCELACION, LF_FACTURAERROR, LF_NUMERO, " + "LF_DESCUENTO, LF_NOTAADICIONAL, LF_SIREVNUMERO, " +
    "LF_SIREVVALOR, LF_IDRADICADO, LF_IDDETCITA, " + "LF_NUMRUNT, LF_IDSOLICRUNT, LF_FECHARADICARUNT, " +
    "LF_IDSOLICITANTE, LF_EMPERSOL, LF_IDAPODERADO, " +
    "LF_TOTALFACTURARUNT, CARGADO, COMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,'T') ";
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, valueObject.getLF_ID());
            stmt.setString(2, valueObject.getLF_TIPO());
            stmt.setString(3, valueObject.getLF_V_ID());
            stmt.setString(4, valueObject.getLF_ID_PERSONA());
            stmt.setString(5, valueObject.getLF_ESTADO());

            if (motor.equals("FIREBIRD"))
                stmt.setString(6, valueObject.getLF_FECHA());
            else if (motor.equals("ORACLE")) {
                java.util.Date ahorautil = new java.util.Date();
                Timestamp t = new Timestamp(ahorautil.getTime());
                stmt.setTimestamp(6, t);
            }

            stmt.setString(7, valueObject.getLF_FECHA_PAGO());
            stmt.setString(8, valueObject.getLF_FECHA_TRAMITE());
            stmt.setString(9, valueObject.getLF_TOTAL());
            stmt.setString(10, valueObject.getLF_NOTA());
            stmt.setString(11, valueObject.getLF_ID_USUARIO());
            stmt.setString(12, valueObject.getLF_ID_ARQUEO());
            stmt.setString(13, valueObject.getLF_ID_USUARIOANULA());
            stmt.setString(14, valueObject.getLF_FECHAANULA());

            //stmt.setString(15, valueObject.getLF_HORAANULA());
            if (Funciones.esTime(valueObject.getLF_HORAANULA()))
                stmt.setTime(15, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getLF_HORAANULA())));
            else
                stmt.setNull(15, Types.TIME);

            stmt.setString(16, valueObject.getLF_MOTIVOCANCELACION());
            stmt.setString(17, valueObject.getLF_FACTURAERROR());
            stmt.setString(18, valueObject.getLF_NUMERO());
            stmt.setString(19, valueObject.getLF_DESCUENTO());
            stmt.setString(20, valueObject.getLF_NOTAADICIONAL());
            stmt.setString(21, valueObject.getLF_SIREVNUMERO());
            stmt.setString(22, valueObject.getLF_SIREVVALOR());
            stmt.setString(23, valueObject.getLF_IDRADICADO());
            stmt.setString(24, valueObject.getLF_IDDETCITA());
            stmt.setString(25, valueObject.getLF_NUMRUNT());
            stmt.setString(26, valueObject.getLF_IDSOLICRUNT());
            stmt.setString(27, valueObject.getLF_FECHARADICARUNT());
            stmt.setString(28, valueObject.getLF_IDSOLICITANTE());
            stmt.setString(29, valueObject.getLF_EMPERSOL());
            stmt.setString(30, valueObject.getLF_IDAPODERADO());
            stmt.setString(31, valueObject.getLF_TOTALFACTURARUNT());
            stmt.setString(32, valueObject.getCARGADO());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount != 1) {
                //System.out.println("PrimaryKey Error when updating DB!");
                throw new SQLException("PrimaryKey Error when updating DB!");
            }

        } finally {
            if (stmt != null)
                stmt.close();
        }


    }


    public synchronized void createTemp(Connection conn, Factura valueObject, String motor) throws SQLException {

        String sql = "";
        PreparedStatement stmt = null;
        ResultSet result = null;

        try {
            sql =
    "INSERT INTO L_FACTURASTEMP ( LF_ID, LF_TIPO, LF_V_ID, " + "LF_ID_PERSONA, LF_ESTADO, LF_FECHA, " + "LF_FECHA_PAGO, LF_FECHA_TRAMITE, LF_TOTAL, " +
    "LF_NOTA, LF_ID_USUARIO, LF_ID_ARQUEO, " + "LF_ID_USUARIOANULA, LF_FECHAANULA, LF_HORAANULA, " +
    "LF_MOTIVOCANCELACION, LF_FACTURAERROR, LF_NUMERO, " + "LF_DESCUENTO, LF_NOTAADICIONAL, LF_SIREVNUMERO, " +
    "LF_SIREVVALOR, LF_IDRADICADO, LF_IDDETCITA, " + "LF_NUMRUNT, LF_IDSOLICRUNT, LF_FECHARADICARUNT, " +
    "LF_IDSOLICITANTE, LF_EMPERSOL, LF_IDAPODERADO, " +
    "LF_TOTALFACTURARUNT, CARGADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, valueObject.getLF_ID());
            stmt.setString(2, valueObject.getLF_TIPO());
            stmt.setString(3, valueObject.getLF_V_ID());
            stmt.setString(4, valueObject.getLF_ID_PERSONA());
            stmt.setString(5, valueObject.getLF_ESTADO());

            if (motor.equals("FIREBIRD"))
                stmt.setString(6, valueObject.getLF_FECHA());
            else if (motor.equals("ORACLE")) {
                java.util.Date ahorautil = new java.util.Date();
                Timestamp t = new Timestamp(ahorautil.getTime());
                stmt.setTimestamp(6, t);
            }

            stmt.setString(7, valueObject.getLF_FECHA_PAGO());
            stmt.setString(8, valueObject.getLF_FECHA_TRAMITE());
            stmt.setString(9, valueObject.getLF_TOTAL());
            stmt.setString(10, valueObject.getLF_NOTA());
            stmt.setString(11, valueObject.getLF_ID_USUARIO());
            stmt.setString(12, valueObject.getLF_ID_ARQUEO());
            stmt.setString(13, valueObject.getLF_ID_USUARIOANULA());
            stmt.setString(14, valueObject.getLF_FECHAANULA());

            //stmt.setString(15, valueObject.getLF_HORAANULA());
            if (Funciones.esTime(valueObject.getLF_HORAANULA()))
                stmt.setTime(15, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getLF_HORAANULA())));
            else
                stmt.setNull(15, Types.TIME);

            stmt.setString(16, valueObject.getLF_MOTIVOCANCELACION());
            stmt.setString(17, valueObject.getLF_FACTURAERROR());
            stmt.setString(18, valueObject.getLF_NUMERO());
            stmt.setString(19, valueObject.getLF_DESCUENTO());
            stmt.setString(20, valueObject.getLF_NOTAADICIONAL());
            stmt.setString(21, valueObject.getLF_SIREVNUMERO());
            stmt.setString(22, valueObject.getLF_SIREVVALOR());
            stmt.setString(23, valueObject.getLF_IDRADICADO());
            stmt.setString(24, valueObject.getLF_IDDETCITA());
            stmt.setString(25, valueObject.getLF_NUMRUNT());
            stmt.setString(26, valueObject.getLF_IDSOLICRUNT());
            stmt.setString(27, valueObject.getLF_FECHARADICARUNT());
            stmt.setString(28, valueObject.getLF_IDSOLICITANTE());
            stmt.setString(29, valueObject.getLF_EMPERSOL());
            stmt.setString(30, valueObject.getLF_IDAPODERADO());
            stmt.setString(31, valueObject.getLF_TOTALFACTURARUNT());
            stmt.setString(32, valueObject.getCARGADO());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount != 1) {
                //System.out.println("PrimaryKey Error when updating DB!");
                throw new SQLException("PrimaryKey Error when updating DB!");
            }

        } finally {
            if (stmt != null)
                stmt.close();
        }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, Factura valueObject) throws NotFoundException, SQLException {

        String sql =
            "UPDATE L_FACTURAS SET LF_TIPO = ?, LF_V_ID = ?, LF_ID_PERSONA = ?, " + "LF_ESTADO = ?, LF_FECHA = ?, LF_FECHA_PAGO = ?, " +
            "LF_FECHA_TRAMITE = ?, LF_TOTAL = ?, LF_NOTA = ?, " +
            "LF_ID_USUARIO = ?, LF_ID_ARQUEO = ?, LF_ID_USUARIOANULA = ?, " +
            "LF_FECHAANULA = ?, LF_HORAANULA = ?, LF_MOTIVOCANCELACION = ?, " +
            "LF_FACTURAERROR = ?, LF_NUMERO = ?, LF_DESCUENTO = ?, " +
            "LF_NOTAADICIONAL = ?, LF_SIREVNUMERO = ?, LF_SIREVVALOR = ?, " +
            "LF_IDRADICADO = ?, LF_IDDETCITA = ?, LF_NUMRUNT = ?, " +
            "LF_IDSOLICRUNT = ?, LF_FECHARADICARUNT = ?, LF_IDSOLICITANTE = ?, " +
            "LF_EMPERSOL = ?, LF_IDAPODERADO = ?, LF_TOTALFACTURARUNT = ?, " + "CARGADO = ? WHERE (LF_ID = ? ) ";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, valueObject.getLF_TIPO());
            stmt.setString(2, valueObject.getLF_V_ID());
            stmt.setString(3, valueObject.getLF_ID_PERSONA());
            stmt.setString(4, valueObject.getLF_ESTADO());
            stmt.setString(5, valueObject.getLF_FECHA());
            stmt.setString(6, valueObject.getLF_FECHA_PAGO());
            stmt.setString(7, valueObject.getLF_FECHA_TRAMITE());
            stmt.setString(8, valueObject.getLF_TOTAL());
            stmt.setString(9, valueObject.getLF_NOTA());
            stmt.setString(10, valueObject.getLF_ID_USUARIO());
            stmt.setString(11, valueObject.getLF_ID_ARQUEO());
            stmt.setString(12, valueObject.getLF_ID_USUARIOANULA());
            stmt.setString(13, valueObject.getLF_FECHAANULA());

            //stmt.setString(14, valueObject.getLF_HORAANULA());
            if (Funciones.esTime(valueObject.getLF_HORAANULA()))
                stmt.setTime(15, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getLF_HORAANULA())));
            else
                stmt.setNull(15, Types.TIME);

            stmt.setString(15, valueObject.getLF_MOTIVOCANCELACION());
            stmt.setString(16, valueObject.getLF_FACTURAERROR());
            stmt.setString(17, valueObject.getLF_NUMERO());
            stmt.setString(18, valueObject.getLF_DESCUENTO());
            stmt.setString(19, valueObject.getLF_NOTAADICIONAL());
            stmt.setString(20, valueObject.getLF_SIREVNUMERO());
            stmt.setString(21, valueObject.getLF_SIREVVALOR());
            stmt.setString(22, valueObject.getLF_IDRADICADO());
            stmt.setString(23, valueObject.getLF_IDDETCITA());
            stmt.setString(24, valueObject.getLF_NUMRUNT());
            stmt.setString(25, valueObject.getLF_IDSOLICRUNT());
            stmt.setString(26, valueObject.getLF_FECHARADICARUNT());
            stmt.setString(27, valueObject.getLF_IDSOLICITANTE());
            stmt.setString(28, valueObject.getLF_EMPERSOL());
            stmt.setString(29, valueObject.getLF_IDAPODERADO());
            stmt.setString(30, valueObject.getLF_TOTALFACTURARUNT());
            stmt.setString(31, valueObject.getCARGADO());

            stmt.setInt(32, valueObject.getLF_ID());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount == 0) {
                //System.out.println("Object could not be saved! (PrimaryKey not found)");
                throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
            }
            if (rowcount > 1) {
                //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
            }
        } finally {
            if (stmt != null)
                stmt.close();
        }
    }

    public void saveEstadoPagado(Connection conn, Factura valueObject) throws NotFoundException, SQLException {

        String sql =
            "UPDATE L_FACTURAS SET LF_ESTADO = 2 " +
            "WHERE (LF_ID = ? ) ";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, valueObject.getLF_ID());

            databaseUpdate(conn, stmt);
            
        } finally {
            if (stmt != null)
                stmt.close();
        }
    }
    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not
     * be restored by calling save. Restoring can only be done using create method but if
     * database is using automatic surrogate-keys, the resulting object will have different
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, Factura valueObject) throws NotFoundException, SQLException {

        String sql = "DELETE FROM L_FACTURAS WHERE (LF_ID = ? ) ";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, valueObject.getLF_ID());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount == 0) {
                //System.out.println("Object could not be deleted (PrimaryKey not found)");
                throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
            }
            if (rowcount > 1) {
                //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
            }
        } finally {
            if (stmt != null)
                stmt.close();
        }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be
     * restored by calling save. Restoring can only be done using create method but if database
     * is using automatic surrogate-keys, the resulting object will have different primary-key
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

        String sql = "DELETE FROM L_FACTURAS";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            int rowcount = databaseUpdate(conn, stmt);
        } finally {
            if (stmt != null)
                stmt.close();
        }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

        String sql = "SELECT count(*) FROM L_FACTURAS";
        PreparedStatement stmt = null;
        ResultSet result = null;
        int allRows = 0;

        try {
            stmt = conn.prepareStatement(sql);
            result = stmt.executeQuery();

            if (result.next())
                allRows = result.getInt(1);
        } finally {
            if (result != null)
                result.close();
            if (stmt != null)
                stmt.close();
        }
        return allRows;
    }


    /**
     * searchMatching-Method. This method provides searching capability to
     * get matching valueObjects from database. It works by searching all
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List,
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, Factura valueObject) throws SQLException {

        List searchResults;

        boolean first = true;
        StringBuffer sql = new StringBuffer("SELECT * FROM L_FACTURAS WHERE 1=1 ");

        if (valueObject.getLF_ID() != 0) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ID = ").append(valueObject.getLF_ID()).append(" ");
        }

        if (valueObject.getLF_TIPO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_TIPO = '").append(valueObject.getLF_TIPO()).append("' ");
        }

        if (valueObject.getLF_V_ID() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_V_ID = '").append(valueObject.getLF_V_ID()).append("' ");
        }

        if (valueObject.getLF_ID_PERSONA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ID_PERSONA = '").append(valueObject.getLF_ID_PERSONA()).append("' ");
        }

        if (valueObject.getLF_ESTADO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ESTADO = '").append(valueObject.getLF_ESTADO()).append("' ");
        }

        if (valueObject.getLF_FECHA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FECHA = '").append(valueObject.getLF_FECHA()).append("' ");
        }

        if (valueObject.getLF_FECHA_PAGO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FECHA_PAGO = '").append(valueObject.getLF_FECHA_PAGO()).append("' ");
        }

        if (valueObject.getLF_FECHA_TRAMITE() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FECHA_TRAMITE = '").append(valueObject.getLF_FECHA_TRAMITE()).append("' ");
        }

        if (valueObject.getLF_TOTAL() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_TOTAL = '").append(valueObject.getLF_TOTAL()).append("' ");
        }

        if (valueObject.getLF_NOTA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_NOTA = '").append(valueObject.getLF_NOTA()).append("' ");
        }

        if (valueObject.getLF_ID_USUARIO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ID_USUARIO = '").append(valueObject.getLF_ID_USUARIO()).append("' ");
        }

        if (valueObject.getLF_ID_ARQUEO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ID_ARQUEO = '").append(valueObject.getLF_ID_ARQUEO()).append("' ");
        }

        if (valueObject.getLF_ID_USUARIOANULA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_ID_USUARIOANULA = '").append(valueObject.getLF_ID_USUARIOANULA()).append("' ");
        }

        if (valueObject.getLF_FECHAANULA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FECHAANULA = '").append(valueObject.getLF_FECHAANULA()).append("' ");
        }

        if (valueObject.getLF_HORAANULA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_HORAANULA = '").append(valueObject.getLF_HORAANULA()).append("' ");
        }

        if (valueObject.getLF_MOTIVOCANCELACION() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_MOTIVOCANCELACION = '").append(valueObject.getLF_MOTIVOCANCELACION()).append("' ");
        }

        if (valueObject.getLF_FACTURAERROR() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FACTURAERROR = '").append(valueObject.getLF_FACTURAERROR()).append("' ");
        }

        if (valueObject.getLF_NUMERO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_NUMERO = '").append(valueObject.getLF_NUMERO()).append("' ");
        }

        if (valueObject.getLF_DESCUENTO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_DESCUENTO = '").append(valueObject.getLF_DESCUENTO()).append("' ");
        }

        if (valueObject.getLF_NOTAADICIONAL() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_NOTAADICIONAL = '").append(valueObject.getLF_NOTAADICIONAL()).append("' ");
        }

        if (valueObject.getLF_SIREVNUMERO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_SIREVNUMERO = '").append(valueObject.getLF_SIREVNUMERO()).append("' ");
        }

        if (valueObject.getLF_SIREVVALOR() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_SIREVVALOR = '").append(valueObject.getLF_SIREVVALOR()).append("' ");
        }

        if (valueObject.getLF_IDRADICADO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_IDRADICADO = '").append(valueObject.getLF_IDRADICADO()).append("' ");
        }

        if (valueObject.getLF_IDDETCITA() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_IDDETCITA = '").append(valueObject.getLF_IDDETCITA()).append("' ");
        }

        if (valueObject.getLF_NUMRUNT() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_NUMRUNT = '").append(valueObject.getLF_NUMRUNT()).append("' ");
        }

        if (valueObject.getLF_IDSOLICRUNT() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_IDSOLICRUNT = '").append(valueObject.getLF_IDSOLICRUNT()).append("' ");
        }

        if (valueObject.getLF_FECHARADICARUNT() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_FECHARADICARUNT = '").append(valueObject.getLF_FECHARADICARUNT()).append("' ");
        }

        if (valueObject.getLF_IDSOLICITANTE() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_IDSOLICITANTE = '").append(valueObject.getLF_IDSOLICITANTE()).append("' ");
        }

        if (valueObject.getLF_EMPERSOL() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_EMPERSOL = '").append(valueObject.getLF_EMPERSOL()).append("' ");
        }

        if (valueObject.getLF_IDAPODERADO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_IDAPODERADO = '").append(valueObject.getLF_IDAPODERADO()).append("' ");
        }

        if (valueObject.getLF_TOTALFACTURARUNT() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND LF_TOTALFACTURARUNT = '").append(valueObject.getLF_TOTALFACTURARUNT()).append("' ");
        }

        if (valueObject.getCARGADO() != null) {
            if (first) {
                first = false;
            }
            sql.append("AND CARGADO = '").append(valueObject.getCARGADO()).append("' ");
        }


        sql.append("ORDER BY LF_ID ASC ");

        System.out.println(sql);

        // Prevent accidential full table results.
        // Use loadAll if all rows must be returned.
        if (first)
            searchResults = new ArrayList();
        else
            searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

        return searchResults;
    }


    /**
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

        int result = stmt.executeUpdate();

        return result;
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, Factura valueObject) throws NotFoundException,
                                                                                                    SQLException {

        ResultSet result = null;

        try {
            result = stmt.executeQuery();

            if (result.next()) {

                valueObject.setLF_ID(result.getInt("LF_ID"));
                valueObject.setLF_TIPO(result.getString("LF_TIPO"));
                valueObject.setLF_V_ID(result.getString("LF_V_ID"));
                valueObject.setLF_ID_PERSONA(result.getString("LF_ID_PERSONA"));
                valueObject.setLF_ESTADO(result.getString("LF_ESTADO"));
                valueObject.setLF_FECHA(result.getString("LF_FECHA"));
                valueObject.setLF_FECHA_PAGO(result.getString("LF_FECHA_PAGO"));
                valueObject.setLF_FECHA_TRAMITE(result.getString("LF_FECHA_TRAMITE"));
                valueObject.setLF_TOTAL(result.getString("LF_TOTAL"));
                valueObject.setLF_NOTA(result.getString("LF_NOTA"));
                valueObject.setLF_ID_USUARIO(result.getString("LF_ID_USUARIO"));
                valueObject.setLF_ID_ARQUEO(result.getString("LF_ID_ARQUEO"));
                valueObject.setLF_ID_USUARIOANULA(result.getString("LF_ID_USUARIOANULA"));
                valueObject.setLF_FECHAANULA(result.getString("LF_FECHAANULA"));
                valueObject.setLF_HORAANULA(result.getString("LF_HORAANULA"));
                valueObject.setLF_MOTIVOCANCELACION(result.getString("LF_MOTIVOCANCELACION"));
                valueObject.setLF_FACTURAERROR(result.getString("LF_FACTURAERROR"));
                valueObject.setLF_NUMERO(result.getString("LF_NUMERO"));
                valueObject.setLF_DESCUENTO(result.getString("LF_DESCUENTO"));
                valueObject.setLF_NOTAADICIONAL(result.getString("LF_NOTAADICIONAL"));
                valueObject.setLF_SIREVNUMERO(result.getString("LF_SIREVNUMERO"));
                valueObject.setLF_SIREVVALOR(result.getString("LF_SIREVVALOR"));
                valueObject.setLF_IDRADICADO(result.getString("LF_IDRADICADO"));
                valueObject.setLF_IDDETCITA(result.getString("LF_IDDETCITA"));
                valueObject.setLF_NUMRUNT(result.getString("LF_NUMRUNT"));
                valueObject.setLF_IDSOLICRUNT(result.getString("LF_IDSOLICRUNT"));
                valueObject.setLF_FECHARADICARUNT(result.getString("LF_FECHARADICARUNT"));
                valueObject.setLF_IDSOLICITANTE(result.getString("LF_IDSOLICITANTE"));
                valueObject.setLF_EMPERSOL(result.getString("LF_EMPERSOL"));
                valueObject.setLF_IDAPODERADO(result.getString("LF_IDAPODERADO"));
                valueObject.setLF_TOTALFACTURARUNT(result.getString("LF_TOTALFACTURARUNT"));
                valueObject.setCARGADO(result.getString("CARGADO"));

            } else {
                //System.out.println("Factura Object Not Found!");
                throw new NotFoundException("Factura Object Not Found!");
            }
        } finally {
            if (result != null)
                result.close();
            if (stmt != null)
                stmt.close();
        }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

        ArrayList searchResults = new ArrayList();
        ResultSet result = null;

        try {
            result = stmt.executeQuery();
            byte[] bdata = null;
            String text = "";
            Blob blob = null;
            while (result.next()) {
                Factura temp = createValueObject();

                temp.setLF_ID(result.getInt("LF_ID"));
                temp.setLF_TIPO(result.getString("LF_TIPO"));
                temp.setLF_V_ID(result.getString("LF_V_ID"));
                temp.setLF_ID_PERSONA(result.getString("LF_ID_PERSONA"));
                temp.setLF_ESTADO(result.getString("LF_ESTADO"));
                temp.setLF_FECHA(result.getString("LF_FECHA"));
                temp.setLF_FECHA_PAGO(result.getString("LF_FECHA_PAGO"));
                temp.setLF_FECHA_TRAMITE(result.getString("LF_FECHA_TRAMITE"));
                temp.setLF_TOTAL(result.getString("LF_TOTAL"));

                temp.setLF_NOTA(result.getString("LF_NOTA"));

                temp.setLF_ID_USUARIO(result.getString("LF_ID_USUARIO"));
                temp.setLF_ID_ARQUEO(result.getString("LF_ID_ARQUEO"));
                temp.setLF_ID_USUARIOANULA(result.getString("LF_ID_USUARIOANULA"));
                temp.setLF_FECHAANULA(result.getString("LF_FECHAANULA"));
                temp.setLF_HORAANULA(result.getString("LF_HORAANULA"));
                temp.setLF_MOTIVOCANCELACION(result.getString("LF_MOTIVOCANCELACION"));
                temp.setLF_FACTURAERROR(result.getString("LF_FACTURAERROR"));
                temp.setLF_NUMERO(result.getString("LF_NUMERO"));
                temp.setLF_DESCUENTO(result.getString("LF_DESCUENTO"));
                //temp.setLF_NOTAADICIONAL(result.getString("LF_NOTAADICIONAL"));//BLOB
                temp.setLF_SIREVNUMERO(result.getString("LF_SIREVNUMERO"));
                temp.setLF_SIREVVALOR(result.getString("LF_SIREVVALOR"));
                temp.setLF_IDRADICADO(result.getString("LF_IDRADICADO"));
                temp.setLF_IDDETCITA(result.getString("LF_IDDETCITA"));
                temp.setLF_NUMRUNT(result.getString("LF_NUMRUNT"));
                temp.setLF_IDSOLICRUNT(result.getString("LF_IDSOLICRUNT"));
                temp.setLF_FECHARADICARUNT(result.getString("LF_FECHARADICARUNT"));
                temp.setLF_IDSOLICITANTE(result.getString("LF_IDSOLICITANTE"));
                temp.setLF_EMPERSOL(result.getString("LF_EMPERSOL"));
                temp.setLF_IDAPODERADO(result.getString("LF_IDAPODERADO"));
                temp.setLF_TOTALFACTURARUNT(result.getString("LF_TOTALFACTURARUNT"));
                temp.setCARGADO(result.getString("CARGADO"));

                searchResults.add(temp);
            }

        } finally {
            if (result != null)
                result.close();
            if (stmt != null)
                stmt.close();
        }

        return (List)searchResults;
    }

    public void saveNumeroFacturaRunt(Connection conn, Factura valueObject) throws NotFoundException, SQLException {

        String sql = "UPDATE L_FACTURAS SET LF_NUMRUNT = ?, LF_TOTALFACTURARUNT = ? WHERE (LF_ID = ? ) ";
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, valueObject.getLF_NUMRUNT());
            stmt.setString(2, valueObject.getLF_TOTALFACTURARUNT());

            stmt.setInt(3, valueObject.getLF_ID());

            int rowcount = databaseUpdate(conn, stmt);
            if (rowcount == 0) {
                //System.out.println("Object could not be saved! (PrimaryKey not found)");
                throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
            }
            if (rowcount > 1) {
                //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
            }
        } finally {
            if (stmt != null)
                stmt.close();
        }
    }

    public int getMaxId(Connection conn, String motor) throws SQLException {

        int allRows = 0;

        if (motor.equals("FIREBIRD")) {
            String sql = "SELECT GEN_ID(GEN_L_FACTURAS_LF_ID,1) FROM TRANSITO";
            PreparedStatement stmt = null;
            ResultSet result = null;
            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1) + 1;
            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }
        } else if (motor.equals("ORACLE")) {

            String sql = "SELECT GEN_L_FACTURAS_LF_ID.nextval FROM dual";
            PreparedStatement stmt = null;
            ResultSet result = null;
            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1) + 1;
            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }
        }

        return allRows;
    }

    public int getMaxIdTemp(Connection conn, String motor) throws SQLException {

        int allRows = 0;

        if (motor.equals("FIREBIRD")) {
            String sql = "SELECT GEN_ID(GEN_L_FACTURASTEMP_LF_ID,1) FROM TRANSITO";
            PreparedStatement stmt = null;
            ResultSet result = null;
            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1) + 1;
            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }
        } else if (motor.equals("ORACLE")) {

            String sql = "SELECT GEN_L_FACTURASTEMP_LF_ID.nextval FROM dual";
            PreparedStatement stmt = null;
            ResultSet result = null;
            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1) + 1;
            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }
        }

        return allRows;
    }

    public int getNuevoFacturaId(Connection conn, String motor) throws SQLException {

        String sql = "";

        System.out.println("getNuevoFacturaId DAO =" + motor);

        if (motor.equals("FIREBIRD"))
            sql = "SELECT GEN_ID(gen_facturas_simple,1) FROM transito";
        else if (motor.equals("ORACLE"))
            sql = "SELECT GEN_FACTURAS_SIMPLE.nextval from dual";

        PreparedStatement stmt = null;
        ResultSet result = null;
        int allRows = 0;
        try {
            stmt = conn.prepareStatement(sql);
            result = stmt.executeQuery();

            if (result.next())
                allRows = result.getInt(1);
        } catch (Exception exp) {

            exp.printStackTrace();

        } finally {
            if (result != null)
                result.close();
            if (stmt != null)
                stmt.close();
        }
        return allRows;
    }

    public int getNuevoFacturaTempId(Connection conn, String motor) throws SQLException {

        String sql = "";

        System.out.println("getNuevoFacturaId DAO =" + motor);

        if (motor.equals("FIREBIRD"))
            sql = "SELECT GEN_ID(gen_facturasTemp_simple,1) FROM transito";
        else if (motor.equals("ORACLE"))
            sql = "SELECT GEN_FACTURASTEMP_SIMPLE.nextval from dual";

        PreparedStatement stmt = null;
        ResultSet result = null;
        int allRows = 0;
        try {
            stmt = conn.prepareStatement(sql);
            result = stmt.executeQuery();

            if (result.next())
                allRows = result.getInt(1);
        } catch (Exception exp) {

            exp.printStackTrace();

        } finally {
            if (result != null)
                result.close();
            if (stmt != null)
                stmt.close();
        }
        return allRows;
    }

    public int consultarNuevoFacturaId(Connection conn, String motor) throws SQLException {

        String sql = "";
        int allRows = 0;

        System.out.println("consultarNuevoFacturaId motor =" + motor);

        if (motor.equals("FIREBIRD")) {
            sql = "SELECT GEN_ID(gen_facturas_simple,0) FROM transito";

            PreparedStatement stmt = null;
            ResultSet result = null;

            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1);
            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }


        } else if (motor.equals("ORACLE")) {


            sql = "SELECT GEN_FACTURAS_SIMPLE.nextval from dual";

            PreparedStatement stmt = null;
            ResultSet result = null;

            try {
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                if (result.next())
                    allRows = result.getInt(1);

                sql = "ALTER SEQUENCE GEN_FACTURAS_SIMPLE INCREMENT BY -1";
                stmt = conn.prepareStatement(sql);
                databaseUpdate(conn, stmt);

                sql = "SELECT GEN_FACTURAS_SIMPLE.nextval from dual";
                stmt = conn.prepareStatement(sql);
                result = stmt.executeQuery();

                sql = "ALTER SEQUENCE GEN_FACTURAS_SIMPLE INCREMENT BY 1";
                stmt = conn.prepareStatement(sql);
                databaseUpdate(conn, stmt);

            } finally {
                if (result != null)
                    result.close();
                if (stmt != null)
                    stmt.close();
            }


        }

        return allRows;
    }


    public void actualizarNuevoFacturaId(Connection conn, int valor, String motor) throws SQLException {

        if (motor.equals("FIREBIRD")) {
            String sql = "set generator gen_facturas_simple to " + String.valueOf(valor);
            PreparedStatement stmt = null;

            stmt = conn.prepareStatement(sql);
            databaseUpdate(conn, stmt);
        } else if (motor.equals("ORACLE")) {

            PreparedStatement stmt = null;

            String sql = "DROP SEQUENCE GEN_FACTURAS_SIMPLE ";
            stmt = conn.prepareStatement(sql);
            databaseUpdate(conn, stmt);

            sql =
"CREATE SEQUENCE GEN_FACTURAS_SIMPLE start with " + String.valueOf(valor - 1) + " increment by 1  minvalue 1 ";
            stmt = conn.prepareStatement(sql);
            databaseUpdate(conn, stmt);

            ResultSet result;
            sql = "SELECT GEN_FACTURAS_SIMPLE.nextval FROM dual ";
            stmt = conn.prepareStatement(sql);
            result = stmt.executeQuery();


        }


    }


    public int editarNotaFactura(Connection conn, String lf_numero, String lf_nota) throws SQLException {

        String sql = "update l_facturas\n" +
            "set l_facturas.lf_nota = '" + lf_nota + "'\n" +
            "where lf_numero = '" + lf_numero + "';";
        PreparedStatement stmt = null;
        //ResultSet result = null;
        int allRows = 0;
        try {
            stmt = conn.prepareStatement(sql);
            allRows = databaseUpdate(conn, stmt);
            //result = stmt.executeQuery();

            //if (result.next())
            //    allRows = result.getInt(1) + 1;
        } finally {
            //if (result != null)
            //    result.close();
            if (stmt != null)
                stmt.close();
        }
        return allRows;
    }

}

