package modelo.datos.objetos.comparendos.documentos.digitales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

/**
  * ElementoDigitalComp Value Object.
  * This class is value object representing database table ElementoDigitalComp
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ElementoDigitalComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_ELEMENTODIGITAL;
    private String COD_ELEMENTODIGITAL;
    private String DESC_ELEMENTODIGITAL;
    private String NOMBREID_PRINCIPAL;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ElementoDigitalComp () {

    }

    public ElementoDigitalComp (int ID_ELEMENTODIGITALIn) {

          this.ID_ELEMENTODIGITAL = ID_ELEMENTODIGITALIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_ELEMENTODIGITAL() {
          return this.ID_ELEMENTODIGITAL;
    }
    public void setID_ELEMENTODIGITAL(int ID_ELEMENTODIGITALIn) {
          this.ID_ELEMENTODIGITAL = ID_ELEMENTODIGITALIn;
    }

    public String getCOD_ELEMENTODIGITAL() {
          return this.COD_ELEMENTODIGITAL;
    }
    public void setCOD_ELEMENTODIGITAL(String COD_ELEMENTODIGITALIn) {
          this.COD_ELEMENTODIGITAL = COD_ELEMENTODIGITALIn;
    }

    public String getDESC_ELEMENTODIGITAL() {
          return this.DESC_ELEMENTODIGITAL;
    }
    public void setDESC_ELEMENTODIGITAL(String DESC_ELEMENTODIGITALIn) {
          this.DESC_ELEMENTODIGITAL = DESC_ELEMENTODIGITALIn;
    }

    public String getNOMBREID_PRINCIPAL() {
          return this.NOMBREID_PRINCIPAL;
    }
    public void setNOMBREID_PRINCIPAL(String NOMBREID_PRINCIPALIn) {
          this.NOMBREID_PRINCIPAL = NOMBREID_PRINCIPALIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_ELEMENTODIGITALIn,
          String COD_ELEMENTODIGITALIn,
          String DESC_ELEMENTODIGITALIn,
          String NOMBREID_PRINCIPALIn) {
          this.ID_ELEMENTODIGITAL = ID_ELEMENTODIGITALIn;
          this.COD_ELEMENTODIGITAL = COD_ELEMENTODIGITALIn;
          this.DESC_ELEMENTODIGITAL = DESC_ELEMENTODIGITALIn;
          this.NOMBREID_PRINCIPAL = NOMBREID_PRINCIPALIn;
    }


    /** 
     * hasEqualMapping-method will compare two ElementoDigitalComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ElementoDigitalComp valueObject) {

          if (valueObject.getID_ELEMENTODIGITAL() != this.ID_ELEMENTODIGITAL) {
                    return(false);
          }
          if (this.COD_ELEMENTODIGITAL == null) {
                    if (valueObject.getCOD_ELEMENTODIGITAL() != null)
                           return(false);
          } else if (!this.COD_ELEMENTODIGITAL.equals(valueObject.getCOD_ELEMENTODIGITAL())) {
                    return(false);
          }
          if (this.DESC_ELEMENTODIGITAL == null) {
                    if (valueObject.getDESC_ELEMENTODIGITAL() != null)
                           return(false);
          } else if (!this.DESC_ELEMENTODIGITAL.equals(valueObject.getDESC_ELEMENTODIGITAL())) {
                    return(false);
          }
          if (this.NOMBREID_PRINCIPAL == null) {
                    if (valueObject.getNOMBREID_PRINCIPAL() != null)
                           return(false);
          } else if (!this.NOMBREID_PRINCIPAL.equals(valueObject.getNOMBREID_PRINCIPAL())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ElementoDigitalComp, mapping to table ElementoDigitalComp\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_ELEMENTODIGITAL = " + this.ID_ELEMENTODIGITAL + "\n"); 
        out.append("COD_ELEMENTODIGITAL = " + this.COD_ELEMENTODIGITAL + "\n"); 
        out.append("DESC_ELEMENTODIGITAL = " + this.DESC_ELEMENTODIGITAL + "\n"); 
        out.append("NOMBREID_PRINCIPAL = " + this.NOMBREID_PRINCIPAL + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ElementoDigitalComp cloned = new ElementoDigitalComp();

        cloned.setID_ELEMENTODIGITAL(this.ID_ELEMENTODIGITAL); 
        if (this.COD_ELEMENTODIGITAL != null)
             cloned.setCOD_ELEMENTODIGITAL(new String(this.COD_ELEMENTODIGITAL)); 
        if (this.DESC_ELEMENTODIGITAL != null)
             cloned.setDESC_ELEMENTODIGITAL(new String(this.DESC_ELEMENTODIGITAL)); 
        if (this.NOMBREID_PRINCIPAL != null)
             cloned.setNOMBREID_PRINCIPAL(new String(this.NOMBREID_PRINCIPAL)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

