package modelo.datos.objetos.comparendos.documentos.digitales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;


/**
  * ElementoDigitalIndiceComp Value Object.
  * This class is value object representing database table ElementoDigitalIndiceComp
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ElementoDigitalIndiceComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDELEMENTO_INDICE;
    private int ID_ELEMENTODIGITAL;
    private int ID_INDICE;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ElementoDigitalIndiceComp () {

    }

    public ElementoDigitalIndiceComp (int IDELEMENTO_INDICEIn) {

          this.IDELEMENTO_INDICE = IDELEMENTO_INDICEIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDELEMENTO_INDICE() {
          return this.IDELEMENTO_INDICE;
    }
    public void setIDELEMENTO_INDICE(int IDELEMENTO_INDICEIn) {
          this.IDELEMENTO_INDICE = IDELEMENTO_INDICEIn;
    }

    public int getID_ELEMENTODIGITAL() {
          return this.ID_ELEMENTODIGITAL;
    }
    public void setID_ELEMENTODIGITAL(int ID_ELEMENTODIGITALIn) {
          this.ID_ELEMENTODIGITAL = ID_ELEMENTODIGITALIn;
    }

    public int getID_INDICE() {
          return this.ID_INDICE;
    }
    public void setID_INDICE(int ID_INDICEIn) {
          this.ID_INDICE = ID_INDICEIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDELEMENTO_INDICEIn,
          int ID_ELEMENTODIGITALIn,
          int ID_INDICEIn) {
          this.IDELEMENTO_INDICE = IDELEMENTO_INDICEIn;
          this.ID_ELEMENTODIGITAL = ID_ELEMENTODIGITALIn;
          this.ID_INDICE = ID_INDICEIn;
    }


    /** 
     * hasEqualMapping-method will compare two ElementoDigitalIndiceComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ElementoDigitalIndiceComp valueObject) {

          if (valueObject.getIDELEMENTO_INDICE() != this.IDELEMENTO_INDICE) {
                    return(false);
          }
          if (valueObject.getID_ELEMENTODIGITAL() != this.ID_ELEMENTODIGITAL) {
                    return(false);
          }
          if (valueObject.getID_INDICE() != this.ID_INDICE) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ElementoDigitalIndiceComp, mapping to table ElementoDigitalIndiceComp\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDELEMENTO_INDICE = " + this.IDELEMENTO_INDICE + "\n"); 
        out.append("ID_ELEMENTODIGITAL = " + this.ID_ELEMENTODIGITAL + "\n"); 
        out.append("ID_INDICE = " + this.ID_INDICE + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ElementoDigitalIndiceComp cloned = new ElementoDigitalIndiceComp();

        cloned.setIDELEMENTO_INDICE(this.IDELEMENTO_INDICE); 
        cloned.setID_ELEMENTODIGITAL(this.ID_ELEMENTODIGITAL); 
        cloned.setID_INDICE(this.ID_INDICE); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

