package modelo.datos.objetos.comparendos.documentos.digitales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

/**
  * TipoDocumentoComp Value Object.
  * This class is value object representing database table TipoDocumentoComp
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TipoDocumentoComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_TIPODOCUMENTO;
    private String COD_TIPODOCUMENTO;
    private String DESC_TIPODOCUMENTO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TipoDocumentoComp () {

    }

    public TipoDocumentoComp (int ID_TIPODOCUMENTOIn) {

          this.ID_TIPODOCUMENTO = ID_TIPODOCUMENTOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_TIPODOCUMENTO() {
          return this.ID_TIPODOCUMENTO;
    }
    public void setID_TIPODOCUMENTO(int ID_TIPODOCUMENTOIn) {
          this.ID_TIPODOCUMENTO = ID_TIPODOCUMENTOIn;
    }

    public String getCOD_TIPODOCUMENTO() {
          return this.COD_TIPODOCUMENTO;
    }
    public void setCOD_TIPODOCUMENTO(String COD_TIPODOCUMENTOIn) {
          this.COD_TIPODOCUMENTO = COD_TIPODOCUMENTOIn;
    }

    public String getDESC_TIPODOCUMENTO() {
          return this.DESC_TIPODOCUMENTO;
    }
    public void setDESC_TIPODOCUMENTO(String DESC_TIPODOCUMENTOIn) {
          this.DESC_TIPODOCUMENTO = DESC_TIPODOCUMENTOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_TIPODOCUMENTOIn,
          String COD_TIPODOCUMENTOIn,
          String DESC_TIPODOCUMENTOIn) {
          this.ID_TIPODOCUMENTO = ID_TIPODOCUMENTOIn;
          this.COD_TIPODOCUMENTO = COD_TIPODOCUMENTOIn;
          this.DESC_TIPODOCUMENTO = DESC_TIPODOCUMENTOIn;
    }


    /** 
     * hasEqualMapping-method will compare two TipoDocumentoComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TipoDocumentoComp valueObject) {

          if (valueObject.getID_TIPODOCUMENTO() != this.ID_TIPODOCUMENTO) {
                    return(false);
          }
          if (this.COD_TIPODOCUMENTO == null) {
                    if (valueObject.getCOD_TIPODOCUMENTO() != null)
                           return(false);
          } else if (!this.COD_TIPODOCUMENTO.equals(valueObject.getCOD_TIPODOCUMENTO())) {
                    return(false);
          }
          if (this.DESC_TIPODOCUMENTO == null) {
                    if (valueObject.getDESC_TIPODOCUMENTO() != null)
                           return(false);
          } else if (!this.DESC_TIPODOCUMENTO.equals(valueObject.getDESC_TIPODOCUMENTO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TipoDocumentoComp, mapping to table TipoDocumentoComp\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_TIPODOCUMENTO = " + this.ID_TIPODOCUMENTO + "\n"); 
        out.append("COD_TIPODOCUMENTO = " + this.COD_TIPODOCUMENTO + "\n"); 
        out.append("DESC_TIPODOCUMENTO = " + this.DESC_TIPODOCUMENTO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TipoDocumentoComp cloned = new TipoDocumentoComp();

        cloned.setID_TIPODOCUMENTO(this.ID_TIPODOCUMENTO); 
        if (this.COD_TIPODOCUMENTO != null)
             cloned.setCOD_TIPODOCUMENTO(new String(this.COD_TIPODOCUMENTO)); 
        if (this.DESC_TIPODOCUMENTO != null)
             cloned.setDESC_TIPODOCUMENTO(new String(this.DESC_TIPODOCUMENTO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
