package modelo.datos.dao.resoluciones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.resoluciones.ViewResolucionesInfractorComp;

import utilidades.Funciones;


/**
  * ViewResolucionesInfractorComp Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve ViewResolucionesInfractorComp object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewResolucionesInfractorCompDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public ViewResolucionesInfractorComp createValueObject() {
          return new ViewResolucionesInfractorComp();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public ViewResolucionesInfractorComp getObject(Connection conn, int ID_RESOLUCION) throws NotFoundException, SQLException {

          ViewResolucionesInfractorComp valueObject = createValueObject();
          valueObject.setID_RESOLUCION(ID_RESOLUCION);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, ViewResolucionesInfractorComp valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM VIEW_RESOLUCIONESINFRACTOR WHERE (ID_RESOLUCION = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getID_RESOLUCION()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VIEW_RESOLUCIONESINFRACTOR ORDER BY ID_RESOLUCION ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VIEW_RESOLUCIONESINFRACTOR";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, ViewResolucionesInfractorComp valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_RESOLUCIONESINFRACTOR WHERE 1=1 ");

          if (valueObject.getID_RESOLUCION() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_RESOLUCION = ").append(valueObject.getID_RESOLUCION()).append(" ");
          }

          if (valueObject.getNUMERO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMERO = '").append(valueObject.getNUMERO()).append("' ");
          }

          if (valueObject.getFECHA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHA = '").append(valueObject.getFECHA()).append("' ");
          }

          if (valueObject.getCONTENIDO() != null) {
              if (first) { first = false; }
              sql.append("AND CONTENIDO = '").append(valueObject.getCONTENIDO()).append("' ");
          }

          if (valueObject.getNOMBRE() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRE = '").append(valueObject.getNOMBRE()).append("' ");
          }

          if (valueObject.getNROIDENTIFICACION() != null) {
              if (first) { first = false; }
              sql.append("AND NROIDENTIFICACION = '").append(valueObject.getNROIDENTIFICACION()).append("' ");
          }

          if (valueObject.getID_DOCTO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTO = ").append(valueObject.getID_DOCTO()).append(" ");
          }

          if (valueObject.getNOMBRES() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRES = '").append(valueObject.getNOMBRES()).append("' ");
          }

          if (valueObject.getAPELLIDOS() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDOS = '").append(valueObject.getAPELLIDOS()).append("' ");
          }

          if (valueObject.getDIRECCION() != null) {
              if (first) { first = false; }
              sql.append("AND DIRECCION = '").append(valueObject.getDIRECCION()).append("' ");
          }

          if (valueObject.getTELEFONO() != null) {
              if (first) { first = false; }
              sql.append("AND TELEFONO = '").append(valueObject.getTELEFONO()).append("' ");
          }
          
        if (valueObject.getID_TIPORESOLUCION() != 0) {
            if (first) { first = false; }
            sql.append("AND ID_TIPORESOLUCION = ").append(valueObject.getID_TIPORESOLUCION()).append(" ");
        }

          sql.append("ORDER BY ID_RESOLUCION ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }

    public List searchMatchingFiltro(Connection conn, ViewResolucionesInfractorComp valueObject, String fechaIni, String fechaFin) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_RESOLUCIONESINFRACTOR WHERE 1=1 ");

          if(fechaIni!=null && fechaFin!=null)
          {
                String filtroFechas = "AND (FECHACOMPARENDO BETWEEN '" +
                Funciones.convFechaFormatoMotor(fechaIni) +
                "' AND '" +
                Funciones.convFechaFormatoMotor(fechaFin) +
                "') ";
                
                sql.append(filtroFechas);
              }

          if (valueObject.getID_RESOLUCION() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_RESOLUCION = ").append(valueObject.getID_RESOLUCION()).append(" ");
          }

          if (valueObject.getNUMERO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMERO = '").append(valueObject.getNUMERO()).append("' ");
          }

          if (valueObject.getFECHA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHA = '").append(valueObject.getFECHA()).append("' ");
          }

          if (valueObject.getCONTENIDO() != null) {
              if (first) { first = false; }
              sql.append("AND CONTENIDO = '").append(valueObject.getCONTENIDO()).append("' ");
          }

          if (valueObject.getNOMBRE() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRE = '").append(valueObject.getNOMBRE()).append("' ");
          }

          if (valueObject.getNROIDENTIFICACION() != null) {
              if (first) { first = false; }
              sql.append("AND NROIDENTIFICACION = '").append(valueObject.getNROIDENTIFICACION()).append("' ");
          }

          if (valueObject.getID_DOCTO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTO = ").append(valueObject.getID_DOCTO()).append(" ");
          }

          if (valueObject.getNOMBRES() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRES = '").append(valueObject.getNOMBRES()).append("' ");
          }

          if (valueObject.getAPELLIDOS() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDOS = '").append(valueObject.getAPELLIDOS()).append("' ");
          }

          if (valueObject.getDIRECCION() != null) {
              if (first) { first = false; }
              sql.append("AND DIRECCION = '").append(valueObject.getDIRECCION()).append("' ");
          }

          if (valueObject.getTELEFONO() != null) {
              if (first) { first = false; }
              sql.append("AND TELEFONO = '").append(valueObject.getTELEFONO()).append("' ");
          }
          
        if (valueObject.getID_TIPORESOLUCION() != 0) {
            if (first) { first = false; }
            sql.append("AND ID_TIPORESOLUCION = ").append(valueObject.getID_TIPORESOLUCION()).append(" ");
        }
                  

          sql.append("ORDER BY ID_RESOLUCION ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, ViewResolucionesInfractorComp valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setID_RESOLUCION(result.getInt("ID_RESOLUCION")); 
                   valueObject.setNUMERO(result.getString("NUMERO")); 
                   valueObject.setFECHA(result.getString("FECHA")); 
                   valueObject.setCONTENIDO(result.getString("CONTENIDO")); 
                   valueObject.setNOMBRE(result.getString("NOMBRE")); 
                   valueObject.setNROIDENTIFICACION(result.getString("NROIDENTIFICACION")); 
                   valueObject.setID_DOCTO(result.getInt("ID_DOCTO")); 
                   valueObject.setNOMBRES(result.getString("NOMBRES")); 
                   valueObject.setAPELLIDOS(result.getString("APELLIDOS")); 
                   valueObject.setDIRECCION(result.getString("DIRECCION")); 
                   valueObject.setTELEFONO(result.getString("TELEFONO")); 
                   valueObject.setID_TIPORESOLUCION(result.getInt("ID_TIPORESOLUCION")); 

              } else {
                    //System.out.println("ViewResolucionesInfractorComp Object Not Found!");
                    throw new NotFoundException("ViewResolucionesInfractorComp Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   ViewResolucionesInfractorComp temp = createValueObject();

                   temp.setID_RESOLUCION(result.getInt("ID_RESOLUCION")); 
                   temp.setNUMERO(result.getString("NUMERO")); 
                   temp.setFECHA(result.getString("FECHA")); 
                   temp.setCONTENIDO(result.getString("CONTENIDO")); 
                   temp.setNOMBRE(result.getString("NOMBRE")); 
                   temp.setNROIDENTIFICACION(result.getString("NROIDENTIFICACION")); 
                   temp.setID_DOCTO(result.getInt("ID_DOCTO")); 
                   temp.setNOMBRES(result.getString("NOMBRES")); 
                   temp.setAPELLIDOS(result.getString("APELLIDOS")); 
                   temp.setDIRECCION(result.getString("DIRECCION")); 
                   temp.setTELEFONO(result.getString("TELEFONO")); 
                   temp.setID_TIPORESOLUCION(result.getInt("ID_TIPORESOLUCION")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }
}
