package modelo.datos.objetos.comparendos.ciatran;

import java.io.Serializable;

/**
  * ViewComparendoCiatran Value Object.
  * This class is value object representing database table VIEW_COMPARENDO_CIATRAN
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewComparendoCiatran implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_COMPARENDO;
    private String ID_DOCTO;
    private String NROIDENTIFICACION;
    private String NOMBRES;
    private String APELLIDOS;
    private String DIRECCION;
    private String TELEFONO;
    private String EMAIL;
    private String NUMEROCOMPARENDO;
    private String ESTADO;
    private String FECHACOMPARENDO;
    private String DIRECCIONINFRACCION;
    private String NUEVO_CODIGO;
    private String INFRACCION;
    private String PLACAAGENTE;
    private String SERVICIO;
    private String PLACA;
    private String OBSERVACION;
    


    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewComparendoCiatran () {

    }

    public ViewComparendoCiatran (int ID_COMPARENDOIn) {

          this.ID_COMPARENDO = ID_COMPARENDOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_COMPARENDO() {
          return this.ID_COMPARENDO;
    }
    public void setID_COMPARENDO(int ID_COMPARENDOIn) {
          this.ID_COMPARENDO = ID_COMPARENDOIn;
    }

    public String getID_DOCTO() {
          return this.ID_DOCTO;
    }
    public void setID_DOCTO(String ID_DOCTOIn) {
          this.ID_DOCTO = ID_DOCTOIn;
    }

    public String getNROIDENTIFICACION() {
          return this.NROIDENTIFICACION;
    }
    public void setNROIDENTIFICACION(String NROIDENTIFICACIONIn) {
          this.NROIDENTIFICACION = NROIDENTIFICACIONIn;
    }

    public String getNOMBRES() {
          return this.NOMBRES;
    }
    public void setNOMBRES(String NOMBRESIn) {
          this.NOMBRES = NOMBRESIn;
    }

    public String getAPELLIDOS() {
          return this.APELLIDOS;
    }
    public void setAPELLIDOS(String APELLIDOSIn) {
          this.APELLIDOS = APELLIDOSIn;
    }

    public String getDIRECCION() {
          return this.DIRECCION;
    }
    public void setDIRECCION(String DIRECCIONIn) {
          this.DIRECCION = DIRECCIONIn;
    }

    public String getTELEFONO() {
          return this.TELEFONO;
    }
    public void setTELEFONO(String TELEFONOIn) {
          this.TELEFONO = TELEFONOIn;
    }

    public String getEMAIL() {
          return this.EMAIL;
    }
    public void setEMAIL(String EMAILIn) {
          this.EMAIL = EMAILIn;
    }

    public String getNUMEROCOMPARENDO() {
          return this.NUMEROCOMPARENDO;
    }
    public void setNUMEROCOMPARENDO(String NUMEROCOMPARENDOIn) {
          this.NUMEROCOMPARENDO = NUMEROCOMPARENDOIn;
    }

    public String getESTADO() {
          return this.ESTADO;
    }
    public void setESTADO(String ESTADOIn) {
          this.ESTADO = ESTADOIn;
    }

    public String getFECHACOMPARENDO() {
          return this.FECHACOMPARENDO;
    }
    public void setFECHACOMPARENDO(String FECHACOMPARENDOIn) {
          this.FECHACOMPARENDO = FECHACOMPARENDOIn;
    }

    public String getDIRECCIONINFRACCION() {
          return this.DIRECCIONINFRACCION;
    }
    public void setDIRECCIONINFRACCION(String DIRECCIONINFRACCIONIn) {
          this.DIRECCIONINFRACCION = DIRECCIONINFRACCIONIn;
    }

    public String getNUEVO_CODIGO() {
          return this.NUEVO_CODIGO;
    }
    public void setNUEVO_CODIGO(String NUEVO_CODIGOIn) {
          this.NUEVO_CODIGO = NUEVO_CODIGOIn;
    }

    public String getINFRACCION() {
          return this.INFRACCION;
    }
    public void setINFRACCION(String INFRACCIONIn) {
          this.INFRACCION = INFRACCIONIn;
    }

    public String getPLACAAGENTE() {
          return this.PLACAAGENTE;
    }
    public void setPLACAAGENTE(String PLACAAGENTEIn) {
          this.PLACAAGENTE = PLACAAGENTEIn;
    }

    public String getSERVICIO() {
          return this.SERVICIO;
    }
    public void setSERVICIO(String SERVICIOIn) {
          this.SERVICIO = SERVICIOIn;
    }

    public String getPLACA() {
          return this.PLACA;
    }
    public void setPLACA(String PLACAIn) {
          this.PLACA = PLACAIn;
    }

    public String getOBSERVACION() {
          return this.OBSERVACION;
    }
    public void setOBSERVACION(String OBSERVACIONIn) {
          this.OBSERVACION = OBSERVACIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_COMPARENDOIn,
          String ID_DOCTOIn,
          String NROIDENTIFICACIONIn,
          String NOMBRESIn,
          String APELLIDOSIn,
          String DIRECCIONIn,
          String TELEFONOIn,
          String EMAILIn,
          String NUMEROCOMPARENDOIn,
          String ESTADOIn,
          String FECHACOMPARENDOIn,
          String DIRECCIONINFRACCIONIn,
          String NUEVO_CODIGOIn,
          String INFRACCIONIn,
          String PLACAAGENTEIn,
          String SERVICIOIn,
          String PLACAIn,
          String OBSERVACIONIn) {
          this.ID_COMPARENDO = ID_COMPARENDOIn;
          this.ID_DOCTO = ID_DOCTOIn;
          this.NROIDENTIFICACION = NROIDENTIFICACIONIn;
          this.NOMBRES = NOMBRESIn;
          this.APELLIDOS = APELLIDOSIn;
          this.DIRECCION = DIRECCIONIn;
          this.TELEFONO = TELEFONOIn;
          this.EMAIL = EMAILIn;
          this.NUMEROCOMPARENDO = NUMEROCOMPARENDOIn;
          this.ESTADO = ESTADOIn;
          this.FECHACOMPARENDO = FECHACOMPARENDOIn;
          this.DIRECCIONINFRACCION = DIRECCIONINFRACCIONIn;
          this.NUEVO_CODIGO = NUEVO_CODIGOIn;
          this.INFRACCION = INFRACCIONIn;
          this.PLACAAGENTE = PLACAAGENTEIn;
          this.SERVICIO = SERVICIOIn;
          this.PLACA = PLACAIn;
          this.OBSERVACION = OBSERVACIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewComparendoCiatran instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewComparendoCiatran valueObject) {

          if (valueObject.getID_COMPARENDO() != this.ID_COMPARENDO) {
                    return(false);
          }
          if (this.ID_DOCTO == null) {
                    if (valueObject.getID_DOCTO() != null)
                           return(false);
          } else if (!this.ID_DOCTO.equals(valueObject.getID_DOCTO())) {
                    return(false);
          }
          if (this.NROIDENTIFICACION == null) {
                    if (valueObject.getNROIDENTIFICACION() != null)
                           return(false);
          } else if (!this.NROIDENTIFICACION.equals(valueObject.getNROIDENTIFICACION())) {
                    return(false);
          }
          if (this.NOMBRES == null) {
                    if (valueObject.getNOMBRES() != null)
                           return(false);
          } else if (!this.NOMBRES.equals(valueObject.getNOMBRES())) {
                    return(false);
          }
          if (this.APELLIDOS == null) {
                    if (valueObject.getAPELLIDOS() != null)
                           return(false);
          } else if (!this.APELLIDOS.equals(valueObject.getAPELLIDOS())) {
                    return(false);
          }
          if (this.DIRECCION == null) {
                    if (valueObject.getDIRECCION() != null)
                           return(false);
          } else if (!this.DIRECCION.equals(valueObject.getDIRECCION())) {
                    return(false);
          }
          if (this.TELEFONO == null) {
                    if (valueObject.getTELEFONO() != null)
                           return(false);
          } else if (!this.TELEFONO.equals(valueObject.getTELEFONO())) {
                    return(false);
          }
          if (this.EMAIL == null) {
                    if (valueObject.getEMAIL() != null)
                           return(false);
          } else if (!this.EMAIL.equals(valueObject.getEMAIL())) {
                    return(false);
          }
          if (this.NUMEROCOMPARENDO == null) {
                    if (valueObject.getNUMEROCOMPARENDO() != null)
                           return(false);
          } else if (!this.NUMEROCOMPARENDO.equals(valueObject.getNUMEROCOMPARENDO())) {
                    return(false);
          }
          if (this.ESTADO == null) {
                    if (valueObject.getESTADO() != null)
                           return(false);
          } else if (!this.ESTADO.equals(valueObject.getESTADO())) {
                    return(false);
          }
          if (this.FECHACOMPARENDO == null) {
                    if (valueObject.getFECHACOMPARENDO() != null)
                           return(false);
          } else if (!this.FECHACOMPARENDO.equals(valueObject.getFECHACOMPARENDO())) {
                    return(false);
          }
          if (this.DIRECCIONINFRACCION == null) {
                    if (valueObject.getDIRECCIONINFRACCION() != null)
                           return(false);
          } else if (!this.DIRECCIONINFRACCION.equals(valueObject.getDIRECCIONINFRACCION())) {
                    return(false);
          }
          if (this.NUEVO_CODIGO == null) {
                    if (valueObject.getNUEVO_CODIGO() != null)
                           return(false);
          } else if (!this.NUEVO_CODIGO.equals(valueObject.getNUEVO_CODIGO())) {
                    return(false);
          }
          if (this.INFRACCION == null) {
                    if (valueObject.getINFRACCION() != null)
                           return(false);
          } else if (!this.INFRACCION.equals(valueObject.getINFRACCION())) {
                    return(false);
          }
          if (this.PLACAAGENTE == null) {
                    if (valueObject.getPLACAAGENTE() != null)
                           return(false);
          } else if (!this.PLACAAGENTE.equals(valueObject.getPLACAAGENTE())) {
                    return(false);
          }
          if (this.SERVICIO == null) {
                    if (valueObject.getSERVICIO() != null)
                           return(false);
          } else if (!this.SERVICIO.equals(valueObject.getSERVICIO())) {
                    return(false);
          }
          if (this.PLACA == null) {
                    if (valueObject.getPLACA() != null)
                           return(false);
          } else if (!this.PLACA.equals(valueObject.getPLACA())) {
                    return(false);
          }
          if (this.OBSERVACION == null) {
                    if (valueObject.getOBSERVACION() != null)
                           return(false);
          } else if (!this.OBSERVACION.equals(valueObject.getOBSERVACION())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewComparendoCiatran, mapping to table VIEW_COMPARENDO_CIATRAN\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_COMPARENDO = " + this.ID_COMPARENDO + "\n"); 
        out.append("ID_DOCTO = " + this.ID_DOCTO + "\n"); 
        out.append("NROIDENTIFICACION = " + this.NROIDENTIFICACION + "\n"); 
        out.append("NOMBRES = " + this.NOMBRES + "\n"); 
        out.append("APELLIDOS = " + this.APELLIDOS + "\n"); 
        out.append("DIRECCION = " + this.DIRECCION + "\n"); 
        out.append("TELEFONO = " + this.TELEFONO + "\n"); 
        out.append("EMAIL = " + this.EMAIL + "\n"); 
        out.append("NUMEROCOMPARENDO = " + this.NUMEROCOMPARENDO + "\n"); 
        out.append("ESTADO = " + this.ESTADO + "\n"); 
        out.append("FECHACOMPARENDO = " + this.FECHACOMPARENDO + "\n"); 
        out.append("DIRECCIONINFRACCION = " + this.DIRECCIONINFRACCION + "\n"); 
        out.append("NUEVO_CODIGO = " + this.NUEVO_CODIGO + "\n"); 
        out.append("INFRACCION = " + this.INFRACCION + "\n"); 
        out.append("PLACAAGENTE = " + this.PLACAAGENTE + "\n"); 
        out.append("SERVICIO = " + this.SERVICIO + "\n"); 
        out.append("PLACA = " + this.PLACA + "\n"); 
        out.append("OBSERVACION = " + this.OBSERVACION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewComparendoCiatran cloned = new ViewComparendoCiatran();

        cloned.setID_COMPARENDO(this.ID_COMPARENDO); 
        if (this.ID_DOCTO != null)
             cloned.setID_DOCTO(new String(this.ID_DOCTO)); 
        if (this.NROIDENTIFICACION != null)
             cloned.setNROIDENTIFICACION(new String(this.NROIDENTIFICACION)); 
        if (this.NOMBRES != null)
             cloned.setNOMBRES(new String(this.NOMBRES)); 
        if (this.APELLIDOS != null)
             cloned.setAPELLIDOS(new String(this.APELLIDOS)); 
        if (this.DIRECCION != null)
             cloned.setDIRECCION(new String(this.DIRECCION)); 
        if (this.TELEFONO != null)
             cloned.setTELEFONO(new String(this.TELEFONO)); 
        if (this.EMAIL != null)
             cloned.setEMAIL(new String(this.EMAIL)); 
        if (this.NUMEROCOMPARENDO != null)
             cloned.setNUMEROCOMPARENDO(new String(this.NUMEROCOMPARENDO)); 
        if (this.ESTADO != null)
             cloned.setESTADO(new String(this.ESTADO)); 
        if (this.FECHACOMPARENDO != null)
             cloned.setFECHACOMPARENDO(new String(this.FECHACOMPARENDO)); 
        if (this.DIRECCIONINFRACCION != null)
             cloned.setDIRECCIONINFRACCION(new String(this.DIRECCIONINFRACCION)); 
        if (this.NUEVO_CODIGO != null)
             cloned.setNUEVO_CODIGO(new String(this.NUEVO_CODIGO)); 
        if (this.INFRACCION != null)
             cloned.setINFRACCION(new String(this.INFRACCION)); 
        if (this.PLACAAGENTE != null)
             cloned.setPLACAAGENTE(new String(this.PLACAAGENTE)); 
        if (this.SERVICIO != null)
             cloned.setSERVICIO(new String(this.SERVICIO)); 
        if (this.PLACA != null)
             cloned.setPLACA(new String(this.PLACA)); 
        if (this.OBSERVACION != null)
             cloned.setOBSERVACION(new String(this.OBSERVACION)); 
        return cloned;
    }
    



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "Hola mundo";
    }

}
