package modelo.datos.dao.generales;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.generales.RuntPropietarioModificado;

import utilidades.Funciones;


/**
  * RuntPropietarioModificado Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve RuntPropietarioModificado object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntPropietarioModificadoDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public RuntPropietarioModificado createValueObject() {
          return new RuntPropietarioModificado();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public RuntPropietarioModificado getObject(Connection conn, int ID_PROPIETARIOMODIF) throws NotFoundException, SQLException {

          RuntPropietarioModificado valueObject = createValueObject();
          valueObject.setID_PROPIETARIOMODIF(ID_PROPIETARIOMODIF);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, RuntPropietarioModificado valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM RUNT_PROPIETARIOMODIFICADO WHERE (ID_PROPIETARIOMODIF = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getID_PROPIETARIOMODIF()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM RUNT_PROPIETARIOMODIFICADO ORDER BY ID_PROPIETARIOMODIF ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, RuntPropietarioModificado valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO RUNT_PROPIETARIOMODIFICADO ( ID_PROPIETARIOMODIF, TIPOPERSONAPROPIETARIO, FECHAINICIOPROPIEDAD, "
               + "FECHAFINPROPIEDAD, PROINDIVISO, PORCENTAJEPROPIEDAD, "
               + "ID_TIPOPROPIEDAD, ID_ESTADO, PRIMERNOMBRE, "
               + "SEGNOMBRE, APELLIDO1, APELLIDO2, "
               + "FECHANACIMIENTO, ID_GRUPOSANGRE, ID_SEXO, "
               + "DIRECCION, TELEFONO, EMAIL, "
               + "ID_RUNTMODIFICACION, ID_DOCTOAPODERADO, NRODOCTOAPODERADO, "
               + "NOMBRE1APODERADO, NOMBRE2APODERADO, APELLIDO1APODERADO, "
               + "APELLIDO2APODERADO, ID_DOCTOPROPIETARIO, NRODOCTOPROPIETARIO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getID_PROPIETARIOMODIF()); 
               if (Funciones.contarCadena(valueObject.getTIPOPERSONAPROPIETARIO(), 30))
                   stmt.setString(2, valueObject.getTIPOPERSONAPROPIETARIO()); 
               else
                   stmt.setNull(2, Types.VARCHAR);
               if (Funciones.esFecha(valueObject.getFECHAINICIOPROPIEDAD()))
                   stmt.setDate(3, Funciones.convFechaSSQL(valueObject.getFECHAINICIOPROPIEDAD())); 
               else
                   stmt.setNull(3, Types.DATE);
               if (Funciones.esFecha(valueObject.getFECHAFINPROPIEDAD()))
                   stmt.setDate(4, Funciones.convFechaSSQL(valueObject.getFECHAFINPROPIEDAD()));  
               else
                   stmt.setNull(4, Types.DATE);
               if (Funciones.contarCadena(valueObject.getPROINDIVISO(), 5))
                   stmt.setString(5, valueObject.getPROINDIVISO()); 
               else
                   stmt.setNull(5, Types.VARCHAR);
               if (!Funciones.DoubleEsNulo(valueObject.getPORCENTAJEPROPIEDAD()))
                   stmt.setDouble(6, valueObject.getPORCENTAJEPROPIEDAD()); 
               else
                   stmt.setNull(6, Types.DOUBLE);
               if (!Funciones.EnteroesNulo(valueObject.getID_TIPOPROPIEDAD()))
                   stmt.setInt(7, valueObject.getID_TIPOPROPIEDAD()); 
               else
                   stmt.setNull(7, Types.INTEGER);
               if (!Funciones.EnteroesNulo(valueObject.getID_ESTADO()))
                   stmt.setInt(8, valueObject.getID_ESTADO()); 
               else
                   stmt.setNull(8, Types.INTEGER);
               if (Funciones.contarCadena(valueObject.getPRIMERNOMBRE(), 40))
                   stmt.setString(9, valueObject.getPRIMERNOMBRE()); 
               else
                   stmt.setNull(9, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getSEGNOMBRE(), 40))
                   stmt.setString(10, valueObject.getSEGNOMBRE()); 
               else
                   stmt.setNull(10, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getAPELLIDO1(), 40))
                   stmt.setString(11, valueObject.getAPELLIDO1()); 
               else
                   stmt.setNull(11, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getAPELLIDO2(), 40))
                   stmt.setString(12, valueObject.getAPELLIDO2()); 
               else
                   stmt.setNull(12, Types.VARCHAR);
               if (Funciones.esFecha(valueObject.getFECHANACIMIENTO()))
                   stmt.setDate(13,Funciones.convFechaSSQL(valueObject.getFECHANACIMIENTO())); 
               else
                   stmt.setNull(13, Types.DATE);
               if(!Funciones.EnteroesNulo(valueObject.getID_GRUPOSANGRE()))
                   stmt.setInt(14, valueObject.getID_GRUPOSANGRE()); 
               else
                   stmt.setNull(14, Types.INTEGER);
               if (!Funciones.EnteroesNulo(valueObject.getID_SEXO()))
                   stmt.setInt(15, valueObject.getID_SEXO()); 
               else
                   stmt.setNull(15, Types.INTEGER);
               if (Funciones.contarCadena(valueObject.getDIRECCION(), 80))
                   stmt.setString(16, valueObject.getDIRECCION()); 
               else
                   stmt.setNull(16, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getTELEFONO(), 20))
                   stmt.setString(17, valueObject.getTELEFONO()); 
               else
                   stmt.setNull(17, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getEMAIL(), 30))
                   stmt.setString(18, valueObject.getEMAIL()); 
               else
                   stmt.setNull(18, Types.VARCHAR);
               if (!Funciones.EnteroesNulo(valueObject.getID_RUNTMODIFICACION()))
                   stmt.setInt(19, valueObject.getID_RUNTMODIFICACION()); 
               else
                   stmt.setNull(19, Types.INTEGER);
               if (Funciones.contarCadena(valueObject.getID_DOCTOAPODERADO(), 5))
                   stmt.setString(20, valueObject.getID_DOCTOAPODERADO()); 
               else
                   stmt.setNull(20, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNRODOCTOAPODERADO(), 40))
                   stmt.setString(21, valueObject.getNRODOCTOAPODERADO()); 
               else
                   stmt.setNull(21, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNOMBRE1APODERADO(), 40))
                    stmt.setString(22, valueObject.getNOMBRE1APODERADO()); 
               else
                   stmt.setNull(22, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNOMBRE2APODERADO(), 40))
                   stmt.setString(23, valueObject.getNOMBRE2APODERADO()); 
               else
                   stmt.setNull(23, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getAPELLIDO1APODERAD(), 40))
                   stmt.setString(24, valueObject.getAPELLIDO1APODERAD()); 
               else
                   stmt.setNull(24, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getAPELLIDO2APODERADO(), 40))
                   stmt.setString(25, valueObject.getAPELLIDO2APODERADO()); 
               else
                   stmt.setNull(25, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getID_DOCTOPROPIETARIO(), 5))
                   stmt.setString(26, valueObject.getID_DOCTOPROPIETARIO()); 
               else
                   stmt.setNull(26, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNRODOCTOPROPIETARIO(), 30))
                   stmt.setString(27, valueObject.getNRODOCTOPROPIETARIO()); 
               else
                   stmt.setNull(27, Types.VARCHAR);

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, RuntPropietarioModificado valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE RUNT_PROPIETARIOMODIFICADO SET TIPOPERSONAPROPIETARIO = ?, FECHAINICIOPROPIEDAD = ?, FECHAFINPROPIEDAD = ?, "
               + "PROINDIVISO = ?, PORCENTAJEPROPIEDAD = ?, ID_TIPOPROPIEDAD = ?, "
               + "ID_ESTADO = ?, PRIMERNOMBRE = ?, SEGNOMBRE = ?, "
               + "APELLIDO1 = ?, APELLIDO2 = ?, FECHANACIMIENTO = ?, "
               + "ID_GRUPOSANGRE = ?, ID_SEXO = ?, DIRECCION = ?, "
               + "TELEFONO = ?, EMAIL = ?, ID_RUNTMODIFICACION = ?, "
               + "ID_DOCTOAPODERADO = ?, NRODOCTOAPODERADO = ?, NOMBRE1APODERADO = ?, "
               + "NOMBRE2APODERADO = ?, APELLIDO1APODERADO = ?, APELLIDO2APODERADO = ?, "
               + "ID_DOCTOPROPIETARIO = ?, NRODOCTOPROPIETARIO = ? WHERE (ID_PROPIETARIOMODIF = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
            if (Funciones.contarCadena(valueObject.getTIPOPERSONAPROPIETARIO(), 30))
                stmt.setString(1, valueObject.getTIPOPERSONAPROPIETARIO()); 
            else
                stmt.setNull(1, Types.VARCHAR);
            if (Funciones.esFecha(valueObject.getFECHAINICIOPROPIEDAD()))
                stmt.setDate(2, Funciones.convFechaSSQL(valueObject.getFECHAINICIOPROPIEDAD())); 
            else
                stmt.setNull(2, Types.DATE);
            if (Funciones.esFecha(valueObject.getFECHAFINPROPIEDAD()))
                stmt.setDate(3, Funciones.convFechaSSQL(valueObject.getFECHAFINPROPIEDAD()));  
            else
                stmt.setNull(3, Types.DATE);
            if (Funciones.contarCadena(valueObject.getPROINDIVISO(), 5))
                stmt.setString(4, valueObject.getPROINDIVISO()); 
            else
                stmt.setNull(4, Types.VARCHAR);
            if (!Funciones.DoubleEsNulo(valueObject.getPORCENTAJEPROPIEDAD()))
                stmt.setDouble(5, valueObject.getPORCENTAJEPROPIEDAD()); 
            else
                stmt.setNull(5, Types.DOUBLE);
            if (!Funciones.EnteroesNulo(valueObject.getID_TIPOPROPIEDAD()))
                stmt.setInt(6, valueObject.getID_TIPOPROPIEDAD()); 
            else
                stmt.setNull(6, Types.INTEGER);
            if (!Funciones.EnteroesNulo(valueObject.getID_ESTADO()))
                stmt.setInt(7, valueObject.getID_ESTADO()); 
            else
                stmt.setNull(7, Types.INTEGER);
            if (Funciones.contarCadena(valueObject.getPRIMERNOMBRE(), 40))
                stmt.setString(8, valueObject.getPRIMERNOMBRE()); 
            else
                stmt.setNull(8, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getSEGNOMBRE(), 40))
                stmt.setString(9, valueObject.getSEGNOMBRE()); 
            else
                stmt.setNull(9, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getAPELLIDO1(), 40))
                stmt.setString(10, valueObject.getAPELLIDO1()); 
            else
                stmt.setNull(10, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getAPELLIDO2(), 40))
                stmt.setString(11, valueObject.getAPELLIDO2()); 
            else
                stmt.setNull(11, Types.VARCHAR);
            if (Funciones.esFecha(valueObject.getFECHANACIMIENTO()))
                stmt.setDate(12,Funciones.convFechaSSQL(valueObject.getFECHANACIMIENTO())); 
            else
                stmt.setNull(12, Types.DATE);
            if(!Funciones.EnteroesNulo(valueObject.getID_GRUPOSANGRE()))
                stmt.setInt(13, valueObject.getID_GRUPOSANGRE()); 
            else
                stmt.setNull(13, Types.INTEGER);
            if (!Funciones.EnteroesNulo(valueObject.getID_SEXO()))
                stmt.setInt(14, valueObject.getID_SEXO()); 
            else
                stmt.setNull(14, Types.INTEGER);
            if (Funciones.contarCadena(valueObject.getDIRECCION(), 80))
                stmt.setString(15, valueObject.getDIRECCION()); 
            else
                stmt.setNull(15, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getTELEFONO(), 20))
                stmt.setString(16, valueObject.getTELEFONO()); 
            else
                stmt.setNull(16, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getEMAIL(), 30))
                stmt.setString(17, valueObject.getEMAIL()); 
            else
                stmt.setNull(17, Types.VARCHAR);
            if (!Funciones.EnteroesNulo(valueObject.getID_RUNTMODIFICACION()))
                stmt.setInt(18, valueObject.getID_RUNTMODIFICACION()); 
            else
                stmt.setNull(18, Types.INTEGER);
            if (Funciones.contarCadena(valueObject.getID_DOCTOAPODERADO(), 5))
                stmt.setString(19, valueObject.getID_DOCTOAPODERADO()); 
            else
                stmt.setNull(19, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNRODOCTOAPODERADO(), 40))
                stmt.setString(20, valueObject.getNRODOCTOAPODERADO()); 
            else
                stmt.setNull(20, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNOMBRE1APODERADO(), 40))
                 stmt.setString(21, valueObject.getNOMBRE1APODERADO()); 
            else
                stmt.setNull(21, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNOMBRE2APODERADO(), 40))
                stmt.setString(22, valueObject.getNOMBRE2APODERADO()); 
            else
                stmt.setNull(22, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getAPELLIDO1APODERAD(), 40))
                stmt.setString(23, valueObject.getAPELLIDO1APODERAD()); 
            else
                stmt.setNull(23, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getAPELLIDO2APODERADO(), 40))
                stmt.setString(24, valueObject.getAPELLIDO2APODERADO()); 
            else
                stmt.setNull(24, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getID_DOCTOPROPIETARIO(), 5))
                stmt.setString(25, valueObject.getID_DOCTOPROPIETARIO()); 
            else
                stmt.setNull(25, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNRODOCTOPROPIETARIO(), 30))
                stmt.setString(26, valueObject.getNRODOCTOPROPIETARIO()); 
            else
                stmt.setNull(26, Types.VARCHAR);
              
              stmt.setInt(27, valueObject.getID_PROPIETARIOMODIF()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, RuntPropietarioModificado valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM RUNT_PROPIETARIOMODIFICADO WHERE (ID_PROPIETARIOMODIF = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getID_PROPIETARIOMODIF()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM RUNT_PROPIETARIOMODIFICADO";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM RUNT_PROPIETARIOMODIFICADO";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, RuntPropietarioModificado valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM RUNT_PROPIETARIOMODIFICADO WHERE 1=1 ");

          if (valueObject.getID_PROPIETARIOMODIF() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_PROPIETARIOMODIF = ").append(valueObject.getID_PROPIETARIOMODIF()).append(" ");
          }

          if (valueObject.getTIPOPERSONAPROPIETARIO() != null) {
              if (first) { first = false; }
              sql.append("AND TIPOPERSONAPROPIETARIO LIKE '").append(valueObject.getTIPOPERSONAPROPIETARIO()).append("%' ");
          }

          if (valueObject.getFECHAINICIOPROPIEDAD() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAINICIOPROPIEDAD LIKE '").append(valueObject.getFECHAINICIOPROPIEDAD()).append("%' ");
          }

          if (valueObject.getFECHAFINPROPIEDAD() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAFINPROPIEDAD LIKE '").append(valueObject.getFECHAFINPROPIEDAD()).append("%' ");
          }

          if (valueObject.getPROINDIVISO() != null) {
              if (first) { first = false; }
              sql.append("AND PROINDIVISO LIKE '").append(valueObject.getPROINDIVISO()).append("%' ");
          }

          if (valueObject.getPORCENTAJEPROPIEDAD() != 0) {
              if (first) { first = false; }
              sql.append("AND PORCENTAJEPROPIEDAD = ").append(valueObject.getPORCENTAJEPROPIEDAD()).append(" ");
          }

          if (valueObject.getID_TIPOPROPIEDAD() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_TIPOPROPIEDAD = ").append(valueObject.getID_TIPOPROPIEDAD()).append(" ");
          }

          if (valueObject.getID_ESTADO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_ESTADO = ").append(valueObject.getID_ESTADO()).append(" ");
          }

          if (valueObject.getPRIMERNOMBRE() != null) {
              if (first) { first = false; }
              sql.append("AND PRIMERNOMBRE LIKE '").append(valueObject.getPRIMERNOMBRE()).append("%' ");
          }

          if (valueObject.getSEGNOMBRE() != null) {
              if (first) { first = false; }
              sql.append("AND SEGNOMBRE LIKE '").append(valueObject.getSEGNOMBRE()).append("%' ");
          }

          if (valueObject.getAPELLIDO1() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDO1 LIKE '").append(valueObject.getAPELLIDO1()).append("%' ");
          }

          if (valueObject.getAPELLIDO2() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDO2 LIKE '").append(valueObject.getAPELLIDO2()).append("%' ");
          }

          if (valueObject.getFECHANACIMIENTO() != null) {
              if (first) { first = false; }
              sql.append("AND FECHANACIMIENTO LIKE '").append(valueObject.getFECHANACIMIENTO()).append("%' ");
          }

          if (valueObject.getID_GRUPOSANGRE() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_GRUPOSANGRE = ").append(valueObject.getID_GRUPOSANGRE()).append(" ");
          }

          if (valueObject.getID_SEXO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_SEXO = ").append(valueObject.getID_SEXO()).append(" ");
          }

          if (valueObject.getDIRECCION() != null) {
              if (first) { first = false; }
              sql.append("AND DIRECCION LIKE '").append(valueObject.getDIRECCION()).append("%' ");
          }

          if (valueObject.getTELEFONO() != null) {
              if (first) { first = false; }
              sql.append("AND TELEFONO LIKE '").append(valueObject.getTELEFONO()).append("%' ");
          }

          if (valueObject.getEMAIL() != null) {
              if (first) { first = false; }
              sql.append("AND EMAIL LIKE '").append(valueObject.getEMAIL()).append("%' ");
          }

          if (valueObject.getID_RUNTMODIFICACION() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_RUNTMODIFICACION = ").append(valueObject.getID_RUNTMODIFICACION()).append(" ");
          }

          if (valueObject.getID_DOCTOAPODERADO() != null) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTOAPODERADO LIKE '").append(valueObject.getID_DOCTOAPODERADO()).append("%' ");
          }

          if (valueObject.getNRODOCTOAPODERADO() != null) {
              if (first) { first = false; }
              sql.append("AND NRODOCTOAPODERADO LIKE '").append(valueObject.getNRODOCTOAPODERADO()).append("%' ");
          }

          if (valueObject.getNOMBRE1APODERADO() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRE1APODERADO LIKE '").append(valueObject.getNOMBRE1APODERADO()).append("%' ");
          }

          if (valueObject.getNOMBRE2APODERADO() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRE2APODERADO LIKE '").append(valueObject.getNOMBRE2APODERADO()).append("%' ");
          }

          if (valueObject.getAPELLIDO1APODERAD() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDO1APODERADO LIKE '").append(valueObject.getAPELLIDO1APODERAD()).append("%' ");
          }

          if (valueObject.getAPELLIDO2APODERADO() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDO2APODERADO LIKE '").append(valueObject.getAPELLIDO2APODERADO()).append("%' ");
          }

          if (valueObject.getID_DOCTOPROPIETARIO() != null) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTOPROPIETARIO LIKE '").append(valueObject.getID_DOCTOPROPIETARIO()).append("%' ");
          }

          if (valueObject.getNRODOCTOPROPIETARIO() != null) {
              if (first) { first = false; }
              sql.append("AND NRODOCTOPROPIETARIO LIKE '").append(valueObject.getNRODOCTOPROPIETARIO()).append("%' ");
          }


          sql.append("ORDER BY ID_PROPIETARIOMODIF ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, RuntPropietarioModificado valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setID_PROPIETARIOMODIF(result.getInt("ID_PROPIETARIOMODIF")); 
                   valueObject.setTIPOPERSONAPROPIETARIO(result.getString("TIPOPERSONAPROPIETARIO")); 
                   valueObject.setFECHAINICIOPROPIEDAD(result.getString("FECHAINICIOPROPIEDAD")); 
                   valueObject.setFECHAFINPROPIEDAD(result.getString("FECHAFINPROPIEDAD")); 
                   valueObject.setPROINDIVISO(result.getString("PROINDIVISO")); 
                   valueObject.setPORCENTAJEPROPIEDAD(result.getDouble("PORCENTAJEPROPIEDAD")); 
                   valueObject.setID_TIPOPROPIEDAD(result.getInt("ID_TIPOPROPIEDAD")); 
                   valueObject.setID_ESTADO(result.getInt("ID_ESTADO")); 
                   valueObject.setPRIMERNOMBRE(result.getString("PRIMERNOMBRE")); 
                   valueObject.setSEGNOMBRE(result.getString("SEGNOMBRE")); 
                   valueObject.setAPELLIDO1(result.getString("APELLIDO1")); 
                   valueObject.setAPELLIDO2(result.getString("APELLIDO2")); 
                   valueObject.setFECHANACIMIENTO(result.getString("FECHANACIMIENTO")); 
                   valueObject.setID_GRUPOSANGRE(result.getInt("ID_GRUPOSANGRE")); 
                   valueObject.setID_SEXO(result.getInt("ID_SEXO")); 
                   valueObject.setDIRECCION(result.getString("DIRECCION")); 
                   valueObject.setTELEFONO(result.getString("TELEFONO")); 
                   valueObject.setEMAIL(result.getString("EMAIL")); 
                   valueObject.setID_RUNTMODIFICACION(result.getInt("ID_RUNTMODIFICACION")); 
                   valueObject.setID_DOCTOAPODERADO(result.getString("ID_DOCTOAPODERADO")); 
                   valueObject.setNRODOCTOAPODERADO(result.getString("NRODOCTOAPODERADO")); 
                   valueObject.setNOMBRE1APODERADO(result.getString("NOMBRE1APODERADO")); 
                   valueObject.setNOMBRE2APODERADO(result.getString("NOMBRE2APODERADO")); 
                   valueObject.setAPELLIDO1APODERAD(result.getString("APELLIDO1APODERADO")); 
                   valueObject.setAPELLIDO2APODERADO(result.getString("APELLIDO2APODERADO")); 
                   valueObject.setID_DOCTOPROPIETARIO(result.getString("ID_DOCTOPROPIETARIO")); 
                   valueObject.setNRODOCTOPROPIETARIO(result.getString("NRODOCTOPROPIETARIO")); 

              } else {
                    //System.out.println("RuntPropietarioModificado Object Not Found!");
                    throw new NotFoundException("RuntPropietarioModificado Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   RuntPropietarioModificado temp = createValueObject();

                   temp.setID_PROPIETARIOMODIF(result.getInt("ID_PROPIETARIOMODIF")); 
                   temp.setTIPOPERSONAPROPIETARIO(result.getString("TIPOPERSONAPROPIETARIO")); 
                   temp.setFECHAINICIOPROPIEDAD(result.getString("FECHAINICIOPROPIEDAD")); 
                   temp.setFECHAFINPROPIEDAD(result.getString("FECHAFINPROPIEDAD")); 
                   temp.setPROINDIVISO(result.getString("PROINDIVISO")); 
                   temp.setPORCENTAJEPROPIEDAD(result.getDouble("PORCENTAJEPROPIEDAD")); 
                   temp.setID_TIPOPROPIEDAD(result.getInt("ID_TIPOPROPIEDAD")); 
                   temp.setID_ESTADO(result.getInt("ID_ESTADO")); 
                   temp.setPRIMERNOMBRE(result.getString("PRIMERNOMBRE")); 
                   temp.setSEGNOMBRE(result.getString("SEGNOMBRE")); 
                   temp.setAPELLIDO1(result.getString("APELLIDO1")); 
                   temp.setAPELLIDO2(result.getString("APELLIDO2")); 
                   temp.setFECHANACIMIENTO(result.getString("FECHANACIMIENTO")); 
                   temp.setID_GRUPOSANGRE(result.getInt("ID_GRUPOSANGRE")); 
                   temp.setID_SEXO(result.getInt("ID_SEXO")); 
                   temp.setDIRECCION(result.getString("DIRECCION")); 
                   temp.setTELEFONO(result.getString("TELEFONO")); 
                   temp.setEMAIL(result.getString("EMAIL")); 
                   temp.setID_RUNTMODIFICACION(result.getInt("ID_RUNTMODIFICACION")); 
                   temp.setID_DOCTOAPODERADO(result.getString("ID_DOCTOAPODERADO")); 
                   temp.setNRODOCTOAPODERADO(result.getString("NRODOCTOAPODERADO")); 
                   temp.setNOMBRE1APODERADO(result.getString("NOMBRE1APODERADO")); 
                   temp.setNOMBRE2APODERADO(result.getString("NOMBRE2APODERADO")); 
                   temp.setAPELLIDO1APODERAD(result.getString("APELLIDO1APODERADO")); 
                   temp.setAPELLIDO2APODERADO(result.getString("APELLIDO2APODERADO")); 
                   temp.setID_DOCTOPROPIETARIO(result.getString("ID_DOCTOPROPIETARIO")); 
                   temp.setNRODOCTOPROPIETARIO(result.getString("NRODOCTOPROPIETARIO")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
