package modelo.datos.dao.generales;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.generales.RuntMedidaCautelarModificada;

import utilidades.Funciones;


/**
  * RuntMedidaCautelarModificada Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve RuntMedidaCautelarModificada object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntMedidaCautelarModificadaDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public RuntMedidaCautelarModificada createValueObject() {
          return new RuntMedidaCautelarModificada();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public RuntMedidaCautelarModificada getObject(Connection conn, int ID_MEDCAUTELARMODIF) throws NotFoundException, SQLException {

          RuntMedidaCautelarModificada valueObject = createValueObject();
          valueObject.setID_MEDCAUTELARMODIF(ID_MEDCAUTELARMODIF);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, RuntMedidaCautelarModificada valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM RUNT_MEDCAUTELARMODIFICADA WHERE (ID_MEDCAUTELARMODIF = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getID_MEDCAUTELARMODIF()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM RUNT_MEDCAUTELARMODIFICADA ORDER BY ID_MEDCAUTELARMODIF ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, RuntMedidaCautelarModificada valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO RUNT_MEDCAUTELARMODIFICADA ( ID_MEDCAUTELARMODIF, ID_DOCTODEMANDADO, NRODOCTODEMANDADO, "
               + "ID_DOCTODEMANDANTE, NRODOCTODEMANDANTE, NOMBREDEMANDADO, "
               + "NOMBREDEMANDANTE, ID_TIPOMEDIDA, NRODOCTOPROCESO, "
               + "FECHAEXPMEDIDA, FECHALEVANTAMEDIDA, NROMEDIDA, "
               + "ESTADOMEDIDA, ID_ENTEJURIDICO, ID_TIPOPROCESO, "
               + "ID_RUNTMODIFICACION) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getID_MEDCAUTELARMODIF()); 
               if (Funciones.contarCadena(valueObject.getID_DOCTODEMANDADO(), 5))
                   stmt.setString(2, valueObject.getID_DOCTODEMANDADO()); 
               else
                   stmt.setNull(2, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNRODOCTODEMANDADO(), 30))
                   stmt.setString(3, valueObject.getNRODOCTODEMANDADO()); 
               else
                   stmt.setNull(3, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getID_DOCTODEMANDANTE(),  5))
                   stmt.setString(4, valueObject.getID_DOCTODEMANDANTE()); 
               else
                   stmt.setNull(4, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNRODOCTODEMANDANTE() , 30))
                   stmt.setString(5, valueObject.getNRODOCTODEMANDANTE()); 
               else
                   stmt.setNull(5, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNOMBREDEMANDADO(), 150))
                   stmt.setString(6, valueObject.getNOMBREDEMANDADO()); 
               else
                   stmt.setNull(6, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getNOMBREDEMANDANTE(), 150))
                   stmt.setString(7, valueObject.getNOMBREDEMANDANTE()); 
               else
                   stmt.setNull(7, Types.VARCHAR);
               if (!Funciones.EnteroesNulo(valueObject.getID_TIPOMEDIDA()))
                   stmt.setInt(8, valueObject.getID_TIPOMEDIDA()); 
               else
                   stmt.setNull(8, Types.INTEGER);
               if (Funciones.contarCadena(valueObject.getNRODOCTOPROCESO(), 40))
                   stmt.setString(9, valueObject.getNRODOCTOPROCESO()); 
               else
                   stmt.setNull(9, Types.VARCHAR);
               if (Funciones.esFecha(valueObject.getFECHAEXPMEDIDA()))
                   stmt.setDate(10,Funciones.convFechaSSQL(valueObject.getFECHAEXPMEDIDA()));
               else
                   stmt.setNull(10, Types.DATE);
               
               if (Funciones.esFecha(valueObject.getFECHALEVANTAMEDIDA()))
                   stmt.setString(11,valueObject.getFECHALEVANTAMEDIDA()); 
               else
                   stmt.setNull(11, Types.DATE);
              
               if (Funciones.contarCadena(valueObject.getNROMEDIDA(), 30))
                   stmt.setString(12, valueObject.getNROMEDIDA()); 
               else
                   stmt.setNull(12, Types.VARCHAR);
               if (Funciones.contarCadena(valueObject.getESTADOMEDIDA(), 40))
                   stmt.setString(13, valueObject.getESTADOMEDIDA()); 
               else
                   stmt.setNull(13, Types.VARCHAR);
               if (!Funciones.EnteroesNulo(valueObject.getID_ENTEJURIDICO()))
                   stmt.setInt(14, valueObject.getID_ENTEJURIDICO()); 
               else
                   stmt.setNull(14, Types.INTEGER);
               if (!Funciones.EnteroesNulo(valueObject.getID_TIPOPROCESO()))
                   stmt.setInt(15, valueObject.getID_TIPOPROCESO()); 
               else
                   stmt.setNull(15, Types.INTEGER);
               if (!Funciones.EnteroesNulo(valueObject.getID_RUNTMODIFICACION()))
                   stmt.setInt(16, valueObject.getID_RUNTMODIFICACION()); 
               else
                   stmt.setNull(16, Types.INTEGER);

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, RuntMedidaCautelarModificada valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE RUNT_MEDCAUTELARMODIFICADA SET ID_DOCTODEMANDADO = ?, NRODOCTODEMANDADO = ?, ID_DOCTODEMANDANTE = ?, "
               + "NRODOCTODEMANDANTE = ?, NOMBREDEMANDADO = ?, NOMBREDEMANDANTE = ?, "
               + "ID_TIPOMEDIDA = ?, NRODOCTOPROCESO = ?, FECHAEXPMEDIDA = ?, "
               + "FECHALEVANTAMEDIDA = ?, NROMEDIDA = ?, ESTADOMEDIDA = ?, "
               + "ID_ENTEJURIDICO = ?, ID_TIPOPROCESO = ?, ID_RUNTMODIFICACION = ? WHERE (ID_MEDCAUTELARMODIF = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
            if (Funciones.contarCadena(valueObject.getID_DOCTODEMANDADO(), 5))
                stmt.setString(1, valueObject.getID_DOCTODEMANDADO()); 
            else
                stmt.setNull(1, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNRODOCTODEMANDADO(), 30))
                stmt.setString(2, valueObject.getNRODOCTODEMANDADO()); 
            else
                stmt.setNull(2, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getID_DOCTODEMANDANTE(),  5))
                stmt.setString(3, valueObject.getID_DOCTODEMANDANTE()); 
            else
                stmt.setNull(3, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNRODOCTODEMANDANTE() , 30))
                stmt.setString(4, valueObject.getNRODOCTODEMANDANTE()); 
            else
                stmt.setNull(4, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNOMBREDEMANDADO(), 150))
                stmt.setString(5, valueObject.getNOMBREDEMANDADO()); 
            else
                stmt.setNull(5, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getNOMBREDEMANDANTE(), 150))
                stmt.setString(6, valueObject.getNOMBREDEMANDANTE()); 
            else
                stmt.setNull(6, Types.VARCHAR);
            if (!Funciones.EnteroesNulo(valueObject.getID_TIPOMEDIDA()))
                stmt.setInt(7, valueObject.getID_TIPOMEDIDA()); 
            else
                stmt.setNull(7, Types.INTEGER);
            if (Funciones.contarCadena(valueObject.getNRODOCTOPROCESO(), 40))
                stmt.setString(8, valueObject.getNRODOCTOPROCESO()); 
            else
                stmt.setNull(8, Types.VARCHAR);
            if (Funciones.esFecha(valueObject.getFECHAEXPMEDIDA()))
                stmt.setDate(9,Funciones.convFechaSSQL(valueObject.getFECHAEXPMEDIDA()));
            else
                stmt.setNull(9, Types.DATE);
            if (Funciones.esFecha(valueObject.getFECHALEVANTAMEDIDA()))
                stmt.setString(10,valueObject.getFECHALEVANTAMEDIDA()); 
            else
                stmt.setNull(10, Types.DATE);
            if (Funciones.contarCadena(valueObject.getNROMEDIDA(), 30))
                stmt.setString(11, valueObject.getNROMEDIDA()); 
            else
                stmt.setNull(11, Types.VARCHAR);
            if (Funciones.contarCadena(valueObject.getESTADOMEDIDA(), 40))
                stmt.setString(12, valueObject.getESTADOMEDIDA()); 
            else
                stmt.setNull(12, Types.VARCHAR);
            if (!Funciones.EnteroesNulo(valueObject.getID_ENTEJURIDICO()))
                stmt.setInt(13, valueObject.getID_ENTEJURIDICO()); 
            else
                stmt.setNull(13, Types.INTEGER);
            if (!Funciones.EnteroesNulo(valueObject.getID_TIPOPROCESO()))
                stmt.setInt(14, valueObject.getID_TIPOPROCESO()); 
            else
                stmt.setNull(14, Types.INTEGER);
            if (!Funciones.EnteroesNulo(valueObject.getID_RUNTMODIFICACION()))
                stmt.setInt(15, valueObject.getID_RUNTMODIFICACION()); 
            else
                stmt.setNull(15, Types.INTEGER);
              
              stmt.setInt(16, valueObject.getID_MEDCAUTELARMODIF()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, RuntMedidaCautelarModificada valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM RUNT_MEDCAUTELARMODIFICADA WHERE (ID_MEDCAUTELARMODIF = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getID_MEDCAUTELARMODIF()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM RUNT_MEDCAUTELARMODIFICADA";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM RUNT_MEDCAUTELARMODIFICADA";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, RuntMedidaCautelarModificada valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM RUNT_MEDCAUTELARMODIFICADA WHERE 1=1 ");

          if (valueObject.getID_MEDCAUTELARMODIF() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_MEDCAUTELARMODIF = ").append(valueObject.getID_MEDCAUTELARMODIF()).append(" ");
          }

          if (valueObject.getID_DOCTODEMANDADO() != null) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTODEMANDADO LIKE '").append(valueObject.getID_DOCTODEMANDADO()).append("%' ");
          }

          if (valueObject.getNRODOCTODEMANDADO() != null) {
              if (first) { first = false; }
              sql.append("AND NRODOCTODEMANDADO LIKE '").append(valueObject.getNRODOCTODEMANDADO()).append("%' ");
          }

          if (valueObject.getID_DOCTODEMANDANTE() != null) {
              if (first) { first = false; }
              sql.append("AND ID_DOCTODEMANDANTE LIKE '").append(valueObject.getID_DOCTODEMANDANTE()).append("%' ");
          }

          if (valueObject.getNRODOCTODEMANDANTE() != null) {
              if (first) { first = false; }
              sql.append("AND NRODOCTODEMANDANTE LIKE '").append(valueObject.getNRODOCTODEMANDANTE()).append("%' ");
          }

          if (valueObject.getNOMBREDEMANDADO() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBREDEMANDADO LIKE '").append(valueObject.getNOMBREDEMANDADO()).append("%' ");
          }

          if (valueObject.getNOMBREDEMANDANTE() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBREDEMANDANTE LIKE '").append(valueObject.getNOMBREDEMANDANTE()).append("%' ");
          }

          if (valueObject.getID_TIPOMEDIDA() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_TIPOMEDIDA = ").append(valueObject.getID_TIPOMEDIDA()).append(" ");
          }

          if (valueObject.getNRODOCTOPROCESO() != null) {
              if (first) { first = false; }
              sql.append("AND NRODOCTOPROCESO LIKE '").append(valueObject.getNRODOCTOPROCESO()).append("%' ");
          }

          if (valueObject.getFECHAEXPMEDIDA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAEXPMEDIDA LIKE '").append(valueObject.getFECHAEXPMEDIDA()).append("%' ");
          }

          if (valueObject.getFECHALEVANTAMEDIDA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHALEVANTAMEDIDA LIKE '").append(valueObject.getFECHALEVANTAMEDIDA()).append("%' ");
          }

          if (valueObject.getNROMEDIDA() != null) {
              if (first) { first = false; }
              sql.append("AND NROMEDIDA LIKE '").append(valueObject.getNROMEDIDA()).append("%' ");
          }

          if (valueObject.getESTADOMEDIDA() != null) {
              if (first) { first = false; }
              sql.append("AND ESTADOMEDIDA LIKE '").append(valueObject.getESTADOMEDIDA()).append("%' ");
          }

          if (valueObject.getID_ENTEJURIDICO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_ENTEJURIDICO = ").append(valueObject.getID_ENTEJURIDICO()).append(" ");
          }

          if (valueObject.getID_TIPOPROCESO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_TIPOPROCESO = ").append(valueObject.getID_TIPOPROCESO()).append(" ");
          }

          if (valueObject.getID_RUNTMODIFICACION() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_RUNTMODIFICACION = ").append(valueObject.getID_RUNTMODIFICACION()).append(" ");
          }


          sql.append("ORDER BY ID_MEDCAUTELARMODIF ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, RuntMedidaCautelarModificada valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setID_MEDCAUTELARMODIF(result.getInt("ID_MEDCAUTELARMODIF")); 
                   valueObject.setID_DOCTODEMANDADO(result.getString("ID_DOCTODEMANDADO")); 
                   valueObject.setNRODOCTODEMANDADO(result.getString("NRODOCTODEMANDADO")); 
                   valueObject.setID_DOCTODEMANDANTE(result.getString("ID_DOCTODEMANDANTE")); 
                   valueObject.setNRODOCTODEMANDANTE(result.getString("NRODOCTODEMANDANTE")); 
                   valueObject.setNOMBREDEMANDADO(result.getString("NOMBREDEMANDADO")); 
                   valueObject.setNOMBREDEMANDANTE(result.getString("NOMBREDEMANDANTE")); 
                   valueObject.setID_TIPOMEDIDA(result.getInt("ID_TIPOMEDIDA")); 
                   valueObject.setNRODOCTOPROCESO(result.getString("NRODOCTOPROCESO")); 
                   valueObject.setFECHAEXPMEDIDA(result.getString("FECHAEXPMEDIDA")); 
                   valueObject.setFECHALEVANTAMEDIDA(result.getString("FECHALEVANTAMEDIDA")); 
                   valueObject.setNROMEDIDA(result.getString("NROMEDIDA")); 
                   valueObject.setESTADOMEDIDA(result.getString("ESTADOMEDIDA")); 
                   valueObject.setID_ENTEJURIDICO(result.getInt("ID_ENTEJURIDICO")); 
                   valueObject.setID_TIPOPROCESO(result.getInt("ID_TIPOPROCESO")); 
                   valueObject.setID_RUNTMODIFICACION(result.getInt("ID_RUNTMODIFICACION")); 

              } else {
                    //System.out.println("RuntMedidaCautelarModificada Object Not Found!");
                    throw new NotFoundException("RuntMedidaCautelarModificada Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   RuntMedidaCautelarModificada temp = createValueObject();

                   temp.setID_MEDCAUTELARMODIF(result.getInt("ID_MEDCAUTELARMODIF")); 
                   temp.setID_DOCTODEMANDADO(result.getString("ID_DOCTODEMANDADO")); 
                   temp.setNRODOCTODEMANDADO(result.getString("NRODOCTODEMANDADO")); 
                   temp.setID_DOCTODEMANDANTE(result.getString("ID_DOCTODEMANDANTE")); 
                   temp.setNRODOCTODEMANDANTE(result.getString("NRODOCTODEMANDANTE")); 
                   temp.setNOMBREDEMANDADO(result.getString("NOMBREDEMANDADO")); 
                   temp.setNOMBREDEMANDANTE(result.getString("NOMBREDEMANDANTE")); 
                   temp.setID_TIPOMEDIDA(result.getInt("ID_TIPOMEDIDA")); 
                   temp.setNRODOCTOPROCESO(result.getString("NRODOCTOPROCESO")); 
                   temp.setFECHAEXPMEDIDA(result.getString("FECHAEXPMEDIDA")); 
                   temp.setFECHALEVANTAMEDIDA(result.getString("FECHALEVANTAMEDIDA")); 
                   temp.setNROMEDIDA(result.getString("NROMEDIDA")); 
                   temp.setESTADOMEDIDA(result.getString("ESTADOMEDIDA")); 
                   temp.setID_ENTEJURIDICO(result.getInt("ID_ENTEJURIDICO")); 
                   temp.setID_TIPOPROCESO(result.getInt("ID_TIPOPROCESO")); 
                   temp.setID_RUNTMODIFICACION(result.getInt("ID_RUNTMODIFICACION")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}

