package modelo.datos.dao.generales;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.generales.VehiculoRadicadoCta;

import utilidades.Funciones;


/**
  * VehiculoRadicadoCta Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve VehiculoRadicadoCta object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class VehiculoRadicadoCtaDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public VehiculoRadicadoCta createValueObject() {
          return new VehiculoRadicadoCta();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public VehiculoRadicadoCta getObject(Connection conn, int ID_VEHRADCTA) throws NotFoundException, SQLException {

          VehiculoRadicadoCta valueObject = createValueObject();
          valueObject.setID_VEHRADCTA(ID_VEHRADCTA);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, VehiculoRadicadoCta valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM VEHICULORADICADOCTA WHERE (ID_VEHRADCTA = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getID_VEHRADCTA()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VEHICULORADICADOCTA ORDER BY ID_VEHRADCTA ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, VehiculoRadicadoCta valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO VEHICULORADICADOCTA ( ID_VEHRADCTA, PLACA, FECHALLEGADA, "
               + "ID_ORGTRANSITO, NUMFOLIOS, NUMOFICIOTRASLADO, "
               + "NUMGUIA, ID_CVEHICULO, ID_SERVICIO, "
               + "ID_MARCA, ID_LINEA, CILINDRAJE, "
               + "ESTADO, ID_USUARIO, FECHAREG, "
               + "HORAREG, ID_MARCPPAL, ID_LINPPAL) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getID_VEHRADCTA()); 
               if(Funciones.contarCadena(valueObject.getPLACA(), 10))
                 stmt.setString(2, valueObject.getPLACA()); 
               else
                 stmt.setNull(2, Types.VARCHAR);
               if(Funciones.esFecha(valueObject.getFECHALLEGADA()))
                 stmt.setDate(3, Funciones.convFechaSSQL(valueObject.getFECHALLEGADA())); 
               else
                 stmt.setNull(3,Types.DATE);
               if(!Funciones.EnteroesNulo(valueObject.getID_ORGTRANSITO()))
                 stmt.setInt(4, valueObject.getID_ORGTRANSITO()); 
               else
                 stmt.setNull(4, Types.INTEGER);
               if(!Funciones.EnteroesNulo(valueObject.getNUMFOLIOS()))
                 stmt.setInt(5, valueObject.getNUMFOLIOS()); 
               else
                 stmt.setNull(5, Types.INTEGER);
               if(Funciones.contarCadena(valueObject.getNUMOFICIOTRASLADO(), 15))
                 stmt.setString(6, valueObject.getNUMOFICIOTRASLADO()); 
               else
                 stmt.setNull(6, Types.VARCHAR);
               if(Funciones.contarCadena(valueObject.getNUMGUIA(), 15))
                 stmt.setString(7, valueObject.getNUMGUIA()); 
               else
                 stmt.setNull(7, Types.VARCHAR);
               if(!Funciones.EnteroesNulo(valueObject.getID_CVEHICULO()))
                 stmt.setInt(8, valueObject.getID_CVEHICULO()); 
               else
                 stmt.setNull(8, Types.INTEGER);
               if(!Funciones.EnteroesNulo(valueObject.getID_SERVICIO()))
                 stmt.setInt(9, valueObject.getID_SERVICIO()); 
               else
                 stmt.setNull(9, Types.INTEGER);
               if(Funciones.contarCadena(valueObject.getID_MARCA(), 2))
                 stmt.setString(10, valueObject.getID_MARCA()); 
               else
                 stmt.setNull(10, Types.VARCHAR);
               if(!Funciones.EnteroesNulo(valueObject.getID_LINEA()))
                 stmt.setInt(11, valueObject.getID_LINEA()); 
               else
                 stmt.setNull(11, Types.INTEGER);
               if(!Funciones.EnteroesNulo(valueObject.getCILINDRAJE()))
                 stmt.setInt(12, valueObject.getCILINDRAJE()); 
               else
                 stmt.setNull(12, Types.INTEGER);
               if(Funciones.contarCadena(valueObject.getESTADO(), 1))
                 stmt.setString(13, valueObject.getESTADO()); 
               else
                 stmt.setNull(13, Types.VARCHAR);
               if(!Funciones.EnteroesNulo(valueObject.getID_USUARIO()))
                 stmt.setInt(14, valueObject.getID_USUARIO()); 
               else
                 stmt.setNull(14, Types.INTEGER);
               if(Funciones.esFecha(valueObject.getFECHAREG()))
                 stmt.setDate(15, Funciones.convFechaSSQL(valueObject.getFECHAREG())); 
               else
                 stmt.setNull(15,Types.DATE);
               if(Funciones.esTime(valueObject.getHORAREG()))
                 stmt.setTime(16, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getHORAREG())));
               else 
                 stmt.setNull(16, Types.TIME);
               if(!Funciones.EnteroesNulo(valueObject.getID_MARCPPAL()))
                 stmt.setInt(17, valueObject.getID_MARCPPAL()); 
               else
                 stmt.setNull(17, Types.INTEGER);
               if(!Funciones.EnteroesNulo(valueObject.getID_LINPPAL()))
                 stmt.setInt(18, valueObject.getID_LINPPAL()); 
               else
                 stmt.setNull(18, Types.INTEGER);

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, VehiculoRadicadoCta valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE VEHICULORADICADOCTA SET PLACA = ?, FECHALLEGADA = ?, ID_ORGTRANSITO = ?, "
               + "NUMFOLIOS = ?, NUMOFICIOTRASLADO = ?, NUMGUIA = ?, "
               + "ID_CVEHICULO = ?, ID_SERVICIO = ?, ID_MARCA = ?, "
               + "ID_LINEA = ?, CILINDRAJE = ?, ESTADO = ?, "
               + "ID_USUARIO = ?, FECHAREG = ?, HORAREG = ?, "
               + "ID_MARCPPAL = ?, ID_LINPPAL = ? WHERE (ID_VEHRADCTA = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPLACA()); 
              
            if (Funciones.esFecha(valueObject.getFECHALLEGADA()))
              stmt.setDate(2, Funciones.convFechaSSQL(valueObject.getFECHALLEGADA()));
            else
              stmt.setNull(2, Types.DATE);
              
              stmt.setInt(3, valueObject.getID_ORGTRANSITO()); 
              stmt.setInt(4, valueObject.getNUMFOLIOS()); 
              stmt.setString(5, valueObject.getNUMOFICIOTRASLADO()); 
              stmt.setString(6, valueObject.getNUMGUIA()); 
              stmt.setInt(7, valueObject.getID_CVEHICULO()); 
              stmt.setInt(8, valueObject.getID_SERVICIO()); 
              stmt.setString(9, valueObject.getID_MARCA()); 
              stmt.setInt(10, valueObject.getID_LINEA()); 
              stmt.setInt(11, valueObject.getCILINDRAJE()); 
              stmt.setString(12, valueObject.getESTADO()); 
              stmt.setInt(13, valueObject.getID_USUARIO()); 
              
            if (Funciones.esFecha(valueObject.getFECHAREG()))
              stmt.setDate(14, Funciones.convFechaSSQL(valueObject.getFECHAREG()));
            else
              stmt.setNull(14, Types.DATE);
              
              
              //stmt.setString(15, valueObject.getHORAREG()); 
            if (Funciones.esTime(valueObject.getHORAREG()))
                stmt.setTime(15, Funciones.calendarToTime(Funciones.stringToCalendar(valueObject.getHORAREG())));
            else
                stmt.setNull(15, Types.TIME);
              
              
              stmt.setInt(16, valueObject.getID_MARCPPAL()); 
              stmt.setInt(17, valueObject.getID_LINPPAL()); 

              stmt.setInt(18, valueObject.getID_VEHRADCTA()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, VehiculoRadicadoCta valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM VEHICULORADICADOCTA WHERE (ID_VEHRADCTA = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getID_VEHRADCTA()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM VEHICULORADICADOCTA";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VEHICULORADICADOCTA";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, VehiculoRadicadoCta valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VEHICULORADICADOCTA WHERE 1=1 ");

          if (valueObject.getID_VEHRADCTA() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_VEHRADCTA = ").append(valueObject.getID_VEHRADCTA()).append(" ");
          }

          if (valueObject.getPLACA() != null) {
              if (first) { first = false; }
              sql.append("AND PLACA LIKE '").append(valueObject.getPLACA()).append("%' ");
          }

          if (valueObject.getFECHALLEGADA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHALLEGADA LIKE '").append(valueObject.getFECHALLEGADA()).append("%' ");
          }

          if (valueObject.getID_ORGTRANSITO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_ORGTRANSITO = ").append(valueObject.getID_ORGTRANSITO()).append(" ");
          }

          if (valueObject.getNUMFOLIOS() != 0) {
              if (first) { first = false; }
              sql.append("AND NUMFOLIOS = ").append(valueObject.getNUMFOLIOS()).append(" ");
          }

          if (valueObject.getNUMOFICIOTRASLADO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMOFICIOTRASLADO LIKE '").append(valueObject.getNUMOFICIOTRASLADO()).append("%' ");
          }

          if (valueObject.getNUMGUIA() != null) {
              if (first) { first = false; }
              sql.append("AND NUMGUIA LIKE '").append(valueObject.getNUMGUIA()).append("%' ");
          }

          if (valueObject.getID_CVEHICULO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_CVEHICULO = ").append(valueObject.getID_CVEHICULO()).append(" ");
          }

          if (valueObject.getID_SERVICIO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_SERVICIO = ").append(valueObject.getID_SERVICIO()).append(" ");
          }

          if (valueObject.getID_MARCA() != null) {
              if (first) { first = false; }
              sql.append("AND ID_MARCA LIKE '").append(valueObject.getID_MARCA()).append("%' ");
          }

          if (valueObject.getID_LINEA() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_LINEA = ").append(valueObject.getID_LINEA()).append(" ");
          }

          if (valueObject.getCILINDRAJE() != 0) {
              if (first) { first = false; }
              sql.append("AND CILINDRAJE = ").append(valueObject.getCILINDRAJE()).append(" ");
          }

          if (valueObject.getESTADO() != null) {
              if (first) { first = false; }
              sql.append("AND ESTADO LIKE '").append(valueObject.getESTADO()).append("%' ");
          }

          if (valueObject.getID_USUARIO() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_USUARIO = ").append(valueObject.getID_USUARIO()).append(" ");
          }

          if (valueObject.getFECHAREG() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAREG LIKE '").append(valueObject.getFECHAREG()).append("%' ");
          }

          if (valueObject.getHORAREG() != null) {
              if (first) { first = false; }
              sql.append("AND HORAREG LIKE '").append(valueObject.getHORAREG()).append("%' ");
          }

          if (valueObject.getID_MARCPPAL() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_MARCPPAL = ").append(valueObject.getID_MARCPPAL()).append(" ");
          }

          if (valueObject.getID_LINPPAL() != 0) {
              if (first) { first = false; }
              sql.append("AND ID_LINPPAL = ").append(valueObject.getID_LINPPAL()).append(" ");
          }


          sql.append("ORDER BY ID_VEHRADCTA ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, VehiculoRadicadoCta valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setID_VEHRADCTA(result.getInt("ID_VEHRADCTA")); 
                   valueObject.setPLACA(result.getString("PLACA")); 
                   valueObject.setFECHALLEGADA(result.getString("FECHALLEGADA")); 
                   valueObject.setID_ORGTRANSITO(result.getInt("ID_ORGTRANSITO")); 
                   valueObject.setNUMFOLIOS(result.getInt("NUMFOLIOS")); 
                   valueObject.setNUMOFICIOTRASLADO(result.getString("NUMOFICIOTRASLADO")); 
                   valueObject.setNUMGUIA(result.getString("NUMGUIA")); 
                   valueObject.setID_CVEHICULO(result.getInt("ID_CVEHICULO")); 
                   valueObject.setID_SERVICIO(result.getInt("ID_SERVICIO")); 
                   valueObject.setID_MARCA(result.getString("ID_MARCA")); 
                   valueObject.setID_LINEA(result.getInt("ID_LINEA")); 
                   valueObject.setCILINDRAJE(result.getInt("CILINDRAJE")); 
                   valueObject.setESTADO(result.getString("ESTADO")); 
                   valueObject.setID_USUARIO(result.getInt("ID_USUARIO")); 
                   valueObject.setFECHAREG(result.getString("FECHAREG")); 
                   valueObject.setHORAREG(result.getString("HORAREG")); 
                   valueObject.setID_MARCPPAL(result.getInt("ID_MARCPPAL")); 
                   valueObject.setID_LINPPAL(result.getInt("ID_LINPPAL")); 

              } else {
                    //System.out.println("VehiculoRadicadoCta Object Not Found!");
                    throw new NotFoundException("VehiculoRadicadoCta Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   VehiculoRadicadoCta temp = createValueObject();

                   temp.setID_VEHRADCTA(result.getInt("ID_VEHRADCTA")); 
                   temp.setPLACA(result.getString("PLACA")); 
                   temp.setFECHALLEGADA(result.getString("FECHALLEGADA")); 
                   temp.setID_ORGTRANSITO(result.getInt("ID_ORGTRANSITO")); 
                   temp.setNUMFOLIOS(result.getInt("NUMFOLIOS")); 
                   temp.setNUMOFICIOTRASLADO(result.getString("NUMOFICIOTRASLADO")); 
                   temp.setNUMGUIA(result.getString("NUMGUIA")); 
                   temp.setID_CVEHICULO(result.getInt("ID_CVEHICULO")); 
                   temp.setID_SERVICIO(result.getInt("ID_SERVICIO")); 
                   temp.setID_MARCA(result.getString("ID_MARCA")); 
                   temp.setID_LINEA(result.getInt("ID_LINEA")); 
                   temp.setCILINDRAJE(result.getInt("CILINDRAJE")); 
                   temp.setESTADO(result.getString("ESTADO")); 
                   temp.setID_USUARIO(result.getInt("ID_USUARIO")); 
                   temp.setFECHAREG(result.getString("FECHAREG")); 
                   temp.setHORAREG(result.getString("HORAREG")); 
                   temp.setID_MARCPPAL(result.getInt("ID_MARCPPAL")); 
                   temp.setID_LINPPAL(result.getInt("ID_LINPPAL")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
