package modelo.datos.objetos.facturacion;

import java.io.Serializable;

/**
  * CamposCodBarFac Value Object.
  * This class is value object representing database table CAMPOS_CODBARFAC
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class CamposCodBarFac implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID;
    private String DESCRIPCION;
    private String VALOR;
    private int LONGITUD;
    private int PRIORIDAD;
    private String PREFIJO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public CamposCodBarFac () {

    }

    public CamposCodBarFac (int IDIn) {

          this.ID = IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID() {
          return this.ID;
    }
    public void setID(int IDIn) {
          this.ID = IDIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getVALOR() {
          return this.VALOR;
    }
    public void setVALOR(String VALORIn) {
          this.VALOR = VALORIn;
    }

    public int getLONGITUD() {
          return this.LONGITUD;
    }
    public void setLONGITUD(int LONGITUDIn) {
          this.LONGITUD = LONGITUDIn;
    }

    public int getPRIORIDAD() {
          return this.PRIORIDAD;
    }
    public void setPRIORIDAD(int PRIORIDADIn) {
          this.PRIORIDAD = PRIORIDADIn;
    }

    public String getPREFIJO() {
          return this.PREFIJO;
    }
    public void setPREFIJO(String PREFIJOIn) {
          this.PREFIJO = PREFIJOIn;
          
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDIn,
          String DESCRIPCIONIn,
          String VALORIn,
          int LONGITUDIn,
          int PRIORIDADIn,
          String PREFIJOIn) {
          this.ID = IDIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.VALOR = VALORIn;
          this.LONGITUD = LONGITUDIn;
          this.PRIORIDAD = PRIORIDADIn;
          this.PREFIJO = PREFIJOIn;
    }


    /** 
     * hasEqualMapping-method will compare two CamposCodBarFac instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(CamposCodBarFac valueObject) {

          if (valueObject.getID() != this.ID) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.VALOR == null) {
                    if (valueObject.getVALOR() != null)
                           return(false);
          } else if (!this.VALOR.equals(valueObject.getVALOR())) {
                    return(false);
          }
          if (valueObject.getLONGITUD() != this.LONGITUD) {
                    return(false);
          }
          if (valueObject.getPRIORIDAD() != this.PRIORIDAD) {
                    return(false);
          }
          if (this.PREFIJO == null) {
                    if (valueObject.getPREFIJO() != null)
                           return(false);
          } else if (!this.PREFIJO.equals(valueObject.getPREFIJO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass CamposCodBarFac, mapping to table CAMPOS_CODBARFAC\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID = " + this.ID + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("VALOR = " + this.VALOR + "\n"); 
        out.append("LONGITUD = " + this.LONGITUD + "\n"); 
        out.append("PRIORIDAD = " + this.PRIORIDAD + "\n"); 
        out.append("PREFIJO = " + this.PREFIJO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        CamposCodBarFac cloned = new CamposCodBarFac();

        cloned.setID(this.ID); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.VALOR != null)
             cloned.setVALOR(new String(this.VALOR)); 
        cloned.setLONGITUD(this.LONGITUD); 
        cloned.setPRIORIDAD(this.PRIORIDAD); 
        if (this.PREFIJO != null)
             cloned.setPREFIJO(new String(this.PREFIJO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
