package modelo.datos.objetos.transportepublico.tramites;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TNuevosVehiculosTrans Value Object.
  * This class is value object representing database table TNuevosVehiculosTrans
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TNuevosVehiculosTrans implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int TNV_ID;
    private int TNV_ID_CVEHICULO;
    private String TNV_MARCA;
    private String TNV_MODELO;
    private String TNV_MOTOR;
    private String TNV_CHASIS;
    private String TNV_PLACA;
    


    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TNuevosVehiculosTrans () {

    }

    public TNuevosVehiculosTrans (int TNV_IDIn) {

          this.TNV_ID = TNV_IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getTNV_ID() {
          return this.TNV_ID;
    }
    public void setTNV_ID(int TNV_IDIn) {
          this.TNV_ID = TNV_IDIn;
    }

    public int getTNV_ID_CVEHICULO() {
          return this.TNV_ID_CVEHICULO;
    }
    public void setTNV_ID_CVEHICULO(int TNV_ID_CVEHICULOIn) {
          this.TNV_ID_CVEHICULO = TNV_ID_CVEHICULOIn;
    }

    public String getTNV_MARCA() {
          return this.TNV_MARCA;
    }
    public void setTNV_MARCA(String TNV_MARCAIn) {
          this.TNV_MARCA = TNV_MARCAIn;
    }

    public String getTNV_MODELO() {
          return this.TNV_MODELO;
    }
    public void setTNV_MODELO(String TNV_MODELOIn) {
          this.TNV_MODELO = TNV_MODELOIn;
    }

    public String getTNV_MOTOR() {
          return this.TNV_MOTOR;
    }
    public void setTNV_MOTOR(String TNV_MOTORIn) {
          this.TNV_MOTOR = TNV_MOTORIn;
    }

    public String getTNV_CHASIS() {
          return this.TNV_CHASIS;
    }
    public void setTNV_CHASIS(String TNV_CHASISIn) {
          this.TNV_CHASIS = TNV_CHASISIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int TNV_IDIn,
          int TNV_ID_CVEHICULOIn,
          String TNV_MARCAIn,
          String TNV_MODELOIn,
          String TNV_MOTORIn,
          String TNV_CHASISIn) {
          this.TNV_ID = TNV_IDIn;
          this.TNV_ID_CVEHICULO = TNV_ID_CVEHICULOIn;
          this.TNV_MARCA = TNV_MARCAIn;
          this.TNV_MODELO = TNV_MODELOIn;
          this.TNV_MOTOR = TNV_MOTORIn;
          this.TNV_CHASIS = TNV_CHASISIn;
    }


    /** 
     * hasEqualMapping-method will compare two TNuevosVehiculosTrans instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TNuevosVehiculosTrans valueObject) {

          if (valueObject.getTNV_ID() != this.TNV_ID) {
                    return(false);
          }
          if (valueObject.getTNV_ID_CVEHICULO() != this.TNV_ID_CVEHICULO) {
                    return(false);
          }
          if (this.TNV_MARCA == null) {
                    if (valueObject.getTNV_MARCA() != null)
                           return(false);
          } else if (!this.TNV_MARCA.equals(valueObject.getTNV_MARCA())) {
                    return(false);
          }
          if (this.TNV_MODELO == null) {
                    if (valueObject.getTNV_MODELO() != null)
                           return(false);
          } else if (!this.TNV_MODELO.equals(valueObject.getTNV_MODELO())) {
                    return(false);
          }
          if (this.TNV_MOTOR == null) {
                    if (valueObject.getTNV_MOTOR() != null)
                           return(false);
          } else if (!this.TNV_MOTOR.equals(valueObject.getTNV_MOTOR())) {
                    return(false);
          }
          if (this.TNV_CHASIS == null) {
                    if (valueObject.getTNV_CHASIS() != null)
                           return(false);
          } else if (!this.TNV_CHASIS.equals(valueObject.getTNV_CHASIS())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TNuevosVehiculosTrans, mapping to table TNuevosVehiculosTrans\n");
        out.append("Persistent attributes: \n"); 
        out.append("TNV_ID = " + this.TNV_ID + "\n"); 
        out.append("TNV_ID_CVEHICULO = " + this.TNV_ID_CVEHICULO + "\n"); 
        out.append("TNV_MARCA = " + this.TNV_MARCA + "\n"); 
        out.append("TNV_MODELO = " + this.TNV_MODELO + "\n"); 
        out.append("TNV_MOTOR = " + this.TNV_MOTOR + "\n"); 
        out.append("TNV_CHASIS = " + this.TNV_CHASIS + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TNuevosVehiculosTrans cloned = new TNuevosVehiculosTrans();

        cloned.setTNV_ID(this.TNV_ID); 
        cloned.setTNV_ID_CVEHICULO(this.TNV_ID_CVEHICULO); 
        if (this.TNV_MARCA != null)
             cloned.setTNV_MARCA(new String(this.TNV_MARCA)); 
        if (this.TNV_MODELO != null)
             cloned.setTNV_MODELO(new String(this.TNV_MODELO)); 
        if (this.TNV_MOTOR != null)
             cloned.setTNV_MOTOR(new String(this.TNV_MOTOR)); 
        if (this.TNV_CHASIS != null)
             cloned.setTNV_CHASIS(new String(this.TNV_CHASIS)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

    public String getTNV_PLACA() {
        return TNV_PLACA;
    }

    public void setTNV_PLACA(String TNV_PLACA) {
        this.TNV_PLACA = TNV_PLACA;
    }
}
