package modelo.datos.objetos.transportepublico.cupos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * HistoricoCupoTrans Value Object.
  * This class is value object representing database table HistoricoCupoTrans
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HistoricoCupoTrans implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID;
    private int IDCUPO;
    private int IDPERSONA;
    private int IDVEHICULO;
    private String DESCRIPCION;
    private int IDRESOLUCION;
    private int IDUSUARIO;
    private String FECHAREGISTRO;
    private int IDEMPRESASERVICIO;
    private int TT_IDEMPRESA;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public HistoricoCupoTrans () {

    }

    public HistoricoCupoTrans (int IDIn) {

          this.ID = IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID() {
          return this.ID;
    }
    public void setID(int IDIn) {
          this.ID = IDIn;
    }

    public int getIDCUPO() {
          return this.IDCUPO;
    }
    public void setIDCUPO(int IDCUPOIn) {
          this.IDCUPO = IDCUPOIn;
    }

    public int getIDPERSONA() {
          return this.IDPERSONA;
    }
    public void setIDPERSONA(int IDPERSONAIn) {
          this.IDPERSONA = IDPERSONAIn;
    }

    public int getIDVEHICULO() {
          return this.IDVEHICULO;
    }
    public void setIDVEHICULO(int IDVEHICULOIn) {
          this.IDVEHICULO = IDVEHICULOIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public int getIDRESOLUCION() {
          return this.IDRESOLUCION;
    }
    public void setIDRESOLUCION(int IDRESOLUCIONIn) {
          this.IDRESOLUCION = IDRESOLUCIONIn;
    }

    public int getIDUSUARIO() {
          return this.IDUSUARIO;
    }
    public void setIDUSUARIO(int IDUSUARIOIn) {
          this.IDUSUARIO = IDUSUARIOIn;
    }

    public String getFECHAREGISTRO() {
          return this.FECHAREGISTRO;
    }
    public void setFECHAREGISTRO(String FECHAREGISTROIn) {
          this.FECHAREGISTRO = FECHAREGISTROIn;
    }

    public int getIDEMPRESASERVICIO() {
          return this.IDEMPRESASERVICIO;
    }
    public void setIDEMPRESASERVICIO(int IDEMPRESASERVICIOIn) {
          this.IDEMPRESASERVICIO = IDEMPRESASERVICIOIn;
    }

    public int getTT_IDEMPRESA() {
          return this.TT_IDEMPRESA;
    }
    public void setTT_IDEMPRESA(int TT_IDEMPRESAIn) {
          this.TT_IDEMPRESA = TT_IDEMPRESAIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDIn,
          int IDCUPOIn,
          int IDPERSONAIn,
          int IDVEHICULOIn,
          String DESCRIPCIONIn,
          int IDRESOLUCIONIn,
          int IDUSUARIOIn,
          String FECHAREGISTROIn,
          int IDEMPRESASERVICIOIn,
          int TT_IDEMPRESAIn) {
          this.ID = IDIn;
          this.IDCUPO = IDCUPOIn;
          this.IDPERSONA = IDPERSONAIn;
          this.IDVEHICULO = IDVEHICULOIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.IDRESOLUCION = IDRESOLUCIONIn;
          this.IDUSUARIO = IDUSUARIOIn;
          this.FECHAREGISTRO = FECHAREGISTROIn;
          this.IDEMPRESASERVICIO = IDEMPRESASERVICIOIn;
          this.TT_IDEMPRESA = TT_IDEMPRESAIn;
    }


    /** 
     * hasEqualMapping-method will compare two HistoricoCupoTrans instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(HistoricoCupoTrans valueObject) {

          if (valueObject.getID() != this.ID) {
                    return(false);
          }
          if (valueObject.getIDCUPO() != this.IDCUPO) {
                    return(false);
          }
          if (valueObject.getIDPERSONA() != this.IDPERSONA) {
                    return(false);
          }
          if (valueObject.getIDVEHICULO() != this.IDVEHICULO) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (valueObject.getIDRESOLUCION() != this.IDRESOLUCION) {
                    return(false);
          }
          if (valueObject.getIDUSUARIO() != this.IDUSUARIO) {
                    return(false);
          }
          if (this.FECHAREGISTRO == null) {
                    if (valueObject.getFECHAREGISTRO() != null)
                           return(false);
          } else if (!this.FECHAREGISTRO.equals(valueObject.getFECHAREGISTRO())) {
                    return(false);
          }
          if (valueObject.getIDEMPRESASERVICIO() != this.IDEMPRESASERVICIO) {
                    return(false);
          }
          if (valueObject.getTT_IDEMPRESA() != this.TT_IDEMPRESA) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HistoricoCupoTrans, mapping to table HistoricoCupoTrans\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID = " + this.ID + "\n"); 
        out.append("IDCUPO = " + this.IDCUPO + "\n"); 
        out.append("IDPERSONA = " + this.IDPERSONA + "\n"); 
        out.append("IDVEHICULO = " + this.IDVEHICULO + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("IDRESOLUCION = " + this.IDRESOLUCION + "\n"); 
        out.append("IDUSUARIO = " + this.IDUSUARIO + "\n"); 
        out.append("FECHAREGISTRO = " + this.FECHAREGISTRO + "\n"); 
        out.append("IDEMPRESASERVICIO = " + this.IDEMPRESASERVICIO + "\n"); 
        out.append("TT_IDEMPRESA = " + this.TT_IDEMPRESA + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        HistoricoCupoTrans cloned = new HistoricoCupoTrans();

        cloned.setID(this.ID); 
        cloned.setIDCUPO(this.IDCUPO); 
        cloned.setIDPERSONA(this.IDPERSONA); 
        cloned.setIDVEHICULO(this.IDVEHICULO); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        cloned.setIDRESOLUCION(this.IDRESOLUCION); 
        cloned.setIDUSUARIO(this.IDUSUARIO); 
        if (this.FECHAREGISTRO != null)
             cloned.setFECHAREGISTRO(new String(this.FECHAREGISTRO)); 
        cloned.setIDEMPRESASERVICIO(this.IDEMPRESASERVICIO); 
        cloned.setTT_IDEMPRESA(this.TT_IDEMPRESA); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
