package modelo.datos.objetos.transportepublico.cupos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * RangoCuposVehiculoPublico Value Object.
  * This class is value object representing database table RangoCuposVehiculoPublico
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RangoCuposVehiculoPublicoTrans implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_RANGOCUPO;
    private int IDEMPRESATRANSP;
    private int IDTIPOVEHICULO;
    private String FECHAREGISTROCUPO;
    private String NRORESOLUCION;
    private String FECHARESOLUCION;
    private String OBSERVACION;
    private String CUPOSASIGNADOS;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public RangoCuposVehiculoPublicoTrans () {

    }

    public RangoCuposVehiculoPublicoTrans (int ID_RANGOCUPOIn) {

          this.ID_RANGOCUPO = ID_RANGOCUPOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_RANGOCUPO() {
          return this.ID_RANGOCUPO;
    }
    public void setID_RANGOCUPO(int ID_RANGOCUPOIn) {
          this.ID_RANGOCUPO = ID_RANGOCUPOIn;
    }

    public int getIDEMPRESATRANSP() {
          return this.IDEMPRESATRANSP;
    }
    public void setIDEMPRESATRANSP(int IDEMPRESATRANSPIn) {
          this.IDEMPRESATRANSP = IDEMPRESATRANSPIn;
    }

    public int getIDTIPOVEHICULO() {
          return this.IDTIPOVEHICULO;
    }
    public void setIDTIPOVEHICULO(int IDTIPOVEHICULOIn) {
          this.IDTIPOVEHICULO = IDTIPOVEHICULOIn;
    }

    public String getFECHAREGISTROCUPO() {
          return this.FECHAREGISTROCUPO;
    }
    public void setFECHAREGISTROCUPO(String FECHAREGISTROCUPOIn) {
          this.FECHAREGISTROCUPO = FECHAREGISTROCUPOIn;
    }

    public String getNRORESOLUCION() {
          return this.NRORESOLUCION;
    }
    public void setNRORESOLUCION(String NRORESOLUCIONIn) {
          this.NRORESOLUCION = NRORESOLUCIONIn;
    }

    public String getFECHARESOLUCION() {
          return this.FECHARESOLUCION;
    }
    public void setFECHARESOLUCION(String FECHARESOLUCIONIn) {
          this.FECHARESOLUCION = FECHARESOLUCIONIn;
    }

    public String getOBSERVACION() {
          return this.OBSERVACION;
    }
    public void setOBSERVACION(String OBSERVACIONIn) {
          this.OBSERVACION = OBSERVACIONIn;
    }

    public String getCUPOSASIGNADOS() {
          return this.CUPOSASIGNADOS;
    }
    public void setCUPOSASIGNADOS(String CUPOSASIGNADOSIn) {
          this.CUPOSASIGNADOS = CUPOSASIGNADOSIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_RANGOCUPOIn,
          int IDEMPRESATRANSPIn,
          int IDTIPOVEHICULOIn,
          String FECHAREGISTROCUPOIn,
          String NRORESOLUCIONIn,
          String FECHARESOLUCIONIn,
          String OBSERVACIONIn,
          String CUPOSASIGNADOSIn) {
          this.ID_RANGOCUPO = ID_RANGOCUPOIn;
          this.IDEMPRESATRANSP = IDEMPRESATRANSPIn;
          this.IDTIPOVEHICULO = IDTIPOVEHICULOIn;
          this.FECHAREGISTROCUPO = FECHAREGISTROCUPOIn;
          this.NRORESOLUCION = NRORESOLUCIONIn;
          this.FECHARESOLUCION = FECHARESOLUCIONIn;
          this.OBSERVACION = OBSERVACIONIn;
          this.CUPOSASIGNADOS = CUPOSASIGNADOSIn;
    }


    /** 
     * hasEqualMapping-method will compare two RangoCuposVehiculoPublico instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(RangoCuposVehiculoPublicoTrans valueObject) {

          if (valueObject.getID_RANGOCUPO() != this.ID_RANGOCUPO) {
                    return(false);
          }
          if (valueObject.getIDEMPRESATRANSP() != this.IDEMPRESATRANSP) {
                    return(false);
          }
          if (valueObject.getIDTIPOVEHICULO() != this.IDTIPOVEHICULO) {
                    return(false);
          }
          if (this.FECHAREGISTROCUPO == null) {
                    if (valueObject.getFECHAREGISTROCUPO() != null)
                           return(false);
          } else if (!this.FECHAREGISTROCUPO.equals(valueObject.getFECHAREGISTROCUPO())) {
                    return(false);
          }
          if (this.NRORESOLUCION == null) {
                    if (valueObject.getNRORESOLUCION() != null)
                           return(false);
          } else if (!this.NRORESOLUCION.equals(valueObject.getNRORESOLUCION())) {
                    return(false);
          }
          if (this.FECHARESOLUCION == null) {
                    if (valueObject.getFECHARESOLUCION() != null)
                           return(false);
          } else if (!this.FECHARESOLUCION.equals(valueObject.getFECHARESOLUCION())) {
                    return(false);
          }
          if (this.OBSERVACION == null) {
                    if (valueObject.getOBSERVACION() != null)
                           return(false);
          } else if (!this.OBSERVACION.equals(valueObject.getOBSERVACION())) {
                    return(false);
          }
          if (this.CUPOSASIGNADOS == null) {
                    if (valueObject.getCUPOSASIGNADOS() != null)
                           return(false);
          } else if (!this.CUPOSASIGNADOS.equals(valueObject.getCUPOSASIGNADOS())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass RangoCuposVehiculoPublico, mapping to table RangoCuposVehiculoPublico\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_RANGOCUPO = " + this.ID_RANGOCUPO + "\n"); 
        out.append("IDEMPRESATRANSP = " + this.IDEMPRESATRANSP + "\n"); 
        out.append("IDTIPOVEHICULO = " + this.IDTIPOVEHICULO + "\n"); 
        out.append("FECHAREGISTROCUPO = " + this.FECHAREGISTROCUPO + "\n"); 
        out.append("NRORESOLUCION = " + this.NRORESOLUCION + "\n"); 
        out.append("FECHARESOLUCION = " + this.FECHARESOLUCION + "\n"); 
        out.append("OBSERVACION = " + this.OBSERVACION + "\n"); 
        out.append("CUPOSASIGNADOS = " + this.CUPOSASIGNADOS + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        RangoCuposVehiculoPublicoTrans cloned = new RangoCuposVehiculoPublicoTrans();

        cloned.setID_RANGOCUPO(this.ID_RANGOCUPO); 
        cloned.setIDEMPRESATRANSP(this.IDEMPRESATRANSP); 
        cloned.setIDTIPOVEHICULO(this.IDTIPOVEHICULO); 
        if (this.FECHAREGISTROCUPO != null)
             cloned.setFECHAREGISTROCUPO(new String(this.FECHAREGISTROCUPO)); 
        if (this.NRORESOLUCION != null)
             cloned.setNRORESOLUCION(new String(this.NRORESOLUCION)); 
        if (this.FECHARESOLUCION != null)
             cloned.setFECHARESOLUCION(new String(this.FECHARESOLUCION)); 
        if (this.OBSERVACION != null)
             cloned.setOBSERVACION(new String(this.OBSERVACION)); 
        if (this.CUPOSASIGNADOS != null)
             cloned.setCUPOSASIGNADOS(new String(this.CUPOSASIGNADOS)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
