package modelo.datos.objetos.transportepublico.cupos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ViewTarjetasCupoTrans Value Object.
  * This class is value object representing database table ViewTarjetasCupoTrans
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewTarjetasCupoTrans implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDCUPO;
    private String NUMERO;
    private String ESTADO;
    private String FECHAVENCIMIENTO;
    private String FECHAREGISTRO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewTarjetasCupoTrans () {

    }

    public ViewTarjetasCupoTrans (int IDCUPOIn) {

          this.IDCUPO = IDCUPOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDCUPO() {
          return this.IDCUPO;
    }
    public void setIDCUPO(int IDCUPOIn) {
          this.IDCUPO = IDCUPOIn;
    }

    public String getNUMERO() {
          return this.NUMERO;
    }
    public void setNUMERO(String NUMEROIn) {
          this.NUMERO = NUMEROIn;
    }

    public String getESTADO() {
          return this.ESTADO;
    }
    public void setESTADO(String ESTADOIn) {
          this.ESTADO = ESTADOIn;
    }

    public String getFECHAVENCIMIENTO() {
          return this.FECHAVENCIMIENTO;
    }
    public void setFECHAVENCIMIENTO(String FECHAVENCIMIENTOIn) {
          this.FECHAVENCIMIENTO = FECHAVENCIMIENTOIn;
    }

    public String getFECHAREGISTRO() {
          return this.FECHAREGISTRO;
    }
    public void setFECHAREGISTRO(String FECHAREGISTROIn) {
          this.FECHAREGISTRO = FECHAREGISTROIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDCUPOIn,
          String NUMEROIn,
          String ESTADOIn,
          String FECHAVENCIMIENTOIn,
          String FECHAREGISTROIn) {
          this.IDCUPO = IDCUPOIn;
          this.NUMERO = NUMEROIn;
          this.ESTADO = ESTADOIn;
          this.FECHAVENCIMIENTO = FECHAVENCIMIENTOIn;
          this.FECHAREGISTRO = FECHAREGISTROIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewTarjetasCupoTrans instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewTarjetasCupoTrans valueObject) {

          if (valueObject.getIDCUPO() != this.IDCUPO) {
                    return(false);
          }
          if (this.NUMERO == null) {
                    if (valueObject.getNUMERO() != null)
                           return(false);
          } else if (!this.NUMERO.equals(valueObject.getNUMERO())) {
                    return(false);
          }
          if (this.ESTADO == null) {
                    if (valueObject.getESTADO() != null)
                           return(false);
          } else if (!this.ESTADO.equals(valueObject.getESTADO())) {
                    return(false);
          }
          if (this.FECHAVENCIMIENTO == null) {
                    if (valueObject.getFECHAVENCIMIENTO() != null)
                           return(false);
          } else if (!this.FECHAVENCIMIENTO.equals(valueObject.getFECHAVENCIMIENTO())) {
                    return(false);
          }
          if (this.FECHAREGISTRO == null) {
                    if (valueObject.getFECHAREGISTRO() != null)
                           return(false);
          } else if (!this.FECHAREGISTRO.equals(valueObject.getFECHAREGISTRO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewTarjetasCupoTrans, mapping to table ViewTarjetasCupoTrans\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDCUPO = " + this.IDCUPO + "\n"); 
        out.append("NUMERO = " + this.NUMERO + "\n"); 
        out.append("ESTADO = " + this.ESTADO + "\n"); 
        out.append("FECHAVENCIMIENTO = " + this.FECHAVENCIMIENTO + "\n"); 
        out.append("FECHAREGISTRO = " + this.FECHAREGISTRO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewTarjetasCupoTrans cloned = new ViewTarjetasCupoTrans();

        cloned.setIDCUPO(this.IDCUPO); 
        if (this.NUMERO != null)
             cloned.setNUMERO(new String(this.NUMERO)); 
        if (this.ESTADO != null)
             cloned.setESTADO(new String(this.ESTADO)); 
        if (this.FECHAVENCIMIENTO != null)
             cloned.setFECHAVENCIMIENTO(new String(this.FECHAVENCIMIENTO)); 
        if (this.FECHAREGISTRO != null)
             cloned.setFECHAREGISTRO(new String(this.FECHAREGISTRO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
