package modelo.datos.dao.generales.vehiculo;



import java.sql.*;
import java.util.*;
import java.math.*;
import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.generales.vehiculo.ViewVehiculo;



 /**
  * ViewVehiculo Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to 
  * permanently store and retrieve ViewVehiculo object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewVehiculoDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public ViewVehiculo createValueObject() {
          return new ViewVehiculo();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public ViewVehiculo getObject(Connection conn, int IDVEHICULO) throws NotFoundException, SQLException {

          ViewVehiculo valueObject = createValueObject();
          valueObject.setIDVEHICULO(IDVEHICULO);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, ViewVehiculo valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM VIEW_VEHICULO WHERE (IDVEHICULO = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getIDVEHICULO()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VIEW_VEHICULO ORDER BY IDVEHICULO ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, ViewVehiculo valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO VIEW_VEHICULO ( IDVEHICULO, PLACA, MARCAVEH, "
               + "LINEAVEH, MODELO, CAPACIDAD, "
               + "POTENCIA, CILINDRAJE, CLASEVEH, "
               + "NUMEROSERIE, NUMEROCHASIS, SERVICIOVEH, "
               + "TIPOCARROCERIA, NUMEROMOTOR, FECHAMATRICULA, "
               + "NUMMANIFIESTO, COLORVEH, NROPUERTAS, "
               + "MOTORREGRABADO, NUMSERIE_REGRABADO, CHASISREGREBADO, "
               + "PESO_BRUTO, DIST_EJES, VOLAD_POSTER, "
               + "NRO_EJES, ANCHO, ALTO, "
               + "LARGO, ACTA, NUM_ACMANIF, "
               + "DES_ADUANA, FECHA_MANIFIESTO, OFICIOTRASLADO, "
               + "NUMFOLIOSTRASLADO, ORGTRANSITO, GENERACERTMOVILIZACION, "
               + "DURACIONCERTMOVILIZACION, CAPACIDADTON, NUMGUIATRASLADOCTA, "
               + "VEHACTIVO"/*, EMPRESADESERICIO*/+") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?"/*, ?*/+") ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getIDVEHICULO()); 
               stmt.setString(2, valueObject.getPLACA()); 
               stmt.setString(3, valueObject.getMARCAVEH()); 
               stmt.setString(4, valueObject.getLINEAVEH()); 
               stmt.setString(5, valueObject.getMODELO()); 
               stmt.setString(6, valueObject.getCAPACIDAD()); 
               stmt.setString(7, valueObject.getPOTENCIA()); 
               stmt.setString(8, valueObject.getCILINDRAJE()); 
               stmt.setString(9, valueObject.getCLASEVEH()); 
               stmt.setString(10, valueObject.getNUMEROSERIE()); 
               stmt.setString(11, valueObject.getNUMEROCHASIS()); 
               stmt.setString(12, valueObject.getSERVICIOVEH()); 
               stmt.setString(13, valueObject.getTIPOCARROCERIA()); 
               stmt.setString(14, valueObject.getNUMEROMOTOR()); 
               stmt.setString(15, valueObject.getFECHAMATRICULA()); 
               stmt.setString(16, valueObject.getNUMMANIFIESTO()); 
               stmt.setString(17, valueObject.getCOLORVEH()); 
               stmt.setString(18, valueObject.getNROPUERTAS()); 
               stmt.setString(19, valueObject.getMOTORREGRABADO()); 
               stmt.setString(20, valueObject.getNUMSERIE_REGRABADO()); 
               stmt.setString(21, valueObject.getCHASISREGREBADO()); 
               stmt.setString(22, valueObject.getPESO_BRUTO()); 
               stmt.setString(23, valueObject.getDIST_EJES()); 
               stmt.setString(24, valueObject.getVOLAD_POSTER()); 
               stmt.setString(25, valueObject.getNRO_EJES()); 
               stmt.setString(26, valueObject.getANCHO()); 
               stmt.setString(27, valueObject.getALTO()); 
               stmt.setString(28, valueObject.getLARGO()); 
               stmt.setString(29, valueObject.getACTA()); 
               stmt.setString(30, valueObject.getNUM_ACMANIF()); 
               stmt.setString(31, valueObject.getDES_ADUANA()); 
               stmt.setString(32, valueObject.getFECHA_MANIFIESTO()); 
               stmt.setString(33, valueObject.getOFICIOTRASLADO()); 
               stmt.setString(34, valueObject.getNUMFOLIOSTRASLADO()); 
               stmt.setString(35, valueObject.getORGTRANSITO()); 
               stmt.setString(36, valueObject.getGENERACERTMOVILIZACION()); 
               stmt.setString(37, valueObject.getDURACIONCERTMOVILIZACION()); 
               stmt.setString(38, valueObject.getCAPACIDADTON()); 
               stmt.setString(39, valueObject.getNUMGUIATRASLADOCTA()); 
               stmt.setString(40, valueObject.getVEHACTIVO()); 
               //stmt.setString(41, valueObject.getEMPRESADESERICIO()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, ViewVehiculo valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE VIEW_VEHICULO SET PLACA = ?, MARCAVEH = ?, LINEAVEH = ?, "
               + "MODELO = ?, CAPACIDAD = ?, POTENCIA = ?, "
               + "CILINDRAJE = ?, CLASEVEH = ?, NUMEROSERIE = ?, "
               + "NUMEROCHASIS = ?, SERVICIOVEH = ?, TIPOCARROCERIA = ?, "
               + "NUMEROMOTOR = ?, FECHAMATRICULA = ?, NUMMANIFIESTO = ?, "
               + "COLORVEH = ?, NROPUERTAS = ?, MOTORREGRABADO = ?, "
               + "NUMSERIE_REGRABADO = ?, CHASISREGREBADO = ?, PESO_BRUTO = ?, "
               + "DIST_EJES = ?, VOLAD_POSTER = ?, NRO_EJES = ?, "
               + "ANCHO = ?, ALTO = ?, LARGO = ?, "
               + "ACTA = ?, NUM_ACMANIF = ?, DES_ADUANA = ?, "
               + "FECHA_MANIFIESTO = ?, OFICIOTRASLADO = ?, NUMFOLIOSTRASLADO = ?, "
               + "ORGTRANSITO = ?, GENERACERTMOVILIZACION = ?, DURACIONCERTMOVILIZACION = ?, "
               + "CAPACIDADTON = ?, NUMGUIATRASLADOCTA = ?, VEHACTIVO = ? "/*, "
               + "EMPRESADESERICIO = ?*/+" WHERE (IDVEHICULO = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPLACA()); 
              stmt.setString(2, valueObject.getMARCAVEH()); 
              stmt.setString(3, valueObject.getLINEAVEH()); 
              stmt.setString(4, valueObject.getMODELO()); 
              stmt.setString(5, valueObject.getCAPACIDAD()); 
              stmt.setString(6, valueObject.getPOTENCIA()); 
              stmt.setString(7, valueObject.getCILINDRAJE()); 
              stmt.setString(8, valueObject.getCLASEVEH()); 
              stmt.setString(9, valueObject.getNUMEROSERIE()); 
              stmt.setString(10, valueObject.getNUMEROCHASIS()); 
              stmt.setString(11, valueObject.getSERVICIOVEH()); 
              stmt.setString(12, valueObject.getTIPOCARROCERIA()); 
              stmt.setString(13, valueObject.getNUMEROMOTOR()); 
              stmt.setString(14, valueObject.getFECHAMATRICULA()); 
              stmt.setString(15, valueObject.getNUMMANIFIESTO()); 
              stmt.setString(16, valueObject.getCOLORVEH()); 
              stmt.setString(17, valueObject.getNROPUERTAS()); 
              stmt.setString(18, valueObject.getMOTORREGRABADO()); 
              stmt.setString(19, valueObject.getNUMSERIE_REGRABADO()); 
              stmt.setString(20, valueObject.getCHASISREGREBADO()); 
              stmt.setString(21, valueObject.getPESO_BRUTO()); 
              stmt.setString(22, valueObject.getDIST_EJES()); 
              stmt.setString(23, valueObject.getVOLAD_POSTER()); 
              stmt.setString(24, valueObject.getNRO_EJES()); 
              stmt.setString(25, valueObject.getANCHO()); 
              stmt.setString(26, valueObject.getALTO()); 
              stmt.setString(27, valueObject.getLARGO()); 
              stmt.setString(28, valueObject.getACTA()); 
              stmt.setString(29, valueObject.getNUM_ACMANIF()); 
              stmt.setString(30, valueObject.getDES_ADUANA()); 
              stmt.setString(31, valueObject.getFECHA_MANIFIESTO()); 
              stmt.setString(32, valueObject.getOFICIOTRASLADO()); 
              stmt.setString(33, valueObject.getNUMFOLIOSTRASLADO()); 
              stmt.setString(34, valueObject.getORGTRANSITO()); 
              stmt.setString(35, valueObject.getGENERACERTMOVILIZACION()); 
              stmt.setString(36, valueObject.getDURACIONCERTMOVILIZACION()); 
              stmt.setString(37, valueObject.getCAPACIDADTON()); 
              stmt.setString(38, valueObject.getNUMGUIATRASLADOCTA()); 
              stmt.setString(39, valueObject.getVEHACTIVO()); 
              //stmt.setString(40, valueObject.getEMPRESADESERICIO()); 

              stmt.setInt(41, valueObject.getIDVEHICULO()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, ViewVehiculo valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM VIEW_VEHICULO WHERE (IDVEHICULO = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getIDVEHICULO()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM VIEW_VEHICULO";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VIEW_VEHICULO";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, ViewVehiculo valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_VEHICULO WHERE 1=1 ");

          if (valueObject.getIDVEHICULO() != 0) {
              if (first) { first = false; }
              sql.append("AND IDVEHICULO = ").append(valueObject.getIDVEHICULO()).append(" ");
          }

          if (valueObject.getPLACA() != null) {
              if (first) { first = false; }
              sql.append("AND PLACA = '").append(valueObject.getPLACA()).append("' ");
          }

          if (valueObject.getMARCAVEH() != null) {
              if (first) { first = false; }
              sql.append("AND MARCAVEH = '").append(valueObject.getMARCAVEH()).append("' ");
          }

          if (valueObject.getLINEAVEH() != null) {
              if (first) { first = false; }
              sql.append("AND LINEAVEH = '").append(valueObject.getLINEAVEH()).append("' ");
          }
          /*
          if (valueObject.getMODELO() != null) {
              if (first) { first = false; }
              sql.append("AND MODELO = '").append(valueObject.getMODELO()).append("' ");
          }*/

          if (valueObject.getCAPACIDAD() != null) {
              if (first) { first = false; }
              sql.append("AND CAPACIDAD = '").append(valueObject.getCAPACIDAD()).append("' ");
          }

          if (valueObject.getPOTENCIA() != null) {
              if (first) { first = false; }
              sql.append("AND POTENCIA = '").append(valueObject.getPOTENCIA()).append("' ");
          }

          if (valueObject.getCILINDRAJE() != null) {
              if (first) { first = false; }
              sql.append("AND CILINDRAJE = '").append(valueObject.getCILINDRAJE()).append("' ");
          }

          if (valueObject.getCLASEVEH() != null) {
              if (first) { first = false; }
              sql.append("AND CLASEVEH = '").append(valueObject.getCLASEVEH()).append("' ");
          }

          if (valueObject.getNUMEROSERIE() != null) {
              if (first) { first = false; }
              sql.append("AND NUMEROSERIE = '").append(valueObject.getNUMEROSERIE()).append("' ");
          }

          if (valueObject.getNUMEROCHASIS() != null) {
              if (first) { first = false; }
              sql.append("AND NUMEROCHASIS = '").append(valueObject.getNUMEROCHASIS()).append("' ");
          }

          if (valueObject.getSERVICIOVEH() != null) {
              if (first) { first = false; }
              sql.append("AND SERVICIOVEH = '").append(valueObject.getSERVICIOVEH()).append("' ");
          }

          if (valueObject.getTIPOCARROCERIA() != null) {
              if (first) { first = false; }
              sql.append("AND TIPOCARROCERIA = '").append(valueObject.getTIPOCARROCERIA()).append("' ");
          }

          if (valueObject.getNUMEROMOTOR() != null) {
              if (first) { first = false; }
              sql.append("AND NUMEROMOTOR = '").append(valueObject.getNUMEROMOTOR()).append("' ");
          }

          if (valueObject.getFECHAMATRICULA() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAMATRICULA = '").append(valueObject.getFECHAMATRICULA()).append("' ");
          }

          if (valueObject.getNUMMANIFIESTO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMMANIFIESTO = '").append(valueObject.getNUMMANIFIESTO()).append("' ");
          }

          if (valueObject.getCOLORVEH() != null) {
              if (first) { first = false; }
              sql.append("AND COLORVEH = '").append(valueObject.getCOLORVEH()).append("' ");
          }
            /*
          if (valueObject.getNROPUERTAS() != null) {
              if (first) { first = false; }
              sql.append("AND NROPUERTAS = '").append(valueObject.getNROPUERTAS()).append("' ");
          }
*/
          if (valueObject.getMOTORREGRABADO() != null) {
              if (first) { first = false; }
              sql.append("AND MOTORREGRABADO = '").append(valueObject.getMOTORREGRABADO()).append("' ");
          }

          if (valueObject.getNUMSERIE_REGRABADO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMSERIE_REGRABADO = '").append(valueObject.getNUMSERIE_REGRABADO()).append("' ");
          }

          if (valueObject.getCHASISREGREBADO() != null) {
              if (first) { first = false; }
              sql.append("AND CHASISREGREBADO = '").append(valueObject.getCHASISREGREBADO()).append("' ");
          }

          if (valueObject.getPESO_BRUTO() != null) {
              if (first) { first = false; }
              sql.append("AND PESO_BRUTO = '").append(valueObject.getPESO_BRUTO()).append("' ");
          }

          if (valueObject.getDIST_EJES() != null) {
              if (first) { first = false; }
              sql.append("AND DIST_EJES = '").append(valueObject.getDIST_EJES()).append("' ");
          }

          if (valueObject.getVOLAD_POSTER() != null) {
              if (first) { first = false; }
              sql.append("AND VOLAD_POSTER = '").append(valueObject.getVOLAD_POSTER()).append("' ");
          }
        /*
          if (valueObject.getNRO_EJES() != null) {
              if (first) { first = false; }
              sql.append("AND NRO_EJES = '").append(valueObject.getNRO_EJES()).append("' ");
          }*/

          if (valueObject.getANCHO() != null) {
              if (first) { first = false; }
              sql.append("AND ANCHO = '").append(valueObject.getANCHO()).append("' ");
          }

          if (valueObject.getALTO() != null) {
              if (first) { first = false; }
              sql.append("AND ALTO = '").append(valueObject.getALTO()).append("' ");
          }

          if (valueObject.getLARGO() != null) {
              if (first) { first = false; }
              sql.append("AND LARGO = '").append(valueObject.getLARGO()).append("' ");
          }

          if (valueObject.getACTA() != null) {
              if (first) { first = false; }
              sql.append("AND ACTA = '").append(valueObject.getACTA()).append("' ");
          }

          if (valueObject.getNUM_ACMANIF() != null) {
              if (first) { first = false; }
              sql.append("AND NUM_ACMANIF = '").append(valueObject.getNUM_ACMANIF()).append("' ");
          }

          if (valueObject.getDES_ADUANA() != null) {
              if (first) { first = false; }
              sql.append("AND DES_ADUANA = '").append(valueObject.getDES_ADUANA()).append("' ");
          }

          if (valueObject.getFECHA_MANIFIESTO() != null) {
              if (first) { first = false; }
              sql.append("AND FECHA_MANIFIESTO = '").append(valueObject.getFECHA_MANIFIESTO()).append("' ");
          }

          if (valueObject.getOFICIOTRASLADO() != null) {
              if (first) { first = false; }
              sql.append("AND OFICIOTRASLADO = '").append(valueObject.getOFICIOTRASLADO()).append("' ");
          }
            /*
          if (valueObject.getNUMFOLIOSTRASLADO() != null) {
              if (first) { first = false; }
              sql.append("AND NUMFOLIOSTRASLADO = '").append(valueObject.getNUMFOLIOSTRASLADO()).append("' ");
          }
            */
          if (valueObject.getORGTRANSITO() != null) {
              if (first) { first = false; }
              sql.append("AND ORGTRANSITO = '").append(valueObject.getORGTRANSITO()).append("' ");
          }

          if (valueObject.getGENERACERTMOVILIZACION() != null) {
              if (first) { first = false; }
              sql.append("AND GENERACERTMOVILIZACION = '").append(valueObject.getGENERACERTMOVILIZACION()).append("' ");
          }
/*
          if (valueObject.getDURACIONCERTMOVILIZACION() != null) {
              if (first) { first = false; }
              sql.append("AND DURACIONCERTMOVILIZACION = '").append(valueObject.getDURACIONCERTMOVILIZACION()).append("' ");
          }
*/
          if (valueObject.getCAPACIDADTON() != null) {
              if (first) { first = false; }
              sql.append("AND CAPACIDADTON = '").append(valueObject.getCAPACIDADTON()).append("' ");
          }

          if (valueObject.getNUMGUIATRASLADOCTA() != null) {
              if (first) { first = false; }
              sql.append("AND NUMGUIATRASLADOCTA = '").append(valueObject.getNUMGUIATRASLADOCTA()).append("' ");
          }

          if (valueObject.getVEHACTIVO() != null) {
              if (first) { first = false; }
              sql.append("AND VEHACTIVO = '").append(valueObject.getVEHACTIVO()).append("' ");
          }

          if (valueObject.getVEHACTIVO() != null) {
              if (first) { first = false; }
              sql.append("AND VEHACTIVO = '").append(valueObject.getVEHACTIVO()).append("' ");
          }

          
          /*if (valueObject.getT_COMBUSTIBLE()!= null) {
              if (first) { first = false; }
              sql.append("AND T_COMBUSTIBLE = '").append(valueObject.getT_COMBUSTIBLE()).append("' ");
          }*/


          sql.append("ORDER BY IDVEHICULO ASC ");
          System.out.println(sql.toString());
          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, ViewVehiculo valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setIDVEHICULO(result.getInt("IDVEHICULO")); 
                   valueObject.setPLACA(result.getString("PLACA")); 
                   valueObject.setMARCAVEH(result.getString("MARCAVEH")); 
                   valueObject.setLINEAVEH(result.getString("LINEAVEH")); 
                   valueObject.setMODELO(result.getString("MODELO")); 
                   valueObject.setCAPACIDAD(result.getString("CAPACIDAD")); 
                   valueObject.setPOTENCIA(result.getString("POTENCIA")); 
                   valueObject.setCILINDRAJE(result.getString("CILINDRAJE")); 
                   valueObject.setCLASEVEH(result.getString("CLASEVEH")); 
                   valueObject.setNUMEROSERIE(result.getString("NUMEROSERIE")); 
                   valueObject.setNUMEROCHASIS(result.getString("NUMEROCHASIS")); 
                   valueObject.setSERVICIOVEH(result.getString("SERVICIOVEH")); 
                   valueObject.setTIPOCARROCERIA(result.getString("TIPOCARROCERIA")); 
                   valueObject.setNUMEROMOTOR(result.getString("NUMEROMOTOR")); 
                   valueObject.setFECHAMATRICULA(result.getString("FECHAMATRICULA")); 
                   valueObject.setNUMMANIFIESTO(result.getString("NUMMANIFIESTO")); 
                   valueObject.setCOLORVEH(result.getString("COLORVEH")); 
                   valueObject.setNROPUERTAS(result.getString("NROPUERTAS")); 
                   valueObject.setMOTORREGRABADO(result.getString("MOTORREGRABADO")); 
                   valueObject.setNUMSERIE_REGRABADO(result.getString("NUMSERIE_REGRABADO")); 
                   valueObject.setCHASISREGREBADO(result.getString("CHASISREGREBADO")); 
                   valueObject.setPESO_BRUTO(result.getString("PESO_BRUTO")); 
                   valueObject.setDIST_EJES(result.getString("DIST_EJES")); 
                   valueObject.setVOLAD_POSTER(result.getString("VOLAD_POSTER")); 
                   valueObject.setNRO_EJES(result.getString("NRO_EJES")); 
                   valueObject.setANCHO(result.getString("ANCHO")); 
                   valueObject.setALTO(result.getString("ALTO")); 
                   valueObject.setLARGO(result.getString("LARGO")); 
                   valueObject.setACTA(result.getString("ACTA")); 
                   valueObject.setNUM_ACMANIF(result.getString("NUM_ACMANIF")); 
                   valueObject.setDES_ADUANA(result.getString("DES_ADUANA")); 
                   valueObject.setFECHA_MANIFIESTO(result.getString("FECHA_MANIFIESTO")); 
                   valueObject.setOFICIOTRASLADO(result.getString("OFICIOTRASLADO")); 
                   valueObject.setNUMFOLIOSTRASLADO(result.getString("NUMFOLIOSTRASLADO")); 
                   valueObject.setORGTRANSITO(result.getString("ORGTRANSITO")); 
                   valueObject.setGENERACERTMOVILIZACION(result.getString("GENERACERTMOVILIZACION")); 
                   valueObject.setDURACIONCERTMOVILIZACION(result.getString("DURACIONCERTMOVILIZACION")); 
                   valueObject.setCAPACIDADTON(result.getString("CAPACIDADTON")); 
                   valueObject.setNUMGUIATRASLADOCTA(result.getString("NUMGUIATRASLADOCTA")); 
                   valueObject.setVEHACTIVO(result.getString("VEHACTIVO")); 
                   valueObject.setT_COMBUSTIBLE(result.getString("T_COMBUSTIBLE")); 

              } else {
                    //System.out.println("ViewVehiculo Object Not Found!");
                    throw new NotFoundException("ViewVehiculo Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   ViewVehiculo temp = createValueObject();

                   temp.setIDVEHICULO(result.getInt("IDVEHICULO")); 
                   temp.setPLACA(result.getString("PLACA")); 
                   temp.setMARCAVEH(result.getString("MARCAVEH")); 
                   temp.setLINEAVEH(result.getString("LINEAVEH")); 
                   temp.setMODELO(result.getString("MODELO")); 
                   temp.setCAPACIDAD(result.getString("CAPACIDAD")); 
                   temp.setPOTENCIA(result.getString("POTENCIA")); 
                   temp.setCILINDRAJE(result.getString("CILINDRAJE")); 
                   temp.setCLASEVEH(result.getString("CLASEVEH")); 
                   temp.setNUMEROSERIE(result.getString("NUMEROSERIE")); 
                   temp.setNUMEROCHASIS(result.getString("NUMEROCHASIS")); 
                   temp.setSERVICIOVEH(result.getString("SERVICIOVEH")); 
                   temp.setTIPOCARROCERIA(result.getString("TIPOCARROCERIA")); 
                   temp.setNUMEROMOTOR(result.getString("NUMEROMOTOR")); 
                   temp.setFECHAMATRICULA(result.getString("FECHAMATRICULA")); 
                   temp.setNUMMANIFIESTO(result.getString("NUMMANIFIESTO")); 
                   temp.setCOLORVEH(result.getString("COLORVEH")); 
                   temp.setNROPUERTAS(result.getString("NROPUERTAS")); 
                   temp.setMOTORREGRABADO(result.getString("MOTORREGRABADO")); 
                   temp.setNUMSERIE_REGRABADO(result.getString("NUMSERIE_REGRABADO")); 
                   temp.setCHASISREGREBADO(result.getString("CHASISREGREBADO")); 
                   temp.setPESO_BRUTO(result.getString("PESO_BRUTO")); 
                   temp.setDIST_EJES(result.getString("DIST_EJES")); 
                   temp.setVOLAD_POSTER(result.getString("VOLAD_POSTER")); 
                   temp.setNRO_EJES(result.getString("NRO_EJES")); 
                   temp.setANCHO(result.getString("ANCHO")); 
                   temp.setALTO(result.getString("ALTO")); 
                   temp.setLARGO(result.getString("LARGO")); 
                   temp.setACTA(result.getString("ACTA")); 
                   temp.setNUM_ACMANIF(result.getString("NUM_ACMANIF")); 
                   temp.setDES_ADUANA(result.getString("DES_ADUANA")); 
                   temp.setFECHA_MANIFIESTO(result.getString("FECHA_MANIFIESTO")); 
                   temp.setOFICIOTRASLADO(result.getString("OFICIOTRASLADO")); 
                   temp.setNUMFOLIOSTRASLADO(result.getString("NUMFOLIOSTRASLADO")); 
                   temp.setORGTRANSITO(result.getString("ORGTRANSITO")); 
                   temp.setGENERACERTMOVILIZACION(result.getString("GENERACERTMOVILIZACION")); 
                   temp.setDURACIONCERTMOVILIZACION(result.getString("DURACIONCERTMOVILIZACION")); 
                   temp.setCAPACIDADTON(result.getString("CAPACIDADTON")); 
                   temp.setNUMGUIATRASLADOCTA(result.getString("NUMGUIATRASLADOCTA")); 
                   temp.setVEHACTIVO(result.getString("VEHACTIVO")); 
                   temp.setEMPRESADESERICIO(result.getString("EMPRESADESERICIO")); 
                   temp.setT_COMBUSTIBLE(result.getString("T_COMBUSTIBLE")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}

