package modelo.datos.dao.generales.vehiculo;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ViewInfoVehiculoPlano Value Object.
  * This class is value object representing database table VIEW_INFOVEHICULOPLANO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewInfoVehiculoPlano implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int id_vehiculo;
    private String placa;
    private String marcaveh;
    private int id_motivocancelacion;
    private int idorg_trasladocta;
    private String lineaveh;
    private String des_color;
    private String id_marca;
    private String fechareg;
    private String codnummarca;
    private int id_linea;
    private int modelo;
    private String cilindraje;
    private String nro_motor;
    private String serie_motor;
    private String chasis;
    private String cod_docto;
    private String cod_orgexpide;
    private String numdocto;
    private String fechadocto;
    private int id_cvehiculo;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewInfoVehiculoPlano () {

    }

    public ViewInfoVehiculoPlano (int id_vehiculoIn) {

          this.id_vehiculo = id_vehiculoIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getId_vehiculo() {
          return this.id_vehiculo;
    }
    public void setId_vehiculo(int id_vehiculoIn) {
          this.id_vehiculo = id_vehiculoIn;
    }

    public String getPlaca() {
          return this.placa;
    }
    public void setPlaca(String placaIn) {
          this.placa = placaIn;
    }

    public String getMarcaveh() {
          return this.marcaveh;
    }
    public void setMarcaveh(String marcavehIn) {
          this.marcaveh = marcavehIn;
    }

    public int getId_motivocancelacion() {
          return this.id_motivocancelacion;
    }
    public void setId_motivocancelacion(int id_motivocancelacionIn) {
          this.id_motivocancelacion = id_motivocancelacionIn;
    }

    public int getIdorg_trasladocta() {
          return this.idorg_trasladocta;
    }
    public void setIdorg_trasladocta(int idorg_trasladoctaIn) {
          this.idorg_trasladocta = idorg_trasladoctaIn;
    }

    public String getLineaveh() {
          return this.lineaveh;
    }
    public void setLineaveh(String lineavehIn) {
          this.lineaveh = lineavehIn;
    }

    public String getDes_color() {
          return this.des_color;
    }
    public void setDes_color(String des_colorIn) {
          this.des_color = des_colorIn;
    }

    public String getId_marca() {
          return this.id_marca;
    }
    public void setId_marca(String id_marcaIn) {
          this.id_marca = id_marcaIn;
    }

    public String getFechareg() {
          return this.fechareg;
    }
    public void setFechareg(String fecharegIn) {
          this.fechareg = fecharegIn;
    }

    public String getCodnummarca() {
          return this.codnummarca;
    }
    public void setCodnummarca(String codnummarcaIn) {
          this.codnummarca = codnummarcaIn;
    }

    public int getId_linea() {
          return this.id_linea;
    }
    public void setId_linea(int id_lineaIn) {
          this.id_linea = id_lineaIn;
    }

    public int getModelo() {
          return this.modelo;
    }
    public void setModelo(int modeloIn) {
          this.modelo = modeloIn;
    }

    public String getCilindraje() {
          return this.cilindraje;
    }
    public void setCilindraje(String cilindrajeIn) {
          this.cilindraje = cilindrajeIn;
    }

    public String getNro_motor() {
          return this.nro_motor;
    }
    public void setNro_motor(String nro_motorIn) {
          this.nro_motor = nro_motorIn;
    }

    public String getSerie_motor() {
          return this.serie_motor;
    }
    public void setSerie_motor(String serie_motorIn) {
          this.serie_motor = serie_motorIn;
    }

    public String getChasis() {
          return this.chasis;
    }
    public void setChasis(String chasisIn) {
          this.chasis = chasisIn;
    }

    public String getCod_docto() {
          return this.cod_docto;
    }
    public void setCod_docto(String cod_doctoIn) {
          this.cod_docto = cod_doctoIn;
    }

    public String getCod_orgexpide() {
          return this.cod_orgexpide;
    }
    public void setCod_orgexpide(String cod_orgexpideIn) {
          this.cod_orgexpide = cod_orgexpideIn;
    }

    public String getNumdocto() {
          return this.numdocto;
    }
    public void setNumdocto(String numdoctoIn) {
          this.numdocto = numdoctoIn;
    }

    public String getFechadocto() {
          return this.fechadocto;
    }
    public void setFechadocto(String fechadoctoIn) {
          this.fechadocto = fechadoctoIn;
    }

    public int getId_cvehiculo() {
          return this.id_cvehiculo;
    }
    public void setId_cvehiculo(int id_cvehiculoIn) {
          this.id_cvehiculo = id_cvehiculoIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int id_vehiculoIn,
          String placaIn,
          String marcavehIn,
          int id_motivocancelacionIn,
          int idorg_trasladoctaIn,
          String lineavehIn,
          String des_colorIn,
          String id_marcaIn,
          String fecharegIn,
          String codnummarcaIn,
          int id_lineaIn,
          int modeloIn,
          String cilindrajeIn,
          String nro_motorIn,
          String serie_motorIn,
          String chasisIn,
          String cod_doctoIn,
          String cod_orgexpideIn,
          String numdoctoIn,
          String fechadoctoIn,
          int id_cvehiculoIn) {
          this.id_vehiculo = id_vehiculoIn;
          this.placa = placaIn;
          this.marcaveh = marcavehIn;
          this.id_motivocancelacion = id_motivocancelacionIn;
          this.idorg_trasladocta = idorg_trasladoctaIn;
          this.lineaveh = lineavehIn;
          this.des_color = des_colorIn;
          this.id_marca = id_marcaIn;
          this.fechareg = fecharegIn;
          this.codnummarca = codnummarcaIn;
          this.id_linea = id_lineaIn;
          this.modelo = modeloIn;
          this.cilindraje = cilindrajeIn;
          this.nro_motor = nro_motorIn;
          this.serie_motor = serie_motorIn;
          this.chasis = chasisIn;
          this.cod_docto = cod_doctoIn;
          this.cod_orgexpide = cod_orgexpideIn;
          this.numdocto = numdoctoIn;
          this.fechadocto = fechadoctoIn;
          this.id_cvehiculo = id_cvehiculoIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewInfoVehiculoPlano instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewInfoVehiculoPlano valueObject) {

          if (valueObject.getId_vehiculo() != this.id_vehiculo) {
                    return(false);
          }
          if (this.placa == null) {
                    if (valueObject.getPlaca() != null)
                           return(false);
          } else if (!this.placa.equals(valueObject.getPlaca())) {
                    return(false);
          }
          if (this.marcaveh == null) {
                    if (valueObject.getMarcaveh() != null)
                           return(false);
          } else if (!this.marcaveh.equals(valueObject.getMarcaveh())) {
                    return(false);
          }
          if (valueObject.getId_motivocancelacion() != this.id_motivocancelacion) {
                    return(false);
          }
          if (valueObject.getIdorg_trasladocta() != this.idorg_trasladocta) {
                    return(false);
          }
          if (this.lineaveh == null) {
                    if (valueObject.getLineaveh() != null)
                           return(false);
          } else if (!this.lineaveh.equals(valueObject.getLineaveh())) {
                    return(false);
          }
          if (this.des_color == null) {
                    if (valueObject.getDes_color() != null)
                           return(false);
          } else if (!this.des_color.equals(valueObject.getDes_color())) {
                    return(false);
          }
          if (this.id_marca == null) {
                    if (valueObject.getId_marca() != null)
                           return(false);
          } else if (!this.id_marca.equals(valueObject.getId_marca())) {
                    return(false);
          }
          if (this.fechareg == null) {
                    if (valueObject.getFechareg() != null)
                           return(false);
          } else if (!this.fechareg.equals(valueObject.getFechareg())) {
                    return(false);
          }
          if (this.codnummarca == null) {
                    if (valueObject.getCodnummarca() != null)
                           return(false);
          } else if (!this.codnummarca.equals(valueObject.getCodnummarca())) {
                    return(false);
          }
          if (valueObject.getId_linea() != this.id_linea) {
                    return(false);
          }
          if (valueObject.getModelo() != this.modelo) {
                    return(false);
          }
          if (this.cilindraje == null) {
                    if (valueObject.getCilindraje() != null)
                           return(false);
          } else if (!this.cilindraje.equals(valueObject.getCilindraje())) {
                    return(false);
          }
          if (this.nro_motor == null) {
                    if (valueObject.getNro_motor() != null)
                           return(false);
          } else if (!this.nro_motor.equals(valueObject.getNro_motor())) {
                    return(false);
          }
          if (this.serie_motor == null) {
                    if (valueObject.getSerie_motor() != null)
                           return(false);
          } else if (!this.serie_motor.equals(valueObject.getSerie_motor())) {
                    return(false);
          }
          if (this.chasis == null) {
                    if (valueObject.getChasis() != null)
                           return(false);
          } else if (!this.chasis.equals(valueObject.getChasis())) {
                    return(false);
          }
          if (this.cod_docto == null) {
                    if (valueObject.getCod_docto() != null)
                           return(false);
          } else if (!this.cod_docto.equals(valueObject.getCod_docto())) {
                    return(false);
          }
          if (this.cod_orgexpide == null) {
                    if (valueObject.getCod_orgexpide() != null)
                           return(false);
          } else if (!this.cod_orgexpide.equals(valueObject.getCod_orgexpide())) {
                    return(false);
          }
          if (this.numdocto == null) {
                    if (valueObject.getNumdocto() != null)
                           return(false);
          } else if (!this.numdocto.equals(valueObject.getNumdocto())) {
                    return(false);
          }
          if (this.fechadocto == null) {
                    if (valueObject.getFechadocto() != null)
                           return(false);
          } else if (!this.fechadocto.equals(valueObject.getFechadocto())) {
                    return(false);
          }
          if (valueObject.getId_cvehiculo() != this.id_cvehiculo) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewInfoVehiculoPlano, mapping to table VIEW_INFOVEHICULOPLANO\n");
        out.append("Persistent attributes: \n"); 
        out.append("id_vehiculo = " + this.id_vehiculo + "\n"); 
        out.append("placa = " + this.placa + "\n"); 
        out.append("marcaveh = " + this.marcaveh + "\n"); 
        out.append("id_motivocancelacion = " + this.id_motivocancelacion + "\n"); 
        out.append("idorg_trasladocta = " + this.idorg_trasladocta + "\n"); 
        out.append("lineaveh = " + this.lineaveh + "\n"); 
        out.append("des_color = " + this.des_color + "\n"); 
        out.append("id_marca = " + this.id_marca + "\n"); 
        out.append("fechareg = " + this.fechareg + "\n"); 
        out.append("codnummarca = " + this.codnummarca + "\n"); 
        out.append("id_linea = " + this.id_linea + "\n"); 
        out.append("modelo = " + this.modelo + "\n"); 
        out.append("cilindraje = " + this.cilindraje + "\n"); 
        out.append("nro_motor = " + this.nro_motor + "\n"); 
        out.append("serie_motor = " + this.serie_motor + "\n"); 
        out.append("chasis = " + this.chasis + "\n"); 
        out.append("cod_docto = " + this.cod_docto + "\n"); 
        out.append("cod_orgexpide = " + this.cod_orgexpide + "\n"); 
        out.append("numdocto = " + this.numdocto + "\n"); 
        out.append("fechadocto = " + this.fechadocto + "\n"); 
        out.append("id_cvehiculo = " + this.id_cvehiculo + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewInfoVehiculoPlano cloned = new ViewInfoVehiculoPlano();

        cloned.setId_vehiculo(this.id_vehiculo); 
        if (this.placa != null)
             cloned.setPlaca(new String(this.placa)); 
        if (this.marcaveh != null)
             cloned.setMarcaveh(new String(this.marcaveh)); 
        cloned.setId_motivocancelacion(this.id_motivocancelacion); 
        cloned.setIdorg_trasladocta(this.idorg_trasladocta); 
        if (this.lineaveh != null)
             cloned.setLineaveh(new String(this.lineaveh)); 
        if (this.des_color != null)
             cloned.setDes_color(new String(this.des_color)); 
        if (this.id_marca != null)
             cloned.setId_marca(new String(this.id_marca)); 
        if (this.fechareg != null)
             cloned.setFechareg(new String(this.fechareg)); 
        if (this.codnummarca != null)
             cloned.setCodnummarca(new String(this.codnummarca)); 
        cloned.setId_linea(this.id_linea); 
        cloned.setModelo(this.modelo); 
        if (this.cilindraje != null)
             cloned.setCilindraje(new String(this.cilindraje)); 
        if (this.nro_motor != null)
             cloned.setNro_motor(new String(this.nro_motor)); 
        if (this.serie_motor != null)
             cloned.setSerie_motor(new String(this.serie_motor)); 
        if (this.chasis != null)
             cloned.setChasis(new String(this.chasis)); 
        if (this.cod_docto != null)
             cloned.setCod_docto(new String(this.cod_docto)); 
        if (this.cod_orgexpide != null)
             cloned.setCod_orgexpide(new String(this.cod_orgexpide)); 
        if (this.numdocto != null)
             cloned.setNumdocto(new String(this.numdocto)); 
        if (this.fechadocto != null)
             cloned.setFechadocto(new String(this.fechadocto)); 
        cloned.setId_cvehiculo(this.id_cvehiculo); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}