package modelo.datos.objetos.comparendos.liquidacion.tarifas;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * LVigenciasComp Value Object.
  * This class is value object representing database table LVigenciasComp
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class LVigenciasComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int LTV_ID;
    private int LTV_VIGENCIA;
    private int LTV_TIPO;
    private String LTV_DESCRIPCION;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public LVigenciasComp () {

    }

    public LVigenciasComp (int LTV_IDIn) {

          this.LTV_ID = LTV_IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getLTV_ID() {
          return this.LTV_ID;
    }
    public void setLTV_ID(int LTV_IDIn) {
          this.LTV_ID = LTV_IDIn;
    }

    public int getLTV_VIGENCIA() {
          return this.LTV_VIGENCIA;
    }
    public void setLTV_VIGENCIA(int LTV_VIGENCIAIn) {
          this.LTV_VIGENCIA = LTV_VIGENCIAIn;
    }

    public int getLTV_TIPO() {
          return this.LTV_TIPO;
    }
    public void setLTV_TIPO(int LTV_TIPOIn) {
          this.LTV_TIPO = LTV_TIPOIn;
    }

    public String getLTV_DESCRIPCION() {
          return this.LTV_DESCRIPCION;
    }
    public void setLTV_DESCRIPCION(String LTV_DESCRIPCIONIn) {
          this.LTV_DESCRIPCION = LTV_DESCRIPCIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int LTV_IDIn,
          int LTV_VIGENCIAIn,
          int LTV_TIPOIn,
          String LTV_DESCRIPCIONIn) {
          this.LTV_ID = LTV_IDIn;
          this.LTV_VIGENCIA = LTV_VIGENCIAIn;
          this.LTV_TIPO = LTV_TIPOIn;
          this.LTV_DESCRIPCION = LTV_DESCRIPCIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two LVigenciasComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(LVigenciasComp valueObject) {

          if (valueObject.getLTV_ID() != this.LTV_ID) {
                    return(false);
          }
          if (valueObject.getLTV_VIGENCIA() != this.LTV_VIGENCIA) {
                    return(false);
          }
          if (valueObject.getLTV_TIPO() != this.LTV_TIPO) {
                    return(false);
          }
          if (this.LTV_DESCRIPCION == null) {
                    if (valueObject.getLTV_DESCRIPCION() != null)
                           return(false);
          } else if (!this.LTV_DESCRIPCION.equals(valueObject.getLTV_DESCRIPCION())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass LVigenciasComp, mapping to table LVigenciasComp\n");
        out.append("Persistent attributes: \n"); 
        out.append("LTV_ID = " + this.LTV_ID + "\n"); 
        out.append("LTV_VIGENCIA = " + this.LTV_VIGENCIA + "\n"); 
        out.append("LTV_TIPO = " + this.LTV_TIPO + "\n"); 
        out.append("LTV_DESCRIPCION = " + this.LTV_DESCRIPCION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        LVigenciasComp cloned = new LVigenciasComp();

        cloned.setLTV_ID(this.LTV_ID); 
        cloned.setLTV_VIGENCIA(this.LTV_VIGENCIA); 
        cloned.setLTV_TIPO(this.LTV_TIPO); 
        if (this.LTV_DESCRIPCION != null)
             cloned.setLTV_DESCRIPCION(new String(this.LTV_DESCRIPCION)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
