package modelo.datos.dao.comparendos.planos;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.comparendos.planos.ViewInfractorComparendo;


import java.sql.*;
import java.util.*;
import java.math.*;


 /**
  * ViewInfractorComparendo Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to 
  * permanently store and retrieve ViewInfractorComparendo object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewInfractorComparendoDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public ViewInfractorComparendo createValueObject() {
          return new ViewInfractorComparendo();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public ViewInfractorComparendo getObject(Connection conn, String NROIDENTIFICACION) throws NotFoundException, SQLException {

          ViewInfractorComparendo valueObject = createValueObject();
          valueObject.setNROIDENTIFICACION(NROIDENTIFICACION);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, ViewInfractorComparendo valueObject) throws NotFoundException, SQLException {

          if (valueObject.getNROIDENTIFICACION() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          String sql = "SELECT * FROM VIEW_INFRACTOR_COMPARENDO WHERE (NROIDENTIFICACION = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getNROIDENTIFICACION()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VIEW_INFRACTOR_COMPARENDO ORDER BY NROIDENTIFICACION ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, ViewInfractorComparendo valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO VIEW_INFRACTOR_COMPARENDO ( NROIDENTIFICACION, IDREPORTECOMPARENDO, ID_INFRACTOR, "
               + "NOMBRES, APELLIDOS, DIRECCION, "
               + "EDAD, EMAIL, TELEFONO, "
               + "CODCIUDAD, ID_DEPTO, NROLICCONDUCCION, "
               + "COD_CATEGORIA, NIT, ID_TRANSITO, "
               + "FECHAVENCELICCONDUCCION, CODTIPOINFRACTOR, NUEVA_CATEGORIA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setString(1, valueObject.getNROIDENTIFICACION()); 
               stmt.setString(2, valueObject.getIDREPORTECOMPARENDO()); 
               stmt.setString(3, valueObject.getID_INFRACTOR()); 
               stmt.setString(4, valueObject.getNOMBRES()); 
               stmt.setString(5, valueObject.getAPELLIDOS()); 
               stmt.setString(6, valueObject.getDIRECCION()); 
               stmt.setString(7, valueObject.getEDAD()); 
               stmt.setString(8, valueObject.getEMAIL()); 
               stmt.setString(9, valueObject.getTELEFONO()); 
               stmt.setString(10, valueObject.getCODCIUDAD()); 
               stmt.setString(11, valueObject.getID_DEPTO()); 
               stmt.setString(12, valueObject.getNROLICCONDUCCION()); 
               stmt.setString(13, valueObject.getCOD_CATEGORIA()); 
               stmt.setString(14, valueObject.getNIT()); 
               stmt.setString(15, valueObject.getID_TRANSITO()); 
               stmt.setString(16, valueObject.getFECHAVENCELICCONDUCCION()); 
               stmt.setString(17, valueObject.getCODTIPOINFRACTOR()); 
               stmt.setString(18, valueObject.getNUEVA_CATEGORIA()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, ViewInfractorComparendo valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE VIEW_INFRACTOR_COMPARENDO SET IDREPORTECOMPARENDO = ?, ID_INFRACTOR = ?, NOMBRES = ?, "
               + "APELLIDOS = ?, DIRECCION = ?, EDAD = ?, "
               + "EMAIL = ?, TELEFONO = ?, CODCIUDAD = ?, "
               + "ID_DEPTO = ?, NROLICCONDUCCION = ?, COD_CATEGORIA = ?, "
               + "NIT = ?, ID_TRANSITO = ?, FECHAVENCELICCONDUCCION = ?, "
               + "CODTIPOINFRACTOR = ?, NUEVA_CATEGORIA = ? WHERE (NROIDENTIFICACION = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getIDREPORTECOMPARENDO()); 
              stmt.setString(2, valueObject.getID_INFRACTOR()); 
              stmt.setString(3, valueObject.getNOMBRES()); 
              stmt.setString(4, valueObject.getAPELLIDOS()); 
              stmt.setString(5, valueObject.getDIRECCION()); 
              stmt.setString(6, valueObject.getEDAD()); 
              stmt.setString(7, valueObject.getEMAIL()); 
              stmt.setString(8, valueObject.getTELEFONO()); 
              stmt.setString(9, valueObject.getCODCIUDAD()); 
              stmt.setString(10, valueObject.getID_DEPTO()); 
              stmt.setString(11, valueObject.getNROLICCONDUCCION()); 
              stmt.setString(12, valueObject.getCOD_CATEGORIA()); 
              stmt.setString(13, valueObject.getNIT()); 
              stmt.setString(14, valueObject.getID_TRANSITO()); 
              stmt.setString(15, valueObject.getFECHAVENCELICCONDUCCION()); 
              stmt.setString(16, valueObject.getCODTIPOINFRACTOR()); 
              stmt.setString(17, valueObject.getNUEVA_CATEGORIA());
              stmt.setString(18, valueObject.getNROIDENTIFICACION()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, ViewInfractorComparendo valueObject) 
          throws NotFoundException, SQLException {

          if (valueObject.getNROIDENTIFICACION() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          String sql = "DELETE FROM VIEW_INFRACTOR_COMPARENDO WHERE (NROIDENTIFICACION = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getNROIDENTIFICACION()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM VIEW_INFRACTOR_COMPARENDO";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VIEW_INFRACTOR_COMPARENDO";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, ViewInfractorComparendo valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_INFRACTOR_COMPARENDO WHERE 1=1 ");

          if (valueObject.getNROIDENTIFICACION() != null) {
              if (first) { first = false; }
              sql.append("AND NROIDENTIFICACION = '").append(valueObject.getNROIDENTIFICACION()).append("' ");
          }

          if (valueObject.getIDREPORTECOMPARENDO() != null) {
              if (first) { first = false; }
              sql.append("AND IDREPORTECOMPARENDO = '").append(valueObject.getIDREPORTECOMPARENDO()).append("' ");
          }

          if (valueObject.getID_INFRACTOR() != null) {
              if (first) { first = false; }
              sql.append("AND ID_INFRACTOR = '").append(valueObject.getID_INFRACTOR()).append("' ");
          }

          if (valueObject.getNOMBRES() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRES = '").append(valueObject.getNOMBRES()).append("' ");
          }

          if (valueObject.getAPELLIDOS() != null) {
              if (first) { first = false; }
              sql.append("AND APELLIDOS = '").append(valueObject.getAPELLIDOS()).append("' ");
          }

          if (valueObject.getDIRECCION() != null) {
              if (first) { first = false; }
              sql.append("AND DIRECCION = '").append(valueObject.getDIRECCION()).append("' ");
          }

          if (valueObject.getEDAD() != null) {
              if (first) { first = false; }
              sql.append("AND EDAD = '").append(valueObject.getEDAD()).append("' ");
          }

          if (valueObject.getEMAIL() != null) {
              if (first) { first = false; }
              sql.append("AND EMAIL = '").append(valueObject.getEMAIL()).append("' ");
          }

          if (valueObject.getTELEFONO() != null) {
              if (first) { first = false; }
              sql.append("AND TELEFONO = '").append(valueObject.getTELEFONO()).append("' ");
          }

          if (valueObject.getCODCIUDAD() != null) {
              if (first) { first = false; }
              sql.append("AND CODCIUDAD = '").append(valueObject.getCODCIUDAD()).append("' ");
          }

          if (valueObject.getID_DEPTO() != null) {
              if (first) { first = false; }
              sql.append("AND ID_DEPTO = '").append(valueObject.getID_DEPTO()).append("' ");
          }

          if (valueObject.getNROLICCONDUCCION() != null) {
              if (first) { first = false; }
              sql.append("AND NROLICCONDUCCION = '").append(valueObject.getNROLICCONDUCCION()).append("' ");
          }

          if (valueObject.getCOD_CATEGORIA() != null) {
              if (first) { first = false; }
              sql.append("AND COD_CATEGORIA = '").append(valueObject.getCOD_CATEGORIA()).append("' ");
          }

          if (valueObject.getNIT() != null) {
              if (first) { first = false; }
              sql.append("AND NIT = '").append(valueObject.getNIT()).append("' ");
          }

          if (valueObject.getID_TRANSITO() != null) {
              if (first) { first = false; }
              sql.append("AND ID_TRANSITO = '").append(valueObject.getID_TRANSITO()).append("' ");
          }

          if (valueObject.getFECHAVENCELICCONDUCCION() != null) {
              if (first) { first = false; }
              sql.append("AND FECHAVENCELICCONDUCCION = '").append(valueObject.getFECHAVENCELICCONDUCCION()).append("' ");
          }

          if (valueObject.getCODTIPOINFRACTOR() != null) {
              if (first) { first = false; }
              sql.append("AND CODTIPOINFRACTOR = '").append(valueObject.getCODTIPOINFRACTOR()).append("' ");
          }
          
          if (valueObject.getNUEVA_CATEGORIA() != null) {
              if (first) { first = false; }
              sql.append("AND NUEVA_CATEGORIA = '").append(valueObject.getNUEVA_CATEGORIA()).append("' ");
          }


          sql.append("ORDER BY NROIDENTIFICACION ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, ViewInfractorComparendo valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setNROIDENTIFICACION(result.getString("NROIDENTIFICACION")); 
                   valueObject.setIDREPORTECOMPARENDO(result.getString("IDREPORTECOMPARENDO")); 
                   valueObject.setID_INFRACTOR(result.getString("ID_INFRACTOR")); 
                   valueObject.setNOMBRES(result.getString("NOMBRES")); 
                   valueObject.setAPELLIDOS(result.getString("APELLIDOS")); 
                   valueObject.setDIRECCION(result.getString("DIRECCION")); 
                   valueObject.setEDAD(result.getString("EDAD")); 
                   valueObject.setEMAIL(result.getString("EMAIL")); 
                   valueObject.setTELEFONO(result.getString("TELEFONO")); 
                   valueObject.setCODCIUDAD(result.getString("CODCIUDAD")); 
                   valueObject.setID_DEPTO(result.getString("ID_DEPTO")); 
                   valueObject.setNROLICCONDUCCION(result.getString("NROLICCONDUCCION")); 
                   valueObject.setCOD_CATEGORIA(result.getString("COD_CATEGORIA")); 
                   valueObject.setNIT(result.getString("NIT")); 
                   valueObject.setID_TRANSITO(result.getString("ID_TRANSITO")); 
                   valueObject.setFECHAVENCELICCONDUCCION(result.getString("FECHAVENCELICCONDUCCION")); 
                   valueObject.setCODTIPOINFRACTOR(result.getString("CODTIPOINFRACTOR")); 
                   valueObject.setNUEVA_CATEGORIA(result.getString("NUEVA_CATEGORIA"));

              } else {
                    //System.out.println("ViewInfractorComparendo Object Not Found!");
                    throw new NotFoundException("ViewInfractorComparendo Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   ViewInfractorComparendo temp = createValueObject();

                   temp.setNROIDENTIFICACION(result.getString("NROIDENTIFICACION")); 
                   temp.setIDREPORTECOMPARENDO(result.getString("IDREPORTECOMPARENDO")); 
                   temp.setID_INFRACTOR(result.getString("ID_INFRACTOR")); 
                   temp.setNOMBRES(result.getString("NOMBRES")); 
                   temp.setAPELLIDOS(result.getString("APELLIDOS")); 
                   temp.setDIRECCION(result.getString("DIRECCION")); 
                   temp.setEDAD(result.getString("EDAD")); 
                   temp.setEMAIL(result.getString("EMAIL")); 
                   temp.setTELEFONO(result.getString("TELEFONO")); 
                   temp.setCODCIUDAD(result.getString("CODCIUDAD")); 
                   temp.setID_DEPTO(result.getString("ID_DEPTO")); 
                   temp.setNROLICCONDUCCION(result.getString("NROLICCONDUCCION")); 
                   temp.setCOD_CATEGORIA(result.getString("COD_CATEGORIA")); 
                   temp.setNIT(result.getString("NIT")); 
                   temp.setID_TRANSITO(result.getString("ID_TRANSITO")); 
                   temp.setFECHAVENCELICCONDUCCION(result.getString("FECHAVENCELICCONDUCCION")); 
                   temp.setCODTIPOINFRACTOR(result.getString("CODTIPOINFRACTOR")); 
                   temp.setNUEVA_CATEGORIA(result.getString("NUEVA_CATEGORIA"));

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }



//M-*-TODOS NUEVOS - AGREGADO POR EDWIN
        public List searchMatchingSql(Connection conn) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer(" SELECT\n" + 
          "  --DISTINCT(ID_INFRACTOR)\n" + 
          "  --COUNT(ID_INFRACTOR)\n" + 
          "  --COUNT(DISTINCT(view_comparendosresolsancion.ID_INFRACTOR))\n" + 
          "  *\n" + 
          "FROM\n" + 
          "  view_comparendosresolsancion\n" + 
          "JOIN VIEW_INFRACTOR_COMPARENDO ON (view_comparendosresolsancion.id_infractor = view_infractor_comparendo.id_infractor)\n" + 
          "WHERE view_comparendosresolsancion.id_estado = 4\n" + 
          "AND view_comparendosresolsancion.id_comparendo NOT IN (SELECT id_comparendo\n" + 
          "FROM expedientecomparendo)\n" + 
          "ORDER BY FECHACOMPARENDO");
          
          searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }

}