package modelo.datos.objetos.liquidacion.tarifas;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ViewDetalleTarifa Value Object.
  * This class is value object representing database table ViewDetalleTarifa
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewDetalleTarifa implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int LTD_ID;
    private int LCC_ID;
    private String LCC_NOMBRE;
    private int LT_ID;
    private int LTD_DESCONTADLE;
    private int LTD_TIPO;
    private int LTD_VALOR;
    private int LTD_FACTOR;
    private String LTD_DATOBASE;
    private String LTD_CALCULO;
    private int LTD_PARCIAL;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewDetalleTarifa () {

    }

    public ViewDetalleTarifa (int LTD_IDIn) {

          this.LTD_ID = LTD_IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getLTD_ID() {
          return this.LTD_ID;
    }
    public void setLTD_ID(int LTD_IDIn) {
          this.LTD_ID = LTD_IDIn;
    }

    public int getLCC_ID() {
          return this.LCC_ID;
    }
    public void setLCC_ID(int LCC_IDIn) {
          this.LCC_ID = LCC_IDIn;
    }

    public String getLCC_NOMBRE() {
          return this.LCC_NOMBRE;
    }
    public void setLCC_NOMBRE(String LCC_NOMBREIn) {
          this.LCC_NOMBRE = LCC_NOMBREIn;
    }

    public int getLT_ID() {
          return this.LT_ID;
    }
    public void setLT_ID(int LT_IDIn) {
          this.LT_ID = LT_IDIn;
    }

    public int getLTD_DESCONTADLE() {
          return this.LTD_DESCONTADLE;
    }
    public void setLTD_DESCONTADLE(int LTD_DESCONTADLEIn) {
          this.LTD_DESCONTADLE = LTD_DESCONTADLEIn;
    }

    public int getLTD_TIPO() {
          return this.LTD_TIPO;
    }
    public void setLTD_TIPO(int LTD_TIPOIn) {
          this.LTD_TIPO = LTD_TIPOIn;
    }

    public int getLTD_VALOR() {
          return this.LTD_VALOR;
    }
    public void setLTD_VALOR(int LTD_VALORIn) {
          this.LTD_VALOR = LTD_VALORIn;
    }

    public int getLTD_FACTOR() {
          return this.LTD_FACTOR;
    }
    public void setLTD_FACTOR(int LTD_FACTORIn) {
          this.LTD_FACTOR = LTD_FACTORIn;
    }

    public String getLTD_DATOBASE() {
          return this.LTD_DATOBASE;
    }
    public void setLTD_DATOBASE(String LTD_DATOBASEIn) {
          this.LTD_DATOBASE = LTD_DATOBASEIn;
    }

    public String getLTD_CALCULO() {
          return this.LTD_CALCULO;
    }
    public void setLTD_CALCULO(String LTD_CALCULOIn) {
          this.LTD_CALCULO = LTD_CALCULOIn;
    }

    public int getLTD_PARCIAL() {
          return this.LTD_PARCIAL;
    }
    public void setLTD_PARCIAL(int LTD_PARCIALIn) {
          this.LTD_PARCIAL = LTD_PARCIALIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int LTD_IDIn,
          int LCC_IDIn,
          String LCC_NOMBREIn,
          int LT_IDIn,
          int LTD_DESCONTADLEIn,
          int LTD_TIPOIn,
          int LTD_VALORIn,
          int LTD_FACTORIn,
          String LTD_DATOBASEIn,
          String LTD_CALCULOIn,
          int LTD_PARCIALIn) {
          this.LTD_ID = LTD_IDIn;
          this.LCC_ID = LCC_IDIn;
          this.LCC_NOMBRE = LCC_NOMBREIn;
          this.LT_ID = LT_IDIn;
          this.LTD_DESCONTADLE = LTD_DESCONTADLEIn;
          this.LTD_TIPO = LTD_TIPOIn;
          this.LTD_VALOR = LTD_VALORIn;
          this.LTD_FACTOR = LTD_FACTORIn;
          this.LTD_DATOBASE = LTD_DATOBASEIn;
          this.LTD_CALCULO = LTD_CALCULOIn;
          this.LTD_PARCIAL = LTD_PARCIALIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewDetalleTarifa instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewDetalleTarifa valueObject) {

          if (valueObject.getLTD_ID() != this.LTD_ID) {
                    return(false);
          }
          if (valueObject.getLCC_ID() != this.LCC_ID) {
                    return(false);
          }
          if (this.LCC_NOMBRE == null) {
                    if (valueObject.getLCC_NOMBRE() != null)
                           return(false);
          } else if (!this.LCC_NOMBRE.equals(valueObject.getLCC_NOMBRE())) {
                    return(false);
          }
          if (valueObject.getLT_ID() != this.LT_ID) {
                    return(false);
          }
          if (valueObject.getLTD_DESCONTADLE() != this.LTD_DESCONTADLE) {
                    return(false);
          }
          if (valueObject.getLTD_TIPO() != this.LTD_TIPO) {
                    return(false);
          }
          if (valueObject.getLTD_VALOR() != this.LTD_VALOR) {
                    return(false);
          }
          if (valueObject.getLTD_FACTOR() != this.LTD_FACTOR) {
                    return(false);
          }
          if (this.LTD_DATOBASE == null) {
                    if (valueObject.getLTD_DATOBASE() != null)
                           return(false);
          } else if (!this.LTD_DATOBASE.equals(valueObject.getLTD_DATOBASE())) {
                    return(false);
          }
          if (this.LTD_CALCULO == null) {
                    if (valueObject.getLTD_CALCULO() != null)
                           return(false);
          } else if (!this.LTD_CALCULO.equals(valueObject.getLTD_CALCULO())) {
                    return(false);
          }
          if (valueObject.getLTD_PARCIAL() != this.LTD_PARCIAL) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewDetalleTarifa, mapping to table ViewDetalleTarifa\n");
        out.append("Persistent attributes: \n"); 
        out.append("LTD_ID = " + this.LTD_ID + "\n"); 
        out.append("LCC_ID = " + this.LCC_ID + "\n"); 
        out.append("LCC_NOMBRE = " + this.LCC_NOMBRE + "\n"); 
        out.append("LT_ID = " + this.LT_ID + "\n"); 
        out.append("LTD_DESCONTADLE = " + this.LTD_DESCONTADLE + "\n"); 
        out.append("LTD_TIPO = " + this.LTD_TIPO + "\n"); 
        out.append("LTD_VALOR = " + this.LTD_VALOR + "\n"); 
        out.append("LTD_FACTOR = " + this.LTD_FACTOR + "\n"); 
        out.append("LTD_DATOBASE = " + this.LTD_DATOBASE + "\n"); 
        out.append("LTD_CALCULO = " + this.LTD_CALCULO + "\n"); 
        out.append("LTD_PARCIAL = " + this.LTD_PARCIAL + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewDetalleTarifa cloned = new ViewDetalleTarifa();

        cloned.setLTD_ID(this.LTD_ID); 
        cloned.setLCC_ID(this.LCC_ID); 
        if (this.LCC_NOMBRE != null)
             cloned.setLCC_NOMBRE(new String(this.LCC_NOMBRE)); 
        cloned.setLT_ID(this.LT_ID); 
        cloned.setLTD_DESCONTADLE(this.LTD_DESCONTADLE); 
        cloned.setLTD_TIPO(this.LTD_TIPO); 
        cloned.setLTD_VALOR(this.LTD_VALOR); 
        cloned.setLTD_FACTOR(this.LTD_FACTOR); 
        if (this.LTD_DATOBASE != null)
             cloned.setLTD_DATOBASE(new String(this.LTD_DATOBASE)); 
        if (this.LTD_CALCULO != null)
             cloned.setLTD_CALCULO(new String(this.LTD_CALCULO)); 
        cloned.setLTD_PARCIAL(this.LTD_PARCIAL); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

