package modelo.datos.objetos.accesorias;



import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * GrupoSanguineo Value Object.
  * This class is value object representing database table GRUPOSANGUINEO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class GrupoSanguineo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID;
    private String CODGIO;
    private String DESCRIPCION;
    private String RUNT;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public GrupoSanguineo () {

    }

    public GrupoSanguineo (int IDIn) {

          this.ID = IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID() {
          return this.ID;
    }
    public void setID(int IDIn) {
          this.ID = IDIn;
    }

    public String getCODGIO() {
          return this.CODGIO;
    }
    public void setCODGIO(String CODGIOIn) {
          this.CODGIO = CODGIOIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getRUNT() {
          return this.RUNT;
    }
    public void setRUNT(String RUNTIn) {
          this.RUNT = RUNTIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDIn,
          String CODGIOIn,
          String DESCRIPCIONIn,
          String RUNTIn) {
          this.ID = IDIn;
          this.CODGIO = CODGIOIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.RUNT = RUNTIn;
    }


    /** 
     * hasEqualMapping-method will compare two GrupoSanguineo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(GrupoSanguineo valueObject) {

          if (valueObject.getID() != this.ID) {
                    return(false);
          }
          if (this.CODGIO == null) {
                    if (valueObject.getCODGIO() != null)
                           return(false);
          } else if (!this.CODGIO.equals(valueObject.getCODGIO())) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.RUNT == null) {
                    if (valueObject.getRUNT() != null)
                           return(false);
          } else if (!this.RUNT.equals(valueObject.getRUNT())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass GrupoSanguineo, mapping to table GRUPOSANGUINEO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID = " + this.ID + "\n"); 
        out.append("CODGIO = " + this.CODGIO + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("RUNT = " + this.RUNT + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        GrupoSanguineo cloned = new GrupoSanguineo();

        cloned.setID(this.ID); 
        if (this.CODGIO != null)
             cloned.setCODGIO(new String(this.CODGIO)); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.RUNT != null)
             cloned.setRUNT(new String(this.RUNT)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}


