package modelo.datos.objetos.accesorias;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * LClaseVehiculo Value Object.
  * This class is value object representing database table LClaseVehiculo
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class LClaseVehiculo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int LCV_ID;
    private String LCV_NOMBRE;
    private String LCV_CONDICION;
    private int LCV_ORDEN_EVAL;
    private int LCV_ACTIVA;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public LClaseVehiculo () {

    }

    public LClaseVehiculo (int LCV_IDIn) {

          this.LCV_ID = LCV_IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getLCV_ID() {
          return this.LCV_ID;
    }
    public void setLCV_ID(int LCV_IDIn) {
          this.LCV_ID = LCV_IDIn;
    }

    public String getLCV_NOMBRE() {
          return this.LCV_NOMBRE;
    }
    public void setLCV_NOMBRE(String LCV_NOMBREIn) {
          this.LCV_NOMBRE = LCV_NOMBREIn;
    }

    public String getLCV_CONDICION() {
          return this.LCV_CONDICION;
    }
    public void setLCV_CONDICION(String LCV_CONDICIONIn) {
          this.LCV_CONDICION = LCV_CONDICIONIn;
    }

    public int getLCV_ORDEN_EVAL() {
          return this.LCV_ORDEN_EVAL;
    }
    public void setLCV_ORDEN_EVAL(int LCV_ORDEN_EVALIn) {
          this.LCV_ORDEN_EVAL = LCV_ORDEN_EVALIn;
    }

    public int getLCV_ACTIVA() {
          return this.LCV_ACTIVA;
    }
    public void setLCV_ACTIVA(int LCV_ACTIVAIn) {
          this.LCV_ACTIVA = LCV_ACTIVAIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int LCV_IDIn,
          String LCV_NOMBREIn,
          String LCV_CONDICIONIn,
          int LCV_ORDEN_EVALIn,
          int LCV_ACTIVAIn) {
          this.LCV_ID = LCV_IDIn;
          this.LCV_NOMBRE = LCV_NOMBREIn;
          this.LCV_CONDICION = LCV_CONDICIONIn;
          this.LCV_ORDEN_EVAL = LCV_ORDEN_EVALIn;
          this.LCV_ACTIVA = LCV_ACTIVAIn;
    }


    /** 
     * hasEqualMapping-method will compare two LClaseVehiculo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(LClaseVehiculo valueObject) {

          if (valueObject.getLCV_ID() != this.LCV_ID) {
                    return(false);
          }
          if (this.LCV_NOMBRE == null) {
                    if (valueObject.getLCV_NOMBRE() != null)
                           return(false);
          } else if (!this.LCV_NOMBRE.equals(valueObject.getLCV_NOMBRE())) {
                    return(false);
          }
          if (this.LCV_CONDICION == null) {
                    if (valueObject.getLCV_CONDICION() != null)
                           return(false);
          } else if (!this.LCV_CONDICION.equals(valueObject.getLCV_CONDICION())) {
                    return(false);
          }
          if (valueObject.getLCV_ORDEN_EVAL() != this.LCV_ORDEN_EVAL) {
                    return(false);
          }
          if (valueObject.getLCV_ACTIVA() != this.LCV_ACTIVA) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass LClaseVehiculo, mapping to table LClaseVehiculo\n");
        out.append("Persistent attributes: \n"); 
        out.append("LCV_ID = " + this.LCV_ID + "\n"); 
        out.append("LCV_NOMBRE = " + this.LCV_NOMBRE + "\n"); 
        out.append("LCV_CONDICION = " + this.LCV_CONDICION + "\n"); 
        out.append("LCV_ORDEN_EVAL = " + this.LCV_ORDEN_EVAL + "\n"); 
        out.append("LCV_ACTIVA = " + this.LCV_ACTIVA + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        LClaseVehiculo cloned = new LClaseVehiculo();

        cloned.setLCV_ID(this.LCV_ID); 
        if (this.LCV_NOMBRE != null)
             cloned.setLCV_NOMBRE(new String(this.LCV_NOMBRE)); 
        if (this.LCV_CONDICION != null)
             cloned.setLCV_CONDICION(new String(this.LCV_CONDICION)); 
        cloned.setLCV_ORDEN_EVAL(this.LCV_ORDEN_EVAL); 
        cloned.setLCV_ACTIVA(this.LCV_ACTIVA); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
