package modelo.datos.objetos.accesorias;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Servicio Value Object.
  * This class is value object representing database table SERVICIO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Servicio implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_SERVICIO;
    private String DESCRIPCION;
    private String GENERACERTMOVILIZACION;
    private String DURACIONCERTMOVILIZACION;
    private String ID_SERVICIORUNT;
    private String SERVALIDOS;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Servicio () {

    }

    public Servicio (int ID_SERVICIOIn) {

          this.ID_SERVICIO = ID_SERVICIOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_SERVICIO() {
          return this.ID_SERVICIO;
    }
    public void setID_SERVICIO(int ID_SERVICIOIn) {
          this.ID_SERVICIO = ID_SERVICIOIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getGENERACERTMOVILIZACION() {
          return this.GENERACERTMOVILIZACION;
    }
    public void setGENERACERTMOVILIZACION(String GENERACERTMOVILIZACIONIn) {
          this.GENERACERTMOVILIZACION = GENERACERTMOVILIZACIONIn;
    }

    public String getDURACIONCERTMOVILIZACION() {
          return this.DURACIONCERTMOVILIZACION;
    }
    public void setDURACIONCERTMOVILIZACION(String DURACIONCERTMOVILIZACIONIn) {
          this.DURACIONCERTMOVILIZACION = DURACIONCERTMOVILIZACIONIn;
    }

    public String getID_SERVICIORUNT() {
          return this.ID_SERVICIORUNT;
    }
    public void setID_SERVICIORUNT(String ID_SERVICIORUNTIn) {
          this.ID_SERVICIORUNT = ID_SERVICIORUNTIn;
    }

    public String getSERVALIDOS() {
          return this.SERVALIDOS;
    }
    public void setSERVALIDOS(String SERVALIDOSIn) {
          this.SERVALIDOS = SERVALIDOSIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_SERVICIOIn,
          String DESCRIPCIONIn,
          String GENERACERTMOVILIZACIONIn,
          String DURACIONCERTMOVILIZACIONIn,
          String ID_SERVICIORUNTIn,
          String SERVALIDOSIn) {
          this.ID_SERVICIO = ID_SERVICIOIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.GENERACERTMOVILIZACION = GENERACERTMOVILIZACIONIn;
          this.DURACIONCERTMOVILIZACION = DURACIONCERTMOVILIZACIONIn;
          this.ID_SERVICIORUNT = ID_SERVICIORUNTIn;
          this.SERVALIDOS = SERVALIDOSIn;
    }


    /** 
     * hasEqualMapping-method will compare two Servicio instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Servicio valueObject) {

          if (valueObject.getID_SERVICIO() != this.ID_SERVICIO) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.GENERACERTMOVILIZACION == null) {
                    if (valueObject.getGENERACERTMOVILIZACION() != null)
                           return(false);
          } else if (!this.GENERACERTMOVILIZACION.equals(valueObject.getGENERACERTMOVILIZACION())) {
                    return(false);
          }
          if (this.DURACIONCERTMOVILIZACION == null) {
                    if (valueObject.getDURACIONCERTMOVILIZACION() != null)
                           return(false);
          } else if (!this.DURACIONCERTMOVILIZACION.equals(valueObject.getDURACIONCERTMOVILIZACION())) {
                    return(false);
          }
          if (this.ID_SERVICIORUNT == null) {
                    if (valueObject.getID_SERVICIORUNT() != null)
                           return(false);
          } else if (!this.ID_SERVICIORUNT.equals(valueObject.getID_SERVICIORUNT())) {
                    return(false);
          }
          if (this.SERVALIDOS == null) {
                    if (valueObject.getSERVALIDOS() != null)
                           return(false);
          } else if (!this.SERVALIDOS.equals(valueObject.getSERVALIDOS())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Servicio, mapping to table SERVICIO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_SERVICIO = " + this.ID_SERVICIO + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("GENERACERTMOVILIZACION = " + this.GENERACERTMOVILIZACION + "\n"); 
        out.append("DURACIONCERTMOVILIZACION = " + this.DURACIONCERTMOVILIZACION + "\n"); 
        out.append("ID_SERVICIORUNT = " + this.ID_SERVICIORUNT + "\n"); 
        out.append("SERVALIDOS = " + this.SERVALIDOS + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Servicio cloned = new Servicio();

        cloned.setID_SERVICIO(this.ID_SERVICIO); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.GENERACERTMOVILIZACION != null)
             cloned.setGENERACERTMOVILIZACION(new String(this.GENERACERTMOVILIZACION)); 
        if (this.DURACIONCERTMOVILIZACION != null)
             cloned.setDURACIONCERTMOVILIZACION(new String(this.DURACIONCERTMOVILIZACION)); 
        if (this.ID_SERVICIORUNT != null)
             cloned.setID_SERVICIORUNT(new String(this.ID_SERVICIORUNT)); 
        if (this.SERVALIDOS != null)
             cloned.setSERVALIDOS(new String(this.SERVALIDOS)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
