package modelo.datos.objetos.accesorias;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TipoOperacion Value Object.
  * This class is value object representing database table TIPOOPERACION
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TipoOperacion implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDTIPOOPERACION;
    private String COD_TIPOOPERACION;
    private String DES_TIPOOPERACION;
    private int ID_ACCIONRUNT;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TipoOperacion () {

    }

    public TipoOperacion (int IDTIPOOPERACIONIn) {

          this.IDTIPOOPERACION = IDTIPOOPERACIONIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDTIPOOPERACION() {
          return this.IDTIPOOPERACION;
    }
    public void setIDTIPOOPERACION(int IDTIPOOPERACIONIn) {
          this.IDTIPOOPERACION = IDTIPOOPERACIONIn;
    }

    public String getCOD_TIPOOPERACION() {
          return this.COD_TIPOOPERACION;
    }
    public void setCOD_TIPOOPERACION(String COD_TIPOOPERACIONIn) {
          this.COD_TIPOOPERACION = COD_TIPOOPERACIONIn;
    }

    public String getDES_TIPOOPERACION() {
          return this.DES_TIPOOPERACION;
    }
    public void setDES_TIPOOPERACION(String DES_TIPOOPERACIONIn) {
          this.DES_TIPOOPERACION = DES_TIPOOPERACIONIn;
    }

    public int getID_ACCIONRUNT() {
          return this.ID_ACCIONRUNT;
    }
    public void setID_ACCIONRUNT(int ID_ACCIONRUNTIn) {
          this.ID_ACCIONRUNT = ID_ACCIONRUNTIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDTIPOOPERACIONIn,
          String COD_TIPOOPERACIONIn,
          String DES_TIPOOPERACIONIn,
          int ID_ACCIONRUNTIn) {
          this.IDTIPOOPERACION = IDTIPOOPERACIONIn;
          this.COD_TIPOOPERACION = COD_TIPOOPERACIONIn;
          this.DES_TIPOOPERACION = DES_TIPOOPERACIONIn;
          this.ID_ACCIONRUNT = ID_ACCIONRUNTIn;
    }


    /** 
     * hasEqualMapping-method will compare two TipoOperacion instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TipoOperacion valueObject) {

          if (valueObject.getIDTIPOOPERACION() != this.IDTIPOOPERACION) {
                    return(false);
          }
          if (this.COD_TIPOOPERACION == null) {
                    if (valueObject.getCOD_TIPOOPERACION() != null)
                           return(false);
          } else if (!this.COD_TIPOOPERACION.equals(valueObject.getCOD_TIPOOPERACION())) {
                    return(false);
          }
          if (this.DES_TIPOOPERACION == null) {
                    if (valueObject.getDES_TIPOOPERACION() != null)
                           return(false);
          } else if (!this.DES_TIPOOPERACION.equals(valueObject.getDES_TIPOOPERACION())) {
                    return(false);
          }
          if (valueObject.getID_ACCIONRUNT() != this.ID_ACCIONRUNT) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TipoOperacion, mapping to table TIPOOPERACION\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDTIPOOPERACION = " + this.IDTIPOOPERACION + "\n"); 
        out.append("COD_TIPOOPERACION = " + this.COD_TIPOOPERACION + "\n"); 
        out.append("DES_TIPOOPERACION = " + this.DES_TIPOOPERACION + "\n"); 
        out.append("ID_ACCIONRUNT = " + this.ID_ACCIONRUNT + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TipoOperacion cloned = new TipoOperacion();

        cloned.setIDTIPOOPERACION(this.IDTIPOOPERACION); 
        if (this.COD_TIPOOPERACION != null)
             cloned.setCOD_TIPOOPERACION(new String(this.COD_TIPOOPERACION)); 
        if (this.DES_TIPOOPERACION != null)
             cloned.setDES_TIPOOPERACION(new String(this.DES_TIPOOPERACION)); 
        cloned.setID_ACCIONRUNT(this.ID_ACCIONRUNT); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
