package modelo.datos.objetos.tramites;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Detrequisitobase Value Object.
  * This class is value object representing database table DET_REQUISITOBASE
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Detrequisitobase implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_DETREQBASE;
    private int ID_CABREQBASE;
    private int ID_REQUISITO;
    private String COD_REQUISITO;
    private String DESC_REQUISITO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Detrequisitobase () {

    }

    public Detrequisitobase (int ID_DETREQBASEIn) {

          this.ID_DETREQBASE = ID_DETREQBASEIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_DETREQBASE() {
          return this.ID_DETREQBASE;
    }
    public void setID_DETREQBASE(int ID_DETREQBASEIn) {
          this.ID_DETREQBASE = ID_DETREQBASEIn;
    }

    public int getID_CABREQBASE() {
          return this.ID_CABREQBASE;
    }
    public void setID_CABREQBASE(int ID_CABREQBASEIn) {
          this.ID_CABREQBASE = ID_CABREQBASEIn;
    }

    public int getID_REQUISITO() {
          return this.ID_REQUISITO;
    }
    public void setID_REQUISITO(int ID_REQUISITOIn) {
          this.ID_REQUISITO = ID_REQUISITOIn;
    }

    public String getCOD_REQUISITO() {
          return this.COD_REQUISITO;
    }
    public void setCOD_REQUISITO(String COD_REQUISITOIn) {
          this.COD_REQUISITO = COD_REQUISITOIn;
    }

    public String getDESC_REQUISITO() {
          return this.DESC_REQUISITO;
    }
    public void setDESC_REQUISITO(String DESC_REQUISITOIn) {
          this.DESC_REQUISITO = DESC_REQUISITOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_DETREQBASEIn,
          int ID_CABREQBASEIn,
          int ID_REQUISITOIn,
          String COD_REQUISITOIn,
          String DESC_REQUISITOIn) {
          this.ID_DETREQBASE = ID_DETREQBASEIn;
          this.ID_CABREQBASE = ID_CABREQBASEIn;
          this.ID_REQUISITO = ID_REQUISITOIn;
          this.COD_REQUISITO = COD_REQUISITOIn;
          this.DESC_REQUISITO = DESC_REQUISITOIn;
    }


    /** 
     * hasEqualMapping-method will compare two Detrequisitobase instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Detrequisitobase valueObject) {

          if (valueObject.getID_DETREQBASE() != this.ID_DETREQBASE) {
                    return(false);
          }
          if (valueObject.getID_CABREQBASE() != this.ID_CABREQBASE) {
                    return(false);
          }
          if (valueObject.getID_REQUISITO() != this.ID_REQUISITO) {
                    return(false);
          }
          if (this.COD_REQUISITO == null) {
                    if (valueObject.getCOD_REQUISITO() != null)
                           return(false);
          } else if (!this.COD_REQUISITO.equals(valueObject.getCOD_REQUISITO())) {
                    return(false);
          }
          if (this.DESC_REQUISITO == null) {
                    if (valueObject.getDESC_REQUISITO() != null)
                           return(false);
          } else if (!this.DESC_REQUISITO.equals(valueObject.getDESC_REQUISITO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Detrequisitobase, mapping to table DET_REQUISITOBASE\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_DETREQBASE = " + this.ID_DETREQBASE + "\n"); 
        out.append("ID_CABREQBASE = " + this.ID_CABREQBASE + "\n"); 
        out.append("ID_REQUISITO = " + this.ID_REQUISITO + "\n"); 
        out.append("COD_REQUISITO = " + this.COD_REQUISITO + "\n"); 
        out.append("DESC_REQUISITO = " + this.DESC_REQUISITO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Detrequisitobase cloned = new Detrequisitobase();

        cloned.setID_DETREQBASE(this.ID_DETREQBASE); 
        cloned.setID_CABREQBASE(this.ID_CABREQBASE); 
        cloned.setID_REQUISITO(this.ID_REQUISITO); 
        if (this.COD_REQUISITO != null)
             cloned.setCOD_REQUISITO(new String(this.COD_REQUISITO)); 
        if (this.DESC_REQUISITO != null)
             cloned.setDESC_REQUISITO(new String(this.DESC_REQUISITO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
