package modelo.datos.objetos.tramites;

import java.io.Serializable;

/**
  * RuntTraspasoVehiculo Value Object.
  * This class is value object representing database table RUNTTRASPASOVEHICULO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntTraspasoVehiculo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_TRASPASOVEH;
    private int ID_VEHICULO;
    private int ID_FACTURA;
    private int ID_TIPOTRASPASO;
    private String ACTUAL;
    private String FECHATRASPASO;
    private String NOMBREJUZGADO;
    private String FECHATRASPASOWS;
    private int ID_CIUDADJUZGADO;
    private String TIPDCTOTRASPINDETERMINADO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public RuntTraspasoVehiculo () {

    }

    public RuntTraspasoVehiculo (int ID_TRASPASOVEHIn) {

          this.ID_TRASPASOVEH = ID_TRASPASOVEHIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_TRASPASOVEH() {
          return this.ID_TRASPASOVEH;
    }
    public void setID_TRASPASOVEH(int ID_TRASPASOVEHIn) {
          this.ID_TRASPASOVEH = ID_TRASPASOVEHIn;
    }

    public int getID_VEHICULO() {
          return this.ID_VEHICULO;
    }
    public void setID_VEHICULO(int ID_VEHICULOIn) {
          this.ID_VEHICULO = ID_VEHICULOIn;
    }

    public int getID_FACTURA() {
          return this.ID_FACTURA;
    }
    public void setID_FACTURA(int ID_FACTURAIn) {
          this.ID_FACTURA = ID_FACTURAIn;
    }

    public int getID_TIPOTRASPASO() {
          return this.ID_TIPOTRASPASO;
    }
    public void setID_TIPOTRASPASO(int ID_TIPOTRASPASOIn) {
          this.ID_TIPOTRASPASO = ID_TIPOTRASPASOIn;
    }

    public String getACTUAL() {
          return this.ACTUAL;
    }
    public void setACTUAL(String ACTUALIn) {
          this.ACTUAL = ACTUALIn;
    }

    public String getFECHATRASPASO() {
          return this.FECHATRASPASO;
    }
    public void setFECHATRASPASO(String FECHATRASPASOIn) {
          this.FECHATRASPASO = FECHATRASPASOIn;
    }

    public String getNOMBREJUZGADO() {
          return this.NOMBREJUZGADO;
    }
    public void setNOMBREJUZGADO(String NOMBREJUZGADOIn) {
          this.NOMBREJUZGADO = NOMBREJUZGADOIn;
    }

    public String getFECHATRASPASOWS() {
          return this.FECHATRASPASOWS;
    }
    public void setFECHATRASPASOWS(String FECHATRASPASOWSIn) {
          this.FECHATRASPASOWS = FECHATRASPASOWSIn;
    }

    public int getID_CIUDADJUZGADO() {
          return this.ID_CIUDADJUZGADO;
    }
    public void setID_CIUDADJUZGADO(int ID_CIUDADJUZGADOIn) {
          this.ID_CIUDADJUZGADO = ID_CIUDADJUZGADOIn;
    }

    public String getTIPDCTOTRASPINDETERMINADO() {
          return this.TIPDCTOTRASPINDETERMINADO;
    }
    public void setTIPDCTOTRASPINDETERMINADO(String TIPDCTOTRASPINDETERMINADOIn) {
          this.TIPDCTOTRASPINDETERMINADO = TIPDCTOTRASPINDETERMINADOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_TRASPASOVEHIn,
          int ID_VEHICULOIn,
          int ID_FACTURAIn,
          int ID_TIPOTRASPASOIn,
          String ACTUALIn,
          String FECHATRASPASOIn,
          String NOMBREJUZGADOIn,
          String FECHATRASPASOWSIn,
          int ID_CIUDADJUZGADOIn,
          String TIPDCTOTRASPINDETERMINADOIn) {
          this.ID_TRASPASOVEH = ID_TRASPASOVEHIn;
          this.ID_VEHICULO = ID_VEHICULOIn;
          this.ID_FACTURA = ID_FACTURAIn;
          this.ID_TIPOTRASPASO = ID_TIPOTRASPASOIn;
          this.ACTUAL = ACTUALIn;
          this.FECHATRASPASO = FECHATRASPASOIn;
          this.NOMBREJUZGADO = NOMBREJUZGADOIn;
          this.FECHATRASPASOWS = FECHATRASPASOWSIn;
          this.ID_CIUDADJUZGADO = ID_CIUDADJUZGADOIn;
          this.TIPDCTOTRASPINDETERMINADO = TIPDCTOTRASPINDETERMINADOIn;
    }


    /** 
     * hasEqualMapping-method will compare two RuntTraspasoVehiculo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(RuntTraspasoVehiculo valueObject) {

          if (valueObject.getID_TRASPASOVEH() != this.ID_TRASPASOVEH) {
                    return(false);
          }
          if (valueObject.getID_VEHICULO() != this.ID_VEHICULO) {
                    return(false);
          }
          if (valueObject.getID_FACTURA() != this.ID_FACTURA) {
                    return(false);
          }
          if (valueObject.getID_TIPOTRASPASO() != this.ID_TIPOTRASPASO) {
                    return(false);
          }
          if (this.ACTUAL == null) {
                    if (valueObject.getACTUAL() != null)
                           return(false);
          } else if (!this.ACTUAL.equals(valueObject.getACTUAL())) {
                    return(false);
          }
          if (this.FECHATRASPASO == null) {
                    if (valueObject.getFECHATRASPASO() != null)
                           return(false);
          } else if (!this.FECHATRASPASO.equals(valueObject.getFECHATRASPASO())) {
                    return(false);
          }
          if (this.NOMBREJUZGADO == null) {
                    if (valueObject.getNOMBREJUZGADO() != null)
                           return(false);
          } else if (!this.NOMBREJUZGADO.equals(valueObject.getNOMBREJUZGADO())) {
                    return(false);
          }
          if (this.FECHATRASPASOWS == null) {
                    if (valueObject.getFECHATRASPASOWS() != null)
                           return(false);
          } else if (!this.FECHATRASPASOWS.equals(valueObject.getFECHATRASPASOWS())) {
                    return(false);
          }
          if (valueObject.getID_CIUDADJUZGADO() != this.ID_CIUDADJUZGADO) {
                    return(false);
          }
          if (this.TIPDCTOTRASPINDETERMINADO == null) {
                    if (valueObject.getTIPDCTOTRASPINDETERMINADO() != null)
                           return(false);
          } else if (!this.TIPDCTOTRASPINDETERMINADO.equals(valueObject.getTIPDCTOTRASPINDETERMINADO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass RuntTraspasoVehiculo, mapping to table RUNTTRASPASOVEHICULO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_TRASPASOVEH = " + this.ID_TRASPASOVEH + "\n"); 
        out.append("ID_VEHICULO = " + this.ID_VEHICULO + "\n"); 
        out.append("ID_FACTURA = " + this.ID_FACTURA + "\n"); 
        out.append("ID_TIPOTRASPASO = " + this.ID_TIPOTRASPASO + "\n"); 
        out.append("ACTUAL = " + this.ACTUAL + "\n"); 
        out.append("FECHATRASPASO = " + this.FECHATRASPASO + "\n"); 
        out.append("NOMBREJUZGADO = " + this.NOMBREJUZGADO + "\n"); 
        out.append("FECHATRASPASOWS = " + this.FECHATRASPASOWS + "\n"); 
        out.append("ID_CIUDADJUZGADO = " + this.ID_CIUDADJUZGADO + "\n"); 
        out.append("TIPDCTOTRASPINDETERMINADO = " + this.TIPDCTOTRASPINDETERMINADO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        RuntTraspasoVehiculo cloned = new RuntTraspasoVehiculo();

        cloned.setID_TRASPASOVEH(this.ID_TRASPASOVEH); 
        cloned.setID_VEHICULO(this.ID_VEHICULO); 
        cloned.setID_FACTURA(this.ID_FACTURA); 
        cloned.setID_TIPOTRASPASO(this.ID_TIPOTRASPASO); 
        if (this.ACTUAL != null)
             cloned.setACTUAL(new String(this.ACTUAL)); 
        if (this.FECHATRASPASO != null)
             cloned.setFECHATRASPASO(new String(this.FECHATRASPASO)); 
        if (this.NOMBREJUZGADO != null)
             cloned.setNOMBREJUZGADO(new String(this.NOMBREJUZGADO)); 
        if (this.FECHATRASPASOWS != null)
             cloned.setFECHATRASPASOWS(new String(this.FECHATRASPASOWS)); 
        cloned.setID_CIUDADJUZGADO(this.ID_CIUDADJUZGADO); 
        if (this.TIPDCTOTRASPINDETERMINADO != null)
             cloned.setTIPDCTOTRASPINDETERMINADO(new String(this.TIPDCTOTRASPINDETERMINADO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
