package modelo.datos.objetos.tramites;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TipoTransformacion Value Object.
  * This class is value object representing database table TIPOTRANSFORMACION
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TipoTransformacion implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDTIP_TRANSFORMACION;
    private String CODTIPOTRANSFORM;
    private String DESTIPOTRANSFORMACION;
    private String DESTIPOTRANFORMACIONRUNT;
    private String TRANSFORMACIONRUNT;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TipoTransformacion () {

    }

    public TipoTransformacion (int IDTIP_TRANSFORMACIONIn) {

          this.IDTIP_TRANSFORMACION = IDTIP_TRANSFORMACIONIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDTIP_TRANSFORMACION() {
          return this.IDTIP_TRANSFORMACION;
    }
    public void setIDTIP_TRANSFORMACION(int IDTIP_TRANSFORMACIONIn) {
          this.IDTIP_TRANSFORMACION = IDTIP_TRANSFORMACIONIn;
    }

    public String getCODTIPOTRANSFORM() {
          return this.CODTIPOTRANSFORM;
    }
    public void setCODTIPOTRANSFORM(String CODTIPOTRANSFORMIn) {
          this.CODTIPOTRANSFORM = CODTIPOTRANSFORMIn;
    }

    public String getDESTIPOTRANSFORMACION() {
          return this.DESTIPOTRANSFORMACION;
    }
    public void setDESTIPOTRANSFORMACION(String DESTIPOTRANSFORMACIONIn) {
          this.DESTIPOTRANSFORMACION = DESTIPOTRANSFORMACIONIn;
    }

    public String getDESTIPOTRANFORMACIONRUNT() {
          return this.DESTIPOTRANFORMACIONRUNT;
    }
    public void setDESTIPOTRANFORMACIONRUNT(String DESTIPOTRANFORMACIONRUNTIn) {
          this.DESTIPOTRANFORMACIONRUNT = DESTIPOTRANFORMACIONRUNTIn;
    }

    public String getTRANSFORMACIONRUNT() {
          return this.TRANSFORMACIONRUNT;
    }
    public void setTRANSFORMACIONRUNT(String TRANSFORMACIONRUNTIn) {
          this.TRANSFORMACIONRUNT = TRANSFORMACIONRUNTIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDTIP_TRANSFORMACIONIn,
          String CODTIPOTRANSFORMIn,
          String DESTIPOTRANSFORMACIONIn,
          String DESTIPOTRANFORMACIONRUNTIn,
          String TRANSFORMACIONRUNTIn) {
          this.IDTIP_TRANSFORMACION = IDTIP_TRANSFORMACIONIn;
          this.CODTIPOTRANSFORM = CODTIPOTRANSFORMIn;
          this.DESTIPOTRANSFORMACION = DESTIPOTRANSFORMACIONIn;
          this.DESTIPOTRANFORMACIONRUNT = DESTIPOTRANFORMACIONRUNTIn;
          this.TRANSFORMACIONRUNT = TRANSFORMACIONRUNTIn;
    }


    /** 
     * hasEqualMapping-method will compare two TipoTransformacion instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TipoTransformacion valueObject) {

          if (valueObject.getIDTIP_TRANSFORMACION() != this.IDTIP_TRANSFORMACION) {
                    return(false);
          }
          if (this.CODTIPOTRANSFORM == null) {
                    if (valueObject.getCODTIPOTRANSFORM() != null)
                           return(false);
          } else if (!this.CODTIPOTRANSFORM.equals(valueObject.getCODTIPOTRANSFORM())) {
                    return(false);
          }
          if (this.DESTIPOTRANSFORMACION == null) {
                    if (valueObject.getDESTIPOTRANSFORMACION() != null)
                           return(false);
          } else if (!this.DESTIPOTRANSFORMACION.equals(valueObject.getDESTIPOTRANSFORMACION())) {
                    return(false);
          }
          if (this.DESTIPOTRANFORMACIONRUNT == null) {
                    if (valueObject.getDESTIPOTRANFORMACIONRUNT() != null)
                           return(false);
          } else if (!this.DESTIPOTRANFORMACIONRUNT.equals(valueObject.getDESTIPOTRANFORMACIONRUNT())) {
                    return(false);
          }
          if (this.TRANSFORMACIONRUNT == null) {
                    if (valueObject.getTRANSFORMACIONRUNT() != null)
                           return(false);
          } else if (!this.TRANSFORMACIONRUNT.equals(valueObject.getTRANSFORMACIONRUNT())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TipoTransformacion, mapping to table TIPOTRANSFORMACION\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDTIP_TRANSFORMACION = " + this.IDTIP_TRANSFORMACION + "\n"); 
        out.append("CODTIPOTRANSFORM = " + this.CODTIPOTRANSFORM + "\n"); 
        out.append("DESTIPOTRANSFORMACION = " + this.DESTIPOTRANSFORMACION + "\n"); 
        out.append("DESTIPOTRANFORMACIONRUNT = " + this.DESTIPOTRANFORMACIONRUNT + "\n"); 
        out.append("TRANSFORMACIONRUNT = " + this.TRANSFORMACIONRUNT + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TipoTransformacion cloned = new TipoTransformacion();

        cloned.setIDTIP_TRANSFORMACION(this.IDTIP_TRANSFORMACION); 
        if (this.CODTIPOTRANSFORM != null)
             cloned.setCODTIPOTRANSFORM(new String(this.CODTIPOTRANSFORM)); 
        if (this.DESTIPOTRANSFORMACION != null)
             cloned.setDESTIPOTRANSFORMACION(new String(this.DESTIPOTRANSFORMACION)); 
        if (this.DESTIPOTRANFORMACIONRUNT != null)
             cloned.setDESTIPOTRANFORMACIONRUNT(new String(this.DESTIPOTRANFORMACIONRUNT)); 
        if (this.TRANSFORMACIONRUNT != null)
             cloned.setTRANSFORMACIONRUNT(new String(this.TRANSFORMACIONRUNT)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}