package modelo.datos.objetos.tramites;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TransformacionVehiculo Value Object.
  * This class is value object representing database table TRANSFORMACIONVEHICULO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TransformacionVehiculo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDTRANSF_VEHICULO;
    private int IDVEHICULO;
    private int IDTIPOTRANSFOR;
    private String ACTIVO;
    private int IDREC_LIQUIDACION;
    private String DESCRIPCION;
    private String ANOTACIONES;
    private int ID_RUNTMODELO;
    private String NUMFICHATECNICA;
    private String NUMEROMOTOR;
    private int ID_TIPOREPOTENCIACION;
    private int ID_COMBUSTIBLE;
    private int ID_TIPCARROCERIA;
    private String FECHAFACVENTAMOTOR;
    private String NUMFACTVENTAMOTOR;
    private String HACECAMBIOMOTOR;
    private String TIPINGRESOMOTOR;
    private String NUMDECLARIMPORTACION;
    private int ID_VENDEDORMOTOR;
    private String TIPOVENDEDORMOTOR;
    private int ID_ANOTACIONTRANSFOR;
    private int ID_USUARIOEXE;
    private String FECHAEXE;
    private String HORAEXE;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TransformacionVehiculo () {

    }

    public TransformacionVehiculo (int IDTRANSF_VEHICULOIn) {

          this.IDTRANSF_VEHICULO = IDTRANSF_VEHICULOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDTRANSF_VEHICULO() {
          return this.IDTRANSF_VEHICULO;
    }
    public void setIDTRANSF_VEHICULO(int IDTRANSF_VEHICULOIn) {
          this.IDTRANSF_VEHICULO = IDTRANSF_VEHICULOIn;
    }

    public int getIDVEHICULO() {
          return this.IDVEHICULO;
    }
    public void setIDVEHICULO(int IDVEHICULOIn) {
          this.IDVEHICULO = IDVEHICULOIn;
    }

    public int getIDTIPOTRANSFOR() {
          return this.IDTIPOTRANSFOR;
    }
    public void setIDTIPOTRANSFOR(int IDTIPOTRANSFORIn) {
          this.IDTIPOTRANSFOR = IDTIPOTRANSFORIn;
    }

    public String getACTIVO() {
          return this.ACTIVO;
    }
    public void setACTIVO(String ACTIVOIn) {
          this.ACTIVO = ACTIVOIn;
    }

    public int getIDREC_LIQUIDACION() {
          return this.IDREC_LIQUIDACION;
    }
    public void setIDREC_LIQUIDACION(int IDREC_LIQUIDACIONIn) {
          this.IDREC_LIQUIDACION = IDREC_LIQUIDACIONIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getANOTACIONES() {
          return this.ANOTACIONES;
    }
    public void setANOTACIONES(String ANOTACIONESIn) {
          this.ANOTACIONES = ANOTACIONESIn;
    }

    public int getID_RUNTMODELO() {
          return this.ID_RUNTMODELO;
    }
    public void setID_RUNTMODELO(int ID_RUNTMODELOIn) {
          this.ID_RUNTMODELO = ID_RUNTMODELOIn;
    }

    public String getNUMFICHATECNICA() {
          return this.NUMFICHATECNICA;
    }
    public void setNUMFICHATECNICA(String NUMFICHATECNICAIn) {
          this.NUMFICHATECNICA = NUMFICHATECNICAIn;
    }

    public String getNUMEROMOTOR() {
          return this.NUMEROMOTOR;
    }
    public void setNUMEROMOTOR(String NUMEROMOTORIn) {
          this.NUMEROMOTOR = NUMEROMOTORIn;
    }

    public int getID_TIPOREPOTENCIACION() {
          return this.ID_TIPOREPOTENCIACION;
    }
    public void setID_TIPOREPOTENCIACION(int ID_TIPOREPOTENCIACIONIn) {
          this.ID_TIPOREPOTENCIACION = ID_TIPOREPOTENCIACIONIn;
    }

    public int getID_COMBUSTIBLE() {
          return this.ID_COMBUSTIBLE;
    }
    public void setID_COMBUSTIBLE(int ID_COMBUSTIBLEIn) {
          this.ID_COMBUSTIBLE = ID_COMBUSTIBLEIn;
    }

    public int getID_TIPCARROCERIA() {
          return this.ID_TIPCARROCERIA;
    }
    public void setID_TIPCARROCERIA(int ID_TIPCARROCERIAIn) {
          this.ID_TIPCARROCERIA = ID_TIPCARROCERIAIn;
    }

    public String getFECHAFACVENTAMOTOR() {
          return this.FECHAFACVENTAMOTOR;
    }
    public void setFECHAFACVENTAMOTOR(String FECHAFACVENTAMOTORIn) {
          this.FECHAFACVENTAMOTOR = FECHAFACVENTAMOTORIn;
    }

    public String getNUMFACTVENTAMOTOR() {
          return this.NUMFACTVENTAMOTOR;
    }
    public void setNUMFACTVENTAMOTOR(String NUMFACTVENTAMOTORIn) {
          this.NUMFACTVENTAMOTOR = NUMFACTVENTAMOTORIn;
    }

    public String getHACECAMBIOMOTOR() {
          return this.HACECAMBIOMOTOR;
    }
    public void setHACECAMBIOMOTOR(String HACECAMBIOMOTORIn) {
          this.HACECAMBIOMOTOR = HACECAMBIOMOTORIn;
    }

    public String getTIPINGRESOMOTOR() {
          return this.TIPINGRESOMOTOR;
    }
    public void setTIPINGRESOMOTOR(String TIPINGRESOMOTORIn) {
          this.TIPINGRESOMOTOR = TIPINGRESOMOTORIn;
    }

    public String getNUMDECLARIMPORTACION() {
          return this.NUMDECLARIMPORTACION;
    }
    public void setNUMDECLARIMPORTACION(String NUMDECLARIMPORTACIONIn) {
          this.NUMDECLARIMPORTACION = NUMDECLARIMPORTACIONIn;
    }

    public int getID_VENDEDORMOTOR() {
          return this.ID_VENDEDORMOTOR;
    }
    public void setID_VENDEDORMOTOR(int ID_VENDEDORMOTORIn) {
          this.ID_VENDEDORMOTOR = ID_VENDEDORMOTORIn;
    }

    public String getTIPOVENDEDORMOTOR() {
          return this.TIPOVENDEDORMOTOR;
    }
    public void setTIPOVENDEDORMOTOR(String TIPOVENDEDORMOTORIn) {
          this.TIPOVENDEDORMOTOR = TIPOVENDEDORMOTORIn;
    }

    public int getID_ANOTACIONTRANSFOR() {
          return this.ID_ANOTACIONTRANSFOR;
    }
    public void setID_ANOTACIONTRANSFOR(int ID_ANOTACIONTRANSFORIn) {
          this.ID_ANOTACIONTRANSFOR = ID_ANOTACIONTRANSFORIn;
    }

    public int getID_USUARIOEXE() {
          return this.ID_USUARIOEXE;
    }
    public void setID_USUARIOEXE(int ID_USUARIOEXEIn) {
          this.ID_USUARIOEXE = ID_USUARIOEXEIn;
    }

    public String getFECHAEXE() {
          return this.FECHAEXE;
    }
    public void setFECHAEXE(String FECHAEXEIn) {
          this.FECHAEXE = FECHAEXEIn;
    }

    public String getHORAEXE() {
          return this.HORAEXE;
    }
    public void setHORAEXE(String HORAEXEIn) {
          this.HORAEXE = HORAEXEIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDTRANSF_VEHICULOIn,
          int IDVEHICULOIn,
          int IDTIPOTRANSFORIn,
          String ACTIVOIn,
          int IDREC_LIQUIDACIONIn,
          String DESCRIPCIONIn,
          String ANOTACIONESIn,
          int ID_RUNTMODELOIn,
          String NUMFICHATECNICAIn,
          String NUMEROMOTORIn,
          int ID_TIPOREPOTENCIACIONIn,
          int ID_COMBUSTIBLEIn,
          int ID_TIPCARROCERIAIn,
          String FECHAFACVENTAMOTORIn,
          String NUMFACTVENTAMOTORIn,
          String HACECAMBIOMOTORIn,
          String TIPINGRESOMOTORIn,
          String NUMDECLARIMPORTACIONIn,
          int ID_VENDEDORMOTORIn,
          String TIPOVENDEDORMOTORIn,
          int ID_ANOTACIONTRANSFORIn,
          int ID_USUARIOEXEIn,
          String FECHAEXEIn,
          String HORAEXEIn) {
          this.IDTRANSF_VEHICULO = IDTRANSF_VEHICULOIn;
          this.IDVEHICULO = IDVEHICULOIn;
          this.IDTIPOTRANSFOR = IDTIPOTRANSFORIn;
          this.ACTIVO = ACTIVOIn;
          this.IDREC_LIQUIDACION = IDREC_LIQUIDACIONIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.ANOTACIONES = ANOTACIONESIn;
          this.ID_RUNTMODELO = ID_RUNTMODELOIn;
          this.NUMFICHATECNICA = NUMFICHATECNICAIn;
          this.NUMEROMOTOR = NUMEROMOTORIn;
          this.ID_TIPOREPOTENCIACION = ID_TIPOREPOTENCIACIONIn;
          this.ID_COMBUSTIBLE = ID_COMBUSTIBLEIn;
          this.ID_TIPCARROCERIA = ID_TIPCARROCERIAIn;
          this.FECHAFACVENTAMOTOR = FECHAFACVENTAMOTORIn;
          this.NUMFACTVENTAMOTOR = NUMFACTVENTAMOTORIn;
          this.HACECAMBIOMOTOR = HACECAMBIOMOTORIn;
          this.TIPINGRESOMOTOR = TIPINGRESOMOTORIn;
          this.NUMDECLARIMPORTACION = NUMDECLARIMPORTACIONIn;
          this.ID_VENDEDORMOTOR = ID_VENDEDORMOTORIn;
          this.TIPOVENDEDORMOTOR = TIPOVENDEDORMOTORIn;
          this.ID_ANOTACIONTRANSFOR = ID_ANOTACIONTRANSFORIn;
          this.ID_USUARIOEXE = ID_USUARIOEXEIn;
          this.FECHAEXE = FECHAEXEIn;
          this.HORAEXE = HORAEXEIn;
    }


    /** 
     * hasEqualMapping-method will compare two TransformacionVehiculo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TransformacionVehiculo valueObject) {

          if (valueObject.getIDTRANSF_VEHICULO() != this.IDTRANSF_VEHICULO) {
                    return(false);
          }
          if (valueObject.getIDVEHICULO() != this.IDVEHICULO) {
                    return(false);
          }
          if (valueObject.getIDTIPOTRANSFOR() != this.IDTIPOTRANSFOR) {
                    return(false);
          }
          if (this.ACTIVO == null) {
                    if (valueObject.getACTIVO() != null)
                           return(false);
          } else if (!this.ACTIVO.equals(valueObject.getACTIVO())) {
                    return(false);
          }
          if (valueObject.getIDREC_LIQUIDACION() != this.IDREC_LIQUIDACION) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.ANOTACIONES == null) {
                    if (valueObject.getANOTACIONES() != null)
                           return(false);
          } else if (!this.ANOTACIONES.equals(valueObject.getANOTACIONES())) {
                    return(false);
          }
          if (valueObject.getID_RUNTMODELO() != this.ID_RUNTMODELO) {
                    return(false);
          }
          if (this.NUMFICHATECNICA == null) {
                    if (valueObject.getNUMFICHATECNICA() != null)
                           return(false);
          } else if (!this.NUMFICHATECNICA.equals(valueObject.getNUMFICHATECNICA())) {
                    return(false);
          }
          if (this.NUMEROMOTOR == null) {
                    if (valueObject.getNUMEROMOTOR() != null)
                           return(false);
          } else if (!this.NUMEROMOTOR.equals(valueObject.getNUMEROMOTOR())) {
                    return(false);
          }
          if (valueObject.getID_TIPOREPOTENCIACION() != this.ID_TIPOREPOTENCIACION) {
                    return(false);
          }
          if (valueObject.getID_COMBUSTIBLE() != this.ID_COMBUSTIBLE) {
                    return(false);
          }
          if (valueObject.getID_TIPCARROCERIA() != this.ID_TIPCARROCERIA) {
                    return(false);
          }
          if (this.FECHAFACVENTAMOTOR == null) {
                    if (valueObject.getFECHAFACVENTAMOTOR() != null)
                           return(false);
          } else if (!this.FECHAFACVENTAMOTOR.equals(valueObject.getFECHAFACVENTAMOTOR())) {
                    return(false);
          }
          if (this.NUMFACTVENTAMOTOR == null) {
                    if (valueObject.getNUMFACTVENTAMOTOR() != null)
                           return(false);
          } else if (!this.NUMFACTVENTAMOTOR.equals(valueObject.getNUMFACTVENTAMOTOR())) {
                    return(false);
          }
          if (this.HACECAMBIOMOTOR == null) {
                    if (valueObject.getHACECAMBIOMOTOR() != null)
                           return(false);
          } else if (!this.HACECAMBIOMOTOR.equals(valueObject.getHACECAMBIOMOTOR())) {
                    return(false);
          }
          if (this.TIPINGRESOMOTOR == null) {
                    if (valueObject.getTIPINGRESOMOTOR() != null)
                           return(false);
          } else if (!this.TIPINGRESOMOTOR.equals(valueObject.getTIPINGRESOMOTOR())) {
                    return(false);
          }
          if (this.NUMDECLARIMPORTACION == null) {
                    if (valueObject.getNUMDECLARIMPORTACION() != null)
                           return(false);
          } else if (!this.NUMDECLARIMPORTACION.equals(valueObject.getNUMDECLARIMPORTACION())) {
                    return(false);
          }
          if (valueObject.getID_VENDEDORMOTOR() != this.ID_VENDEDORMOTOR) {
                    return(false);
          }
          if (this.TIPOVENDEDORMOTOR == null) {
                    if (valueObject.getTIPOVENDEDORMOTOR() != null)
                           return(false);
          } else if (!this.TIPOVENDEDORMOTOR.equals(valueObject.getTIPOVENDEDORMOTOR())) {
                    return(false);
          }
          if (valueObject.getID_ANOTACIONTRANSFOR() != this.ID_ANOTACIONTRANSFOR) {
                    return(false);
          }
          if (valueObject.getID_USUARIOEXE() != this.ID_USUARIOEXE) {
                    return(false);
          }
          if (this.FECHAEXE == null) {
                    if (valueObject.getFECHAEXE() != null)
                           return(false);
          } else if (!this.FECHAEXE.equals(valueObject.getFECHAEXE())) {
                    return(false);
          }
          if (this.HORAEXE == null) {
                    if (valueObject.getHORAEXE() != null)
                           return(false);
          } else if (!this.HORAEXE.equals(valueObject.getHORAEXE())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TransformacionVehiculo, mapping to table TRANSFORMACIONVEHICULO\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDTRANSF_VEHICULO = " + this.IDTRANSF_VEHICULO + "\n"); 
        out.append("IDVEHICULO = " + this.IDVEHICULO + "\n"); 
        out.append("IDTIPOTRANSFOR = " + this.IDTIPOTRANSFOR + "\n"); 
        out.append("ACTIVO = " + this.ACTIVO + "\n"); 
        out.append("IDREC_LIQUIDACION = " + this.IDREC_LIQUIDACION + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("ANOTACIONES = " + this.ANOTACIONES + "\n"); 
        out.append("ID_RUNTMODELO = " + this.ID_RUNTMODELO + "\n"); 
        out.append("NUMFICHATECNICA = " + this.NUMFICHATECNICA + "\n"); 
        out.append("NUMEROMOTOR = " + this.NUMEROMOTOR + "\n"); 
        out.append("ID_TIPOREPOTENCIACION = " + this.ID_TIPOREPOTENCIACION + "\n"); 
        out.append("ID_COMBUSTIBLE = " + this.ID_COMBUSTIBLE + "\n"); 
        out.append("ID_TIPCARROCERIA = " + this.ID_TIPCARROCERIA + "\n"); 
        out.append("FECHAFACVENTAMOTOR = " + this.FECHAFACVENTAMOTOR + "\n"); 
        out.append("NUMFACTVENTAMOTOR = " + this.NUMFACTVENTAMOTOR + "\n"); 
        out.append("HACECAMBIOMOTOR = " + this.HACECAMBIOMOTOR + "\n"); 
        out.append("TIPINGRESOMOTOR = " + this.TIPINGRESOMOTOR + "\n"); 
        out.append("NUMDECLARIMPORTACION = " + this.NUMDECLARIMPORTACION + "\n"); 
        out.append("ID_VENDEDORMOTOR = " + this.ID_VENDEDORMOTOR + "\n"); 
        out.append("TIPOVENDEDORMOTOR = " + this.TIPOVENDEDORMOTOR + "\n"); 
        out.append("ID_ANOTACIONTRANSFOR = " + this.ID_ANOTACIONTRANSFOR + "\n"); 
        out.append("ID_USUARIOEXE = " + this.ID_USUARIOEXE + "\n"); 
        out.append("FECHAEXE = " + this.FECHAEXE + "\n"); 
        out.append("HORAEXE = " + this.HORAEXE + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TransformacionVehiculo cloned = new TransformacionVehiculo();

        cloned.setIDTRANSF_VEHICULO(this.IDTRANSF_VEHICULO); 
        cloned.setIDVEHICULO(this.IDVEHICULO); 
        cloned.setIDTIPOTRANSFOR(this.IDTIPOTRANSFOR); 
        if (this.ACTIVO != null)
             cloned.setACTIVO(new String(this.ACTIVO)); 
        cloned.setIDREC_LIQUIDACION(this.IDREC_LIQUIDACION); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.ANOTACIONES != null)
             cloned.setANOTACIONES(new String(this.ANOTACIONES)); 
        cloned.setID_RUNTMODELO(this.ID_RUNTMODELO); 
        if (this.NUMFICHATECNICA != null)
             cloned.setNUMFICHATECNICA(new String(this.NUMFICHATECNICA)); 
        if (this.NUMEROMOTOR != null)
             cloned.setNUMEROMOTOR(new String(this.NUMEROMOTOR)); 
        cloned.setID_TIPOREPOTENCIACION(this.ID_TIPOREPOTENCIACION); 
        cloned.setID_COMBUSTIBLE(this.ID_COMBUSTIBLE); 
        cloned.setID_TIPCARROCERIA(this.ID_TIPCARROCERIA); 
        if (this.FECHAFACVENTAMOTOR != null)
             cloned.setFECHAFACVENTAMOTOR(new String(this.FECHAFACVENTAMOTOR)); 
        if (this.NUMFACTVENTAMOTOR != null)
             cloned.setNUMFACTVENTAMOTOR(new String(this.NUMFACTVENTAMOTOR)); 
        if (this.HACECAMBIOMOTOR != null)
             cloned.setHACECAMBIOMOTOR(new String(this.HACECAMBIOMOTOR)); 
        if (this.TIPINGRESOMOTOR != null)
             cloned.setTIPINGRESOMOTOR(new String(this.TIPINGRESOMOTOR)); 
        if (this.NUMDECLARIMPORTACION != null)
             cloned.setNUMDECLARIMPORTACION(new String(this.NUMDECLARIMPORTACION)); 
        cloned.setID_VENDEDORMOTOR(this.ID_VENDEDORMOTOR); 
        if (this.TIPOVENDEDORMOTOR != null)
             cloned.setTIPOVENDEDORMOTOR(new String(this.TIPOVENDEDORMOTOR)); 
        cloned.setID_ANOTACIONTRANSFOR(this.ID_ANOTACIONTRANSFOR); 
        cloned.setID_USUARIOEXE(this.ID_USUARIOEXE); 
        if (this.FECHAEXE != null)
             cloned.setFECHAEXE(new String(this.FECHAEXE)); 
        if (this.HORAEXE != null)
             cloned.setHORAEXE(new String(this.HORAEXE)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
