package modelo.datos.objetos.licenciasConduccion;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * LicenciasConduccion Value Object.
  * This class is value object representing database table LICENCIADECONDUCCION
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class LicenciasConduccion implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String ID_LICENCIAC;
    private String FECHA_EXP;
    private String CATEGORIA;
    private String FECHA_VENC;
    private int ID_TRAMITECOND;
    private int ID_TRANSITO;
    private int CODESCUELA;
    private String CODRANGO;
    private String NROCOMPROBANTE;
    private int CODESPECIEVENAL;
    private int NROCONSIGNACION;
    private String NROCUENTA;
    private int ID_BANCO;
    private int ID_SUCBANCO;
    private String FECHACONSIGNACION;
    private int VALORCONSIGNACION;
    private int ID_CONDUCTOR;
    private String FECHATRAMITE;
    private String NROCERTIFICADOESCUELA;
    private String FECHAEXPCERTESCLA;
    private String NROCERTIFCRC;
    private String FECHAEXPCERTIF_CRC;
    private int ID_CRC;
    private int ID_FACTURA;
    private int ID_USUARIO;
    private String NROLICANTERIOR;
    private String CONVALIDACION;
    private int IDPAIS_LICEXTRANJERA;
    private String ID_CATEGORIA_LICEXTRAJ;
    private String NROLICCONDUCCION_EXTRANJ;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public LicenciasConduccion () {

    }

    public LicenciasConduccion (String ID_LICENCIACIn) {

          this.ID_LICENCIAC = ID_LICENCIACIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getID_LICENCIAC() {
          return this.ID_LICENCIAC;
    }
    public void setID_LICENCIAC(String ID_LICENCIACIn) {
          this.ID_LICENCIAC = ID_LICENCIACIn;
    }

    public String getFECHA_EXP() {
          return this.FECHA_EXP;
    }
    public void setFECHA_EXP(String FECHA_EXPIn) {
          this.FECHA_EXP = FECHA_EXPIn;
    }

    public String getCATEGORIA() {
          return this.CATEGORIA;
    }
    public void setCATEGORIA(String CATEGORIAIn) {
          this.CATEGORIA = CATEGORIAIn;
    }

    public String getFECHA_VENC() {
          return this.FECHA_VENC;
    }
    public void setFECHA_VENC(String FECHA_VENCIn) {
          this.FECHA_VENC = FECHA_VENCIn;
    }

    public int getID_TRAMITECOND() {
          return this.ID_TRAMITECOND;
    }
    public void setID_TRAMITECOND(int ID_TRAMITECONDIn) {
          this.ID_TRAMITECOND = ID_TRAMITECONDIn;
    }

    public int getID_TRANSITO() {
          return this.ID_TRANSITO;
    }
    public void setID_TRANSITO(int ID_TRANSITOIn) {
          this.ID_TRANSITO = ID_TRANSITOIn;
    }

    public int getCODESCUELA() {
          return this.CODESCUELA;
    }
    public void setCODESCUELA(int CODESCUELAIn) {
          this.CODESCUELA = CODESCUELAIn;
    }

    public String getCODRANGO() {
          return this.CODRANGO;
    }
    public void setCODRANGO(String CODRANGOIn) {
          this.CODRANGO = CODRANGOIn;
    }

    public String getNROCOMPROBANTE() {
          return this.NROCOMPROBANTE;
    }
    public void setNROCOMPROBANTE(String NROCOMPROBANTEIn) {
          this.NROCOMPROBANTE = NROCOMPROBANTEIn;
    }

    public int getCODESPECIEVENAL() {
          return this.CODESPECIEVENAL;
    }
    public void setCODESPECIEVENAL(int CODESPECIEVENALIn) {
          this.CODESPECIEVENAL = CODESPECIEVENALIn;
    }

    public int getNROCONSIGNACION() {
          return this.NROCONSIGNACION;
    }
    public void setNROCONSIGNACION(int NROCONSIGNACIONIn) {
          this.NROCONSIGNACION = NROCONSIGNACIONIn;
    }

    public String getNROCUENTA() {
          return this.NROCUENTA;
    }
    public void setNROCUENTA(String NROCUENTAIn) {
          this.NROCUENTA = NROCUENTAIn;
    }

    public int getID_BANCO() {
          return this.ID_BANCO;
    }
    public void setID_BANCO(int ID_BANCOIn) {
          this.ID_BANCO = ID_BANCOIn;
    }

    public int getID_SUCBANCO() {
          return this.ID_SUCBANCO;
    }
    public void setID_SUCBANCO(int ID_SUCBANCOIn) {
          this.ID_SUCBANCO = ID_SUCBANCOIn;
    }

    public String getFECHACONSIGNACION() {
          return this.FECHACONSIGNACION;
    }
    public void setFECHACONSIGNACION(String FECHACONSIGNACIONIn) {
          this.FECHACONSIGNACION = FECHACONSIGNACIONIn;
    }

    public int getVALORCONSIGNACION() {
          return this.VALORCONSIGNACION;
    }
    public void setVALORCONSIGNACION(int VALORCONSIGNACIONIn) {
          this.VALORCONSIGNACION = VALORCONSIGNACIONIn;
    }

    public int getID_CONDUCTOR() {
          return this.ID_CONDUCTOR;
    }
    public void setID_CONDUCTOR(int ID_CONDUCTORIn) {
          this.ID_CONDUCTOR = ID_CONDUCTORIn;
    }

    public String getFECHATRAMITE() {
          return this.FECHATRAMITE;
    }
    public void setFECHATRAMITE(String FECHATRAMITEIn) {
          this.FECHATRAMITE = FECHATRAMITEIn;
    }

    public String getNROCERTIFICADOESCUELA() {
          return this.NROCERTIFICADOESCUELA;
    }
    public void setNROCERTIFICADOESCUELA(String NROCERTIFICADOESCUELAIn) {
          this.NROCERTIFICADOESCUELA = NROCERTIFICADOESCUELAIn;
    }

    public String getFECHAEXPCERTESCLA() {
          return this.FECHAEXPCERTESCLA;
    }
    public void setFECHAEXPCERTESCLA(String FECHAEXPCERTESCLAIn) {
          this.FECHAEXPCERTESCLA = FECHAEXPCERTESCLAIn;
    }

    public String getNROCERTIFCRC() {
          return this.NROCERTIFCRC;
    }
    public void setNROCERTIFCRC(String NROCERTIFCRCIn) {
          this.NROCERTIFCRC = NROCERTIFCRCIn;
    }

    public String getFECHAEXPCERTIF_CRC() {
          return this.FECHAEXPCERTIF_CRC;
    }
    public void setFECHAEXPCERTIF_CRC(String FECHAEXPCERTIF_CRCIn) {
          this.FECHAEXPCERTIF_CRC = FECHAEXPCERTIF_CRCIn;
    }

    public int getID_CRC() {
          return this.ID_CRC;
    }
    public void setID_CRC(int ID_CRCIn) {
          this.ID_CRC = ID_CRCIn;
    }

    public int getID_FACTURA() {
          return this.ID_FACTURA;
    }
    public void setID_FACTURA(int ID_FACTURAIn) {
          this.ID_FACTURA = ID_FACTURAIn;
    }

    public int getID_USUARIO() {
          return this.ID_USUARIO;
    }
    public void setID_USUARIO(int ID_USUARIOIn) {
          this.ID_USUARIO = ID_USUARIOIn;
    }

    public String getNROLICANTERIOR() {
          return this.NROLICANTERIOR;
    }
    public void setNROLICANTERIOR(String NROLICANTERIORIn) {
          this.NROLICANTERIOR = NROLICANTERIORIn;
    }

    public String getCONVALIDACION() {
          return this.CONVALIDACION;
    }
    public void setCONVALIDACION(String CONVALIDACIONIn) {
          this.CONVALIDACION = CONVALIDACIONIn;
    }

    public int getIDPAIS_LICEXTRANJERA() {
          return this.IDPAIS_LICEXTRANJERA;
    }
    public void setIDPAIS_LICEXTRANJERA(int IDPAIS_LICEXTRANJERAIn) {
          this.IDPAIS_LICEXTRANJERA = IDPAIS_LICEXTRANJERAIn;
    }

    public String getID_CATEGORIA_LICEXTRAJ() {
          return this.ID_CATEGORIA_LICEXTRAJ;
    }
    public void setID_CATEGORIA_LICEXTRAJ(String ID_CATEGORIA_LICEXTRAJIn) {
          this.ID_CATEGORIA_LICEXTRAJ = ID_CATEGORIA_LICEXTRAJIn;
    }

    public String getNROLICCONDUCCION_EXTRANJ() {
          return this.NROLICCONDUCCION_EXTRANJ;
    }
    public void setNROLICCONDUCCION_EXTRANJ(String NROLICCONDUCCION_EXTRANJIn) {
          this.NROLICCONDUCCION_EXTRANJ = NROLICCONDUCCION_EXTRANJIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String ID_LICENCIACIn,
          String FECHA_EXPIn,
          String CATEGORIAIn,
          String FECHA_VENCIn,
          int ID_TRAMITECONDIn,
          int ID_TRANSITOIn,
          int CODESCUELAIn,
          String CODRANGOIn,
          String NROCOMPROBANTEIn,
          int CODESPECIEVENALIn,
          int NROCONSIGNACIONIn,
          String NROCUENTAIn,
          int ID_BANCOIn,
          int ID_SUCBANCOIn,
          String FECHACONSIGNACIONIn,
          int VALORCONSIGNACIONIn,
          int ID_CONDUCTORIn,
          String FECHATRAMITEIn,
          String NROCERTIFICADOESCUELAIn,
          String FECHAEXPCERTESCLAIn,
          String NROCERTIFCRCIn,
          String FECHAEXPCERTIF_CRCIn,
          int ID_CRCIn,
          int ID_FACTURAIn,
          int ID_USUARIOIn,
          String NROLICANTERIORIn,
          String CONVALIDACIONIn,
          int IDPAIS_LICEXTRANJERAIn,
          String ID_CATEGORIA_LICEXTRAJIn,
          String NROLICCONDUCCION_EXTRANJIn) {
          this.ID_LICENCIAC = ID_LICENCIACIn;
          this.FECHA_EXP = FECHA_EXPIn;
          this.CATEGORIA = CATEGORIAIn;
          this.FECHA_VENC = FECHA_VENCIn;
          this.ID_TRAMITECOND = ID_TRAMITECONDIn;
          this.ID_TRANSITO = ID_TRANSITOIn;
          this.CODESCUELA = CODESCUELAIn;
          this.CODRANGO = CODRANGOIn;
          this.NROCOMPROBANTE = NROCOMPROBANTEIn;
          this.CODESPECIEVENAL = CODESPECIEVENALIn;
          this.NROCONSIGNACION = NROCONSIGNACIONIn;
          this.NROCUENTA = NROCUENTAIn;
          this.ID_BANCO = ID_BANCOIn;
          this.ID_SUCBANCO = ID_SUCBANCOIn;
          this.FECHACONSIGNACION = FECHACONSIGNACIONIn;
          this.VALORCONSIGNACION = VALORCONSIGNACIONIn;
          this.ID_CONDUCTOR = ID_CONDUCTORIn;
          this.FECHATRAMITE = FECHATRAMITEIn;
          this.NROCERTIFICADOESCUELA = NROCERTIFICADOESCUELAIn;
          this.FECHAEXPCERTESCLA = FECHAEXPCERTESCLAIn;
          this.NROCERTIFCRC = NROCERTIFCRCIn;
          this.FECHAEXPCERTIF_CRC = FECHAEXPCERTIF_CRCIn;
          this.ID_CRC = ID_CRCIn;
          this.ID_FACTURA = ID_FACTURAIn;
          this.ID_USUARIO = ID_USUARIOIn;
          this.NROLICANTERIOR = NROLICANTERIORIn;
          this.CONVALIDACION = CONVALIDACIONIn;
          this.IDPAIS_LICEXTRANJERA = IDPAIS_LICEXTRANJERAIn;
          this.ID_CATEGORIA_LICEXTRAJ = ID_CATEGORIA_LICEXTRAJIn;
          this.NROLICCONDUCCION_EXTRANJ = NROLICCONDUCCION_EXTRANJIn;
    }


    /** 
     * hasEqualMapping-method will compare two LicenciasConduccion instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(LicenciasConduccion valueObject) {

          if (this.ID_LICENCIAC == null) {
                    if (valueObject.getID_LICENCIAC() != null)
                           return(false);
          } else if (!this.ID_LICENCIAC.equals(valueObject.getID_LICENCIAC())) {
                    return(false);
          }
          if (this.FECHA_EXP == null) {
                    if (valueObject.getFECHA_EXP() != null)
                           return(false);
          } else if (!this.FECHA_EXP.equals(valueObject.getFECHA_EXP())) {
                    return(false);
          }
          if (this.CATEGORIA == null) {
                    if (valueObject.getCATEGORIA() != null)
                           return(false);
          } else if (!this.CATEGORIA.equals(valueObject.getCATEGORIA())) {
                    return(false);
          }
          if (this.FECHA_VENC == null) {
                    if (valueObject.getFECHA_VENC() != null)
                           return(false);
          } else if (!this.FECHA_VENC.equals(valueObject.getFECHA_VENC())) {
                    return(false);
          }
          if (valueObject.getID_TRAMITECOND() != this.ID_TRAMITECOND) {
                    return(false);
          }
          if (valueObject.getID_TRANSITO() != this.ID_TRANSITO) {
                    return(false);
          }
          if (valueObject.getCODESCUELA() != this.CODESCUELA) {
                    return(false);
          }
          if (this.CODRANGO == null) {
                if (valueObject.getCODRANGO() != null)
                    return(false);
          } else if (!this.CODRANGO.equals(valueObject.getCODRANGO())) {
                  return(false);
          }
          if (this.NROCOMPROBANTE == null) {
                    if (valueObject.getNROCOMPROBANTE() != null)
                           return(false);
          } else if (!this.NROCOMPROBANTE.equals(valueObject.getNROCOMPROBANTE())) {
                    return(false);
          }
          if (valueObject.getCODESPECIEVENAL() != this.CODESPECIEVENAL) {
                    return(false);
          }
          if (valueObject.getNROCONSIGNACION() != this.NROCONSIGNACION) {
                    return(false);
          }
          if (this.NROCUENTA == null) {
                    if (valueObject.getNROCUENTA() != null)
                           return(false);
          } else if (!this.NROCUENTA.equals(valueObject.getNROCUENTA())) {
                    return(false);
          }
          if (valueObject.getID_BANCO() != this.ID_BANCO) {
                    return(false);
          }
          if (valueObject.getID_SUCBANCO() != this.ID_SUCBANCO) {
                    return(false);
          }
          if (this.FECHACONSIGNACION == null) {
                    if (valueObject.getFECHACONSIGNACION() != null)
                           return(false);
          } else if (!this.FECHACONSIGNACION.equals(valueObject.getFECHACONSIGNACION())) {
                    return(false);
          }
          if (valueObject.getVALORCONSIGNACION() != this.VALORCONSIGNACION) {
                    return(false);
          }
          if (valueObject.getID_CONDUCTOR() != this.ID_CONDUCTOR) {
                    return(false);
          }
          if (this.FECHATRAMITE == null) {
                    if (valueObject.getFECHATRAMITE() != null)
                           return(false);
          } else if (!this.FECHATRAMITE.equals(valueObject.getFECHATRAMITE())) {
                    return(false);
          }
          if (this.NROCERTIFICADOESCUELA == null) {
                    if (valueObject.getNROCERTIFICADOESCUELA() != null)
                           return(false);
          } else if (!this.NROCERTIFICADOESCUELA.equals(valueObject.getNROCERTIFICADOESCUELA())) {
                    return(false);
          }
          if (this.FECHAEXPCERTESCLA == null) {
                    if (valueObject.getFECHAEXPCERTESCLA() != null)
                           return(false);
          } else if (!this.FECHAEXPCERTESCLA.equals(valueObject.getFECHAEXPCERTESCLA())) {
                    return(false);
          }
          if (this.NROCERTIFCRC == null) {
                    if (valueObject.getNROCERTIFCRC() != null)
                           return(false);
          } else if (!this.NROCERTIFCRC.equals(valueObject.getNROCERTIFCRC())) {
                    return(false);
          }
          if (this.FECHAEXPCERTIF_CRC == null) {
                    if (valueObject.getFECHAEXPCERTIF_CRC() != null)
                           return(false);
          } else if (!this.FECHAEXPCERTIF_CRC.equals(valueObject.getFECHAEXPCERTIF_CRC())) {
                    return(false);
          }
          if (valueObject.getID_CRC() != this.ID_CRC) {
                    return(false);
          }
          if (valueObject.getID_FACTURA() != this.ID_FACTURA) {
                    return(false);
          }
          if (valueObject.getID_USUARIO() != this.ID_USUARIO) {
                    return(false);
          }
          if (this.NROLICANTERIOR == null) {
                    if (valueObject.getNROLICANTERIOR() != null)
                           return(false);
          } else if (!this.NROLICANTERIOR.equals(valueObject.getNROLICANTERIOR())) {
                    return(false);
          }
          if (this.CONVALIDACION == null) {
                    if (valueObject.getCONVALIDACION() != null)
                           return(false);
          } else if (!this.CONVALIDACION.equals(valueObject.getCONVALIDACION())) {
                    return(false);
          }
          if (valueObject.getIDPAIS_LICEXTRANJERA() != this.IDPAIS_LICEXTRANJERA) {
                    return(false);
          }
          if (this.ID_CATEGORIA_LICEXTRAJ == null) {
                    if (valueObject.getID_CATEGORIA_LICEXTRAJ() != null)
                           return(false);
          } else if (!this.ID_CATEGORIA_LICEXTRAJ.equals(valueObject.getID_CATEGORIA_LICEXTRAJ())) {
                    return(false);
          }
          if (this.NROLICCONDUCCION_EXTRANJ == null) {
                    if (valueObject.getNROLICCONDUCCION_EXTRANJ() != null)
                           return(false);
          } else if (!this.NROLICCONDUCCION_EXTRANJ.equals(valueObject.getNROLICCONDUCCION_EXTRANJ())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass LicenciasConduccion, mapping to table LICENCIADECONDUCCION\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_LICENCIAC = " + this.ID_LICENCIAC + "\n"); 
        out.append("FECHA_EXP = " + this.FECHA_EXP + "\n"); 
        out.append("CATEGORIA = " + this.CATEGORIA + "\n"); 
        out.append("FECHA_VENC = " + this.FECHA_VENC + "\n"); 
        out.append("ID_TRAMITECOND = " + this.ID_TRAMITECOND + "\n"); 
        out.append("ID_TRANSITO = " + this.ID_TRANSITO + "\n"); 
        out.append("CODESCUELA = " + this.CODESCUELA + "\n"); 
        out.append("CODRANGO = " + this.CODRANGO + "\n"); 
        out.append("NROCOMPROBANTE = " + this.NROCOMPROBANTE + "\n"); 
        out.append("CODESPECIEVENAL = " + this.CODESPECIEVENAL + "\n"); 
        out.append("NROCONSIGNACION = " + this.NROCONSIGNACION + "\n"); 
        out.append("NROCUENTA = " + this.NROCUENTA + "\n"); 
        out.append("ID_BANCO = " + this.ID_BANCO + "\n"); 
        out.append("ID_SUCBANCO = " + this.ID_SUCBANCO + "\n"); 
        out.append("FECHACONSIGNACION = " + this.FECHACONSIGNACION + "\n"); 
        out.append("VALORCONSIGNACION = " + this.VALORCONSIGNACION + "\n"); 
        out.append("ID_CONDUCTOR = " + this.ID_CONDUCTOR + "\n"); 
        out.append("FECHATRAMITE = " + this.FECHATRAMITE + "\n"); 
        out.append("NROCERTIFICADOESCUELA = " + this.NROCERTIFICADOESCUELA + "\n"); 
        out.append("FECHAEXPCERTESCLA = " + this.FECHAEXPCERTESCLA + "\n"); 
        out.append("NROCERTIFCRC = " + this.NROCERTIFCRC + "\n"); 
        out.append("FECHAEXPCERTIF_CRC = " + this.FECHAEXPCERTIF_CRC + "\n"); 
        out.append("ID_CRC = " + this.ID_CRC + "\n"); 
        out.append("ID_FACTURA = " + this.ID_FACTURA + "\n"); 
        out.append("ID_USUARIO = " + this.ID_USUARIO + "\n"); 
        out.append("NROLICANTERIOR = " + this.NROLICANTERIOR + "\n"); 
        out.append("CONVALIDACION = " + this.CONVALIDACION + "\n"); 
        out.append("IDPAIS_LICEXTRANJERA = " + this.IDPAIS_LICEXTRANJERA + "\n"); 
        out.append("ID_CATEGORIA_LICEXTRAJ = " + this.ID_CATEGORIA_LICEXTRAJ + "\n"); 
        out.append("NROLICCONDUCCION_EXTRANJ = " + this.NROLICCONDUCCION_EXTRANJ + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        LicenciasConduccion cloned = new LicenciasConduccion();

        if (this.ID_LICENCIAC != null)
             cloned.setID_LICENCIAC(new String(this.ID_LICENCIAC)); 
        if (this.FECHA_EXP != null)
             cloned.setFECHA_EXP(this.FECHA_EXP); 
        if (this.CATEGORIA != null)
             cloned.setCATEGORIA(new String(this.CATEGORIA)); 
        if (this.FECHA_VENC != null)
             cloned.setFECHA_VENC(this.FECHA_VENC); 
        cloned.setID_TRAMITECOND(this.ID_TRAMITECOND); 
        cloned.setID_TRANSITO(this.ID_TRANSITO); 
        cloned.setCODESCUELA(this.CODESCUELA); 
        if (this.CODRANGO != null)
            cloned.setCODRANGO(new String(this.CODRANGO)); 
        if (this.NROCOMPROBANTE != null)
             cloned.setNROCOMPROBANTE(new String(this.NROCOMPROBANTE)); 
        cloned.setCODESPECIEVENAL(this.CODESPECIEVENAL); 
        cloned.setNROCONSIGNACION(this.NROCONSIGNACION); 
        if (this.NROCUENTA != null)
             cloned.setNROCUENTA(new String(this.NROCUENTA)); 
        cloned.setID_BANCO(this.ID_BANCO); 
        cloned.setID_SUCBANCO(this.ID_SUCBANCO); 
        if (this.FECHACONSIGNACION != null)
             cloned.setFECHACONSIGNACION(this.FECHACONSIGNACION); 
        cloned.setVALORCONSIGNACION(this.VALORCONSIGNACION); 
        cloned.setID_CONDUCTOR(this.ID_CONDUCTOR); 
        if (this.FECHATRAMITE != null)
             cloned.setFECHATRAMITE(this.FECHATRAMITE); 
        if (this.NROCERTIFICADOESCUELA != null)
             cloned.setNROCERTIFICADOESCUELA(new String(this.NROCERTIFICADOESCUELA)); 
        if (this.FECHAEXPCERTESCLA != null)
             cloned.setFECHAEXPCERTESCLA(this.FECHAEXPCERTESCLA); 
        if (this.NROCERTIFCRC != null)
             cloned.setNROCERTIFCRC(new String(this.NROCERTIFCRC)); 
        if (this.FECHAEXPCERTIF_CRC != null)
             cloned.setFECHAEXPCERTIF_CRC(this.FECHAEXPCERTIF_CRC); 
        cloned.setID_CRC(this.ID_CRC); 
        cloned.setID_FACTURA(this.ID_FACTURA); 
        cloned.setID_USUARIO(this.ID_USUARIO); 
        if (this.NROLICANTERIOR != null)
             cloned.setNROLICANTERIOR(new String(this.NROLICANTERIOR)); 
        if (this.CONVALIDACION != null)
             cloned.setCONVALIDACION(new String(this.CONVALIDACION)); 
        cloned.setIDPAIS_LICEXTRANJERA(this.IDPAIS_LICEXTRANJERA); 
        if (this.ID_CATEGORIA_LICEXTRAJ != null)
             cloned.setID_CATEGORIA_LICEXTRAJ(new String(this.ID_CATEGORIA_LICEXTRAJ)); 
        if (this.NROLICCONDUCCION_EXTRANJ != null)
             cloned.setNROLICCONDUCCION_EXTRANJ(new String(this.NROLICCONDUCCION_EXTRANJ)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}