package modelo.datos.objetos.generales.vehiculo;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ViewVehiculo Value Object.
  * This class is value object representing database table VIEW_VEHICULO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewVehiculo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDVEHICULO;
    private String PLACA;
    private String MARCAVEH;
    private String LINEAVEH;
    private String MODELO;
    private String CAPACIDAD;
    private String POTENCIA;
    private String CILINDRAJE;
    private String CLASEVEH;
    private String NUMEROSERIE;
    private String NUMEROCHASIS;
    private String SERVICIOVEH;
    private String TIPOCARROCERIA;
    private String NUMEROMOTOR;
    private String FECHAMATRICULA;
    private String NUMMANIFIESTO;
    private String COLORVEH;
    private String NROPUERTAS;
    private String MOTORREGRABADO;
    private String NUMSERIE_REGRABADO;
    private String CHASISREGREBADO;
    private String PESO_BRUTO;
    private String DIST_EJES;
    private String VOLAD_POSTER;
    private String NRO_EJES;
    private String ANCHO;
    private String ALTO;
    private String LARGO;
    private String ACTA;
    private String NUM_ACMANIF;
    private String DES_ADUANA;
    private String FECHA_MANIFIESTO;
    private String OFICIOTRASLADO;
    private String NUMFOLIOSTRASLADO;
    private String ORGTRANSITO;
    private String GENERACERTMOVILIZACION;
    private String DURACIONCERTMOVILIZACION;
    private String CAPACIDADTON;
    private String NUMGUIATRASLADOCTA;
    private String VEHACTIVO;
    private String EMPRESADESERICIO;
    private String T_COMBUSTIBLE;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewVehiculo () {

    }

    public ViewVehiculo (int IDVEHICULOIn) {

          this.IDVEHICULO = IDVEHICULOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDVEHICULO() {
          return this.IDVEHICULO;
    }
    public void setIDVEHICULO(int IDVEHICULOIn) {
          this.IDVEHICULO = IDVEHICULOIn;
    }

    public String getPLACA() {
          return this.PLACA;
    }
    public void setPLACA(String PLACAIn) {
          this.PLACA = PLACAIn;
    }

    public String getMARCAVEH() {
          return this.MARCAVEH;
    }
    public void setMARCAVEH(String MARCAVEHIn) {
          this.MARCAVEH = MARCAVEHIn;
    }

    public String getLINEAVEH() {
          return this.LINEAVEH;
    }
    public void setLINEAVEH(String LINEAVEHIn) {
          this.LINEAVEH = LINEAVEHIn;
    }

    public String getMODELO() {
          return this.MODELO;
    }
    public void setMODELO(String MODELOIn) {
          this.MODELO = MODELOIn;
    }

    public String getCAPACIDAD() {
          return this.CAPACIDAD;
    }
    public void setCAPACIDAD(String CAPACIDADIn) {
          this.CAPACIDAD = CAPACIDADIn;
    }

    public String getPOTENCIA() {
          return this.POTENCIA;
    }
    public void setPOTENCIA(String POTENCIAIn) {
          this.POTENCIA = POTENCIAIn;
    }

    public String getCILINDRAJE() {
          return this.CILINDRAJE;
    }
    public void setCILINDRAJE(String CILINDRAJEIn) {
          this.CILINDRAJE = CILINDRAJEIn;
    }

    public String getCLASEVEH() {
          return this.CLASEVEH;
    }
    public void setCLASEVEH(String CLASEVEHIn) {
          this.CLASEVEH = CLASEVEHIn;
    }

    public String getNUMEROSERIE() {
          return this.NUMEROSERIE;
    }
    public void setNUMEROSERIE(String NUMEROSERIEIn) {
          this.NUMEROSERIE = NUMEROSERIEIn;
    }

    public String getNUMEROCHASIS() {
          return this.NUMEROCHASIS;
    }
    public void setNUMEROCHASIS(String NUMEROCHASISIn) {
          this.NUMEROCHASIS = NUMEROCHASISIn;
    }

    public String getSERVICIOVEH() {
          return this.SERVICIOVEH;
    }
    public void setSERVICIOVEH(String SERVICIOVEHIn) {
          this.SERVICIOVEH = SERVICIOVEHIn;
    }

    public String getTIPOCARROCERIA() {
          return this.TIPOCARROCERIA;
    }
    public void setTIPOCARROCERIA(String TIPOCARROCERIAIn) {
          this.TIPOCARROCERIA = TIPOCARROCERIAIn;
    }

    public String getNUMEROMOTOR() {
          return this.NUMEROMOTOR;
    }
    public void setNUMEROMOTOR(String NUMEROMOTORIn) {
          this.NUMEROMOTOR = NUMEROMOTORIn;
    }

    public String getFECHAMATRICULA() {
          return this.FECHAMATRICULA;
    }
    public void setFECHAMATRICULA(String FECHAMATRICULAIn) {
          this.FECHAMATRICULA = FECHAMATRICULAIn;
    }

    public String getNUMMANIFIESTO() {
          return this.NUMMANIFIESTO;
    }
    public void setNUMMANIFIESTO(String NUMMANIFIESTOIn) {
          this.NUMMANIFIESTO = NUMMANIFIESTOIn;
    }

    public String getCOLORVEH() {
          return this.COLORVEH;
    }
    public void setCOLORVEH(String COLORVEHIn) {
          this.COLORVEH = COLORVEHIn;
    }

    public String getNROPUERTAS() {
          return this.NROPUERTAS;
    }
    public void setNROPUERTAS(String NROPUERTASIn) {
          this.NROPUERTAS = NROPUERTASIn;
    }

    public String getMOTORREGRABADO() {
          return this.MOTORREGRABADO;
    }
    public void setMOTORREGRABADO(String MOTORREGRABADOIn) {
          this.MOTORREGRABADO = MOTORREGRABADOIn;
    }

    public String getNUMSERIE_REGRABADO() {
          return this.NUMSERIE_REGRABADO;
    }
    public void setNUMSERIE_REGRABADO(String NUMSERIE_REGRABADOIn) {
          this.NUMSERIE_REGRABADO = NUMSERIE_REGRABADOIn;
    }

    public String getCHASISREGREBADO() {
          return this.CHASISREGREBADO;
    }
    public void setCHASISREGREBADO(String CHASISREGREBADOIn) {
          this.CHASISREGREBADO = CHASISREGREBADOIn;
    }

    public String getPESO_BRUTO() {
          return this.PESO_BRUTO;
    }
    public void setPESO_BRUTO(String PESO_BRUTOIn) {
          this.PESO_BRUTO = PESO_BRUTOIn;
    }

    public String getDIST_EJES() {
          return this.DIST_EJES;
    }
    public void setDIST_EJES(String DIST_EJESIn) {
          this.DIST_EJES = DIST_EJESIn;
    }

    public String getVOLAD_POSTER() {
          return this.VOLAD_POSTER;
    }
    public void setVOLAD_POSTER(String VOLAD_POSTERIn) {
          this.VOLAD_POSTER = VOLAD_POSTERIn;
    }

    public String getNRO_EJES() {
          return this.NRO_EJES;
    }
    public void setNRO_EJES(String NRO_EJESIn) {
          this.NRO_EJES = NRO_EJESIn;
    }

    public String getANCHO() {
          return this.ANCHO;
    }
    public void setANCHO(String ANCHOIn) {
          this.ANCHO = ANCHOIn;
    }

    public String getALTO() {
          return this.ALTO;
    }
    public void setALTO(String ALTOIn) {
          this.ALTO = ALTOIn;
    }

    public String getLARGO() {
          return this.LARGO;
    }
    public void setLARGO(String LARGOIn) {
          this.LARGO = LARGOIn;
    }

    public String getACTA() {
          return this.ACTA;
    }
    public void setACTA(String ACTAIn) {
          this.ACTA = ACTAIn;
    }

    public String getNUM_ACMANIF() {
          return this.NUM_ACMANIF;
    }
    public void setNUM_ACMANIF(String NUM_ACMANIFIn) {
          this.NUM_ACMANIF = NUM_ACMANIFIn;
    }

    public String getDES_ADUANA() {
          return this.DES_ADUANA;
    }
    public void setDES_ADUANA(String DES_ADUANAIn) {
          this.DES_ADUANA = DES_ADUANAIn;
    }

    public String getFECHA_MANIFIESTO() {
          return this.FECHA_MANIFIESTO;
    }
    public void setFECHA_MANIFIESTO(String FECHA_MANIFIESTOIn) {
          this.FECHA_MANIFIESTO = FECHA_MANIFIESTOIn;
    }

    public String getOFICIOTRASLADO() {
          return this.OFICIOTRASLADO;
    }
    public void setOFICIOTRASLADO(String OFICIOTRASLADOIn) {
          this.OFICIOTRASLADO = OFICIOTRASLADOIn;
    }

    public String getNUMFOLIOSTRASLADO() {
          return this.NUMFOLIOSTRASLADO;
    }
    public void setNUMFOLIOSTRASLADO(String NUMFOLIOSTRASLADOIn) {
          this.NUMFOLIOSTRASLADO = NUMFOLIOSTRASLADOIn;
    }

    public String getORGTRANSITO() {
          return this.ORGTRANSITO;
    }
    public void setORGTRANSITO(String ORGTRANSITOIn) {
          this.ORGTRANSITO = ORGTRANSITOIn;
    }

    public String getGENERACERTMOVILIZACION() {
          return this.GENERACERTMOVILIZACION;
    }
    public void setGENERACERTMOVILIZACION(String GENERACERTMOVILIZACIONIn) {
          this.GENERACERTMOVILIZACION = GENERACERTMOVILIZACIONIn;
    }

    public String getDURACIONCERTMOVILIZACION() {
          return this.DURACIONCERTMOVILIZACION;
    }
    public void setDURACIONCERTMOVILIZACION(String DURACIONCERTMOVILIZACIONIn) {
          this.DURACIONCERTMOVILIZACION = DURACIONCERTMOVILIZACIONIn;
    }

    public String getCAPACIDADTON() {
          return this.CAPACIDADTON;
    }
    public void setCAPACIDADTON(String CAPACIDADTONIn) {
          this.CAPACIDADTON = CAPACIDADTONIn;
    }

    public String getNUMGUIATRASLADOCTA() {
          return this.NUMGUIATRASLADOCTA;
    }
    public void setNUMGUIATRASLADOCTA(String NUMGUIATRASLADOCTAIn) {
          this.NUMGUIATRASLADOCTA = NUMGUIATRASLADOCTAIn;
    }

    public String getVEHACTIVO() {
          return this.VEHACTIVO;
    }
    public void setVEHACTIVO(String VEHACTIVOIn) {
          this.VEHACTIVO = VEHACTIVOIn;
    }

    public String getEMPRESADESERICIO() {
          return this.EMPRESADESERICIO;
    }
    public void setEMPRESADESERICIO(String EMPRESADESERICIOIn) {
          this.EMPRESADESERICIO = EMPRESADESERICIOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDVEHICULOIn,
          String PLACAIn,
          String MARCAVEHIn,
          String LINEAVEHIn,
          String MODELOIn,
          String CAPACIDADIn,
          String POTENCIAIn,
          String CILINDRAJEIn,
          String CLASEVEHIn,
          String NUMEROSERIEIn,
          String NUMEROCHASISIn,
          String SERVICIOVEHIn,
          String TIPOCARROCERIAIn,
          String NUMEROMOTORIn,
          String FECHAMATRICULAIn,
          String NUMMANIFIESTOIn,
          String COLORVEHIn,
          String NROPUERTASIn,
          String MOTORREGRABADOIn,
          String NUMSERIE_REGRABADOIn,
          String CHASISREGREBADOIn,
          String PESO_BRUTOIn,
          String DIST_EJESIn,
          String VOLAD_POSTERIn,
          String NRO_EJESIn,
          String ANCHOIn,
          String ALTOIn,
          String LARGOIn,
          String ACTAIn,
          String NUM_ACMANIFIn,
          String DES_ADUANAIn,
          String FECHA_MANIFIESTOIn,
          String OFICIOTRASLADOIn,
          String NUMFOLIOSTRASLADOIn,
          String ORGTRANSITOIn,
          String GENERACERTMOVILIZACIONIn,
          String DURACIONCERTMOVILIZACIONIn,
          String CAPACIDADTONIn,
          String NUMGUIATRASLADOCTAIn,
          String VEHACTIVOIn,
          String EMPRESADESERICIOIn) {
          this.IDVEHICULO = IDVEHICULOIn;
          this.PLACA = PLACAIn;
          this.MARCAVEH = MARCAVEHIn;
          this.LINEAVEH = LINEAVEHIn;
          this.MODELO = MODELOIn;
          this.CAPACIDAD = CAPACIDADIn;
          this.POTENCIA = POTENCIAIn;
          this.CILINDRAJE = CILINDRAJEIn;
          this.CLASEVEH = CLASEVEHIn;
          this.NUMEROSERIE = NUMEROSERIEIn;
          this.NUMEROCHASIS = NUMEROCHASISIn;
          this.SERVICIOVEH = SERVICIOVEHIn;
          this.TIPOCARROCERIA = TIPOCARROCERIAIn;
          this.NUMEROMOTOR = NUMEROMOTORIn;
          this.FECHAMATRICULA = FECHAMATRICULAIn;
          this.NUMMANIFIESTO = NUMMANIFIESTOIn;
          this.COLORVEH = COLORVEHIn;
          this.NROPUERTAS = NROPUERTASIn;
          this.MOTORREGRABADO = MOTORREGRABADOIn;
          this.NUMSERIE_REGRABADO = NUMSERIE_REGRABADOIn;
          this.CHASISREGREBADO = CHASISREGREBADOIn;
          this.PESO_BRUTO = PESO_BRUTOIn;
          this.DIST_EJES = DIST_EJESIn;
          this.VOLAD_POSTER = VOLAD_POSTERIn;
          this.NRO_EJES = NRO_EJESIn;
          this.ANCHO = ANCHOIn;
          this.ALTO = ALTOIn;
          this.LARGO = LARGOIn;
          this.ACTA = ACTAIn;
          this.NUM_ACMANIF = NUM_ACMANIFIn;
          this.DES_ADUANA = DES_ADUANAIn;
          this.FECHA_MANIFIESTO = FECHA_MANIFIESTOIn;
          this.OFICIOTRASLADO = OFICIOTRASLADOIn;
          this.NUMFOLIOSTRASLADO = NUMFOLIOSTRASLADOIn;
          this.ORGTRANSITO = ORGTRANSITOIn;
          this.GENERACERTMOVILIZACION = GENERACERTMOVILIZACIONIn;
          this.DURACIONCERTMOVILIZACION = DURACIONCERTMOVILIZACIONIn;
          this.CAPACIDADTON = CAPACIDADTONIn;
          this.NUMGUIATRASLADOCTA = NUMGUIATRASLADOCTAIn;
          this.VEHACTIVO = VEHACTIVOIn;
          this.EMPRESADESERICIO = EMPRESADESERICIOIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewVehiculo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewVehiculo valueObject) {

          if (valueObject.getIDVEHICULO() != this.IDVEHICULO) {
                    return(false);
          }
          if (this.PLACA == null) {
                    if (valueObject.getPLACA() != null)
                           return(false);
          } else if (!this.PLACA.equals(valueObject.getPLACA())) {
                    return(false);
          }
          if (this.MARCAVEH == null) {
                    if (valueObject.getMARCAVEH() != null)
                           return(false);
          } else if (!this.MARCAVEH.equals(valueObject.getMARCAVEH())) {
                    return(false);
          }
          if (this.LINEAVEH == null) {
                    if (valueObject.getLINEAVEH() != null)
                           return(false);
          } else if (!this.LINEAVEH.equals(valueObject.getLINEAVEH())) {
                    return(false);
          }
          if (this.MODELO == null) {
                    if (valueObject.getMODELO() != null)
                           return(false);
          } else if (!this.MODELO.equals(valueObject.getMODELO())) {
                    return(false);
          }
          if (this.CAPACIDAD == null) {
                    if (valueObject.getCAPACIDAD() != null)
                           return(false);
          } else if (!this.CAPACIDAD.equals(valueObject.getCAPACIDAD())) {
                    return(false);
          }
          if (this.POTENCIA == null) {
                    if (valueObject.getPOTENCIA() != null)
                           return(false);
          } else if (!this.POTENCIA.equals(valueObject.getPOTENCIA())) {
                    return(false);
          }
          if (this.CILINDRAJE == null) {
                    if (valueObject.getCILINDRAJE() != null)
                           return(false);
          } else if (!this.CILINDRAJE.equals(valueObject.getCILINDRAJE())) {
                    return(false);
          }
          if (this.CLASEVEH == null) {
                    if (valueObject.getCLASEVEH() != null)
                           return(false);
          } else if (!this.CLASEVEH.equals(valueObject.getCLASEVEH())) {
                    return(false);
          }
          if (this.NUMEROSERIE == null) {
                    if (valueObject.getNUMEROSERIE() != null)
                           return(false);
          } else if (!this.NUMEROSERIE.equals(valueObject.getNUMEROSERIE())) {
                    return(false);
          }
          if (this.NUMEROCHASIS == null) {
                    if (valueObject.getNUMEROCHASIS() != null)
                           return(false);
          } else if (!this.NUMEROCHASIS.equals(valueObject.getNUMEROCHASIS())) {
                    return(false);
          }
          if (this.SERVICIOVEH == null) {
                    if (valueObject.getSERVICIOVEH() != null)
                           return(false);
          } else if (!this.SERVICIOVEH.equals(valueObject.getSERVICIOVEH())) {
                    return(false);
          }
          if (this.TIPOCARROCERIA == null) {
                    if (valueObject.getTIPOCARROCERIA() != null)
                           return(false);
          } else if (!this.TIPOCARROCERIA.equals(valueObject.getTIPOCARROCERIA())) {
                    return(false);
          }
          if (this.NUMEROMOTOR == null) {
                    if (valueObject.getNUMEROMOTOR() != null)
                           return(false);
          } else if (!this.NUMEROMOTOR.equals(valueObject.getNUMEROMOTOR())) {
                    return(false);
          }
          if (this.FECHAMATRICULA == null) {
                    if (valueObject.getFECHAMATRICULA() != null)
                           return(false);
          } else if (!this.FECHAMATRICULA.equals(valueObject.getFECHAMATRICULA())) {
                    return(false);
          }
          if (this.NUMMANIFIESTO == null) {
                    if (valueObject.getNUMMANIFIESTO() != null)
                           return(false);
          } else if (!this.NUMMANIFIESTO.equals(valueObject.getNUMMANIFIESTO())) {
                    return(false);
          }
          if (this.COLORVEH == null) {
                    if (valueObject.getCOLORVEH() != null)
                           return(false);
          } else if (!this.COLORVEH.equals(valueObject.getCOLORVEH())) {
                    return(false);
          }
          if (this.NROPUERTAS == null) {
                    if (valueObject.getNROPUERTAS() != null)
                           return(false);
          } else if (!this.NROPUERTAS.equals(valueObject.getNROPUERTAS())) {
                    return(false);
          }
          if (this.MOTORREGRABADO == null) {
                    if (valueObject.getMOTORREGRABADO() != null)
                           return(false);
          } else if (!this.MOTORREGRABADO.equals(valueObject.getMOTORREGRABADO())) {
                    return(false);
          }
          if (this.NUMSERIE_REGRABADO == null) {
                    if (valueObject.getNUMSERIE_REGRABADO() != null)
                           return(false);
          } else if (!this.NUMSERIE_REGRABADO.equals(valueObject.getNUMSERIE_REGRABADO())) {
                    return(false);
          }
          if (this.CHASISREGREBADO == null) {
                    if (valueObject.getCHASISREGREBADO() != null)
                           return(false);
          } else if (!this.CHASISREGREBADO.equals(valueObject.getCHASISREGREBADO())) {
                    return(false);
          }
          if (this.PESO_BRUTO == null) {
                    if (valueObject.getPESO_BRUTO() != null)
                           return(false);
          } else if (!this.PESO_BRUTO.equals(valueObject.getPESO_BRUTO())) {
                    return(false);
          }
          if (this.DIST_EJES == null) {
                    if (valueObject.getDIST_EJES() != null)
                           return(false);
          } else if (!this.DIST_EJES.equals(valueObject.getDIST_EJES())) {
                    return(false);
          }
          if (this.VOLAD_POSTER == null) {
                    if (valueObject.getVOLAD_POSTER() != null)
                           return(false);
          } else if (!this.VOLAD_POSTER.equals(valueObject.getVOLAD_POSTER())) {
                    return(false);
          }
          if (this.NRO_EJES == null) {
                    if (valueObject.getNRO_EJES() != null)
                           return(false);
          } else if (!this.NRO_EJES.equals(valueObject.getNRO_EJES())) {
                    return(false);
          }
          if (this.ANCHO == null) {
                    if (valueObject.getANCHO() != null)
                           return(false);
          } else if (!this.ANCHO.equals(valueObject.getANCHO())) {
                    return(false);
          }
          if (this.ALTO == null) {
                    if (valueObject.getALTO() != null)
                           return(false);
          } else if (!this.ALTO.equals(valueObject.getALTO())) {
                    return(false);
          }
          if (this.LARGO == null) {
                    if (valueObject.getLARGO() != null)
                           return(false);
          } else if (!this.LARGO.equals(valueObject.getLARGO())) {
                    return(false);
          }
          if (this.ACTA == null) {
                    if (valueObject.getACTA() != null)
                           return(false);
          } else if (!this.ACTA.equals(valueObject.getACTA())) {
                    return(false);
          }
          if (this.NUM_ACMANIF == null) {
                    if (valueObject.getNUM_ACMANIF() != null)
                           return(false);
          } else if (!this.NUM_ACMANIF.equals(valueObject.getNUM_ACMANIF())) {
                    return(false);
          }
          if (this.DES_ADUANA == null) {
                    if (valueObject.getDES_ADUANA() != null)
                           return(false);
          } else if (!this.DES_ADUANA.equals(valueObject.getDES_ADUANA())) {
                    return(false);
          }
          if (this.FECHA_MANIFIESTO == null) {
                    if (valueObject.getFECHA_MANIFIESTO() != null)
                           return(false);
          } else if (!this.FECHA_MANIFIESTO.equals(valueObject.getFECHA_MANIFIESTO())) {
                    return(false);
          }
          if (this.OFICIOTRASLADO == null) {
                    if (valueObject.getOFICIOTRASLADO() != null)
                           return(false);
          } else if (!this.OFICIOTRASLADO.equals(valueObject.getOFICIOTRASLADO())) {
                    return(false);
          }
          if (this.NUMFOLIOSTRASLADO == null) {
                    if (valueObject.getNUMFOLIOSTRASLADO() != null)
                           return(false);
          } else if (!this.NUMFOLIOSTRASLADO.equals(valueObject.getNUMFOLIOSTRASLADO())) {
                    return(false);
          }
          if (this.ORGTRANSITO == null) {
                    if (valueObject.getORGTRANSITO() != null)
                           return(false);
          } else if (!this.ORGTRANSITO.equals(valueObject.getORGTRANSITO())) {
                    return(false);
          }
          if (this.GENERACERTMOVILIZACION == null) {
                    if (valueObject.getGENERACERTMOVILIZACION() != null)
                           return(false);
          } else if (!this.GENERACERTMOVILIZACION.equals(valueObject.getGENERACERTMOVILIZACION())) {
                    return(false);
          }
          if (this.DURACIONCERTMOVILIZACION == null) {
                    if (valueObject.getDURACIONCERTMOVILIZACION() != null)
                           return(false);
          } else if (!this.DURACIONCERTMOVILIZACION.equals(valueObject.getDURACIONCERTMOVILIZACION())) {
                    return(false);
          }
          if (this.CAPACIDADTON == null) {
                    if (valueObject.getCAPACIDADTON() != null)
                           return(false);
          } else if (!this.CAPACIDADTON.equals(valueObject.getCAPACIDADTON())) {
                    return(false);
          }
          if (this.NUMGUIATRASLADOCTA == null) {
                    if (valueObject.getNUMGUIATRASLADOCTA() != null)
                           return(false);
          } else if (!this.NUMGUIATRASLADOCTA.equals(valueObject.getNUMGUIATRASLADOCTA())) {
                    return(false);
          }
          if (this.VEHACTIVO == null) {
                    if (valueObject.getVEHACTIVO() != null)
                           return(false);
          } else if (!this.VEHACTIVO.equals(valueObject.getVEHACTIVO())) {
                    return(false);
          }
          if (this.EMPRESADESERICIO == null) {
                    if (valueObject.getEMPRESADESERICIO() != null)
                           return(false);
          } else if (!this.EMPRESADESERICIO.equals(valueObject.getEMPRESADESERICIO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewVehiculo, mapping to table VIEW_VEHICULO\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDVEHICULO = " + this.IDVEHICULO + "\n"); 
        out.append("PLACA = " + this.PLACA + "\n"); 
        out.append("MARCAVEH = " + this.MARCAVEH + "\n"); 
        out.append("LINEAVEH = " + this.LINEAVEH + "\n"); 
        out.append("MODELO = " + this.MODELO + "\n"); 
        out.append("CAPACIDAD = " + this.CAPACIDAD + "\n"); 
        out.append("POTENCIA = " + this.POTENCIA + "\n"); 
        out.append("CILINDRAJE = " + this.CILINDRAJE + "\n"); 
        out.append("CLASEVEH = " + this.CLASEVEH + "\n"); 
        out.append("NUMEROSERIE = " + this.NUMEROSERIE + "\n"); 
        out.append("NUMEROCHASIS = " + this.NUMEROCHASIS + "\n"); 
        out.append("SERVICIOVEH = " + this.SERVICIOVEH + "\n"); 
        out.append("TIPOCARROCERIA = " + this.TIPOCARROCERIA + "\n"); 
        out.append("NUMEROMOTOR = " + this.NUMEROMOTOR + "\n"); 
        out.append("FECHAMATRICULA = " + this.FECHAMATRICULA + "\n"); 
        out.append("NUMMANIFIESTO = " + this.NUMMANIFIESTO + "\n"); 
        out.append("COLORVEH = " + this.COLORVEH + "\n"); 
        out.append("NROPUERTAS = " + this.NROPUERTAS + "\n"); 
        out.append("MOTORREGRABADO = " + this.MOTORREGRABADO + "\n"); 
        out.append("NUMSERIE_REGRABADO = " + this.NUMSERIE_REGRABADO + "\n"); 
        out.append("CHASISREGREBADO = " + this.CHASISREGREBADO + "\n"); 
        out.append("PESO_BRUTO = " + this.PESO_BRUTO + "\n"); 
        out.append("DIST_EJES = " + this.DIST_EJES + "\n"); 
        out.append("VOLAD_POSTER = " + this.VOLAD_POSTER + "\n"); 
        out.append("NRO_EJES = " + this.NRO_EJES + "\n"); 
        out.append("ANCHO = " + this.ANCHO + "\n"); 
        out.append("ALTO = " + this.ALTO + "\n"); 
        out.append("LARGO = " + this.LARGO + "\n"); 
        out.append("ACTA = " + this.ACTA + "\n"); 
        out.append("NUM_ACMANIF = " + this.NUM_ACMANIF + "\n"); 
        out.append("DES_ADUANA = " + this.DES_ADUANA + "\n"); 
        out.append("FECHA_MANIFIESTO = " + this.FECHA_MANIFIESTO + "\n"); 
        out.append("OFICIOTRASLADO = " + this.OFICIOTRASLADO + "\n"); 
        out.append("NUMFOLIOSTRASLADO = " + this.NUMFOLIOSTRASLADO + "\n"); 
        out.append("ORGTRANSITO = " + this.ORGTRANSITO + "\n"); 
        out.append("GENERACERTMOVILIZACION = " + this.GENERACERTMOVILIZACION + "\n"); 
        out.append("DURACIONCERTMOVILIZACION = " + this.DURACIONCERTMOVILIZACION + "\n"); 
        out.append("CAPACIDADTON = " + this.CAPACIDADTON + "\n"); 
        out.append("NUMGUIATRASLADOCTA = " + this.NUMGUIATRASLADOCTA + "\n"); 
        out.append("VEHACTIVO = " + this.VEHACTIVO + "\n"); 
        out.append("EMPRESADESERICIO = " + this.EMPRESADESERICIO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewVehiculo cloned = new ViewVehiculo();

        cloned.setIDVEHICULO(this.IDVEHICULO); 
        if (this.PLACA != null)
             cloned.setPLACA(new String(this.PLACA)); 
        if (this.MARCAVEH != null)
             cloned.setMARCAVEH(new String(this.MARCAVEH)); 
        if (this.LINEAVEH != null)
             cloned.setLINEAVEH(new String(this.LINEAVEH)); 
        if (this.MODELO != null)
             cloned.setMODELO(new String(this.MODELO)); 
        if (this.CAPACIDAD != null)
             cloned.setCAPACIDAD(new String(this.CAPACIDAD)); 
        if (this.POTENCIA != null)
             cloned.setPOTENCIA(new String(this.POTENCIA)); 
        if (this.CILINDRAJE != null)
             cloned.setCILINDRAJE(new String(this.CILINDRAJE)); 
        if (this.CLASEVEH != null)
             cloned.setCLASEVEH(new String(this.CLASEVEH)); 
        if (this.NUMEROSERIE != null)
             cloned.setNUMEROSERIE(new String(this.NUMEROSERIE)); 
        if (this.NUMEROCHASIS != null)
             cloned.setNUMEROCHASIS(new String(this.NUMEROCHASIS)); 
        if (this.SERVICIOVEH != null)
             cloned.setSERVICIOVEH(new String(this.SERVICIOVEH)); 
        if (this.TIPOCARROCERIA != null)
             cloned.setTIPOCARROCERIA(new String(this.TIPOCARROCERIA)); 
        if (this.NUMEROMOTOR != null)
             cloned.setNUMEROMOTOR(new String(this.NUMEROMOTOR)); 
        if (this.FECHAMATRICULA != null)
             cloned.setFECHAMATRICULA(new String(this.FECHAMATRICULA)); 
        if (this.NUMMANIFIESTO != null)
             cloned.setNUMMANIFIESTO(new String(this.NUMMANIFIESTO)); 
        if (this.COLORVEH != null)
             cloned.setCOLORVEH(new String(this.COLORVEH)); 
        if (this.NROPUERTAS != null)
             cloned.setNROPUERTAS(new String(this.NROPUERTAS)); 
        if (this.MOTORREGRABADO != null)
             cloned.setMOTORREGRABADO(new String(this.MOTORREGRABADO)); 
        if (this.NUMSERIE_REGRABADO != null)
             cloned.setNUMSERIE_REGRABADO(new String(this.NUMSERIE_REGRABADO)); 
        if (this.CHASISREGREBADO != null)
             cloned.setCHASISREGREBADO(new String(this.CHASISREGREBADO)); 
        if (this.PESO_BRUTO != null)
             cloned.setPESO_BRUTO(new String(this.PESO_BRUTO)); 
        if (this.DIST_EJES != null)
             cloned.setDIST_EJES(new String(this.DIST_EJES)); 
        if (this.VOLAD_POSTER != null)
             cloned.setVOLAD_POSTER(new String(this.VOLAD_POSTER)); 
        if (this.NRO_EJES != null)
             cloned.setNRO_EJES(new String(this.NRO_EJES)); 
        if (this.ANCHO != null)
             cloned.setANCHO(new String(this.ANCHO)); 
        if (this.ALTO != null)
             cloned.setALTO(new String(this.ALTO)); 
        if (this.LARGO != null)
             cloned.setLARGO(new String(this.LARGO)); 
        if (this.ACTA != null)
             cloned.setACTA(new String(this.ACTA)); 
        if (this.NUM_ACMANIF != null)
             cloned.setNUM_ACMANIF(new String(this.NUM_ACMANIF)); 
        if (this.DES_ADUANA != null)
             cloned.setDES_ADUANA(new String(this.DES_ADUANA)); 
        if (this.FECHA_MANIFIESTO != null)
             cloned.setFECHA_MANIFIESTO(new String(this.FECHA_MANIFIESTO)); 
        if (this.OFICIOTRASLADO != null)
             cloned.setOFICIOTRASLADO(new String(this.OFICIOTRASLADO)); 
        if (this.NUMFOLIOSTRASLADO != null)
             cloned.setNUMFOLIOSTRASLADO(new String(this.NUMFOLIOSTRASLADO)); 
        if (this.ORGTRANSITO != null)
             cloned.setORGTRANSITO(new String(this.ORGTRANSITO)); 
        if (this.GENERACERTMOVILIZACION != null)
             cloned.setGENERACERTMOVILIZACION(new String(this.GENERACERTMOVILIZACION)); 
        if (this.DURACIONCERTMOVILIZACION != null)
             cloned.setDURACIONCERTMOVILIZACION(new String(this.DURACIONCERTMOVILIZACION)); 
        if (this.CAPACIDADTON != null)
             cloned.setCAPACIDADTON(new String(this.CAPACIDADTON)); 
        if (this.NUMGUIATRASLADOCTA != null)
             cloned.setNUMGUIATRASLADOCTA(new String(this.NUMGUIATRASLADOCTA)); 
        if (this.VEHACTIVO != null)
             cloned.setVEHACTIVO(new String(this.VEHACTIVO)); 
        if (this.EMPRESADESERICIO != null)
             cloned.setEMPRESADESERICIO(new String(this.EMPRESADESERICIO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

    /**
     * @return the T_COMBUSTIBLE
     */
    public String getT_COMBUSTIBLE() {
        return T_COMBUSTIBLE;
    }

    /**
     * @param T_COMBUSTIBLE the T_COMBUSTIBLE to set
     */
    public void setT_COMBUSTIBLE(String T_COMBUSTIBLE) {
        this.T_COMBUSTIBLE = T_COMBUSTIBLE;
    }

}

