package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Empresa Value Object.
  * This class is value object representing database table Empresa
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Empresa implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_EMPRESA;
    private String NIT;
    private String RAZONSOCIAL;
    private String SIGLA;
    private int DIG_VERIF;
    private int ID_CLASEEMPRESA;
    private String FECHACONST;
    private String ID_DOCTO;
    private int ID_RUNTTIPOSOCIEDAD;
    private String PRESTADOR_SERVICIOS;
    private double CAPITAL_PAGADO;
    private double PATRIMONIO_LIQUIDO;
    private String COD_TIPOENTIDAD;
    private String CERTIFICADO_EXISREPLEGAL;
    private String EMAIL;
    private String REGISTRADO_RUNT;
    private String CELULAR;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Empresa () {

    }

    public Empresa (int ID_EMPRESAIn) {

          this.ID_EMPRESA = ID_EMPRESAIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_EMPRESA() {
          return this.ID_EMPRESA;
    }
    public void setID_EMPRESA(int ID_EMPRESAIn) {
          this.ID_EMPRESA = ID_EMPRESAIn;
    }

    public String getNIT() {
          return this.NIT;
    }
    public void setNIT(String NITIn) {
          this.NIT = NITIn;
    }

    public String getRAZONSOCIAL() {
          return this.RAZONSOCIAL;
    }
    public void setRAZONSOCIAL(String RAZONSOCIALIn) {
          this.RAZONSOCIAL = RAZONSOCIALIn;
    }

    public String getSIGLA() {
          return this.SIGLA;
    }
    public void setSIGLA(String SIGLAIn) {
          this.SIGLA = SIGLAIn;
    }

    public int getDIG_VERIF() {
          return this.DIG_VERIF;
    }
    public void setDIG_VERIF(int DIG_VERIFIn) {
          this.DIG_VERIF = DIG_VERIFIn;
    }

    public int getID_CLASEEMPRESA() {
          return this.ID_CLASEEMPRESA;
    }
    public void setID_CLASEEMPRESA(int ID_CLASEEMPRESAIn) {
          this.ID_CLASEEMPRESA = ID_CLASEEMPRESAIn;
    }

    public String getFECHACONST() {
          return this.FECHACONST;
    }
    public void setFECHACONST(String FECHACONSTIn) {
          this.FECHACONST = FECHACONSTIn;
    }

    public String getID_DOCTO() {
          return this.ID_DOCTO;
    }
    public void setID_DOCTO(String ID_DOCTOIn) {
          this.ID_DOCTO = ID_DOCTOIn;
    }

    public int getID_RUNTTIPOSOCIEDAD() {
          return this.ID_RUNTTIPOSOCIEDAD;
    }
    public void setID_RUNTTIPOSOCIEDAD(int ID_RUNTTIPOSOCIEDADIn) {
          this.ID_RUNTTIPOSOCIEDAD = ID_RUNTTIPOSOCIEDADIn;
    }

    public String getPRESTADOR_SERVICIOS() {
          return this.PRESTADOR_SERVICIOS;
    }
    public void setPRESTADOR_SERVICIOS(String PRESTADOR_SERVICIOSIn) {
          this.PRESTADOR_SERVICIOS = PRESTADOR_SERVICIOSIn;
    }

    public double getCAPITAL_PAGADO() {
          return this.CAPITAL_PAGADO;
    }
    public void setCAPITAL_PAGADO(double CAPITAL_PAGADOIn) {
          this.CAPITAL_PAGADO = CAPITAL_PAGADOIn;
    }

    public double getPATRIMONIO_LIQUIDO() {
          return this.PATRIMONIO_LIQUIDO;
    }
    public void setPATRIMONIO_LIQUIDO(double PATRIMONIO_LIQUIDOIn) {
          this.PATRIMONIO_LIQUIDO = PATRIMONIO_LIQUIDOIn;
    }

    public String getCOD_TIPOENTIDAD() {
          return this.COD_TIPOENTIDAD;
    }
    public void setCOD_TIPOENTIDAD(String COD_TIPOENTIDADIn) {
          this.COD_TIPOENTIDAD = COD_TIPOENTIDADIn;
    }

    public String getCERTIFICADO_EXISREPLEGAL() {
          return this.CERTIFICADO_EXISREPLEGAL;
    }
    public void setCERTIFICADO_EXISREPLEGAL(String CERTIFICADO_EXISREPLEGALIn) {
          this.CERTIFICADO_EXISREPLEGAL = CERTIFICADO_EXISREPLEGALIn;
    }

    public String getEMAIL() {
          return this.EMAIL;
    }
    public void setEMAIL(String EMAILIn) {
          this.EMAIL = EMAILIn;
    }

    public String getREGISTRADO_RUNT() {
          return this.REGISTRADO_RUNT;
    }
    public void setREGISTRADO_RUNT(String REGISTRADO_RUNTIn) {
          this.REGISTRADO_RUNT = REGISTRADO_RUNTIn;
    }

    public String getCELULAR() {
          return this.CELULAR;
    }
    public void setCELULAR(String CELULARIn) {
          this.CELULAR = CELULARIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_EMPRESAIn,
          String NITIn,
          String RAZONSOCIALIn,
          String SIGLAIn,
          int DIG_VERIFIn,
          int ID_CLASEEMPRESAIn,
          String FECHACONSTIn,
          String ID_DOCTOIn,
          int ID_RUNTTIPOSOCIEDADIn,
          String PRESTADOR_SERVICIOSIn,
          double CAPITAL_PAGADOIn,
          double PATRIMONIO_LIQUIDOIn,
          String COD_TIPOENTIDADIn,
          String CERTIFICADO_EXISREPLEGALIn,
          String EMAILIn,
          String REGISTRADO_RUNTIn,
          String CELULARIn) {
          this.ID_EMPRESA = ID_EMPRESAIn;
          this.NIT = NITIn;
          this.RAZONSOCIAL = RAZONSOCIALIn;
          this.SIGLA = SIGLAIn;
          this.DIG_VERIF = DIG_VERIFIn;
          this.ID_CLASEEMPRESA = ID_CLASEEMPRESAIn;
          this.FECHACONST = FECHACONSTIn;
          this.ID_DOCTO = ID_DOCTOIn;
          this.ID_RUNTTIPOSOCIEDAD = ID_RUNTTIPOSOCIEDADIn;
          this.PRESTADOR_SERVICIOS = PRESTADOR_SERVICIOSIn;
          this.CAPITAL_PAGADO = CAPITAL_PAGADOIn;
          this.PATRIMONIO_LIQUIDO = PATRIMONIO_LIQUIDOIn;
          this.COD_TIPOENTIDAD = COD_TIPOENTIDADIn;
          this.CERTIFICADO_EXISREPLEGAL = CERTIFICADO_EXISREPLEGALIn;
          this.EMAIL = EMAILIn;
          this.REGISTRADO_RUNT = REGISTRADO_RUNTIn;
          this.CELULAR = CELULARIn;
    }


    /** 
     * hasEqualMapping-method will compare two Empresa instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Empresa valueObject) {

          if (valueObject.getID_EMPRESA() != this.ID_EMPRESA) {
                    return(false);
          }
          if (this.NIT == null) {
                    if (valueObject.getNIT() != null)
                           return(false);
          } else if (!this.NIT.equals(valueObject.getNIT())) {
                    return(false);
          }
          if (this.RAZONSOCIAL == null) {
                    if (valueObject.getRAZONSOCIAL() != null)
                           return(false);
          } else if (!this.RAZONSOCIAL.equals(valueObject.getRAZONSOCIAL())) {
                    return(false);
          }
          if (this.SIGLA == null) {
                    if (valueObject.getSIGLA() != null)
                           return(false);
          } else if (!this.SIGLA.equals(valueObject.getSIGLA())) {
                    return(false);
          }
          if (valueObject.getDIG_VERIF() != this.DIG_VERIF) {
                    return(false);
          }
          if (valueObject.getID_CLASEEMPRESA() != this.ID_CLASEEMPRESA) {
                    return(false);
          }
          if (this.FECHACONST == null) {
                    if (valueObject.getFECHACONST() != null)
                           return(false);
          } else if (!this.FECHACONST.equals(valueObject.getFECHACONST())) {
                    return(false);
          }
          if (this.ID_DOCTO == null) {
                    if (valueObject.getID_DOCTO() != null)
                           return(false);
          } else if (!this.ID_DOCTO.equals(valueObject.getID_DOCTO())) {
                    return(false);
          }
          if (valueObject.getID_RUNTTIPOSOCIEDAD() != this.ID_RUNTTIPOSOCIEDAD) {
                    return(false);
          }
          if (this.PRESTADOR_SERVICIOS == null) {
                    if (valueObject.getPRESTADOR_SERVICIOS() != null)
                           return(false);
          } else if (!this.PRESTADOR_SERVICIOS.equals(valueObject.getPRESTADOR_SERVICIOS())) {
                    return(false);
          }
          if (valueObject.getCAPITAL_PAGADO() != this.CAPITAL_PAGADO) {
                    return(false);
          }
          if (valueObject.getPATRIMONIO_LIQUIDO() != this.PATRIMONIO_LIQUIDO) {
                    return(false);
          }
          if (this.COD_TIPOENTIDAD == null) {
                    if (valueObject.getCOD_TIPOENTIDAD() != null)
                           return(false);
          } else if (!this.COD_TIPOENTIDAD.equals(valueObject.getCOD_TIPOENTIDAD())) {
                    return(false);
          }
          if (this.CERTIFICADO_EXISREPLEGAL == null) {
                    if (valueObject.getCERTIFICADO_EXISREPLEGAL() != null)
                           return(false);
          } else if (!this.CERTIFICADO_EXISREPLEGAL.equals(valueObject.getCERTIFICADO_EXISREPLEGAL())) {
                    return(false);
          }
          if (this.EMAIL == null) {
                    if (valueObject.getEMAIL() != null)
                           return(false);
          } else if (!this.EMAIL.equals(valueObject.getEMAIL())) {
                    return(false);
          }
          if (this.REGISTRADO_RUNT == null) {
                    if (valueObject.getREGISTRADO_RUNT() != null)
                           return(false);
          } else if (!this.REGISTRADO_RUNT.equals(valueObject.getREGISTRADO_RUNT())) {
                    return(false);
          }
          if (this.CELULAR == null) {
                    if (valueObject.getCELULAR() != null)
                           return(false);
          } else if (!this.CELULAR.equals(valueObject.getCELULAR())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Empresa, mapping to table Empresa\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_EMPRESA = " + this.ID_EMPRESA + "\n"); 
        out.append("NIT = " + this.NIT + "\n"); 
        out.append("RAZONSOCIAL = " + this.RAZONSOCIAL + "\n"); 
        out.append("SIGLA = " + this.SIGLA + "\n"); 
        out.append("DIG_VERIF = " + this.DIG_VERIF + "\n"); 
        out.append("ID_CLASEEMPRESA = " + this.ID_CLASEEMPRESA + "\n"); 
        out.append("FECHACONST = " + this.FECHACONST + "\n"); 
        out.append("ID_DOCTO = " + this.ID_DOCTO + "\n"); 
        out.append("ID_RUNTTIPOSOCIEDAD = " + this.ID_RUNTTIPOSOCIEDAD + "\n"); 
        out.append("PRESTADOR_SERVICIOS = " + this.PRESTADOR_SERVICIOS + "\n"); 
        out.append("CAPITAL_PAGADO = " + this.CAPITAL_PAGADO + "\n"); 
        out.append("PATRIMONIO_LIQUIDO = " + this.PATRIMONIO_LIQUIDO + "\n"); 
        out.append("COD_TIPOENTIDAD = " + this.COD_TIPOENTIDAD + "\n"); 
        out.append("CERTIFICADO_EXISREPLEGAL = " + this.CERTIFICADO_EXISREPLEGAL + "\n"); 
        out.append("EMAIL = " + this.EMAIL + "\n"); 
        out.append("REGISTRADO_RUNT = " + this.REGISTRADO_RUNT + "\n"); 
        out.append("CELULAR = " + this.CELULAR + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Empresa cloned = new Empresa();

        cloned.setID_EMPRESA(this.ID_EMPRESA); 
        if (this.NIT != null)
             cloned.setNIT(new String(this.NIT)); 
        if (this.RAZONSOCIAL != null)
             cloned.setRAZONSOCIAL(new String(this.RAZONSOCIAL)); 
        if (this.SIGLA != null)
             cloned.setSIGLA(new String(this.SIGLA)); 
        cloned.setDIG_VERIF(this.DIG_VERIF); 
        cloned.setID_CLASEEMPRESA(this.ID_CLASEEMPRESA); 
        if (this.FECHACONST != null)
             cloned.setFECHACONST(new String(this.FECHACONST)); 
        if (this.ID_DOCTO != null)
             cloned.setID_DOCTO(new String(this.ID_DOCTO)); 
        cloned.setID_RUNTTIPOSOCIEDAD(this.ID_RUNTTIPOSOCIEDAD); 
        if (this.PRESTADOR_SERVICIOS != null)
             cloned.setPRESTADOR_SERVICIOS(new String(this.PRESTADOR_SERVICIOS)); 
        cloned.setCAPITAL_PAGADO(this.CAPITAL_PAGADO); 
        cloned.setPATRIMONIO_LIQUIDO(this.PATRIMONIO_LIQUIDO); 
        if (this.COD_TIPOENTIDAD != null)
             cloned.setCOD_TIPOENTIDAD(new String(this.COD_TIPOENTIDAD)); 
        if (this.CERTIFICADO_EXISREPLEGAL != null)
             cloned.setCERTIFICADO_EXISREPLEGAL(new String(this.CERTIFICADO_EXISREPLEGAL)); 
        if (this.EMAIL != null)
             cloned.setEMAIL(new String(this.EMAIL)); 
        if (this.REGISTRADO_RUNT != null)
             cloned.setREGISTRADO_RUNT(new String(this.REGISTRADO_RUNT)); 
        if (this.CELULAR != null)
             cloned.setCELULAR(new String(this.CELULAR)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
