package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * HistoriaDeVehiculo Value Object.
  * This class is value object representing database table HISTORIAVEHICULO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HistoriaDeVehiculo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int GEN_HISTORIAVEHICULO;
    private int ID_TRAMITEINTERNO;
    private String DESCRIPCION;
    private String FECHA;
    private int NROCONSIGNACION;
    private String FECHACONSIGNACION;
    private int VALOR;
    private int GEN_IDLICTRANSITO;
    private int NUMCONSIGNACIONVEHICULO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public HistoriaDeVehiculo () {

    }

    public HistoriaDeVehiculo (int GEN_HISTORIAVEHICULOIn) {

          this.GEN_HISTORIAVEHICULO = GEN_HISTORIAVEHICULOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getGEN_HISTORIAVEHICULO() {
          return this.GEN_HISTORIAVEHICULO;
    }
    public void setGEN_HISTORIAVEHICULO(int GEN_HISTORIAVEHICULOIn) {
          this.GEN_HISTORIAVEHICULO = GEN_HISTORIAVEHICULOIn;
    }

    public int getID_TRAMITEINTERNO() {
          return this.ID_TRAMITEINTERNO;
    }
    public void setID_TRAMITEINTERNO(int ID_TRAMITEINTERNOIn) {
          this.ID_TRAMITEINTERNO = ID_TRAMITEINTERNOIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getFECHA() {
          return this.FECHA;
    }
    public void setFECHA(String FECHAIn) {
          this.FECHA = FECHAIn;
    }

    public int getNROCONSIGNACION() {
          return this.NROCONSIGNACION;
    }
    public void setNROCONSIGNACION(int NROCONSIGNACIONIn) {
          this.NROCONSIGNACION = NROCONSIGNACIONIn;
    }

    public String getFECHACONSIGNACION() {
          return this.FECHACONSIGNACION;
    }
    public void setFECHACONSIGNACION(String FECHACONSIGNACIONIn) {
          this.FECHACONSIGNACION = FECHACONSIGNACIONIn;
    }

    public int getVALOR() {
          return this.VALOR;
    }
    public void setVALOR(int VALORIn) {
          this.VALOR = VALORIn;
    }

    public int getGEN_IDLICTRANSITO() {
          return this.GEN_IDLICTRANSITO;
    }
    public void setGEN_IDLICTRANSITO(int GEN_IDLICTRANSITOIn) {
          this.GEN_IDLICTRANSITO = GEN_IDLICTRANSITOIn;
    }

    public int getNUMCONSIGNACIONVEHICULO() {
          return this.NUMCONSIGNACIONVEHICULO;
    }
    public void setNUMCONSIGNACIONVEHICULO(int NUMCONSIGNACIONVEHICULOIn) {
          this.NUMCONSIGNACIONVEHICULO = NUMCONSIGNACIONVEHICULOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int GEN_HISTORIAVEHICULOIn,
          int ID_TRAMITEINTERNOIn,
          String DESCRIPCIONIn,
          String FECHAIn,
          int NROCONSIGNACIONIn,
          String FECHACONSIGNACIONIn,
          int VALORIn,
          int GEN_IDLICTRANSITOIn,
          int NUMCONSIGNACIONVEHICULOIn) {
          this.GEN_HISTORIAVEHICULO = GEN_HISTORIAVEHICULOIn;
          this.ID_TRAMITEINTERNO = ID_TRAMITEINTERNOIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.FECHA = FECHAIn;
          this.NROCONSIGNACION = NROCONSIGNACIONIn;
          this.FECHACONSIGNACION = FECHACONSIGNACIONIn;
          this.VALOR = VALORIn;
          this.GEN_IDLICTRANSITO = GEN_IDLICTRANSITOIn;
          this.NUMCONSIGNACIONVEHICULO = NUMCONSIGNACIONVEHICULOIn;
    }


    /** 
     * hasEqualMapping-method will compare two HistoriaDeVehiculo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(HistoriaDeVehiculo valueObject) {

          if (valueObject.getGEN_HISTORIAVEHICULO() != this.GEN_HISTORIAVEHICULO) {
                    return(false);
          }
          if (valueObject.getID_TRAMITEINTERNO() != this.ID_TRAMITEINTERNO) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.FECHA == null) {
                    if (valueObject.getFECHA() != null)
                           return(false);
          } else if (!this.FECHA.equals(valueObject.getFECHA())) {
                    return(false);
          }
          if (valueObject.getNROCONSIGNACION() != this.NROCONSIGNACION) {
                    return(false);
          }
          if (this.FECHACONSIGNACION == null) {
                    if (valueObject.getFECHACONSIGNACION() != null)
                           return(false);
          } else if (!this.FECHACONSIGNACION.equals(valueObject.getFECHACONSIGNACION())) {
                    return(false);
          }
          if (valueObject.getVALOR() != this.VALOR) {
                    return(false);
          }
          if (valueObject.getGEN_IDLICTRANSITO() != this.GEN_IDLICTRANSITO) {
                    return(false);
          }
          if (valueObject.getNUMCONSIGNACIONVEHICULO() != this.NUMCONSIGNACIONVEHICULO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HistoriaDeVehiculo, mapping to table HISTORIAVEHICULO\n");
        out.append("Persistent attributes: \n"); 
        out.append("GEN_HISTORIAVEHICULO = " + this.GEN_HISTORIAVEHICULO + "\n"); 
        out.append("ID_TRAMITEINTERNO = " + this.ID_TRAMITEINTERNO + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("FECHA = " + this.FECHA + "\n"); 
        out.append("NROCONSIGNACION = " + this.NROCONSIGNACION + "\n"); 
        out.append("FECHACONSIGNACION = " + this.FECHACONSIGNACION + "\n"); 
        out.append("VALOR = " + this.VALOR + "\n"); 
        out.append("GEN_IDLICTRANSITO = " + this.GEN_IDLICTRANSITO + "\n"); 
        out.append("NUMCONSIGNACIONVEHICULO = " + this.NUMCONSIGNACIONVEHICULO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        HistoriaDeVehiculo cloned = new HistoriaDeVehiculo();

        cloned.setGEN_HISTORIAVEHICULO(this.GEN_HISTORIAVEHICULO); 
        cloned.setID_TRAMITEINTERNO(this.ID_TRAMITEINTERNO); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.FECHA != null)
             cloned.setFECHA(new String(this.FECHA)); 
        cloned.setNROCONSIGNACION(this.NROCONSIGNACION); 
        if (this.FECHACONSIGNACION != null)
             cloned.setFECHACONSIGNACION(new String(this.FECHACONSIGNACION)); 
        cloned.setVALOR(this.VALOR); 
        cloned.setGEN_IDLICTRANSITO(this.GEN_IDLICTRANSITO); 
        cloned.setNUMCONSIGNACIONVEHICULO(this.NUMCONSIGNACIONVEHICULO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}