package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * LPagoImpuesto Value Object.
  * This class is value object representing database table L_PAGOIMPUESTO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class LPagoImpuesto implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int L_IDPAGOIMP;
    private int IDVEHICULO;
    private int ANIOHASTAPAGO;
    private int ULTIMOPAGO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public LPagoImpuesto () {

    }

    public LPagoImpuesto (int L_IDPAGOIMPIn) {

          this.L_IDPAGOIMP = L_IDPAGOIMPIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getL_IDPAGOIMP() {
          return this.L_IDPAGOIMP;
    }
    public void setL_IDPAGOIMP(int L_IDPAGOIMPIn) {
          this.L_IDPAGOIMP = L_IDPAGOIMPIn;
    }

    public int getIDVEHICULO() {
          return this.IDVEHICULO;
    }
    public void setIDVEHICULO(int IDVEHICULOIn) {
          this.IDVEHICULO = IDVEHICULOIn;
    }

    public int getANIOHASTAPAGO() {
          return this.ANIOHASTAPAGO;
    }
    public void setANIOHASTAPAGO(int ANIOHASTAPAGOIn) {
          this.ANIOHASTAPAGO = ANIOHASTAPAGOIn;
    }

    public int getULTIMOPAGO() {
          return this.ULTIMOPAGO;
    }
    public void setULTIMOPAGO(int ULTIMOPAGOIn) {
          this.ULTIMOPAGO = ULTIMOPAGOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int L_IDPAGOIMPIn,
          int IDVEHICULOIn,
          int ANIOHASTAPAGOIn,
          int ULTIMOPAGOIn) {
          this.L_IDPAGOIMP = L_IDPAGOIMPIn;
          this.IDVEHICULO = IDVEHICULOIn;
          this.ANIOHASTAPAGO = ANIOHASTAPAGOIn;
          this.ULTIMOPAGO = ULTIMOPAGOIn;
    }


    /** 
     * hasEqualMapping-method will compare two LPagoImpuesto instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(LPagoImpuesto valueObject) {

          if (valueObject.getL_IDPAGOIMP() != this.L_IDPAGOIMP) {
                    return(false);
          }
          if (valueObject.getIDVEHICULO() != this.IDVEHICULO) {
                    return(false);
          }
          if (valueObject.getANIOHASTAPAGO() != this.ANIOHASTAPAGO) {
                    return(false);
          }
          if (valueObject.getULTIMOPAGO() != this.ULTIMOPAGO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass LPagoImpuesto, mapping to table L_PAGOIMPUESTO\n");
        out.append("Persistent attributes: \n"); 
        out.append("L_IDPAGOIMP = " + this.L_IDPAGOIMP + "\n"); 
        out.append("IDVEHICULO = " + this.IDVEHICULO + "\n"); 
        out.append("ANIOHASTAPAGO = " + this.ANIOHASTAPAGO + "\n"); 
        out.append("ULTIMOPAGO = " + this.ULTIMOPAGO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        LPagoImpuesto cloned = new LPagoImpuesto();

        cloned.setL_IDPAGOIMP(this.L_IDPAGOIMP); 
        cloned.setIDVEHICULO(this.IDVEHICULO); 
        cloned.setANIOHASTAPAGO(this.ANIOHASTAPAGO); 
        cloned.setULTIMOPAGO(this.ULTIMOPAGO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}