package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * RuntPropietarioModificado Value Object.
  * This class is value object representing database table RUNT_PROPIETARIOMODIFICADO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntPropietarioModificado implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_PROPIETARIOMODIF;
    private String TIPOPERSONAPROPIETARIO;
    private String FECHAINICIOPROPIEDAD;
    private String FECHAFINPROPIEDAD;
    private String PROINDIVISO;
    private double PORCENTAJEPROPIEDAD;
    private int ID_TIPOPROPIEDAD;
    private int ID_ESTADO;
    private String PRIMERNOMBRE;
    private String SEGNOMBRE;
    private String APELLIDO1;
    private String APELLIDO2;
    private String FECHANACIMIENTO;
    private int ID_GRUPOSANGRE;
    private int ID_SEXO;
    private String DIRECCION;
    private String TELEFONO;
    private String EMAIL;
    private int ID_RUNTMODIFICACION;
    private String ID_DOCTOAPODERADO;
    private String NRODOCTOAPODERADO;
    private String NOMBRE1APODERADO;
    private String NOMBRE2APODERADO;
    private String APELLIDO1APODERAD;
    private String APELLIDO2APODERADO;
    private String ID_DOCTOPROPIETARIO;
    private String NRODOCTOPROPIETARIO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public RuntPropietarioModificado () {

    }

    public RuntPropietarioModificado (int ID_PROPIETARIOMODIFIn) {

          this.ID_PROPIETARIOMODIF = ID_PROPIETARIOMODIFIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_PROPIETARIOMODIF() {
          return this.ID_PROPIETARIOMODIF;
    }
    public void setID_PROPIETARIOMODIF(int ID_PROPIETARIOMODIFIn) {
          this.ID_PROPIETARIOMODIF = ID_PROPIETARIOMODIFIn;
    }

    public String getTIPOPERSONAPROPIETARIO() {
          return this.TIPOPERSONAPROPIETARIO;
    }
    public void setTIPOPERSONAPROPIETARIO(String TIPOPERSONAPROPIETARIOIn) {
          this.TIPOPERSONAPROPIETARIO = TIPOPERSONAPROPIETARIOIn;
    }

    public String getFECHAINICIOPROPIEDAD() {
          return this.FECHAINICIOPROPIEDAD;
    }
    public void setFECHAINICIOPROPIEDAD(String FECHAINICIOPROPIEDADIn) {
          this.FECHAINICIOPROPIEDAD = FECHAINICIOPROPIEDADIn;
    }

    public String getFECHAFINPROPIEDAD() {
          return this.FECHAFINPROPIEDAD;
    }
    public void setFECHAFINPROPIEDAD(String FECHAFINPROPIEDADIn) {
          this.FECHAFINPROPIEDAD = FECHAFINPROPIEDADIn;
    }

    public String getPROINDIVISO() {
          return this.PROINDIVISO;
    }
    public void setPROINDIVISO(String PROINDIVISOIn) {
          this.PROINDIVISO = PROINDIVISOIn;
    }

    public double getPORCENTAJEPROPIEDAD() {
          return this.PORCENTAJEPROPIEDAD;
    }
    public void setPORCENTAJEPROPIEDAD(double PORCENTAJEPROPIEDADIn) {
          this.PORCENTAJEPROPIEDAD = PORCENTAJEPROPIEDADIn;
    }

    public int getID_TIPOPROPIEDAD() {
          return this.ID_TIPOPROPIEDAD;
    }
    public void setID_TIPOPROPIEDAD(int ID_TIPOPROPIEDADIn) {
          this.ID_TIPOPROPIEDAD = ID_TIPOPROPIEDADIn;
    }

    public int getID_ESTADO() {
          return this.ID_ESTADO;
    }
    public void setID_ESTADO(int ID_ESTADOIn) {
          this.ID_ESTADO = ID_ESTADOIn;
    }

    public String getPRIMERNOMBRE() {
          return this.PRIMERNOMBRE;
    }
    public void setPRIMERNOMBRE(String PRIMERNOMBREIn) {
          this.PRIMERNOMBRE = PRIMERNOMBREIn;
    }

    public String getSEGNOMBRE() {
          return this.SEGNOMBRE;
    }
    public void setSEGNOMBRE(String SEGNOMBREIn) {
          this.SEGNOMBRE = SEGNOMBREIn;
    }

    public String getAPELLIDO1() {
          return this.APELLIDO1;
    }
    public void setAPELLIDO1(String APELLIDO1In) {
          this.APELLIDO1 = APELLIDO1In;
    }

    public String getAPELLIDO2() {
          return this.APELLIDO2;
    }
    public void setAPELLIDO2(String APELLIDO2In) {
          this.APELLIDO2 = APELLIDO2In;
    }

    public String getFECHANACIMIENTO() {
          return this.FECHANACIMIENTO;
    }
    public void setFECHANACIMIENTO(String FECHANACIMIENTOIn) {
          this.FECHANACIMIENTO = FECHANACIMIENTOIn;
    }

    public int getID_GRUPOSANGRE() {
          return this.ID_GRUPOSANGRE;
    }
    public void setID_GRUPOSANGRE(int ID_GRUPOSANGREIn) {
          this.ID_GRUPOSANGRE = ID_GRUPOSANGREIn;
    }

    public int getID_SEXO() {
          return this.ID_SEXO;
    }
    public void setID_SEXO(int ID_SEXOIn) {
          this.ID_SEXO = ID_SEXOIn;
    }

    public String getDIRECCION() {
          return this.DIRECCION;
    }
    public void setDIRECCION(String DIRECCIONIn) {
          this.DIRECCION = DIRECCIONIn;
    }

    public String getTELEFONO() {
          return this.TELEFONO;
    }
    public void setTELEFONO(String TELEFONOIn) {
          this.TELEFONO = TELEFONOIn;
    }

    public String getEMAIL() {
          return this.EMAIL;
    }
    public void setEMAIL(String EMAILIn) {
          this.EMAIL = EMAILIn;
    }

    public int getID_RUNTMODIFICACION() {
          return this.ID_RUNTMODIFICACION;
    }
    public void setID_RUNTMODIFICACION(int ID_RUNTMODIFICACIONIn) {
          this.ID_RUNTMODIFICACION = ID_RUNTMODIFICACIONIn;
    }

    public String getID_DOCTOAPODERADO() {
          return this.ID_DOCTOAPODERADO;
    }
    public void setID_DOCTOAPODERADO(String ID_DOCTOAPODERADOIn) {
          this.ID_DOCTOAPODERADO = ID_DOCTOAPODERADOIn;
    }

    public String getNRODOCTOAPODERADO() {
          return this.NRODOCTOAPODERADO;
    }
    public void setNRODOCTOAPODERADO(String NRODOCTOAPODERADOIn) {
          this.NRODOCTOAPODERADO = NRODOCTOAPODERADOIn;
    }

    public String getNOMBRE1APODERADO() {
          return this.NOMBRE1APODERADO;
    }
    public void setNOMBRE1APODERADO(String NOMBRE1APODERADOIn) {
          this.NOMBRE1APODERADO = NOMBRE1APODERADOIn;
    }

    public String getNOMBRE2APODERADO() {
          return this.NOMBRE2APODERADO;
    }
    public void setNOMBRE2APODERADO(String NOMBRE2APODERADOIn) {
          this.NOMBRE2APODERADO = NOMBRE2APODERADOIn;
    }

    public String getAPELLIDO1APODERAD() {
          return this.APELLIDO1APODERAD;
    }
    public void setAPELLIDO1APODERAD(String APELLIDO1APODERADIn) {
          this.APELLIDO1APODERAD = APELLIDO1APODERADIn;
    }

    public String getAPELLIDO2APODERADO() {
          return this.APELLIDO2APODERADO;
    }
    public void setAPELLIDO2APODERADO(String APELLIDO2APODERADOIn) {
          this.APELLIDO2APODERADO = APELLIDO2APODERADOIn;
    }

    public String getID_DOCTOPROPIETARIO() {
          return this.ID_DOCTOPROPIETARIO;
    }
    public void setID_DOCTOPROPIETARIO(String ID_DOCTOPROPIETARIOIn) {
          this.ID_DOCTOPROPIETARIO = ID_DOCTOPROPIETARIOIn;
    }

    public String getNRODOCTOPROPIETARIO() {
          return this.NRODOCTOPROPIETARIO;
    }
    public void setNRODOCTOPROPIETARIO(String NRODOCTOPROPIETARIOIn) {
          this.NRODOCTOPROPIETARIO = NRODOCTOPROPIETARIOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_PROPIETARIOMODIFIn,
          String TIPOPERSONAPROPIETARIOIn,
          String FECHAINICIOPROPIEDADIn,
          String FECHAFINPROPIEDADIn,
          String PROINDIVISOIn,
          double PORCENTAJEPROPIEDADIn,
          int ID_TIPOPROPIEDADIn,
          int ID_ESTADOIn,
          String PRIMERNOMBREIn,
          String SEGNOMBREIn,
          String APELLIDO1In,
          String APELLIDO2In,
          String FECHANACIMIENTOIn,
          int ID_GRUPOSANGREIn,
          int ID_SEXOIn,
          String DIRECCIONIn,
          String TELEFONOIn,
          String EMAILIn,
          int ID_RUNTMODIFICACIONIn,
          String ID_DOCTOAPODERADOIn,
          String NRODOCTOAPODERADOIn,
          String NOMBRE1APODERADOIn,
          String NOMBRE2APODERADOIn,
          String APELLIDO1APODERADIn,
          String APELLIDO2APODERADOIn,
          String ID_DOCTOPROPIETARIOIn,
          String NRODOCTOPROPIETARIOIn) {
          this.ID_PROPIETARIOMODIF = ID_PROPIETARIOMODIFIn;
          this.TIPOPERSONAPROPIETARIO = TIPOPERSONAPROPIETARIOIn;
          this.FECHAINICIOPROPIEDAD = FECHAINICIOPROPIEDADIn;
          this.FECHAFINPROPIEDAD = FECHAFINPROPIEDADIn;
          this.PROINDIVISO = PROINDIVISOIn;
          this.PORCENTAJEPROPIEDAD = PORCENTAJEPROPIEDADIn;
          this.ID_TIPOPROPIEDAD = ID_TIPOPROPIEDADIn;
          this.ID_ESTADO = ID_ESTADOIn;
          this.PRIMERNOMBRE = PRIMERNOMBREIn;
          this.SEGNOMBRE = SEGNOMBREIn;
          this.APELLIDO1 = APELLIDO1In;
          this.APELLIDO2 = APELLIDO2In;
          this.FECHANACIMIENTO = FECHANACIMIENTOIn;
          this.ID_GRUPOSANGRE = ID_GRUPOSANGREIn;
          this.ID_SEXO = ID_SEXOIn;
          this.DIRECCION = DIRECCIONIn;
          this.TELEFONO = TELEFONOIn;
          this.EMAIL = EMAILIn;
          this.ID_RUNTMODIFICACION = ID_RUNTMODIFICACIONIn;
          this.ID_DOCTOAPODERADO = ID_DOCTOAPODERADOIn;
          this.NRODOCTOAPODERADO = NRODOCTOAPODERADOIn;
          this.NOMBRE1APODERADO = NOMBRE1APODERADOIn;
          this.NOMBRE2APODERADO = NOMBRE2APODERADOIn;
          this.APELLIDO1APODERAD = APELLIDO1APODERADIn;
          this.APELLIDO2APODERADO = APELLIDO2APODERADOIn;
          this.ID_DOCTOPROPIETARIO = ID_DOCTOPROPIETARIOIn;
          this.NRODOCTOPROPIETARIO = NRODOCTOPROPIETARIOIn;
    }


    /** 
     * hasEqualMapping-method will compare two RuntPropietarioModificado instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(RuntPropietarioModificado valueObject) {

          if (valueObject.getID_PROPIETARIOMODIF() != this.ID_PROPIETARIOMODIF) {
                    return(false);
          }
          if (this.TIPOPERSONAPROPIETARIO == null) {
                    if (valueObject.getTIPOPERSONAPROPIETARIO() != null)
                           return(false);
          } else if (!this.TIPOPERSONAPROPIETARIO.equals(valueObject.getTIPOPERSONAPROPIETARIO())) {
                    return(false);
          }
          if (this.FECHAINICIOPROPIEDAD == null) {
                    if (valueObject.getFECHAINICIOPROPIEDAD() != null)
                           return(false);
          } else if (!this.FECHAINICIOPROPIEDAD.equals(valueObject.getFECHAINICIOPROPIEDAD())) {
                    return(false);
          }
          if (this.FECHAFINPROPIEDAD == null) {
                    if (valueObject.getFECHAFINPROPIEDAD() != null)
                           return(false);
          } else if (!this.FECHAFINPROPIEDAD.equals(valueObject.getFECHAFINPROPIEDAD())) {
                    return(false);
          }
          if (this.PROINDIVISO == null) {
                    if (valueObject.getPROINDIVISO() != null)
                           return(false);
          } else if (!this.PROINDIVISO.equals(valueObject.getPROINDIVISO())) {
                    return(false);
          }
          if (valueObject.getPORCENTAJEPROPIEDAD() != this.PORCENTAJEPROPIEDAD) {
                    return(false);
          }
          if (valueObject.getID_TIPOPROPIEDAD() != this.ID_TIPOPROPIEDAD) {
                    return(false);
          }
          if (valueObject.getID_ESTADO() != this.ID_ESTADO) {
                    return(false);
          }
          if (this.PRIMERNOMBRE == null) {
                    if (valueObject.getPRIMERNOMBRE() != null)
                           return(false);
          } else if (!this.PRIMERNOMBRE.equals(valueObject.getPRIMERNOMBRE())) {
                    return(false);
          }
          if (this.SEGNOMBRE == null) {
                    if (valueObject.getSEGNOMBRE() != null)
                           return(false);
          } else if (!this.SEGNOMBRE.equals(valueObject.getSEGNOMBRE())) {
                    return(false);
          }
          if (this.APELLIDO1 == null) {
                    if (valueObject.getAPELLIDO1() != null)
                           return(false);
          } else if (!this.APELLIDO1.equals(valueObject.getAPELLIDO1())) {
                    return(false);
          }
          if (this.APELLIDO2 == null) {
                    if (valueObject.getAPELLIDO2() != null)
                           return(false);
          } else if (!this.APELLIDO2.equals(valueObject.getAPELLIDO2())) {
                    return(false);
          }
          if (this.FECHANACIMIENTO == null) {
                    if (valueObject.getFECHANACIMIENTO() != null)
                           return(false);
          } else if (!this.FECHANACIMIENTO.equals(valueObject.getFECHANACIMIENTO())) {
                    return(false);
          }
          if (valueObject.getID_GRUPOSANGRE() != this.ID_GRUPOSANGRE) {
                    return(false);
          }
          if (valueObject.getID_SEXO() != this.ID_SEXO) {
                    return(false);
          }
          if (this.DIRECCION == null) {
                    if (valueObject.getDIRECCION() != null)
                           return(false);
          } else if (!this.DIRECCION.equals(valueObject.getDIRECCION())) {
                    return(false);
          }
          if (this.TELEFONO == null) {
                    if (valueObject.getTELEFONO() != null)
                           return(false);
          } else if (!this.TELEFONO.equals(valueObject.getTELEFONO())) {
                    return(false);
          }
          if (this.EMAIL == null) {
                    if (valueObject.getEMAIL() != null)
                           return(false);
          } else if (!this.EMAIL.equals(valueObject.getEMAIL())) {
                    return(false);
          }
          if (valueObject.getID_RUNTMODIFICACION() != this.ID_RUNTMODIFICACION) {
                    return(false);
          }
          if (this.ID_DOCTOAPODERADO == null) {
                    if (valueObject.getID_DOCTOAPODERADO() != null)
                           return(false);
          } else if (!this.ID_DOCTOAPODERADO.equals(valueObject.getID_DOCTOAPODERADO())) {
                    return(false);
          }
          if (this.NRODOCTOAPODERADO == null) {
                    if (valueObject.getNRODOCTOAPODERADO() != null)
                           return(false);
          } else if (!this.NRODOCTOAPODERADO.equals(valueObject.getNRODOCTOAPODERADO())) {
                    return(false);
          }
          if (this.NOMBRE1APODERADO == null) {
                    if (valueObject.getNOMBRE1APODERADO() != null)
                           return(false);
          } else if (!this.NOMBRE1APODERADO.equals(valueObject.getNOMBRE1APODERADO())) {
                    return(false);
          }
          if (this.NOMBRE2APODERADO == null) {
                    if (valueObject.getNOMBRE2APODERADO() != null)
                           return(false);
          } else if (!this.NOMBRE2APODERADO.equals(valueObject.getNOMBRE2APODERADO())) {
                    return(false);
          }
          if (this.APELLIDO1APODERAD == null) {
                    if (valueObject.getAPELLIDO1APODERAD() != null)
                           return(false);
          } else if (!this.APELLIDO1APODERAD.equals(valueObject.getAPELLIDO1APODERAD())) {
                    return(false);
          }
          if (this.APELLIDO2APODERADO == null) {
                    if (valueObject.getAPELLIDO2APODERADO() != null)
                           return(false);
          } else if (!this.APELLIDO2APODERADO.equals(valueObject.getAPELLIDO2APODERADO())) {
                    return(false);
          }
          if (this.ID_DOCTOPROPIETARIO == null) {
                    if (valueObject.getID_DOCTOPROPIETARIO() != null)
                           return(false);
          } else if (!this.ID_DOCTOPROPIETARIO.equals(valueObject.getID_DOCTOPROPIETARIO())) {
                    return(false);
          }
          if (this.NRODOCTOPROPIETARIO == null) {
                    if (valueObject.getNRODOCTOPROPIETARIO() != null)
                           return(false);
          } else if (!this.NRODOCTOPROPIETARIO.equals(valueObject.getNRODOCTOPROPIETARIO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass RuntPropietarioModificado, mapping to table RUNT_PROPIETARIOMODIFICADO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_PROPIETARIOMODIF = " + this.ID_PROPIETARIOMODIF + "\n"); 
        out.append("TIPOPERSONAPROPIETARIO = " + this.TIPOPERSONAPROPIETARIO + "\n"); 
        out.append("FECHAINICIOPROPIEDAD = " + this.FECHAINICIOPROPIEDAD + "\n"); 
        out.append("FECHAFINPROPIEDAD = " + this.FECHAFINPROPIEDAD + "\n"); 
        out.append("PROINDIVISO = " + this.PROINDIVISO + "\n"); 
        out.append("PORCENTAJEPROPIEDAD = " + this.PORCENTAJEPROPIEDAD + "\n"); 
        out.append("ID_TIPOPROPIEDAD = " + this.ID_TIPOPROPIEDAD + "\n"); 
        out.append("ID_ESTADO = " + this.ID_ESTADO + "\n"); 
        out.append("PRIMERNOMBRE = " + this.PRIMERNOMBRE + "\n"); 
        out.append("SEGNOMBRE = " + this.SEGNOMBRE + "\n"); 
        out.append("APELLIDO1 = " + this.APELLIDO1 + "\n"); 
        out.append("APELLIDO2 = " + this.APELLIDO2 + "\n"); 
        out.append("FECHANACIMIENTO = " + this.FECHANACIMIENTO + "\n"); 
        out.append("ID_GRUPOSANGRE = " + this.ID_GRUPOSANGRE + "\n"); 
        out.append("ID_SEXO = " + this.ID_SEXO + "\n"); 
        out.append("DIRECCION = " + this.DIRECCION + "\n"); 
        out.append("TELEFONO = " + this.TELEFONO + "\n"); 
        out.append("EMAIL = " + this.EMAIL + "\n"); 
        out.append("ID_RUNTMODIFICACION = " + this.ID_RUNTMODIFICACION + "\n"); 
        out.append("ID_DOCTOAPODERADO = " + this.ID_DOCTOAPODERADO + "\n"); 
        out.append("NRODOCTOAPODERADO = " + this.NRODOCTOAPODERADO + "\n"); 
        out.append("NOMBRE1APODERADO = " + this.NOMBRE1APODERADO + "\n"); 
        out.append("NOMBRE2APODERADO = " + this.NOMBRE2APODERADO + "\n"); 
        out.append("APELLIDO1APODERAD = " + this.APELLIDO1APODERAD + "\n"); 
        out.append("APELLIDO2APODERADO = " + this.APELLIDO2APODERADO + "\n"); 
        out.append("ID_DOCTOPROPIETARIO = " + this.ID_DOCTOPROPIETARIO + "\n"); 
        out.append("NRODOCTOPROPIETARIO = " + this.NRODOCTOPROPIETARIO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        RuntPropietarioModificado cloned = new RuntPropietarioModificado();

        cloned.setID_PROPIETARIOMODIF(this.ID_PROPIETARIOMODIF); 
        if (this.TIPOPERSONAPROPIETARIO != null)
             cloned.setTIPOPERSONAPROPIETARIO(new String(this.TIPOPERSONAPROPIETARIO)); 
        if (this.FECHAINICIOPROPIEDAD != null)
             cloned.setFECHAINICIOPROPIEDAD(new String(this.FECHAINICIOPROPIEDAD)); 
        if (this.FECHAFINPROPIEDAD != null)
             cloned.setFECHAFINPROPIEDAD(new String(this.FECHAFINPROPIEDAD)); 
        if (this.PROINDIVISO != null)
             cloned.setPROINDIVISO(new String(this.PROINDIVISO)); 
        cloned.setPORCENTAJEPROPIEDAD(this.PORCENTAJEPROPIEDAD); 
        cloned.setID_TIPOPROPIEDAD(this.ID_TIPOPROPIEDAD); 
        cloned.setID_ESTADO(this.ID_ESTADO); 
        if (this.PRIMERNOMBRE != null)
             cloned.setPRIMERNOMBRE(new String(this.PRIMERNOMBRE)); 
        if (this.SEGNOMBRE != null)
             cloned.setSEGNOMBRE(new String(this.SEGNOMBRE)); 
        if (this.APELLIDO1 != null)
             cloned.setAPELLIDO1(new String(this.APELLIDO1)); 
        if (this.APELLIDO2 != null)
             cloned.setAPELLIDO2(new String(this.APELLIDO2)); 
        if (this.FECHANACIMIENTO != null)
             cloned.setFECHANACIMIENTO(new String(this.FECHANACIMIENTO)); 
        cloned.setID_GRUPOSANGRE(this.ID_GRUPOSANGRE); 
        cloned.setID_SEXO(this.ID_SEXO); 
        if (this.DIRECCION != null)
             cloned.setDIRECCION(new String(this.DIRECCION)); 
        if (this.TELEFONO != null)
             cloned.setTELEFONO(new String(this.TELEFONO)); 
        if (this.EMAIL != null)
             cloned.setEMAIL(new String(this.EMAIL)); 
        cloned.setID_RUNTMODIFICACION(this.ID_RUNTMODIFICACION); 
        if (this.ID_DOCTOAPODERADO != null)
             cloned.setID_DOCTOAPODERADO(new String(this.ID_DOCTOAPODERADO)); 
        if (this.NRODOCTOAPODERADO != null)
             cloned.setNRODOCTOAPODERADO(new String(this.NRODOCTOAPODERADO)); 
        if (this.NOMBRE1APODERADO != null)
             cloned.setNOMBRE1APODERADO(new String(this.NOMBRE1APODERADO)); 
        if (this.NOMBRE2APODERADO != null)
             cloned.setNOMBRE2APODERADO(new String(this.NOMBRE2APODERADO)); 
        if (this.APELLIDO1APODERAD != null)
             cloned.setAPELLIDO1APODERAD(new String(this.APELLIDO1APODERAD)); 
        if (this.APELLIDO2APODERADO != null)
             cloned.setAPELLIDO2APODERADO(new String(this.APELLIDO2APODERADO)); 
        if (this.ID_DOCTOPROPIETARIO != null)
             cloned.setID_DOCTOPROPIETARIO(new String(this.ID_DOCTOPROPIETARIO)); 
        if (this.NRODOCTOPROPIETARIO != null)
             cloned.setNRODOCTOPROPIETARIO(new String(this.NRODOCTOPROPIETARIO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

