package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * RuntModificarAutomotor Value Object.
  * This class is value object representing database table RUNT_MODIFICARAUTOMOTOR
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntModificarAutomotor implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_MODIFICARRUNT;
    private String FECHA;
    private String HORA;
    private int ID_USUARIO;
    private String PLACA;
    private int ID_OPERACION;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public RuntModificarAutomotor () {

    }

    public RuntModificarAutomotor (int ID_MODIFICARRUNTIn) {

          this.ID_MODIFICARRUNT = ID_MODIFICARRUNTIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_MODIFICARRUNT() {
          return this.ID_MODIFICARRUNT;
    }
    public void setID_MODIFICARRUNT(int ID_MODIFICARRUNTIn) {
          this.ID_MODIFICARRUNT = ID_MODIFICARRUNTIn;
    }

    public String getFECHA() {
          return this.FECHA;
    }
    public void setFECHA(String FECHAIn) {
          this.FECHA = FECHAIn;
    }

    public String getHORA() {
          return this.HORA;
    }
    public void setHORA(String HORAIn) {
          this.HORA = HORAIn;
    }

    public int getID_USUARIO() {
          return this.ID_USUARIO;
    }
    public void setID_USUARIO(int ID_USUARIOIn) {
          this.ID_USUARIO = ID_USUARIOIn;
    }

    public String getPLACA() {
          return this.PLACA;
    }
    public void setPLACA(String PLACAIn) {
          this.PLACA = PLACAIn;
    }

    public int getID_OPERACION() {
          return this.ID_OPERACION;
    }
    public void setID_OPERACION(int ID_OPERACIONIn) {
          this.ID_OPERACION = ID_OPERACIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_MODIFICARRUNTIn,
          String FECHAIn,
          String HORAIn,
          int ID_USUARIOIn,
          String PLACAIn,
          int ID_OPERACIONIn) {
          this.ID_MODIFICARRUNT = ID_MODIFICARRUNTIn;
          this.FECHA = FECHAIn;
          this.HORA = HORAIn;
          this.ID_USUARIO = ID_USUARIOIn;
          this.PLACA = PLACAIn;
          this.ID_OPERACION = ID_OPERACIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two RuntModificarAutomotor instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(RuntModificarAutomotor valueObject) {

          if (valueObject.getID_MODIFICARRUNT() != this.ID_MODIFICARRUNT) {
                    return(false);
          }
          if (this.FECHA == null) {
                    if (valueObject.getFECHA() != null)
                           return(false);
          } else if (!this.FECHA.equals(valueObject.getFECHA())) {
                    return(false);
          }
          if (this.HORA == null) {
                    if (valueObject.getHORA() != null)
                           return(false);
          } else if (!this.HORA.equals(valueObject.getHORA())) {
                    return(false);
          }
          if (valueObject.getID_USUARIO() != this.ID_USUARIO) {
                    return(false);
          }
          if (this.PLACA == null) {
                    if (valueObject.getPLACA() != null)
                           return(false);
          } else if (!this.PLACA.equals(valueObject.getPLACA())) {
                    return(false);
          }
          if (valueObject.getID_OPERACION() != this.ID_OPERACION) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass RuntModificarAutomotor, mapping to table RUNT_MODIFICARAUTOMOTOR\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_MODIFICARRUNT = " + this.ID_MODIFICARRUNT + "\n"); 
        out.append("FECHA = " + this.FECHA + "\n"); 
        out.append("HORA = " + this.HORA + "\n"); 
        out.append("ID_USUARIO = " + this.ID_USUARIO + "\n"); 
        out.append("PLACA = " + this.PLACA + "\n"); 
        out.append("ID_OPERACION = " + this.ID_OPERACION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        RuntModificarAutomotor cloned = new RuntModificarAutomotor();

        cloned.setID_MODIFICARRUNT(this.ID_MODIFICARRUNT); 
        if (this.FECHA != null)
             cloned.setFECHA(new String(this.FECHA)); 
        if (this.HORA != null)
             cloned.setHORA(new String(this.HORA)); 
        cloned.setID_USUARIO(this.ID_USUARIO); 
        if (this.PLACA != null)
             cloned.setPLACA(new String(this.PLACA)); 
        cloned.setID_OPERACION(this.ID_OPERACION); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
