package modelo.datos.objetos.generales;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * VehiculoRadicadoCta Value Object.
  * This class is value object representing database table VEHICULORADICADOCTA
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class VehiculoRadicadoCta implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_VEHRADCTA;
    private String PLACA;
    private String FECHALLEGADA;
    private int ID_ORGTRANSITO;
    private int NUMFOLIOS;
    private String NUMOFICIOTRASLADO;
    private String NUMGUIA;
    private int ID_CVEHICULO;
    private int ID_SERVICIO;
    private String ID_MARCA;
    private int ID_LINEA;
    private int CILINDRAJE;
    private String ESTADO;
    private int ID_USUARIO;
    private String FECHAREG;
    private String HORAREG;
    private int ID_MARCPPAL;
    private int ID_LINPPAL;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public VehiculoRadicadoCta () {

    }

    public VehiculoRadicadoCta (int ID_VEHRADCTAIn) {

          this.ID_VEHRADCTA = ID_VEHRADCTAIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_VEHRADCTA() {
          return this.ID_VEHRADCTA;
    }
    public void setID_VEHRADCTA(int ID_VEHRADCTAIn) {
          this.ID_VEHRADCTA = ID_VEHRADCTAIn;
    }

    public String getPLACA() {
          return this.PLACA;
    }
    public void setPLACA(String PLACAIn) {
          this.PLACA = PLACAIn;
    }

    public String getFECHALLEGADA() {
          return this.FECHALLEGADA;
    }
    public void setFECHALLEGADA(String FECHALLEGADAIn) {
          this.FECHALLEGADA = FECHALLEGADAIn;
    }

    public int getID_ORGTRANSITO() {
          return this.ID_ORGTRANSITO;
    }
    public void setID_ORGTRANSITO(int ID_ORGTRANSITOIn) {
          this.ID_ORGTRANSITO = ID_ORGTRANSITOIn;
    }

    public int getNUMFOLIOS() {
          return this.NUMFOLIOS;
    }
    public void setNUMFOLIOS(int NUMFOLIOSIn) {
          this.NUMFOLIOS = NUMFOLIOSIn;
    }

    public String getNUMOFICIOTRASLADO() {
          return this.NUMOFICIOTRASLADO;
    }
    public void setNUMOFICIOTRASLADO(String NUMOFICIOTRASLADOIn) {
          this.NUMOFICIOTRASLADO = NUMOFICIOTRASLADOIn;
    }

    public String getNUMGUIA() {
          return this.NUMGUIA;
    }
    public void setNUMGUIA(String NUMGUIAIn) {
          this.NUMGUIA = NUMGUIAIn;
    }

    public int getID_CVEHICULO() {
          return this.ID_CVEHICULO;
    }
    public void setID_CVEHICULO(int ID_CVEHICULOIn) {
          this.ID_CVEHICULO = ID_CVEHICULOIn;
    }

    public int getID_SERVICIO() {
          return this.ID_SERVICIO;
    }
    public void setID_SERVICIO(int ID_SERVICIOIn) {
          this.ID_SERVICIO = ID_SERVICIOIn;
    }

    public String getID_MARCA() {
          return this.ID_MARCA;
    }
    public void setID_MARCA(String ID_MARCAIn) {
          this.ID_MARCA = ID_MARCAIn;
    }

    public int getID_LINEA() {
          return this.ID_LINEA;
    }
    public void setID_LINEA(int ID_LINEAIn) {
          this.ID_LINEA = ID_LINEAIn;
    }

    public int getCILINDRAJE() {
          return this.CILINDRAJE;
    }
    public void setCILINDRAJE(int CILINDRAJEIn) {
          this.CILINDRAJE = CILINDRAJEIn;
    }

    public String getESTADO() {
          return this.ESTADO;
    }
    public void setESTADO(String ESTADOIn) {
          this.ESTADO = ESTADOIn;
    }

    public int getID_USUARIO() {
          return this.ID_USUARIO;
    }
    public void setID_USUARIO(int ID_USUARIOIn) {
          this.ID_USUARIO = ID_USUARIOIn;
    }

    public String getFECHAREG() {
          return this.FECHAREG;
    }
    public void setFECHAREG(String FECHAREGIn) {
          this.FECHAREG = FECHAREGIn;
    }

    public String getHORAREG() {
          return this.HORAREG;
    }
    public void setHORAREG(String HORAREGIn) {
          this.HORAREG = HORAREGIn;
    }

    public int getID_MARCPPAL() {
          return this.ID_MARCPPAL;
    }
    public void setID_MARCPPAL(int ID_MARCPPALIn) {
          this.ID_MARCPPAL = ID_MARCPPALIn;
    }

    public int getID_LINPPAL() {
          return this.ID_LINPPAL;
    }
    public void setID_LINPPAL(int ID_LINPPALIn) {
          this.ID_LINPPAL = ID_LINPPALIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_VEHRADCTAIn,
          String PLACAIn,
          String FECHALLEGADAIn,
          int ID_ORGTRANSITOIn,
          int NUMFOLIOSIn,
          String NUMOFICIOTRASLADOIn,
          String NUMGUIAIn,
          int ID_CVEHICULOIn,
          int ID_SERVICIOIn,
          String ID_MARCAIn,
          int ID_LINEAIn,
          int CILINDRAJEIn,
          String ESTADOIn,
          int ID_USUARIOIn,
          String FECHAREGIn,
          String HORAREGIn,
          int ID_MARCPPALIn,
          int ID_LINPPALIn) {
          this.ID_VEHRADCTA = ID_VEHRADCTAIn;
          this.PLACA = PLACAIn;
          this.FECHALLEGADA = FECHALLEGADAIn;
          this.ID_ORGTRANSITO = ID_ORGTRANSITOIn;
          this.NUMFOLIOS = NUMFOLIOSIn;
          this.NUMOFICIOTRASLADO = NUMOFICIOTRASLADOIn;
          this.NUMGUIA = NUMGUIAIn;
          this.ID_CVEHICULO = ID_CVEHICULOIn;
          this.ID_SERVICIO = ID_SERVICIOIn;
          this.ID_MARCA = ID_MARCAIn;
          this.ID_LINEA = ID_LINEAIn;
          this.CILINDRAJE = CILINDRAJEIn;
          this.ESTADO = ESTADOIn;
          this.ID_USUARIO = ID_USUARIOIn;
          this.FECHAREG = FECHAREGIn;
          this.HORAREG = HORAREGIn;
          this.ID_MARCPPAL = ID_MARCPPALIn;
          this.ID_LINPPAL = ID_LINPPALIn;
    }


    /** 
     * hasEqualMapping-method will compare two VehiculoRadicadoCta instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(VehiculoRadicadoCta valueObject) {

          if (valueObject.getID_VEHRADCTA() != this.ID_VEHRADCTA) {
                    return(false);
          }
          if (this.PLACA == null) {
                    if (valueObject.getPLACA() != null)
                           return(false);
          } else if (!this.PLACA.equals(valueObject.getPLACA())) {
                    return(false);
          }
          if (this.FECHALLEGADA == null) {
                    if (valueObject.getFECHALLEGADA() != null)
                           return(false);
          } else if (!this.FECHALLEGADA.equals(valueObject.getFECHALLEGADA())) {
                    return(false);
          }
          if (valueObject.getID_ORGTRANSITO() != this.ID_ORGTRANSITO) {
                    return(false);
          }
          if (valueObject.getNUMFOLIOS() != this.NUMFOLIOS) {
                    return(false);
          }
          if (this.NUMOFICIOTRASLADO == null) {
                    if (valueObject.getNUMOFICIOTRASLADO() != null)
                           return(false);
          } else if (!this.NUMOFICIOTRASLADO.equals(valueObject.getNUMOFICIOTRASLADO())) {
                    return(false);
          }
          if (this.NUMGUIA == null) {
                    if (valueObject.getNUMGUIA() != null)
                           return(false);
          } else if (!this.NUMGUIA.equals(valueObject.getNUMGUIA())) {
                    return(false);
          }
          if (valueObject.getID_CVEHICULO() != this.ID_CVEHICULO) {
                    return(false);
          }
          if (valueObject.getID_SERVICIO() != this.ID_SERVICIO) {
                    return(false);
          }
          if (this.ID_MARCA == null) {
                    if (valueObject.getID_MARCA() != null)
                           return(false);
          } else if (!this.ID_MARCA.equals(valueObject.getID_MARCA())) {
                    return(false);
          }
          if (valueObject.getID_LINEA() != this.ID_LINEA) {
                    return(false);
          }
          if (valueObject.getCILINDRAJE() != this.CILINDRAJE) {
                    return(false);
          }
          if (this.ESTADO == null) {
                    if (valueObject.getESTADO() != null)
                           return(false);
          } else if (!this.ESTADO.equals(valueObject.getESTADO())) {
                    return(false);
          }
          if (valueObject.getID_USUARIO() != this.ID_USUARIO) {
                    return(false);
          }
          if (this.FECHAREG == null) {
                    if (valueObject.getFECHAREG() != null)
                           return(false);
          } else if (!this.FECHAREG.equals(valueObject.getFECHAREG())) {
                    return(false);
          }
          if (this.HORAREG == null) {
                    if (valueObject.getHORAREG() != null)
                           return(false);
          } else if (!this.HORAREG.equals(valueObject.getHORAREG())) {
                    return(false);
          }
          if (valueObject.getID_MARCPPAL() != this.ID_MARCPPAL) {
                    return(false);
          }
          if (valueObject.getID_LINPPAL() != this.ID_LINPPAL) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass VehiculoRadicadoCta, mapping to table VEHICULORADICADOCTA\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_VEHRADCTA = " + this.ID_VEHRADCTA + "\n"); 
        out.append("PLACA = " + this.PLACA + "\n"); 
        out.append("FECHALLEGADA = " + this.FECHALLEGADA + "\n"); 
        out.append("ID_ORGTRANSITO = " + this.ID_ORGTRANSITO + "\n"); 
        out.append("NUMFOLIOS = " + this.NUMFOLIOS + "\n"); 
        out.append("NUMOFICIOTRASLADO = " + this.NUMOFICIOTRASLADO + "\n"); 
        out.append("NUMGUIA = " + this.NUMGUIA + "\n"); 
        out.append("ID_CVEHICULO = " + this.ID_CVEHICULO + "\n"); 
        out.append("ID_SERVICIO = " + this.ID_SERVICIO + "\n"); 
        out.append("ID_MARCA = " + this.ID_MARCA + "\n"); 
        out.append("ID_LINEA = " + this.ID_LINEA + "\n"); 
        out.append("CILINDRAJE = " + this.CILINDRAJE + "\n"); 
        out.append("ESTADO = " + this.ESTADO + "\n"); 
        out.append("ID_USUARIO = " + this.ID_USUARIO + "\n"); 
        out.append("FECHAREG = " + this.FECHAREG + "\n"); 
        out.append("HORAREG = " + this.HORAREG + "\n"); 
        out.append("ID_MARCPPAL = " + this.ID_MARCPPAL + "\n"); 
        out.append("ID_LINPPAL = " + this.ID_LINPPAL + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        VehiculoRadicadoCta cloned = new VehiculoRadicadoCta();

        cloned.setID_VEHRADCTA(this.ID_VEHRADCTA); 
        if (this.PLACA != null)
             cloned.setPLACA(new String(this.PLACA)); 
        if (this.FECHALLEGADA != null)
             cloned.setFECHALLEGADA(new String(this.FECHALLEGADA)); 
        cloned.setID_ORGTRANSITO(this.ID_ORGTRANSITO); 
        cloned.setNUMFOLIOS(this.NUMFOLIOS); 
        if (this.NUMOFICIOTRASLADO != null)
             cloned.setNUMOFICIOTRASLADO(new String(this.NUMOFICIOTRASLADO)); 
        if (this.NUMGUIA != null)
             cloned.setNUMGUIA(new String(this.NUMGUIA)); 
        cloned.setID_CVEHICULO(this.ID_CVEHICULO); 
        cloned.setID_SERVICIO(this.ID_SERVICIO); 
        if (this.ID_MARCA != null)
             cloned.setID_MARCA(new String(this.ID_MARCA)); 
        cloned.setID_LINEA(this.ID_LINEA); 
        cloned.setCILINDRAJE(this.CILINDRAJE); 
        if (this.ESTADO != null)
             cloned.setESTADO(new String(this.ESTADO)); 
        cloned.setID_USUARIO(this.ID_USUARIO); 
        if (this.FECHAREG != null)
             cloned.setFECHAREG(new String(this.FECHAREG)); 
        if (this.HORAREG != null)
             cloned.setHORAREG(new String(this.HORAREG)); 
        cloned.setID_MARCPPAL(this.ID_MARCPPAL); 
        cloned.setID_LINPPAL(this.ID_LINPPAL); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

