package modelo.datos.objetos.radicacion;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TramitesPorDependencia Value Object.
  * This class is value object representing database table VIEW_TRAMITESPORDEPENDENCIA
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TramitesPorDependencia implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_TRAMITEDEPEN;
    private int ID_DEPENDENCIA;
    private int ID_TRAMITEINTERNO;
    private String CODTRAMITE;
    private String DESCTRAMITE;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TramitesPorDependencia () {

    }

    public TramitesPorDependencia (int ID_TRAMITEDEPENIn) {

          this.ID_TRAMITEDEPEN = ID_TRAMITEDEPENIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_TRAMITEDEPEN() {
          return this.ID_TRAMITEDEPEN;
    }
    public void setID_TRAMITEDEPEN(int ID_TRAMITEDEPENIn) {
          this.ID_TRAMITEDEPEN = ID_TRAMITEDEPENIn;
    }

    public int getID_DEPENDENCIA() {
          return this.ID_DEPENDENCIA;
    }
    public void setID_DEPENDENCIA(int ID_DEPENDENCIAIn) {
          this.ID_DEPENDENCIA = ID_DEPENDENCIAIn;
    }

    public int getID_TRAMITEINTERNO() {
          return this.ID_TRAMITEINTERNO;
    }
    public void setID_TRAMITEINTERNO(int ID_TRAMITEINTERNOIn) {
          this.ID_TRAMITEINTERNO = ID_TRAMITEINTERNOIn;
    }

    public String getCODTRAMITE() {
          return this.CODTRAMITE;
    }
    public void setCODTRAMITE(String CODTRAMITEIn) {
          this.CODTRAMITE = CODTRAMITEIn;
    }

    public String getDESCTRAMITE() {
          return this.DESCTRAMITE;
    }
    public void setDESCTRAMITE(String DESCTRAMITEIn) {
          this.DESCTRAMITE = DESCTRAMITEIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_TRAMITEDEPENIn,
          int ID_DEPENDENCIAIn,
          int ID_TRAMITEINTERNOIn,
          String CODTRAMITEIn,
          String DESCTRAMITEIn) {
          this.ID_TRAMITEDEPEN = ID_TRAMITEDEPENIn;
          this.ID_DEPENDENCIA = ID_DEPENDENCIAIn;
          this.ID_TRAMITEINTERNO = ID_TRAMITEINTERNOIn;
          this.CODTRAMITE = CODTRAMITEIn;
          this.DESCTRAMITE = DESCTRAMITEIn;
    }


    /** 
     * hasEqualMapping-method will compare two TramitesPorDependencia instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TramitesPorDependencia valueObject) {

          if (valueObject.getID_TRAMITEDEPEN() != this.ID_TRAMITEDEPEN) {
                    return(false);
          }
          if (valueObject.getID_DEPENDENCIA() != this.ID_DEPENDENCIA) {
                    return(false);
          }
          if (valueObject.getID_TRAMITEINTERNO() != this.ID_TRAMITEINTERNO) {
                    return(false);
          }
          if (this.CODTRAMITE == null) {
                    if (valueObject.getCODTRAMITE() != null)
                           return(false);
          } else if (!this.CODTRAMITE.equals(valueObject.getCODTRAMITE())) {
                    return(false);
          }
          if (this.DESCTRAMITE == null) {
                    if (valueObject.getDESCTRAMITE() != null)
                           return(false);
          } else if (!this.DESCTRAMITE.equals(valueObject.getDESCTRAMITE())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TramitesPorDependencia, mapping to table VIEW_TRAMITESPORDEPENDENCIA\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_TRAMITEDEPEN = " + this.ID_TRAMITEDEPEN + "\n"); 
        out.append("ID_DEPENDENCIA = " + this.ID_DEPENDENCIA + "\n"); 
        out.append("ID_TRAMITEINTERNO = " + this.ID_TRAMITEINTERNO + "\n"); 
        out.append("CODTRAMITE = " + this.CODTRAMITE + "\n"); 
        out.append("DESCTRAMITE = " + this.DESCTRAMITE + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TramitesPorDependencia cloned = new TramitesPorDependencia();

        cloned.setID_TRAMITEDEPEN(this.ID_TRAMITEDEPEN); 
        cloned.setID_DEPENDENCIA(this.ID_DEPENDENCIA); 
        cloned.setID_TRAMITEINTERNO(this.ID_TRAMITEINTERNO); 
        if (this.CODTRAMITE != null)
             cloned.setCODTRAMITE(new String(this.CODTRAMITE)); 
        if (this.DESCTRAMITE != null)
             cloned.setDESCTRAMITE(new String(this.DESCTRAMITE)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}