package modelo.datos.objetos.comparendos.generales;

import java.io.*;

import java.sql.*;

import java.util.*;

import java.math.*;

/**
  * TipoInfraccionComp Value Object.
  * This class is value object representing database table TIPO_INFRACCION
  * This class is intented to be used together with associated Dao object.
  */

/**
 * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
 * The usage of generated code is restricted to OpenSource software projects
 * only. DaoGen is available in http://titaniclinux.net/daogen/
 * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
 *
 * DaoGen license: The following DaoGen generated source code is licensed
 * under the terms of GNU GPL license. The full text for license is available
 * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
 *
 * If you wish to use the DaoGen generator to produce code for closed-source
 * commercial applications, you must pay the lisence fee. The price is
 * 5 USD or 5 Eur for each database table, you are generating code for.
 * (That includes unlimited amount of iterations with all supported languages
 * for each database table you are paying for.) Send mail to
 * "Tuomo.Lukka@iki.fi" for more information. Thank you!
 */


public class TipoInfrInfraccionComp implements Cloneable, Serializable {

    /**
     * Persistent Instance variables. This data is directly
     * mapped to the columns of database table.
     */
    private int ID_TIPO_INFR_INFRACCION;
    private int ID_TIPO_INFRACCION;
    private int ID_INFRACCION;
    private String DESCRIPCION;


    /**
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TipoInfrInfraccionComp() {

    }

    public TipoInfrInfraccionComp(int ID_TIPO_INFR_INFRACCIONIn) {

        this.ID_TIPO_INFR_INFRACCION = ID_TIPO_INFR_INFRACCIONIn;

    }


    /**
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_TIPO_INFR_INFRACCION() {
        return this.ID_TIPO_INFR_INFRACCION;
    }

    public void setID_TIPO_INFR_INFRACCION(int ID_TIPO_INFR_INFRACCIONIn) {
        this.ID_TIPO_INFR_INFRACCION = ID_TIPO_INFR_INFRACCIONIn;
    }

    public int getID_TIPO_INFRACCION() {
        return this.ID_TIPO_INFRACCION;
    }

    public void setID_TIPO_INFRACCION(int ID_TIPO_INFRACCIONIn) {
        this.ID_TIPO_INFRACCION = ID_TIPO_INFRACCIONIn;
    }

    public int getID_INFRACCION() {
        return this.ID_INFRACCION;
    }

    public void setID_INFRACCION(int COD_TIPO_INFRACCIONIn) {
        this.ID_INFRACCION = COD_TIPO_INFRACCIONIn;
    }

    public String getDESCRIPCION() {
        return this.DESCRIPCION;
    }

    public void setDESCRIPCION(String TIPO_INFRACCIONIn) {
        this.DESCRIPCION = TIPO_INFRACCIONIn;
    }


    /**
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the
     * individual set-methods.
     */

    public void setAll(int ID_TIPO_INFRACCIONIn, int COD_TIPO_INFRACCIONIn, String TIPO_INFRACCIONIn) {
        this.ID_TIPO_INFRACCION = ID_TIPO_INFRACCIONIn;
        this.ID_INFRACCION = COD_TIPO_INFRACCIONIn;
        this.DESCRIPCION = TIPO_INFRACCIONIn;
    }


    /**
     * hasEqualMapping-method will compare two TipoInfraccionComp instances
     * and return true if they contain same values in all persistent instance
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TipoInfrInfraccionComp valueObject) {

        if (valueObject.getID_TIPO_INFRACCION() != this.ID_TIPO_INFRACCION) {
            return (false);
        }
        if (this.ID_INFRACCION == -1) {
            if (valueObject.getID_INFRACCION() > 0)
                return (false);
        } else if (this.ID_INFRACCION != valueObject.getID_INFRACCION()) {
            return (false);
        }
        if (this.DESCRIPCION == null) {
            if (valueObject.getDESCRIPCION() != null)
                return (false);
        } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
            return (false);
        }

        return true;
    }


    /**
     * toString will return String object representing the state of this
     * valueObject. This is useful during application development, and
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TipoInfraccionComp, mapping to table TIPO_INFRACCION\n");
        out.append("Persistent attributes: \n");
        out.append("ID_TIPO_INFRACCION = " + this.ID_TIPO_INFRACCION + "\n");
        out.append("COD_TIPO_INFRACCION = " + this.ID_INFRACCION + "\n");
        out.append("TIPO_INFRACCION = " + this.DESCRIPCION + "\n");
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TipoInfrInfraccionComp cloned = new TipoInfrInfraccionComp();

        cloned.setID_TIPO_INFRACCION(this.ID_TIPO_INFRACCION);
        if (this.ID_INFRACCION > 0)
            cloned.setID_INFRACCION(this.ID_INFRACCION);
        if (this.DESCRIPCION != null)
            cloned.setDESCRIPCION(new String(this.DESCRIPCION));
        return cloned;
    }


    /**
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
