package modelo.datos.objetos.comparendos.generales;

import java.io.*;

import java.sql.*;

import java.util.*;

import java.math.*;

/**
  * VehiculosComp Value Object.
  * This class is value object representing database table VEHICULOSCOM
  * This class is intented to be used together with associated Dao object.
  */

/**
 * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
 * The usage of generated code is restricted to OpenSource software projects
 * only. DaoGen is available in http://titaniclinux.net/daogen/
 * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
 *
 * DaoGen license: The following DaoGen generated source code is licensed
 * under the terms of GNU GPL license. The full text for license is available
 * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
 *
 * If you wish to use the DaoGen generator to produce code for closed-source
 * commercial applications, you must pay the lisence fee. The price is
 * 5 USD or 5 Eur for each database table, you are generating code for.
 * (That includes unlimited amount of iterations with all supported languages
 * for each database table you are paying for.) Send mail to
 * "Tuomo.Lukka@iki.fi" for more information. Thank you!
 */


public class VehiculosComp implements Cloneable, Serializable {

    /**
     * Persistent Instance variables. This data is directly
     * mapped to the columns of database table.
     */
    private int IDVEHICULOCOMP;
    private String PLACA;
    private int ID_SERVICIO;
    private int ID_CVEHICULO;
    private int ID_EMPRESA;
    private String TARJETAOPERACION;
    private String NROLICENCIA;
    private int ID_ORGTRANSITODEMATRICULA;
    private int ID_RADIOACCION;
    private int ID_MODALIDADTRANSPORTE;
    private int ID_TIPOTRANSPORTEPASAJERO;


    /**
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public VehiculosComp() {

    }

    public VehiculosComp(int IDVEHICULOCOMPIn) {

        this.IDVEHICULOCOMP = IDVEHICULOCOMPIn;

    }


    /**
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDVEHICULOCOMP() {
        return this.IDVEHICULOCOMP;
    }

    public void setIDVEHICULOCOMP(int IDVEHICULOCOMPIn) {
        this.IDVEHICULOCOMP = IDVEHICULOCOMPIn;
    }

    public String getPLACA() {
        return this.PLACA;
    }

    public void setPLACA(String PLACAIn) {
        this.PLACA = PLACAIn;
    }

    public int getID_SERVICIO() {
        return this.ID_SERVICIO;
    }

    public void setID_SERVICIO(int ID_SERVICIOIn) {
        this.ID_SERVICIO = ID_SERVICIOIn;
    }

    public int getID_CVEHICULO() {
        return this.ID_CVEHICULO;
    }

    public void setID_CVEHICULO(int ID_CVEHICULOIn) {
        this.ID_CVEHICULO = ID_CVEHICULOIn;
    }

    public int getID_EMPRESA() {
        return this.ID_EMPRESA;
    }

    public void setID_EMPRESA(int ID_EMPRESAIn) {
        this.ID_EMPRESA = ID_EMPRESAIn;
    }

    public String getTARJETAOPERACION() {
        return this.TARJETAOPERACION;
    }

    public void setTARJETAOPERACION(String TARJETAOPERACIONIn) {
        this.TARJETAOPERACION = TARJETAOPERACIONIn;
    }

    public String getNROLICENCIA() {
        return this.NROLICENCIA;
    }

    public void setNROLICENCIA(String NROLICENCIAIn) {
        this.NROLICENCIA = NROLICENCIAIn;
    }

    public int getID_ORGTRANSITODEMATRICULA() {
        return this.ID_ORGTRANSITODEMATRICULA;
    }

    public void setID_ORGTRANSITODEMATRICULA(int ID_ORGTRANSITODEMATRICULAIn) {
        this.ID_ORGTRANSITODEMATRICULA = ID_ORGTRANSITODEMATRICULAIn;
    }

    public int getID_RADIOACCION() {
        return this.ID_RADIOACCION;
    }

    public void setID_RADIOACCION(int ID_RADIOACCIONIn) {
        this.ID_RADIOACCION = ID_RADIOACCIONIn;
    }

    public int getID_MODALIDADTRANSPORTE() {
        return this.ID_MODALIDADTRANSPORTE;
    }

    public void setID_MODALIDADTRANSPORTE(int ID_MODALIDADTRANSPORTEIn) {
        this.ID_MODALIDADTRANSPORTE = ID_MODALIDADTRANSPORTEIn;
    }

    public int getID_TIPOTRANSPORTEPASAJERO() {
        return this.ID_TIPOTRANSPORTEPASAJERO;
    }

    public void setID_TIPOTRANSPORTEPASAJERO(int ID_TIPOTRANSPORTEPASAJEROIn) {
        this.ID_TIPOTRANSPORTEPASAJERO = ID_TIPOTRANSPORTEPASAJEROIn;
    }


    /**
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the
     * individual set-methods.
     */

    public void setAll(int IDVEHICULOCOMPIn, String PLACAIn, int ID_SERVICIOIn, int ID_CVEHICULOIn, int ID_EMPRESAIn,
                       String TARJETAOPERACIONIn, String NROLICENCIAIn, int ID_ORGTRANSITODEMATRICULAIn,
                       int ID_RADIOACCIONIn, int ID_MODALIDADTRANSPORTEIn, int ID_TIPOTRANSPORTEPASAJEROIn) {
        this.IDVEHICULOCOMP = IDVEHICULOCOMPIn;
        this.PLACA = PLACAIn;
        this.ID_SERVICIO = ID_SERVICIOIn;
        this.ID_CVEHICULO = ID_CVEHICULOIn;
        this.ID_EMPRESA = ID_EMPRESAIn;
        this.TARJETAOPERACION = TARJETAOPERACIONIn;
        this.NROLICENCIA = NROLICENCIAIn;
        this.ID_ORGTRANSITODEMATRICULA = ID_ORGTRANSITODEMATRICULAIn;
        this.ID_RADIOACCION = ID_RADIOACCIONIn;
        this.ID_MODALIDADTRANSPORTE = ID_MODALIDADTRANSPORTEIn;
        this.ID_TIPOTRANSPORTEPASAJERO = ID_TIPOTRANSPORTEPASAJEROIn;
    }


    /**
     * hasEqualMapping-method will compare two VehiculosComp instances
     * and return true if they contain same values in all persistent instance
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(VehiculosComp valueObject) {

        if (valueObject.getIDVEHICULOCOMP() != this.IDVEHICULOCOMP) {
            return (false);
        }
        if (this.PLACA == null) {
            if (valueObject.getPLACA() != null)
                return (false);
        } else if (!this.PLACA.equals(valueObject.getPLACA())) {
            return (false);
        }
        if (valueObject.getID_SERVICIO() != this.ID_SERVICIO) {
            return (false);
        }
        if (valueObject.getID_CVEHICULO() != this.ID_CVEHICULO) {
            return (false);
        }
        if (valueObject.getID_EMPRESA() != this.ID_EMPRESA) {
            return (false);
        }
        if (this.TARJETAOPERACION == null) {
            if (valueObject.getTARJETAOPERACION() != null)
                return (false);
        } else if (!this.TARJETAOPERACION.equals(valueObject.getTARJETAOPERACION())) {
            return (false);
        }
        if (this.NROLICENCIA == null) {
            if (valueObject.getNROLICENCIA() != null)
                return (false);
        } else if (!this.NROLICENCIA.equals(valueObject.getNROLICENCIA())) {
            return (false);
        }
        if (valueObject.getID_ORGTRANSITODEMATRICULA() != this.ID_ORGTRANSITODEMATRICULA) {
            return (false);
        }
        if (valueObject.getID_RADIOACCION() != this.ID_RADIOACCION) {
            return (false);
        }
        if (valueObject.getID_MODALIDADTRANSPORTE() != this.ID_MODALIDADTRANSPORTE) {
            return (false);
        }
        if (valueObject.getID_TIPOTRANSPORTEPASAJERO() != this.ID_TIPOTRANSPORTEPASAJERO) {
            return (false);
        }

        return true;
    }


    /**
     * toString will return String object representing the state of this
     * valueObject. This is useful during application development, and
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass VehiculosComp, mapping to table VEHICULOSCOM\n");
        out.append("Persistent attributes: \n");
        out.append("IDVEHICULOCOMP = " + this.IDVEHICULOCOMP + "\n");
        out.append("PLACA = " + this.PLACA + "\n");
        out.append("ID_SERVICIO = " + this.ID_SERVICIO + "\n");
        out.append("ID_CVEHICULO = " + this.ID_CVEHICULO + "\n");
        out.append("ID_EMPRESA = " + this.ID_EMPRESA + "\n");
        out.append("TARJETAOPERACION = " + this.TARJETAOPERACION + "\n");
        out.append("NROLICENCIA = " + this.NROLICENCIA + "\n");
        out.append("ID_ORGTRANSITODEMATRICULA = " + this.ID_ORGTRANSITODEMATRICULA + "\n");
        out.append("ID_RADIOACCION = " + this.ID_RADIOACCION + "\n");
        out.append("ID_MODALIDADTRANSPORTE = " + this.ID_MODALIDADTRANSPORTE + "\n");
        out.append("ID_TIPOTRANSPORTEPASAJERO = " + this.ID_TIPOTRANSPORTEPASAJERO + "\n");
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        VehiculosComp cloned = new VehiculosComp();

        cloned.setIDVEHICULOCOMP(this.IDVEHICULOCOMP);
        if (this.PLACA != null)
            cloned.setPLACA(new String(this.PLACA));
        cloned.setID_SERVICIO(this.ID_SERVICIO);
        cloned.setID_CVEHICULO(this.ID_CVEHICULO);
        cloned.setID_EMPRESA(this.ID_EMPRESA);
        if (this.TARJETAOPERACION != null)
            cloned.setTARJETAOPERACION(new String(this.TARJETAOPERACION));
        if (this.NROLICENCIA != null)
            cloned.setNROLICENCIA(new String(this.NROLICENCIA));
        cloned.setID_ORGTRANSITODEMATRICULA(this.ID_ORGTRANSITODEMATRICULA);
        cloned.setID_RADIOACCION(this.ID_RADIOACCION);
        cloned.setID_MODALIDADTRANSPORTE(this.ID_MODALIDADTRANSPORTE);
        cloned.setID_TIPOTRANSPORTEPASAJERO(this.ID_TIPOTRANSPORTEPASAJERO);
        return cloned;
    }


    /**
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
