package modelo.datos.dao.generales.vistas;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.generales.vistas.ViewPopietarioEmpresa2;


/**
  * ViewPopietarioEmpresa2 Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve ViewPopietarioEmpresa2 object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewPopietarioEmpresa2Dao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public ViewPopietarioEmpresa2 createValueObject() {
          return new ViewPopietarioEmpresa2();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public ViewPopietarioEmpresa2 getObject(Connection conn, int id_empresa) throws NotFoundException, SQLException {

          ViewPopietarioEmpresa2 valueObject = createValueObject();
          valueObject.setId_empresa(id_empresa);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, ViewPopietarioEmpresa2 valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM VIEW_PROPIETARIOEMPRESA2 WHERE (id_empresa = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getId_empresa()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VIEW_PROPIETARIOEMPRESA2 ORDER BY id_empresa ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, ViewPopietarioEmpresa2 valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO VIEW_PROPIETARIOEMPRESA2 ( id_empresa, nit, razonsocial, "
               + "sigla, id_docto, direccion, "
               + "telefono1, nombre, codciudad, "
               + "id_depto, id_propvehiculo, placa, "
               + "fecha, estado, id_propietario, "
               + "empper, gen_lictransito, id_vehiculo, "
               + "propietarioactual, id_tipopropiedad, porcentajepropiedad, "
               + "proindiviso, fechafinpropiedad) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getId_empresa()); 
               stmt.setString(2, valueObject.getNit()); 
               stmt.setString(3, valueObject.getRazonsocial()); 
               stmt.setString(4, valueObject.getSigla()); 
               stmt.setString(5, valueObject.getId_docto()); 
               stmt.setString(6, valueObject.getDireccion()); 
               stmt.setString(7, valueObject.getTelefono1()); 
               stmt.setString(8, valueObject.getNombre()); 
               stmt.setString(9, valueObject.getCodciudad()); 
               stmt.setInt(10, valueObject.getId_depto()); 
               stmt.setInt(11, valueObject.getId_propvehiculo()); 
               stmt.setString(12, valueObject.getPlaca()); 
               stmt.setString(13, valueObject.getFecha()); 
               stmt.setString(14, valueObject.getEstado()); 
               stmt.setInt(15, valueObject.getId_propietario()); 
               stmt.setString(16, valueObject.getEmpper()); 
               stmt.setInt(17, valueObject.getGen_lictransito()); 
               stmt.setInt(18, valueObject.getId_vehiculo()); 
               stmt.setString(19, valueObject.getPropietarioactual()); 
               stmt.setInt(20, valueObject.getId_tipopropiedad()); 
               stmt.setInt(21, valueObject.getPorcentajepropiedad()); 
               stmt.setString(22, valueObject.getProindiviso()); 
               stmt.setString(23, valueObject.getFechafinpropiedad()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, ViewPopietarioEmpresa2 valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE VIEW_PROPIETARIOEMPRESA2 SET nit = ?, razonsocial = ?, sigla = ?, "
               + "id_docto = ?, direccion = ?, telefono1 = ?, "
               + "nombre = ?, codciudad = ?, id_depto = ?, "
               + "id_propvehiculo = ?, placa = ?, fecha = ?, "
               + "estado = ?, id_propietario = ?, empper = ?, "
               + "gen_lictransito = ?, id_vehiculo = ?, propietarioactual = ?, "
               + "id_tipopropiedad = ?, porcentajepropiedad = ?, proindiviso = ?, "
               + "fechafinpropiedad = ? WHERE (id_empresa = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getNit()); 
              stmt.setString(2, valueObject.getRazonsocial()); 
              stmt.setString(3, valueObject.getSigla()); 
              stmt.setString(4, valueObject.getId_docto()); 
              stmt.setString(5, valueObject.getDireccion()); 
              stmt.setString(6, valueObject.getTelefono1()); 
              stmt.setString(7, valueObject.getNombre()); 
              stmt.setString(8, valueObject.getCodciudad()); 
              stmt.setInt(9, valueObject.getId_depto()); 
              stmt.setInt(10, valueObject.getId_propvehiculo()); 
              stmt.setString(11, valueObject.getPlaca()); 
              stmt.setString(12, valueObject.getFecha()); 
              stmt.setString(13, valueObject.getEstado()); 
              stmt.setInt(14, valueObject.getId_propietario()); 
              stmt.setString(15, valueObject.getEmpper()); 
              stmt.setInt(16, valueObject.getGen_lictransito()); 
              stmt.setInt(17, valueObject.getId_vehiculo()); 
              stmt.setString(18, valueObject.getPropietarioactual()); 
              stmt.setInt(19, valueObject.getId_tipopropiedad()); 
              stmt.setInt(20, valueObject.getPorcentajepropiedad()); 
              stmt.setString(21, valueObject.getProindiviso()); 
              stmt.setString(22, valueObject.getFechafinpropiedad()); 

              stmt.setInt(23, valueObject.getId_empresa()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, ViewPopietarioEmpresa2 valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM VIEW_PROPIETARIOEMPRESA2 WHERE (id_empresa = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getId_empresa()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM VIEW_PROPIETARIOEMPRESA2";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VIEW_PROPIETARIOEMPRESA2";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, ViewPopietarioEmpresa2 valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_PROPIETARIOEMPRESA2 WHERE 1=1 ");

          if (valueObject.getId_empresa() != 0) {
              if (first) { first = false; }
              sql.append("AND id_empresa = ").append(valueObject.getId_empresa()).append(" ");
          }

          if (valueObject.getNit() != null) {
              if (first) { first = false; }
              sql.append("AND nit = '").append(valueObject.getNit()).append("' ");
          }

          if (valueObject.getRazonsocial() != null) {
              if (first) { first = false; }
              sql.append("AND razonsocial = '").append(valueObject.getRazonsocial()).append("' ");
          }

          if (valueObject.getSigla() != null) {
              if (first) { first = false; }
              sql.append("AND sigla = '").append(valueObject.getSigla()).append("' ");
          }

          if (valueObject.getId_docto() != null) {
              if (first) { first = false; }
              sql.append("AND id_docto = '").append(valueObject.getId_docto()).append("' ");
          }

          if (valueObject.getDireccion() != null) {
              if (first) { first = false; }
              sql.append("AND direccion = '").append(valueObject.getDireccion()).append("' ");
          }

          if (valueObject.getTelefono1() != null) {
              if (first) { first = false; }
              sql.append("AND telefono1 = '").append(valueObject.getTelefono1()).append("' ");
          }

          if (valueObject.getNombre() != null) {
              if (first) { first = false; }
              sql.append("AND nombre = '").append(valueObject.getNombre()).append("' ");
          }

          if (valueObject.getCodciudad() != null) {
              if (first) { first = false; }
              sql.append("AND codciudad = '").append(valueObject.getCodciudad()).append("' ");
          }

          if (valueObject.getId_depto() != 0) {
              if (first) { first = false; }
              sql.append("AND id_depto = ").append(valueObject.getId_depto()).append(" ");
          }

          if (valueObject.getId_propvehiculo() != 0) {
              if (first) { first = false; }
              sql.append("AND id_propvehiculo = ").append(valueObject.getId_propvehiculo()).append(" ");
          }

          if (valueObject.getPlaca() != null) {
              if (first) { first = false; }
              sql.append("AND placa = '").append(valueObject.getPlaca()).append("' ");
          }

          if (valueObject.getFecha() != null) {
              if (first) { first = false; }
              sql.append("AND fecha = '").append(valueObject.getFecha()).append("' ");
          }

          if (valueObject.getEstado() != null) {
              if (first) { first = false; }
              sql.append("AND estado = '").append(valueObject.getEstado()).append("' ");
          }

          if (valueObject.getId_propietario() != 0) {
              if (first) { first = false; }
              sql.append("AND id_propietario = ").append(valueObject.getId_propietario()).append(" ");
          }

          if (valueObject.getEmpper() != null) {
              if (first) { first = false; }
              sql.append("AND empper = '").append(valueObject.getEmpper()).append("' ");
          }

          if (valueObject.getGen_lictransito() != 0) {
              if (first) { first = false; }
              sql.append("AND gen_lictransito = ").append(valueObject.getGen_lictransito()).append(" ");
          }

          if (valueObject.getId_vehiculo() != 0) {
              if (first) { first = false; }
              sql.append("AND id_vehiculo = ").append(valueObject.getId_vehiculo()).append(" ");
          }

          if (valueObject.getPropietarioactual() != null) {
              if (first) { first = false; }
              sql.append("AND propietarioactual = '").append(valueObject.getPropietarioactual()).append("' ");
          }

          if (valueObject.getId_tipopropiedad() != 0) {
              if (first) { first = false; }
              sql.append("AND id_tipopropiedad = ").append(valueObject.getId_tipopropiedad()).append(" ");
          }

          if (valueObject.getPorcentajepropiedad() != 0) {
              if (first) { first = false; }
              sql.append("AND porcentajepropiedad = ").append(valueObject.getPorcentajepropiedad()).append(" ");
          }

          if (valueObject.getProindiviso() != null) {
              if (first) { first = false; }
              sql.append("AND proindiviso = '").append(valueObject.getProindiviso()).append("' ");
          }

          if (valueObject.getFechafinpropiedad() != null) {
              if (first) { first = false; }
              sql.append("AND fechafinpropiedad = '").append(valueObject.getFechafinpropiedad()).append("' ");
          }


          sql.append("ORDER BY id_empresa ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, ViewPopietarioEmpresa2 valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setId_empresa(result.getInt("id_empresa")); 
                   valueObject.setNit(result.getString("nit")); 
                   valueObject.setRazonsocial(result.getString("razonsocial")); 
                   valueObject.setSigla(result.getString("sigla")); 
                   valueObject.setId_docto(result.getString("id_docto")); 
                   valueObject.setDireccion(result.getString("direccion")); 
                   valueObject.setTelefono1(result.getString("telefono1")); 
                   valueObject.setNombre(result.getString("nombre")); 
                   valueObject.setCodciudad(result.getString("codciudad")); 
                   valueObject.setId_depto(result.getInt("id_depto")); 
                   valueObject.setId_propvehiculo(result.getInt("id_propvehiculo")); 
                   valueObject.setPlaca(result.getString("placa")); 
                   valueObject.setFecha(result.getString("fecha")); 
                   valueObject.setEstado(result.getString("estado")); 
                   valueObject.setId_propietario(result.getInt("id_propietario")); 
                   valueObject.setEmpper(result.getString("empper")); 
                   valueObject.setGen_lictransito(result.getInt("gen_lictransito")); 
                   valueObject.setId_vehiculo(result.getInt("id_vehiculo")); 
                   valueObject.setPropietarioactual(result.getString("propietarioactual")); 
                   valueObject.setId_tipopropiedad(result.getInt("id_tipopropiedad")); 
                   valueObject.setPorcentajepropiedad(result.getInt("porcentajepropiedad")); 
                   valueObject.setProindiviso(result.getString("proindiviso")); 
                   valueObject.setFechafinpropiedad(result.getString("fechafinpropiedad")); 

              } else {
                    //System.out.println("ViewPopietarioEmpresa2 Object Not Found!");
                    throw new NotFoundException("ViewPopietarioEmpresa2 Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   ViewPopietarioEmpresa2 temp = createValueObject();

                   temp.setId_empresa(result.getInt("id_empresa")); 
                   temp.setNit(result.getString("nit")); 
                   temp.setRazonsocial(result.getString("razonsocial")); 
                   temp.setSigla(result.getString("sigla")); 
                   temp.setId_docto(result.getString("id_docto")); 
                   temp.setDireccion(result.getString("direccion")); 
                   temp.setTelefono1(result.getString("telefono1")); 
                   temp.setNombre(result.getString("nombre")); 
                   temp.setCodciudad(result.getString("codciudad")); 
                   temp.setId_depto(result.getInt("id_depto")); 
                   temp.setId_propvehiculo(result.getInt("id_propvehiculo")); 
                   temp.setPlaca(result.getString("placa")); 
                   temp.setFecha(result.getString("fecha")); 
                   temp.setEstado(result.getString("estado")); 
                   temp.setId_propietario(result.getInt("id_propietario")); 
                   temp.setEmpper(result.getString("empper")); 
                   temp.setGen_lictransito(result.getInt("gen_lictransito")); 
                   temp.setId_vehiculo(result.getInt("id_vehiculo")); 
                   temp.setPropietarioactual(result.getString("propietarioactual")); 
                   temp.setId_tipopropiedad(result.getInt("id_tipopropiedad")); 
                   temp.setPorcentajepropiedad(result.getInt("porcentajepropiedad")); 
                   temp.setProindiviso(result.getString("proindiviso")); 
                   temp.setFechafinpropiedad(result.getString("fechafinpropiedad")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}