package modelo.datos.dao.liquidacion;


import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.liquidacion.ViewFacturaRNC;


/**
  * ViewFacturaRNC Data Access Object (DAO).
  * This class contains all database handling that is needed to
  * permanently store and retrieve ViewFacturaRNC object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewFacturaRNCDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public ViewFacturaRNC createValueObject() {
          return new ViewFacturaRNC();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public ViewFacturaRNC getObject(Connection conn, int LF_ID) throws NotFoundException, SQLException {

          ViewFacturaRNC valueObject = createValueObject();
          valueObject.setLF_ID(LF_ID);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, ViewFacturaRNC valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT * FROM VIEW_FACTURA_RNC WHERE (LF_ID = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setInt(1, valueObject.getLF_ID()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM VIEW_FACTURA_RNC ORDER BY LF_ID ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, ViewFacturaRNC valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO VIEW_FACTURA_RNC ( LF_ID, CONCEPTO, IDENTIFICACION, "
               + "NOMBRE, LF_TIPO, LF_ID_PERSONA, "
               + "LF_ESTADO, LF_FECHA, LF_FECHA_PAGO, "
               + "LF_FECHA_TRAMITE, TOTAL, LF_FECHAANULA, "
               + "LF_HORAANULA, LF_NUMERO, LF_DESCUENTO, "
               + "LF_NUMRUNT, LF_FECHARADICARUNT, LF_TOTALFACTURARUNT, "
               + "CARGADO, ESTADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getLF_ID()); 
               stmt.setString(2, valueObject.getCONCEPTO()); 
               stmt.setString(3, valueObject.getIDENTIFICACION()); 
               stmt.setString(4, valueObject.getNOMBRE()); 
               stmt.setObject(5, valueObject.getLF_TIPO(), Types.INTEGER); 
               stmt.setObject(6, valueObject.getLF_ID_PERSONA(), Types.INTEGER); 
               stmt.setObject(7, valueObject.getLF_ESTADO(), Types.INTEGER); 
               stmt.setString(8, valueObject.getLF_FECHA()); 
               stmt.setString(9, valueObject.getLF_FECHA_PAGO()); 
               stmt.setString(10, valueObject.getLF_FECHA_TRAMITE()); 
               stmt.setObject(11, valueObject.getTOTAL(), Types.DOUBLE); 
               stmt.setString(12, valueObject.getLF_FECHAANULA()); 
               stmt.setString(13, valueObject.getLF_HORAANULA()); 
               stmt.setString(14, valueObject.getLF_NUMERO()); 
               stmt.setObject(15, valueObject.getLF_DESCUENTO(), Types.DOUBLE); 
               stmt.setString(16, valueObject.getLF_NUMRUNT()); 
               stmt.setString(17, valueObject.getLF_FECHARADICARUNT()); 
               stmt.setObject(18, valueObject.getLF_TOTALFACTURARUNT(), Types.DOUBLE); 
               stmt.setString(19, valueObject.getCARGADO()); 
               stmt.setString(20, valueObject.getESTADO()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, ViewFacturaRNC valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE VIEW_FACTURA_RNC SET CONCEPTO = ?, IDENTIFICACION = ?, NOMBRE = ?, "
               + "LF_TIPO = ?, LF_ID_PERSONA = ?, LF_ESTADO = ?, "
               + "LF_FECHA = ?, LF_FECHA_PAGO = ?, LF_FECHA_TRAMITE = ?, "
               + "TOTAL = ?, LF_FECHAANULA = ?, LF_HORAANULA = ?, "
               + "LF_NUMERO = ?, LF_DESCUENTO = ?, LF_NUMRUNT = ?, "
               + "LF_FECHARADICARUNT = ?, LF_TOTALFACTURARUNT = ?, CARGADO = ?, "
               + "ESTADO = ? WHERE (LF_ID = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getCONCEPTO()); 
              stmt.setString(2, valueObject.getIDENTIFICACION()); 
              stmt.setString(3, valueObject.getNOMBRE()); 
              stmt.setObject(4, valueObject.getLF_TIPO(), Types.INTEGER); 
              stmt.setObject(5, valueObject.getLF_ID_PERSONA(), Types.INTEGER); 
              stmt.setObject(6, valueObject.getLF_ESTADO(), Types.INTEGER); 
              stmt.setString(7, valueObject.getLF_FECHA()); 
              stmt.setString(8, valueObject.getLF_FECHA_PAGO()); 
              stmt.setString(9, valueObject.getLF_FECHA_TRAMITE()); 
              stmt.setObject(10, valueObject.getTOTAL(), Types.DOUBLE); 
              stmt.setString(11, valueObject.getLF_FECHAANULA()); 
              stmt.setString(12, valueObject.getLF_HORAANULA()); 
              stmt.setString(13, valueObject.getLF_NUMERO()); 
              stmt.setObject(14, valueObject.getLF_DESCUENTO(), Types.DOUBLE); 
              stmt.setString(15, valueObject.getLF_NUMRUNT()); 
              stmt.setString(16, valueObject.getLF_FECHARADICARUNT()); 
              stmt.setObject(17, valueObject.getLF_TOTALFACTURARUNT(), Types.DOUBLE); 
              stmt.setString(18, valueObject.getCARGADO()); 
              stmt.setString(19, valueObject.getESTADO()); 

              stmt.setInt(20, valueObject.getLF_ID()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, ViewFacturaRNC valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM VIEW_FACTURA_RNC WHERE (LF_ID = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getLF_ID()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM VIEW_FACTURA_RNC";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM VIEW_FACTURA_RNC";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, ViewFacturaRNC valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM VIEW_FACTURA_RNC WHERE 1=1 ");

          if (valueObject.getLF_ID() != 0) {
              if (first) { first = false; }
              sql.append("AND LF_ID = ").append(valueObject.getLF_ID()).append(" ");
          }

          if (valueObject.getCONCEPTO() != null) {
              if (first) { first = false; }
              sql.append("AND CONCEPTO LIKE '").append(valueObject.getCONCEPTO()).append("%' ");
          }

          if (valueObject.getIDENTIFICACION() != null) {
              if (first) { first = false; }
              sql.append("AND IDENTIFICACION = '").append(valueObject.getIDENTIFICACION()).append("' ");
          }

          if (valueObject.getNOMBRE() != null) {
              if (first) { first = false; }
              sql.append("AND NOMBRE LIKE '").append(valueObject.getNOMBRE()).append("%' ");
          }

          if (valueObject.getLF_TIPO() != null) {
              if (first) { first = false; }
              sql.append("AND LF_TIPO = ").append(valueObject.getLF_TIPO()).append(" ");
          }

          if (valueObject.getLF_ID_PERSONA() != null) {
              if (first) { first = false; }
              sql.append("AND LF_ID_PERSONA = ").append(valueObject.getLF_ID_PERSONA()).append(" ");
          }

          if (valueObject.getLF_ESTADO() != null) {
              if (first) { first = false; }
              sql.append("AND LF_ESTADO = ").append(valueObject.getLF_ESTADO()).append(" ");
          }

          if (valueObject.getLF_FECHA() != null) {
              if (first) { first = false; }
              sql.append("AND LF_FECHA LIKE '").append(valueObject.getLF_FECHA()).append("%' ");
          }

          if (valueObject.getLF_FECHA_PAGO() != null) {
              if (first) { first = false; }
              sql.append("AND LF_FECHA_PAGO LIKE '").append(valueObject.getLF_FECHA_PAGO()).append("%' ");
          }

          if (valueObject.getLF_FECHA_TRAMITE() != null) {
              if (first) { first = false; }
              sql.append("AND LF_FECHA_TRAMITE LIKE '").append(valueObject.getLF_FECHA_TRAMITE()).append("%' ");
          }

          if (valueObject.getTOTAL() != null) {
              if (first) { first = false; }
              sql.append("AND TOTAL = ").append(valueObject.getTOTAL()).append(" ");
          }

          if (valueObject.getLF_FECHAANULA() != null) {
              if (first) { first = false; }
              sql.append("AND LF_FECHAANULA LIKE '").append(valueObject.getLF_FECHAANULA()).append("%' ");
          }

          if (valueObject.getLF_HORAANULA() != null) {
              if (first) { first = false; }
              sql.append("AND LF_HORAANULA LIKE '").append(valueObject.getLF_HORAANULA()).append("%' ");
          }

          if (valueObject.getLF_NUMERO() != null) {
              if (first) { first = false; }
              sql.append("AND LF_NUMERO LIKE '").append(valueObject.getLF_NUMERO()).append("%' ");
          }

          if (valueObject.getLF_DESCUENTO() != null) {
              if (first) { first = false; }
              sql.append("AND LF_DESCUENTO = ").append(valueObject.getLF_DESCUENTO()).append(" ");
          }

          if (valueObject.getLF_NUMRUNT() != null) {
              if (first) { first = false; }
              sql.append("AND LF_NUMRUNT LIKE '").append(valueObject.getLF_NUMRUNT()).append("%' ");
          }

          if (valueObject.getLF_FECHARADICARUNT() != null) {
              if (first) { first = false; }
              sql.append("AND LF_FECHARADICARUNT LIKE '").append(valueObject.getLF_FECHARADICARUNT()).append("%' ");
          }

          if (valueObject.getLF_TOTALFACTURARUNT() != null) {
              if (first) { first = false; }
              sql.append("AND LF_TOTALFACTURARUNT = ").append(valueObject.getLF_TOTALFACTURARUNT()).append(" ");
          }

          if (valueObject.getCARGADO() != null) {
              if (first) { first = false; }
              sql.append("AND CARGADO LIKE '").append(valueObject.getCARGADO()).append("%' ");
          }

          if (valueObject.getESTADO() != null) {
              if (first) { first = false; }
              sql.append("AND ESTADO LIKE '").append(valueObject.getESTADO()).append("%' ");
          }


          sql.append("ORDER BY LF_ID ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, ViewFacturaRNC valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setLF_ID(result.getInt("LF_ID")); 
                   valueObject.setCONCEPTO(result.getString("CONCEPTO")); 
                   valueObject.setIDENTIFICACION(result.getString("IDENTIFICACION")); 
                   valueObject.setNOMBRE(result.getString("NOMBRE")); 
                   valueObject.setLF_TIPO((Integer)result.getObject("LF_TIPO")); 
                   valueObject.setLF_ID_PERSONA((Integer)result.getObject("LF_ID_PERSONA")); 
                   valueObject.setLF_ESTADO((Integer)result.getObject("LF_ESTADO")); 
                   valueObject.setLF_FECHA(result.getString("LF_FECHA")); 
                   valueObject.setLF_FECHA_PAGO(result.getString("LF_FECHA_PAGO")); 
                   valueObject.setLF_FECHA_TRAMITE(result.getString("LF_FECHA_TRAMITE")); 
                   valueObject.setTOTAL((Double)result.getObject("TOTAL")); 
                   valueObject.setLF_FECHAANULA(result.getString("LF_FECHAANULA")); 
                   valueObject.setLF_HORAANULA(result.getString("LF_HORAANULA")); 
                   valueObject.setLF_NUMERO(result.getString("LF_NUMERO")); 
                   valueObject.setLF_DESCUENTO((Double)result.getObject("LF_DESCUENTO")); 
                   valueObject.setLF_NUMRUNT(result.getString("LF_NUMRUNT")); 
                   valueObject.setLF_FECHARADICARUNT(result.getString("LF_FECHARADICARUNT")); 
                   valueObject.setLF_TOTALFACTURARUNT((Double)result.getObject("LF_TOTALFACTURARUNT")); 
                   valueObject.setCARGADO(result.getString("CARGADO")); 
                   valueObject.setESTADO(result.getString("ESTADO")); 

              } else {
                    //System.out.println("ViewFacturaRNC Object Not Found!");
                    throw new NotFoundException("ViewFacturaRNC Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   ViewFacturaRNC temp = createValueObject();

                   temp.setLF_ID(result.getInt("LF_ID")); 
                   temp.setCONCEPTO(result.getString("CONCEPTO")); 
                   temp.setIDENTIFICACION(result.getString("IDENTIFICACION")); 
                   temp.setNOMBRE(result.getString("NOMBRE")); 
                   temp.setLF_TIPO((Integer)result.getObject("LF_TIPO")); 
                   temp.setLF_ID_PERSONA((Integer)result.getObject("LF_ID_PERSONA")); 
                   temp.setLF_ESTADO((Integer)result.getObject("LF_ESTADO")); 
                   temp.setLF_FECHA(result.getString("LF_FECHA")); 
                   temp.setLF_FECHA_PAGO(result.getString("LF_FECHA_PAGO")); 
                   temp.setLF_FECHA_TRAMITE(result.getString("LF_FECHA_TRAMITE")); 
                   temp.setTOTAL((Double)result.getObject("TOTAL")); 
                   temp.setLF_FECHAANULA(result.getString("LF_FECHAANULA")); 
                   temp.setLF_HORAANULA(result.getString("LF_HORAANULA")); 
                   temp.setLF_NUMERO(result.getString("LF_NUMERO")); 
                   temp.setLF_DESCUENTO((Double)result.getObject("LF_DESCUENTO")); 
                   temp.setLF_NUMRUNT(result.getString("LF_NUMRUNT")); 
                   temp.setLF_FECHARADICARUNT(result.getString("LF_FECHARADICARUNT")); 
                   temp.setLF_TOTALFACTURARUNT((Double)result.getObject("LF_TOTALFACTURARUNT")); 
                   temp.setCARGADO(result.getString("CARGADO")); 
                   temp.setESTADO(result.getString("ESTADO")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}

