package modelo.datos.dao.accesorias;

import java.sql.*;
import java.util.*;
import java.math.*;

import modelo.datos.dao.NotFoundException;
import modelo.datos.objetos.accesorias.RuntLinea;


/**
  * RuntLinea Data Access Object (DAO) migrado a firebird 2.5.
  * This class contains all database handling that is needed to
  * permanently store and retrieve RuntLinea object instances.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RuntLineaDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public RuntLinea createValueObject() {
          return new RuntLinea();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public RuntLinea getObject(Connection conn, int ID_LINEA) throws NotFoundException, SQLException {

          RuntLinea valueObject = createValueObject();
          valueObject.setID_LINEA(ID_LINEA);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, RuntLinea valueObject) throws NotFoundException, SQLException {

          String sql = "SELECT CODIGO AS ID_LINEA, CODIGO_MARCA AS ID_MARCA, LINEA AS DESCRIPCION, 'S' AS REVISADA, CODIGO AS ID_MARCA_NUM, CODIGO AS ID_LINEA_PPAL, 'S' AS CHEQUEADO, CODIGO_MARCA AS ID_MARCAPPAL, CODIGO AS ID_LINEARUNT, CODIGO AS ID_LINEAMIN  FROM RUNT_LINEAS_RNA WHERE (CODIGO = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getID_LINEAPPAL()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              //if (stmt != null)
              //    stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT CODIGO AS ID_LINEA, CODIGO_MARCA AS ID_MARCA, LINEA AS DESCRIPCION, 'S' AS REVISADA, CODIGO AS ID_MARCA_NUM, CODIGO AS ID_LINEA_PPAL, 'S' AS CHEQUEADO, CODIGO_MARCA AS ID_MARCAPPAL, CODIGO AS ID_LINEARUNT, CODIGO AS ID_LINEAMIN  FROM RUNT_LINEAS_RNA ORDER BY LINEA ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }

    public List loadAllAvaluo(Connection conn) throws SQLException {

          String sql = "SELECT CODIGO AS ID_LINEA, CODIGO_MARCA AS ID_MARCA, LINEA AS DESCRIPCION, 'S' AS REVISADA, CODIGO AS ID_MARCA_NUM, CODIGO AS ID_LINEA_PPAL, 'S' AS CHEQUEADO, CODIGO_MARCA AS ID_MARCAPPAL, CODIGO AS ID_LINEARUNT, CODIGO AS ID_LINEAMIN  FROM RUNT_LINEAS_RNA ORDER BY LINEA ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }

    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, RuntLinea valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO RUNT_LINEAS_RNA ( ID_LINEA, ID_MARCA, DESCRIPCION, "
               + "REVISADA, IDMARCANUM, ID_LINEAPPAL, "
               + "CHEQUEADO, ID_MARCAPPAL, ID_LINEARUNT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setInt(1, valueObject.getID_LINEA()); 
               stmt.setString(2, valueObject.getID_MARCA()); 
               stmt.setString(3, valueObject.getDESCRIPCION()); 
               stmt.setString(4, valueObject.getREVISADA()); 
               stmt.setString(5, valueObject.getIDMARCANUM()); 
               stmt.setString(6, valueObject.getID_LINEAPPAL()); 
               stmt.setString(7, valueObject.getCHEQUEADO()); 
               stmt.setString(8, valueObject.getID_MARCAPPAL()); 
               stmt.setString(9, valueObject.getID_LINEARUNT()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, RuntLinea valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE RUNT_LINEAS_RNA SET ID_MARCA = ?, DESCRIPCION = ?, REVISADA = ?, "
               + "IDMARCANUM = ?, ID_LINEAPPAL = ?, CHEQUEADO = ?, "
               + "ID_MARCAPPAL = ?, ID_LINEARUNT = ? WHERE (ID_LINEA = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getID_MARCA()); 
              stmt.setString(2, valueObject.getDESCRIPCION()); 
              stmt.setString(3, valueObject.getREVISADA()); 
              stmt.setString(4, valueObject.getIDMARCANUM()); 
              stmt.setString(5, valueObject.getID_LINEAPPAL()); 
              stmt.setString(6, valueObject.getCHEQUEADO()); 
              stmt.setString(7, valueObject.getID_MARCAPPAL()); 
              stmt.setString(8, valueObject.getID_LINEARUNT()); 

              stmt.setInt(9, valueObject.getID_LINEA()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, RuntLinea valueObject) 
          throws NotFoundException, SQLException {

          String sql = "DELETE FROM RUNT_LINEAS_RNA WHERE (CODIGO = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setInt(1, valueObject.getID_LINEA()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM RUNT_LINEAS_RNA";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM RUNT_LINEAS_RNA";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, RuntLinea valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT CODIGO AS ID_LINEA, CODIGO_MARCA AS ID_MARCA, LINEA AS DESCRIPCION, 'S' AS REVISADA, CODIGO AS ID_MARCA_NUM, CODIGO AS ID_LINEA_PPAL, 'S' AS CHEQUEADO, CODIGO_MARCA AS ID_MARCAPPAL, CODIGO AS ID_LINEARUNT, CODIGO AS ID_LINEAMIN  FROM RUNT_LINEAS_RNA WHERE 1=1 ");

          if (valueObject.getID_LINEA() != 0) {
              if (first) { first = false; }
              sql.append("AND CODIGO = ").append(valueObject.getID_LINEA()).append(" ");
          }

          if (valueObject.getID_MARCA() != null) {
              if (first) { first = false; }
              sql.append("AND CODIGO_MARCA = '").append(valueObject.getID_MARCA()).append("' ");
          }

          if (valueObject.getDESCRIPCION() != null) {
              if (first) { first = false; }
              sql.append("AND LINEA = '").append(valueObject.getDESCRIPCION()).append("' ");
          }

          if (valueObject.getREVISADA() != null) {
              if (first) { first = false; }
              sql.append("AND REVISADA = '").append(valueObject.getREVISADA()).append("' ");
          }

          if (valueObject.getIDMARCANUM() != null) {
              if (first) { first = false; }
              sql.append("AND CODIGO_MARCA = '").append(valueObject.getIDMARCANUM()).append("' ");
          }

          if (valueObject.getID_LINEAPPAL() != null) {
              if (first) { first = false; }
              sql.append("AND CODIGO = '").append(valueObject.getID_LINEAPPAL()).append("' ");
          }

          if (valueObject.getCHEQUEADO() != null) {
              if (first) { first = false; }
              sql.append("AND CHEQUEADO = '").append(valueObject.getCHEQUEADO()).append("' ");
          }

          if (valueObject.getID_MARCAPPAL() != null) {
              if (first) { first = false; }
              sql.append("AND CODIGO_MARCA ='").append(valueObject.getID_MARCAPPAL()).append("' ");
          }

          if (valueObject.getID_LINEARUNT() != null) {
              if (first) { first = false; }
              sql.append("AND CODIGO = '").append(valueObject.getID_LINEARUNT()).append("' ");
          }


          sql.append("ORDER BY LINEA ASC ");

//System.out.println(sql);
          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, RuntLinea valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setID_LINEA(result.getInt("ID_LINEA")); 
                   valueObject.setID_MARCA(result.getString("ID_MARCA")); 
                   valueObject.setDESCRIPCION(result.getString("DESCRIPCION")); 
                   valueObject.setREVISADA(result.getString("REVISADA")); 
                   valueObject.setIDMARCANUM(result.getString("ID_MARCA")); 
                   valueObject.setID_LINEAPPAL(result.getString("ID_LINEA")); 
                   valueObject.setCHEQUEADO(result.getString("CHEQUEADO")); 
                   valueObject.setID_MARCAPPAL(result.getString("ID_MARCA")); 
                   valueObject.setID_LINEARUNT(result.getString("ID_LINEA")); 

              } else {
                    //System.out.println("RuntLinea Object Not Found!");
                    throw new NotFoundException("RuntLinea Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   RuntLinea temp = createValueObject();

                   temp.setID_LINEA(result.getInt("ID_LINEA")); 
                   temp.setID_MARCA(result.getString("ID_MARCA")); 
                   temp.setDESCRIPCION(result.getString("DESCRIPCION")); 
                   temp.setREVISADA(result.getString("REVISADA")); 
                   temp.setIDMARCANUM(result.getString("ID_MARCA")); 
                   temp.setID_LINEAPPAL(result.getString("ID_LINEA")); 
                   temp.setCHEQUEADO(result.getString("CHEQUEADO")); 
                   temp.setID_MARCAPPAL(result.getString("ID_MARCA")); 
                   temp.setID_LINEARUNT(result.getString("ID_LINEA")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
