package modelo.datos.objetos.comparendos.accesorias;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * DocumentoComp Value Object.
  * This class is value object representing database table DOCUMENTO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class DocumentoComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String ID_DOCTO;
    private String DESCRIPCION;
    private int IDREPORTECOMPARENDO;
    private String IDCONSULTASIMIT;
    private int ID_DOCCOMP;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public DocumentoComp () {

    }

    public DocumentoComp (String ID_DOCTOIn) {

          this.ID_DOCTO = ID_DOCTOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getID_DOCTO() {
          return this.ID_DOCTO;
    }
    public void setID_DOCTO(String ID_DOCTOIn) {
          this.ID_DOCTO = ID_DOCTOIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public int getIDREPORTECOMPARENDO() {
          return this.IDREPORTECOMPARENDO;
    }
    public void setIDREPORTECOMPARENDO(int IDREPORTECOMPARENDOIn) {
          this.IDREPORTECOMPARENDO = IDREPORTECOMPARENDOIn;
    }

    public String getIDCONSULTASIMIT() {
          return this.IDCONSULTASIMIT;
    }
    public void setIDCONSULTASIMIT(String IDCONSULTASIMITIn) {
          this.IDCONSULTASIMIT = IDCONSULTASIMITIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String ID_DOCTOIn,
          String DESCRIPCIONIn,
          int IDREPORTECOMPARENDOIn,
          String IDCONSULTASIMITIn, int ID_DOCCOMPIn) {
          this.ID_DOCTO = ID_DOCTOIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.IDREPORTECOMPARENDO = IDREPORTECOMPARENDOIn;
          this.IDCONSULTASIMIT = IDCONSULTASIMITIn;
          this.ID_DOCCOMP = ID_DOCCOMPIn;
    }


    /** 
     * hasEqualMapping-method will compare two DocumentoComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(DocumentoComp valueObject) {

          if (this.ID_DOCTO == null) {
                    if (valueObject.getID_DOCTO() != null)
                           return(false);
          } else if (!this.ID_DOCTO.equals(valueObject.getID_DOCTO())) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (valueObject.getIDREPORTECOMPARENDO() != this.IDREPORTECOMPARENDO) {
                    return(false);
          }
          if (this.IDCONSULTASIMIT == null) {
                    if (valueObject.getIDCONSULTASIMIT() != null)
                           return(false);
          } else if (!this.IDCONSULTASIMIT.equals(valueObject.getIDCONSULTASIMIT())) {
                    return(false);
          }
          if (valueObject.getID_DOCCOMP() != this.ID_DOCCOMP) {
                  return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass DocumentoComp, mapping to table DOCUMENTO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_DOCTO = " + this.ID_DOCTO + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("IDREPORTECOMPARENDO = " + this.IDREPORTECOMPARENDO + "\n"); 
        out.append("IDCONSULTASIMIT = " + this.IDCONSULTASIMIT + "\n"); 
        out.append("ID_DOCCOMP = " + this.ID_DOCCOMP + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        DocumentoComp cloned = new DocumentoComp();

        if (this.ID_DOCTO != null)
             cloned.setID_DOCTO(new String(this.ID_DOCTO)); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        cloned.setIDREPORTECOMPARENDO(this.IDREPORTECOMPARENDO); 
        if (this.IDCONSULTASIMIT != null)
             cloned.setIDCONSULTASIMIT(new String(this.IDCONSULTASIMIT)); 
        cloned.setID_DOCCOMP(this.ID_DOCCOMP);
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

    public int getID_DOCCOMP() {
        return ID_DOCCOMP;
    }

    public void setID_DOCCOMP(int ID_DOCCOMP) {
        this.ID_DOCCOMP = ID_DOCCOMP;
    }
}
