package modelo.datos.objetos.comparendos.accesorias;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * RadioDeAccionComp Value Object.
  * This class is value object representing database table RADIODEACCION
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class RadioDeAccionComp implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_RADIODEACCION;
    private String COD_RADIOACCION;
    private String DESC_RADIOACCION;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public RadioDeAccionComp () {

    }

    public RadioDeAccionComp (int ID_RADIODEACCIONIn) {

          this.ID_RADIODEACCION = ID_RADIODEACCIONIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_RADIODEACCION() {
          return this.ID_RADIODEACCION;
    }
    public void setID_RADIODEACCION(int ID_RADIODEACCIONIn) {
          this.ID_RADIODEACCION = ID_RADIODEACCIONIn;
    }

    public String getCOD_RADIOACCION() {
          return this.COD_RADIOACCION;
    }
    public void setCOD_RADIOACCION(String COD_RADIOACCIONIn) {
          this.COD_RADIOACCION = COD_RADIOACCIONIn;
    }

    public String getDESC_RADIOACCION() {
          return this.DESC_RADIOACCION;
    }
    public void setDESC_RADIOACCION(String DESC_RADIOACCIONIn) {
          this.DESC_RADIOACCION = DESC_RADIOACCIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_RADIODEACCIONIn,
          String COD_RADIOACCIONIn,
          String DESC_RADIOACCIONIn) {
          this.ID_RADIODEACCION = ID_RADIODEACCIONIn;
          this.COD_RADIOACCION = COD_RADIOACCIONIn;
          this.DESC_RADIOACCION = DESC_RADIOACCIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two RadioDeAccionComp instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(RadioDeAccionComp valueObject) {

          if (valueObject.getID_RADIODEACCION() != this.ID_RADIODEACCION) {
                    return(false);
          }
          if (this.COD_RADIOACCION == null) {
                    if (valueObject.getCOD_RADIOACCION() != null)
                           return(false);
          } else if (!this.COD_RADIOACCION.equals(valueObject.getCOD_RADIOACCION())) {
                    return(false);
          }
          if (this.DESC_RADIOACCION == null) {
                    if (valueObject.getDESC_RADIOACCION() != null)
                           return(false);
          } else if (!this.DESC_RADIOACCION.equals(valueObject.getDESC_RADIOACCION())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass RadioDeAccionComp, mapping to table RADIODEACCION\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_RADIODEACCION = " + this.ID_RADIODEACCION + "\n"); 
        out.append("COD_RADIOACCION = " + this.COD_RADIOACCION + "\n"); 
        out.append("DESC_RADIOACCION = " + this.DESC_RADIOACCION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        RadioDeAccionComp cloned = new RadioDeAccionComp();

        cloned.setID_RADIODEACCION(this.ID_RADIODEACCION); 
        if (this.COD_RADIOACCION != null)
             cloned.setCOD_RADIOACCION(new String(this.COD_RADIOACCION)); 
        if (this.DESC_RADIOACCION != null)
             cloned.setDESC_RADIOACCION(new String(this.DESC_RADIOACCION)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

