package modelo.datos.objetos.comparendos.accesorias;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * TipoInfraccioEstado Value Object.
  * This class is value object representing database table TIPO_INFRACCION_ESTADO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class TipoInfraccioEstado implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_TIPO_INFR_ESTADO;
    private int ID_TIPO_INFRACCION;
    private int ID_ESTADOCOM;
    private String DESCRIPCION;
    private String TIPO_OPERACION;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public TipoInfraccioEstado () {

    }

    public TipoInfraccioEstado (int ID_TIPO_INFR_ESTADOIn) {

          this.ID_TIPO_INFR_ESTADO = ID_TIPO_INFR_ESTADOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_TIPO_INFR_ESTADO() {
          return this.ID_TIPO_INFR_ESTADO;
    }
    public void setID_TIPO_INFR_ESTADO(int ID_TIPO_INFR_ESTADOIn) {
          this.ID_TIPO_INFR_ESTADO = ID_TIPO_INFR_ESTADOIn;
    }

    public int getID_TIPO_INFRACCION() {
          return this.ID_TIPO_INFRACCION;
    }
    public void setID_TIPO_INFRACCION(int ID_TIPO_INFRACCIONIn) {
          this.ID_TIPO_INFRACCION = ID_TIPO_INFRACCIONIn;
    }

    public int getID_ESTADOCOM() {
          return this.ID_ESTADOCOM;
    }
    public void setID_ESTADOCOM(int ID_ESTADOCOMIn) {
          this.ID_ESTADOCOM = ID_ESTADOCOMIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_TIPO_INFR_ESTADOIn,
          int ID_TIPO_INFRACCIONIn,
          int ID_ESTADOCOMIn,
          String DESCRIPCIONIn) {
          this.ID_TIPO_INFR_ESTADO = ID_TIPO_INFR_ESTADOIn;
          this.ID_TIPO_INFRACCION = ID_TIPO_INFRACCIONIn;
          this.ID_ESTADOCOM = ID_ESTADOCOMIn;
          this.DESCRIPCION = DESCRIPCIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two TipoInfraccioEstado instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(TipoInfraccioEstado valueObject) {

          if (valueObject.getID_TIPO_INFR_ESTADO() != this.ID_TIPO_INFR_ESTADO) {
                    return(false);
          }
          if (valueObject.getID_TIPO_INFRACCION() != this.ID_TIPO_INFRACCION) {
                    return(false);
          }
          if (valueObject.getID_ESTADOCOM() != this.ID_ESTADOCOM) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass TipoInfraccioEstado, mapping to table TIPO_INFRACCION_ESTADO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_TIPO_INFR_ESTADO = " + this.ID_TIPO_INFR_ESTADO + "\n"); 
        out.append("ID_TIPO_INFRACCION = " + this.ID_TIPO_INFRACCION + "\n"); 
        out.append("ID_ESTADOCOM = " + this.ID_ESTADOCOM + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        TipoInfraccioEstado cloned = new TipoInfraccioEstado();

        cloned.setID_TIPO_INFR_ESTADO(this.ID_TIPO_INFR_ESTADO); 
        cloned.setID_TIPO_INFRACCION(this.ID_TIPO_INFRACCION); 
        cloned.setID_ESTADOCOM(this.ID_ESTADOCOM); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

    public String getTIPO_OPERACION() {
        return TIPO_OPERACION;
    }

    public void setTIPO_OPERACION(String TIPO_OPERACION) {
        this.TIPO_OPERACION = TIPO_OPERACION;
    }
}
