package modelo.datos.objetos.avaluos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * CarroceriaMin Value Object.
  * This class is value object representing database table CARROCERIAMIN
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class CarroceriaMin implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_CARROCERIAMIN;
    private String COD_CARROCERIA;
    private String DES_CARROCERIA;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public CarroceriaMin () {

    }

    public CarroceriaMin (int ID_CARROCERIAMINIn) {

          this.ID_CARROCERIAMIN = ID_CARROCERIAMINIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_CARROCERIAMIN() {
          return this.ID_CARROCERIAMIN;
    }
    public void setID_CARROCERIAMIN(int ID_CARROCERIAMINIn) {
          this.ID_CARROCERIAMIN = ID_CARROCERIAMINIn;
    }

    public String getCOD_CARROCERIA() {
          return this.COD_CARROCERIA;
    }
    public void setCOD_CARROCERIA(String COD_CARROCERIAIn) {
          this.COD_CARROCERIA = COD_CARROCERIAIn;
    }

    public String getDES_CARROCERIA() {
          return this.DES_CARROCERIA;
    }
    public void setDES_CARROCERIA(String DES_CARROCERIAIn) {
          this.DES_CARROCERIA = DES_CARROCERIAIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_CARROCERIAMINIn,
          String COD_CARROCERIAIn,
          String DES_CARROCERIAIn) {
          this.ID_CARROCERIAMIN = ID_CARROCERIAMINIn;
          this.COD_CARROCERIA = COD_CARROCERIAIn;
          this.DES_CARROCERIA = DES_CARROCERIAIn;
    }


    /** 
     * hasEqualMapping-method will compare two CarroceriaMin instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(CarroceriaMin valueObject) {

          if (valueObject.getID_CARROCERIAMIN() != this.ID_CARROCERIAMIN) {
                    return(false);
          }
          if (this.COD_CARROCERIA == null) {
                    if (valueObject.getCOD_CARROCERIA() != null)
                           return(false);
          } else if (!this.COD_CARROCERIA.equals(valueObject.getCOD_CARROCERIA())) {
                    return(false);
          }
          if (this.DES_CARROCERIA == null) {
                    if (valueObject.getDES_CARROCERIA() != null)
                           return(false);
          } else if (!this.DES_CARROCERIA.equals(valueObject.getDES_CARROCERIA())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass CarroceriaMin, mapping to table CARROCERIAMIN\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_CARROCERIAMIN = " + this.ID_CARROCERIAMIN + "\n"); 
        out.append("COD_CARROCERIA = " + this.COD_CARROCERIA + "\n"); 
        out.append("DES_CARROCERIA = " + this.DES_CARROCERIA + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        CarroceriaMin cloned = new CarroceriaMin();

        cloned.setID_CARROCERIAMIN(this.ID_CARROCERIAMIN); 
        if (this.COD_CARROCERIA != null)
             cloned.setCOD_CARROCERIA(new String(this.COD_CARROCERIA)); 
        if (this.DES_CARROCERIA != null)
             cloned.setDES_CARROCERIA(new String(this.DES_CARROCERIA)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

