package modelo.datos.objetos.avaluos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

/**
  * ExepAvaluo Value Object.
  * This class is value object representing database table EXCEP_AVALUO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ExepAvaluo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_EXCEP_AVALUO;
    private String EXCEPCION;
    private int VIGENCIA;
    private String PARAMETRO;
    private String VALOR;
    private int ID_TIPO_VEHICULO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ExepAvaluo () {

    }

    public ExepAvaluo (int ID_EXCEP_AVALUOIn) {

          this.ID_EXCEP_AVALUO = ID_EXCEP_AVALUOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_EXCEP_AVALUO() {
          return this.ID_EXCEP_AVALUO;
    }
    public void setID_EXCEP_AVALUO(int ID_EXCEP_AVALUOIn) {
          this.ID_EXCEP_AVALUO = ID_EXCEP_AVALUOIn;
    }

    public String getEXCEPCION() {
          return this.EXCEPCION;
    }
    public void setEXCEPCION(String EXCEPCIONIn) {
          this.EXCEPCION = EXCEPCIONIn;
    }

    public int getVIGENCIA() {
          return this.VIGENCIA;
    }
    public void setVIGENCIA(int VIGENCIAIn) {
          this.VIGENCIA = VIGENCIAIn;
    }

    public String getPARAMETRO() {
          return this.PARAMETRO;
    }
    public void setPARAMETRO(String PARAMETROIn) {
          this.PARAMETRO = PARAMETROIn;
    }

    public String getVALOR() {
          return this.VALOR;
    }
    public void setVALOR(String VALORIn) {
          this.VALOR = VALORIn;
    }

    public int getID_TIPO_VEHICULO() {
          return this.ID_TIPO_VEHICULO;
    }
    public void setID_TIPO_VEHICULO(int ID_TIPO_VEHICULOIn) {
          this.ID_TIPO_VEHICULO = ID_TIPO_VEHICULOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_EXCEP_AVALUOIn,
          String EXCEPCIONIn,
          int VIGENCIAIn,
          String PARAMETROIn,
          String VALORIn,
          int ID_TIPO_VEHICULOIn) {
          this.ID_EXCEP_AVALUO = ID_EXCEP_AVALUOIn;
          this.EXCEPCION = EXCEPCIONIn;
          this.VIGENCIA = VIGENCIAIn;
          this.PARAMETRO = PARAMETROIn;
          this.VALOR = VALORIn;
          this.ID_TIPO_VEHICULO = ID_TIPO_VEHICULOIn;
    }


    /** 
     * hasEqualMapping-method will compare two ExepAvaluo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ExepAvaluo valueObject) {

          if (valueObject.getID_EXCEP_AVALUO() != this.ID_EXCEP_AVALUO) {
                    return(false);
          }
          if (this.EXCEPCION == null) {
                    if (valueObject.getEXCEPCION() != null)
                           return(false);
          } else if (!this.EXCEPCION.equals(valueObject.getEXCEPCION())) {
                    return(false);
          }
          if (valueObject.getVIGENCIA() != this.VIGENCIA) {
                    return(false);
          }
          if (this.PARAMETRO == null) {
                    if (valueObject.getPARAMETRO() != null)
                           return(false);
          } else if (!this.PARAMETRO.equals(valueObject.getPARAMETRO())) {
                    return(false);
          }
          if (this.VALOR == null) {
                    if (valueObject.getVALOR() != null)
                           return(false);
          } else if (!this.VALOR.equals(valueObject.getVALOR())) {
                    return(false);
          }
          if (valueObject.getID_TIPO_VEHICULO() != this.ID_TIPO_VEHICULO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ExepAvaluo, mapping to table EXCEP_AVALUO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_EXCEP_AVALUO = " + this.ID_EXCEP_AVALUO + "\n"); 
        out.append("EXCEPCION = " + this.EXCEPCION + "\n"); 
        out.append("VIGENCIA = " + this.VIGENCIA + "\n"); 
        out.append("PARAMETRO = " + this.PARAMETRO + "\n"); 
        out.append("VALOR = " + this.VALOR + "\n"); 
        out.append("ID_TIPO_VEHICULO = " + this.ID_TIPO_VEHICULO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ExepAvaluo cloned = new ExepAvaluo();

        cloned.setID_EXCEP_AVALUO(this.ID_EXCEP_AVALUO); 
        if (this.EXCEPCION != null)
             cloned.setEXCEPCION(new String(this.EXCEPCION)); 
        cloned.setVIGENCIA(this.VIGENCIA); 
        if (this.PARAMETRO != null)
             cloned.setPARAMETRO(new String(this.PARAMETRO)); 
        if (this.VALOR != null)
             cloned.setVALOR(new String(this.VALOR)); 
        cloned.setID_TIPO_VEHICULO(this.ID_TIPO_VEHICULO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
