package modelo.datos.objetos.logs;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ErroresSW Value Object.
  * This class is value object representing database table ERRORES_SW
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ErroresSW implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_ERRORES_SW;
    private String NOMBRE;
    private String ERROR;
    private String DESCRIPCION;
    private String SUGERENCIA;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ErroresSW () {

    }

    public ErroresSW (int ID_ERRORES_SWIn) {

          this.ID_ERRORES_SW = ID_ERRORES_SWIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_ERRORES_SW() {
          return this.ID_ERRORES_SW;
    }
    public void setID_ERRORES_SW(int ID_ERRORES_SWIn) {
          this.ID_ERRORES_SW = ID_ERRORES_SWIn;
    }

    public String getNOMBRE() {
          return this.NOMBRE;
    }
    public void setNOMBRE(String NOMBREIn) {
          this.NOMBRE = NOMBREIn;
    }

    public String getERROR() {
          return this.ERROR;
    }
    public void setERROR(String ERRORIn) {
          this.ERROR = ERRORIn;
    }

    public String getDESCRIPCION() {
          return this.DESCRIPCION;
    }
    public void setDESCRIPCION(String DESCRIPCIONIn) {
          this.DESCRIPCION = DESCRIPCIONIn;
    }

    public String getSUGERENCIA() {
          return this.SUGERENCIA;
    }
    public void setSUGERENCIA(String SUGERENCIAIn) {
          this.SUGERENCIA = SUGERENCIAIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_ERRORES_SWIn,
          String NOMBREIn,
          String ERRORIn,
          String DESCRIPCIONIn,
          String SUGERENCIAIn) {
          this.ID_ERRORES_SW = ID_ERRORES_SWIn;
          this.NOMBRE = NOMBREIn;
          this.ERROR = ERRORIn;
          this.DESCRIPCION = DESCRIPCIONIn;
          this.SUGERENCIA = SUGERENCIAIn;
    }


    /** 
     * hasEqualMapping-method will compare two ErroresSW instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ErroresSW valueObject) {

          if (valueObject.getID_ERRORES_SW() != this.ID_ERRORES_SW) {
                    return(false);
          }
          if (this.NOMBRE == null) {
                    if (valueObject.getNOMBRE() != null)
                           return(false);
          } else if (!this.NOMBRE.equals(valueObject.getNOMBRE())) {
                    return(false);
          }
          if (this.ERROR == null) {
                    if (valueObject.getERROR() != null)
                           return(false);
          } else if (!this.ERROR.equals(valueObject.getERROR())) {
                    return(false);
          }
          if (this.DESCRIPCION == null) {
                    if (valueObject.getDESCRIPCION() != null)
                           return(false);
          } else if (!this.DESCRIPCION.equals(valueObject.getDESCRIPCION())) {
                    return(false);
          }
          if (this.SUGERENCIA == null) {
                    if (valueObject.getSUGERENCIA() != null)
                           return(false);
          } else if (!this.SUGERENCIA.equals(valueObject.getSUGERENCIA())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ErroresSW, mapping to table ERRORES_SW\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_ERRORES_SW = " + this.ID_ERRORES_SW + "\n"); 
        out.append("NOMBRE = " + this.NOMBRE + "\n"); 
        out.append("ERROR = " + this.ERROR + "\n"); 
        out.append("DESCRIPCION = " + this.DESCRIPCION + "\n"); 
        out.append("SUGERENCIA = " + this.SUGERENCIA + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ErroresSW cloned = new ErroresSW();

        cloned.setID_ERRORES_SW(this.ID_ERRORES_SW); 
        if (this.NOMBRE != null)
             cloned.setNOMBRE(new String(this.NOMBRE)); 
        if (this.ERROR != null)
             cloned.setERROR(new String(this.ERROR)); 
        if (this.DESCRIPCION != null)
             cloned.setDESCRIPCION(new String(this.DESCRIPCION)); 
        if (this.SUGERENCIA != null)
             cloned.setSUGERENCIA(new String(this.SUGERENCIA)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}