package modelo.datos.objetos.liquidacion.caja;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * AperturaTurno Value Object.
  * This class is value object representing database table AperturaTurno
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class AperturaTurno implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int IDAPERTURA;
    private String FECHA_INI;
    private String HORA_INI;
    private String FECHA_FIN;
    private String HORA_FIN;
    private String VLR_BASE;
    private String ACTIVO;
    private String ID_CAJERO;
    private int ID_ARQUEO;
    private int ID_USUARIOREGISTRA;
    private String FECHAHORA_USUARIOREGISTRA;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public AperturaTurno () {

    }

    public AperturaTurno (int IDAPERTURAIn) {

          this.IDAPERTURA = IDAPERTURAIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getIDAPERTURA() {
          return this.IDAPERTURA;
    }
    public void setIDAPERTURA(int IDAPERTURAIn) {
          this.IDAPERTURA = IDAPERTURAIn;
    }

    public String getFECHA_INI() {
          return this.FECHA_INI;
    }
    public void setFECHA_INI(String FECHA_INIIn) {
          this.FECHA_INI = FECHA_INIIn;
    }

    public String getHORA_INI() {
          return this.HORA_INI;
    }
    public void setHORA_INI(String HORA_INIIn) {
          this.HORA_INI = HORA_INIIn;
    }

    public String getFECHA_FIN() {
          return this.FECHA_FIN;
    }
    public void setFECHA_FIN(String FECHA_FINIn) {
          this.FECHA_FIN = FECHA_FINIn;
    }

    public String getHORA_FIN() {
          return this.HORA_FIN;
    }
    public void setHORA_FIN(String HORA_FINIn) {
          this.HORA_FIN = HORA_FINIn;
    }

    public String getVLR_BASE() {
          return this.VLR_BASE;
    }
    public void setVLR_BASE(String VLR_BASEIn) {
          this.VLR_BASE = VLR_BASEIn;
    }

    public String getACTIVO() {
          return this.ACTIVO;
    }
    public void setACTIVO(String ACTIVOIn) {
          this.ACTIVO = ACTIVOIn;
    }

    public String getID_CAJERO() {
          return this.ID_CAJERO;
    }
    public void setID_CAJERO(String ID_CAJEROIn) {
          this.ID_CAJERO = ID_CAJEROIn;
    }

    public int getID_ARQUEO() {
          return this.ID_ARQUEO;
    }
    public void setID_ARQUEO(int ID_ARQUEOIn) {
          this.ID_ARQUEO = ID_ARQUEOIn;
    }

    public int getID_USUARIOREGISTRA() {
          return this.ID_USUARIOREGISTRA;
    }
    public void setID_USUARIOREGISTRA(int ID_USUARIOREGISTRAIn) {
          this.ID_USUARIOREGISTRA = ID_USUARIOREGISTRAIn;
    }

    public String getFECHAHORA_USUARIOREGISTRA() {
          return this.FECHAHORA_USUARIOREGISTRA;
    }
    public void setFECHAHORA_USUARIOREGISTRA(String FECHAHORA_USUARIOREGISTRAIn) {
          this.FECHAHORA_USUARIOREGISTRA = FECHAHORA_USUARIOREGISTRAIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDAPERTURAIn,
          String FECHA_INIIn,
          String HORA_INIIn,
          String FECHA_FINIn,
          String HORA_FINIn,
          String VLR_BASEIn,
          String ACTIVOIn,
          String ID_CAJEROIn,
          int ID_ARQUEOIn,
          int ID_USUARIOREGISTRAIn,
          String FECHAHORA_USUARIOREGISTRAIn) {
          this.IDAPERTURA = IDAPERTURAIn;
          this.FECHA_INI = FECHA_INIIn;
          this.HORA_INI = HORA_INIIn;
          this.FECHA_FIN = FECHA_FINIn;
          this.HORA_FIN = HORA_FINIn;
          this.VLR_BASE = VLR_BASEIn;
          this.ACTIVO = ACTIVOIn;
          this.ID_CAJERO = ID_CAJEROIn;
          this.ID_ARQUEO = ID_ARQUEOIn;
          this.ID_USUARIOREGISTRA = ID_USUARIOREGISTRAIn;
          this.FECHAHORA_USUARIOREGISTRA = FECHAHORA_USUARIOREGISTRAIn;
    }


    /** 
     * hasEqualMapping-method will compare two AperturaTurno instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(AperturaTurno valueObject) {

          if (valueObject.getIDAPERTURA() != this.IDAPERTURA) {
                    return(false);
          }
          if (this.FECHA_INI == null) {
                    if (valueObject.getFECHA_INI() != null)
                           return(false);
          } else if (!this.FECHA_INI.equals(valueObject.getFECHA_INI())) {
                    return(false);
          }
          if (this.HORA_INI == null) {
                    if (valueObject.getHORA_INI() != null)
                           return(false);
          } else if (!this.HORA_INI.equals(valueObject.getHORA_INI())) {
                    return(false);
          }
          if (this.FECHA_FIN == null) {
                    if (valueObject.getFECHA_FIN() != null)
                           return(false);
          } else if (!this.FECHA_FIN.equals(valueObject.getFECHA_FIN())) {
                    return(false);
          }
          if (this.HORA_FIN == null) {
                    if (valueObject.getHORA_FIN() != null)
                           return(false);
          } else if (!this.HORA_FIN.equals(valueObject.getHORA_FIN())) {
                    return(false);
          }
          if (this.VLR_BASE == null) {
                    if (valueObject.getVLR_BASE() != null)
                           return(false);
          } else if (!this.VLR_BASE.equals(valueObject.getVLR_BASE())) {
                    return(false);
          }
          if (this.ACTIVO == null) {
                    if (valueObject.getACTIVO() != null)
                           return(false);
          } else if (!this.ACTIVO.equals(valueObject.getACTIVO())) {
                    return(false);
          }
          if (this.ID_CAJERO == null) {
                    if (valueObject.getID_CAJERO() != null)
                           return(false);
          } else if (!this.ID_CAJERO.equals(valueObject.getID_CAJERO())) {
                    return(false);
          }
          if (valueObject.getID_ARQUEO() != this.ID_ARQUEO) {
                    return(false);
          }
          if (valueObject.getID_USUARIOREGISTRA() != this.ID_USUARIOREGISTRA) {
                    return(false);
          }
          if (this.FECHAHORA_USUARIOREGISTRA == null) {
                    if (valueObject.getFECHAHORA_USUARIOREGISTRA() != null)
                           return(false);
          } else if (!this.FECHAHORA_USUARIOREGISTRA.equals(valueObject.getFECHAHORA_USUARIOREGISTRA())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass AperturaTurno, mapping to table AperturaTurno\n");
        out.append("Persistent attributes: \n"); 
        out.append("IDAPERTURA = " + this.IDAPERTURA + "\n"); 
        out.append("FECHA_INI = " + this.FECHA_INI + "\n"); 
        out.append("HORA_INI = " + this.HORA_INI + "\n"); 
        out.append("FECHA_FIN = " + this.FECHA_FIN + "\n"); 
        out.append("HORA_FIN = " + this.HORA_FIN + "\n"); 
        out.append("VLR_BASE = " + this.VLR_BASE + "\n"); 
        out.append("ACTIVO = " + this.ACTIVO + "\n"); 
        out.append("ID_CAJERO = " + this.ID_CAJERO + "\n"); 
        out.append("ID_ARQUEO = " + this.ID_ARQUEO + "\n"); 
        out.append("ID_USUARIOREGISTRA = " + this.ID_USUARIOREGISTRA + "\n"); 
        out.append("FECHAHORA_USUARIOREGISTRA = " + this.FECHAHORA_USUARIOREGISTRA + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        AperturaTurno cloned = new AperturaTurno();

        cloned.setIDAPERTURA(this.IDAPERTURA); 
        if (this.FECHA_INI != null)
             cloned.setFECHA_INI(new String(this.FECHA_INI)); 
        if (this.HORA_INI != null)
             cloned.setHORA_INI(new String(this.HORA_INI)); 
        if (this.FECHA_FIN != null)
             cloned.setFECHA_FIN(new String(this.FECHA_FIN)); 
        if (this.HORA_FIN != null)
             cloned.setHORA_FIN(new String(this.HORA_FIN)); 
        if (this.VLR_BASE != null)
             cloned.setVLR_BASE(new String(this.VLR_BASE)); 
        if (this.ACTIVO != null)
             cloned.setACTIVO(new String(this.ACTIVO)); 
        if (this.ID_CAJERO != null)
             cloned.setID_CAJERO(new String(this.ID_CAJERO)); 
        cloned.setID_ARQUEO(this.ID_ARQUEO); 
        cloned.setID_USUARIOREGISTRA(this.ID_USUARIOREGISTRA); 
        if (this.FECHAHORA_USUARIOREGISTRA != null)
             cloned.setFECHAHORA_USUARIOREGISTRA(new String(this.FECHAHORA_USUARIOREGISTRA)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
