package modelo.datos.objetos.comparendos.planos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * PlanosSimit Value Object.
  * This class is value object representing database table PLANOSSIMIT
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class PlanosSimit implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID;
    private String RUTA;
    private int OFICIO;
    private String FECHAREGISTRO;
    private String NOMBRECARGA;
    private int ID_RANGOCOMPARENDOS;
    private String FECHAINIPLANOS;
    private String FECHAFINPLANOS;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public PlanosSimit () {

    }

    public PlanosSimit (int IDIn) {

          this.ID = IDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID() {
          return this.ID;
    }
    public void setID(int IDIn) {
          this.ID = IDIn;
    }

    public String getRUTA() {
          return this.RUTA;
    }
    public void setRUTA(String RUTAIn) {
          this.RUTA = RUTAIn;
    }

    public int getOFICIO() {
          return this.OFICIO;
    }
    public void setOFICIO(int OFICIOIn) {
          this.OFICIO = OFICIOIn;
    }

    public String getFECHAREGISTRO() {
          return this.FECHAREGISTRO;
    }
    public void setFECHAREGISTRO(String FECHAREGISTROIn) {
          this.FECHAREGISTRO = FECHAREGISTROIn;
    }

    public String getNOMBRECARGA() {
          return this.NOMBRECARGA;
    }
    public void setNOMBRECARGA(String NOMBRECARGAIn) {
          this.NOMBRECARGA = NOMBRECARGAIn;
    }

    public int getID_RANGOCOMPARENDOS() {
          return this.ID_RANGOCOMPARENDOS;
    }
    public void setID_RANGOCOMPARENDOS(int ID_RANGOCOMPARENDOSIn) {
          this.ID_RANGOCOMPARENDOS = ID_RANGOCOMPARENDOSIn;
    }

    public String getFECHAINIPLANOS() {
          return this.FECHAINIPLANOS;
    }
    public void setFECHAINIPLANOS(String FECHAINIPLANOSIn) {
          this.FECHAINIPLANOS = FECHAINIPLANOSIn;
    }

    public String getFECHAFINPLANOS() {
          return this.FECHAFINPLANOS;
    }
    public void setFECHAFINPLANOS(String FECHAFINPLANOSIn) {
          this.FECHAFINPLANOS = FECHAFINPLANOSIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int IDIn,
          String RUTAIn,
          int OFICIOIn,
          String FECHAREGISTROIn,
          String NOMBRECARGAIn,
          int ID_RANGOCOMPARENDOSIn,
          String FECHAINIPLANOSIn,
          String FECHAFINPLANOSIn) {
          this.ID = IDIn;
          this.RUTA = RUTAIn;
          this.OFICIO = OFICIOIn;
          this.FECHAREGISTRO = FECHAREGISTROIn;
          this.NOMBRECARGA = NOMBRECARGAIn;
          this.ID_RANGOCOMPARENDOS = ID_RANGOCOMPARENDOSIn;
          this.FECHAINIPLANOS = FECHAINIPLANOSIn;
          this.FECHAFINPLANOS = FECHAFINPLANOSIn;
    }


    /** 
     * hasEqualMapping-method will compare two PlanosSimit instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(PlanosSimit valueObject) {

          if (valueObject.getID() != this.ID) {
                    return(false);
          }
          if (this.RUTA == null) {
                    if (valueObject.getRUTA() != null)
                           return(false);
          } else if (!this.RUTA.equals(valueObject.getRUTA())) {
                    return(false);
          }
          if (valueObject.getOFICIO() != this.OFICIO) {
                    return(false);
          }
          if (this.FECHAREGISTRO == null) {
                    if (valueObject.getFECHAREGISTRO() != null)
                           return(false);
          } else if (!this.FECHAREGISTRO.equals(valueObject.getFECHAREGISTRO())) {
                    return(false);
          }
          if (this.NOMBRECARGA == null) {
                    if (valueObject.getNOMBRECARGA() != null)
                           return(false);
          } else if (!this.NOMBRECARGA.equals(valueObject.getNOMBRECARGA())) {
                    return(false);
          }
          if (valueObject.getID_RANGOCOMPARENDOS() != this.ID_RANGOCOMPARENDOS) {
                    return(false);
          }
          if (this.FECHAINIPLANOS == null) {
                    if (valueObject.getFECHAINIPLANOS() != null)
                           return(false);
          } else if (!this.FECHAINIPLANOS.equals(valueObject.getFECHAINIPLANOS())) {
                    return(false);
          }
          if (this.FECHAFINPLANOS == null) {
                    if (valueObject.getFECHAFINPLANOS() != null)
                           return(false);
          } else if (!this.FECHAFINPLANOS.equals(valueObject.getFECHAFINPLANOS())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass PlanosSimit, mapping to table PLANOSSIMIT\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID = " + this.ID + "\n"); 
        out.append("RUTA = " + this.RUTA + "\n"); 
        out.append("OFICIO = " + this.OFICIO + "\n"); 
        out.append("FECHAREGISTRO = " + this.FECHAREGISTRO + "\n"); 
        out.append("NOMBRECARGA = " + this.NOMBRECARGA + "\n"); 
        out.append("ID_RANGOCOMPARENDOS = " + this.ID_RANGOCOMPARENDOS + "\n"); 
        out.append("FECHAINIPLANOS = " + this.FECHAINIPLANOS + "\n"); 
        out.append("FECHAFINPLANOS = " + this.FECHAFINPLANOS + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        PlanosSimit cloned = new PlanosSimit();

        cloned.setID(this.ID); 
        if (this.RUTA != null)
             cloned.setRUTA(new String(this.RUTA)); 
        cloned.setOFICIO(this.OFICIO); 
        if (this.FECHAREGISTRO != null)
             cloned.setFECHAREGISTRO(new String(this.FECHAREGISTRO)); 
        if (this.NOMBRECARGA != null)
             cloned.setNOMBRECARGA(new String(this.NOMBRECARGA)); 
        cloned.setID_RANGOCOMPARENDOS(this.ID_RANGOCOMPARENDOS); 
        if (this.FECHAINIPLANOS != null)
             cloned.setFECHAINIPLANOS(new String(this.FECHAINIPLANOS)); 
        if (this.FECHAFINPLANOS != null)
             cloned.setFECHAFINPLANOS(new String(this.FECHAFINPLANOS)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}