package modelo.datos.objetos.comparendos.planos;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * ViewPropVehiculoComparendo Value Object.
  * This class is value object representing database table VIEW_PROPVEHICULO_COMPARENDO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class ViewPropVehiculoComparendo implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String NROIDENTIFICACION;
    private String IDREPORTECOMPARENDO;
    private String NOMBRES;
    private String APELLIDOS;
    private String ID_COMPARENDO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public ViewPropVehiculoComparendo () {

    }

    public ViewPropVehiculoComparendo (String NROIDENTIFICACIONIn) {

          this.NROIDENTIFICACION = NROIDENTIFICACIONIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getNROIDENTIFICACION() {
          return this.NROIDENTIFICACION;
    }
    public void setNROIDENTIFICACION(String NROIDENTIFICACIONIn) {
          this.NROIDENTIFICACION = NROIDENTIFICACIONIn;
    }

    public String getIDREPORTECOMPARENDO() {
          return this.IDREPORTECOMPARENDO;
    }
    public void setIDREPORTECOMPARENDO(String IDREPORTECOMPARENDOIn) {
          this.IDREPORTECOMPARENDO = IDREPORTECOMPARENDOIn;
    }

    public String getNOMBRES() {
          return this.NOMBRES;
    }
    public void setNOMBRES(String NOMBRESIn) {
          this.NOMBRES = NOMBRESIn;
    }

    public String getAPELLIDOS() {
          return this.APELLIDOS;
    }
    public void setAPELLIDOS(String APELLIDOSIn) {
          this.APELLIDOS = APELLIDOSIn;
    }

    public String getID_COMPARENDO() {
          return this.ID_COMPARENDO;
    }
    public void setID_COMPARENDO(String ID_COMPARENDOIn) {
          this.ID_COMPARENDO = ID_COMPARENDOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String NROIDENTIFICACIONIn,
          String IDREPORTECOMPARENDOIn,
          String NOMBRESIn,
          String APELLIDOSIn,
          String ID_COMPARENDOIn) {
          this.NROIDENTIFICACION = NROIDENTIFICACIONIn;
          this.IDREPORTECOMPARENDO = IDREPORTECOMPARENDOIn;
          this.NOMBRES = NOMBRESIn;
          this.APELLIDOS = APELLIDOSIn;
          this.ID_COMPARENDO = ID_COMPARENDOIn;
    }


    /** 
     * hasEqualMapping-method will compare two ViewPropVehiculoComparendo instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(ViewPropVehiculoComparendo valueObject) {

          if (this.NROIDENTIFICACION == null) {
                    if (valueObject.getNROIDENTIFICACION() != null)
                           return(false);
          } else if (!this.NROIDENTIFICACION.equals(valueObject.getNROIDENTIFICACION())) {
                    return(false);
          }
          if (this.IDREPORTECOMPARENDO == null) {
                    if (valueObject.getIDREPORTECOMPARENDO() != null)
                           return(false);
          } else if (!this.IDREPORTECOMPARENDO.equals(valueObject.getIDREPORTECOMPARENDO())) {
                    return(false);
          }
          if (this.NOMBRES == null) {
                    if (valueObject.getNOMBRES() != null)
                           return(false);
          } else if (!this.NOMBRES.equals(valueObject.getNOMBRES())) {
                    return(false);
          }
          if (this.APELLIDOS == null) {
                    if (valueObject.getAPELLIDOS() != null)
                           return(false);
          } else if (!this.APELLIDOS.equals(valueObject.getAPELLIDOS())) {
                    return(false);
          }
          if (this.ID_COMPARENDO == null) {
                    if (valueObject.getID_COMPARENDO() != null)
                           return(false);
          } else if (!this.ID_COMPARENDO.equals(valueObject.getID_COMPARENDO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass ViewPropVehiculoComparendo, mapping to table VIEW_PROPVEHICULO_COMPARENDO\n");
        out.append("Persistent attributes: \n"); 
        out.append("NROIDENTIFICACION = " + this.NROIDENTIFICACION + "\n"); 
        out.append("IDREPORTECOMPARENDO = " + this.IDREPORTECOMPARENDO + "\n"); 
        out.append("NOMBRES = " + this.NOMBRES + "\n"); 
        out.append("APELLIDOS = " + this.APELLIDOS + "\n"); 
        out.append("ID_COMPARENDO = " + this.ID_COMPARENDO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        ViewPropVehiculoComparendo cloned = new ViewPropVehiculoComparendo();

        if (this.NROIDENTIFICACION != null)
             cloned.setNROIDENTIFICACION(new String(this.NROIDENTIFICACION)); 
        if (this.IDREPORTECOMPARENDO != null)
             cloned.setIDREPORTECOMPARENDO(new String(this.IDREPORTECOMPARENDO)); 
        if (this.NOMBRES != null)
             cloned.setNOMBRES(new String(this.NOMBRES)); 
        if (this.APELLIDOS != null)
             cloned.setAPELLIDOS(new String(this.APELLIDOS)); 
        if (this.ID_COMPARENDO != null)
             cloned.setID_COMPARENDO(new String(this.ID_COMPARENDO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}